### ISSUE TITLE
Add citation file

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1004]
## 🚀 Feature
We should add a citation file using the [citation file format](https://citation-file-format.github.io/). We could potentially use a citation format that is provided by CiteAs - see here http://citeas.org/cite/https://github.com/napari/napari for example (i'm not saying we want to use that exact one, but linking to a place which autogenerates them). I do like having a dedicated file though.

**Comment by sofroniewn** [comment]
cc @neuromusic this is one potential approach for capturing citation info for us and plugins

**Comment by neuromusic** [comment]
some other implementations...

qiime2 uses `citations.bib`, which gets parsed by the `Plugin` object when defining the plugin (the `Plugin` object is largely just a container for plugin metadata.... otherwise, qiime2 uses a similar approach to napari). [example implementation](https://github.com/qiime2/q2-feature-classifier/blob/master/q2_feature_classifier/plugin_setup.py)
