### ISSUE TITLE
big image (68 megapixels) does not display entirely

### ISSUE THREAD

**Issue by amedyukhina** [napari/napari#1050]
## 🐛 Bug

I am trying to display a very large image (6898 x 9946 pixels), but only the part of it is displayed: the bottom part is black. If I display only a part of the image, everything works fine. From my experience, problems start to occur from image size > ~55 megapixels.

## To Reproduce

This is the code to reproduce the issue with a random image:

img = np.random.randint(0, 100, size=(6898, 9946))

with napari.gui_qt(): 
    ...:     v = napari.view_image(img)

This is the result that I get:

![partly_displayed_image](https://user-images.githubusercontent.com/37274810/76669882-ac938600-655b-11ea-850f-044d480ac3b6.png)

Displaying the first 8000 pixels in x gives the result that I expect:

with napari.gui_qt(): 
    ...:     v = napari.view_image(img[:,:8000]) 

![expected_result](https://user-images.githubusercontent.com/37274810/76669931-e49ac900-655b-11ea-846c-e2c4fa8aca2c.png)

The problem starts to occur starting from the x-size of ~8200 pixels

## Environment

napari: 0.2.12
Platform: Linux-3.10.0-1062.4.3.el7.x86_64-x86_64-with-redhat-7.7-Maipo
Python: 3.7.6 (default, Jan 8 2020, 19:59:22) [GCC 7.3.0]
Qt: 5.14.1
PySide2: 5.14.1
VisPy: 0.6.4
NumPy: 1.18.1
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.12.0

GL version: 4.6.0 NVIDIA 440.31
MAX_TEXTURE_SIZE: 32768

**Comment by sofroniewn** [comment]
Hi @amedyukhina, sorry that you're running into this problem and thanks for reporting it. This is actually the same problem as reported in #458 that we still havn't fixed yet, but will hopefully get to soon as it is coming up a lot for people.

What's happening now is that we have a size threshold (8095) above which we're actually automatically generating an image pyramid under the hood to avoid passing too big images to your graphics card. We've actually probably been too conservative here and are planning to improve this behavior (see #736 for a summary of these issues).

For now, I'm curious if you pass `is_pyramid=False` to `view_image` if that might help.

Otherwise as I'll start work on a fix soon - @jni I will get to this during the world coordinates work after #1042 merges, either during the first PR or in a followup

**Comment by amedyukhina** [comment]
Passing `is_pyramid=False` solves the issue. Thanks for your quick response!

**Comment by sofroniewn** [comment]
> Passing is_pyramid=False solves the issue. Thanks for your quick response!

Ok good to know, thanks for the quick test and response too. It's a bit of a bandaid unfortunately. I'm going to leave this issue open for now and will close once we have a solution that doesn't require passing another keyword argument
