### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by ambrosejcarr** [napari/napari#106]
You've all added quite a few features that we'd like to use in starfish (here I'm thinking about 3-d markers and improvements to the index). When will you make the next release? Do you have plans to instantiate a release schedule?

**Comment by sofroniewn** [comment]
Not yet - we're in the process of some big refactoring, both of the internal gui code and the project structure. I don't think we'll make a new release until we feel we've gotten both of those into a good place. After that we might be able to think about something more regular.

**Comment by jni** [comment]
LOL at @AhmetCanSolak's reaction.

@sofroniewn I'm not sure anything needs to wait to push something new to PyPI, as long as the features mentioned by @ambrosejcarr are working correctly? Of course, it would be ideal if the cmaps PR were merged first. =P

**Comment by sofroniewn** [comment]
@jni that sounds good. The nD markers isn't merged into master yet, but we should be able to get that done this week, and there's nothing holding but the colormaps PR.

My only slight hesitation is that right now our main `imshow` api has currently changed to return a `window` instead of a `viewer` and I'm not sure that's the right call. I think we should look at this again before updating PyPi as I don't like the idea of something so fundamental flipping back and forth too often! I can make a separate issue to discuss this now.

**Comment by sofroniewn** [comment]
We have made our `0.0.6` release now which should have the features @ambrosejcarr is interested in. Moving forward I think we will try and release a little more frequently, but I'm not sure we are ready for a schedule yet. Closing this for now, but can always create a new issue to discuss this again when our next release is coming up.

**Comment by ambrosejcarr** [comment]
When you decide to move to a schedule, we're investigating automating releases and would be happy to communicate any learnings. 

spacetx/starfish#1059
