### ISSUE TITLE
Update conda forge recipe

### ISSUE THREAD

**Issue by kne42** [napari/napari#1070]
With the merging of #1059, our installation instructions for `pip` and `conda` will differ with regards to the installation of PyQt5. We should add the same functionality to our conda forge recipe if possible.

cc @jakirkham @jni

**Comment by jakirkham** [comment]
Thanks Kira! 😄

What happens if neither are installed for some reason? Will it raise an informative error?

If so, one option might be to put both in [`run_constrained`]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained ) and let the user decide at install time. We could also make one of them a hard requirement. Curious what @jni thinks of these options as well.

On a related note, are you familiar with [QtPy]( https://github.com/spyder-ide/qtpy )? 😉

**Comment by kne42** [comment]
@jakirkham Yeah, we use QtPy. Basically what we want to do is:
- if PyQt5 is installed, make sure it meets a minimum version
- if PySide2 is installed, make sure it meets a minimum version
- if neither are installed, install PySide2

**Comment by jakirkham** [comment]
Ah ok. Should have read more closely 😅

Yeah that makes sense. 🙂

`run_constrained` would solve the meeting minimum requirements. Though it doesn't pick which one to install. There is a `qtpy` package in conda-forge. So making that a requirement (if we haven't already) would make sense.

**Comment by sofroniewn** [comment]
@jni as we approach the `0.3.0` release is there anything more we need to do here?

**Comment by jni** [comment]
@sofroniewn I don't think this is urgent. We can bundle in conda differently from how we bundle in pip. When we make a new pip release, conda-forge bots will suggest an update to the recipe, and we'll check then whether we want to update our PySide/PyQt dependencies there or not. (I think probably not.)

**Comment by jakirkham** [comment]
FWIW there is [`qtpy`]( https://github.com/conda-forge/qtpy-feedstock ) in conda-forge. Probably still want to ensure one of either PyQt or PySide is required (since that package pulls in neither).

**Comment by sofroniewn** [comment]
@jni just pinging to see if this can be closed now, or if this is still needed?

**Comment by jni** [comment]
I think we can close this, thanks for bringing it up @sofroniewn! We can update issues with conda-forge as they come.
