### ISSUE TITLE
lazy console not working with keybinding or menu

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1073]
## 🐛 Bug
I missed this during review, but just noticed that #1055 seems to have added a bug when you open the console using either the `Shift+cmd+C` keybinding, or use the `Window > Console`  menu: the dock widget opens, but the console is missing until you press the actual button in the GUI.  haven't looked at the code yet.

**Comment by sofroniewn** [comment]
Good catch, sorry I should have caught that. The problem is that the menubar / shortcut option just trigger the changing of the visibility of the viewer doc widget and are automatically added by the `add_viewer_doc_widget` code, but what we really want to happen is call the `QtViewer.toggle_console_visibility` method which will also trigger the lazy import. Any ideas on a clean way to do this @tlambert03? If so a quick bug fix PR would be appreciated. I can think on it too
