### ISSUE TITLE
Viewer, slicing sliders, and Co

### ISSUE THREAD

**Issue by royerloic** [napari/napari#11]
A few features for the viewer's sliders:

- [x] The number of sliders adapts to the number of dimensions in the images or objects (max)
- [ ] Interval sliders are shown for displayed dimensions so that what is displayed can be cropped
       Very useful for 3D cropping for example...
- [ ]  There is a button for max/avg/... projections next to each slider
- [x] There is 3 small square buttons to toggle 1D, 2D, and 3D viewing.
- [x] Displayed dimensions can be chosen with 1, 2 or 3 context drop-down menus, depending on how many dimensions are displayed
- [ ]  There is a small squared 'play' button next to each slider so that we can animate
         the display or stop it. The speed can be controlled by right clicking and changing 
         the speed on some context menu.

**Comment by sofroniewn** [comment]
I might add here toggling between layers and slices which could be useful when dealing with color channel data. It might be nicer to view 4 color channels as 4 different layers which can be individually toggled on / off, contrast adjusted, and opacity filtered - instead of having a slider with 4 locations on it that you have to drag between.

**Comment by sofroniewn** [comment]
we're pretty close to all these features! we're still missing the max proj / crop, but issue #7 is explicitly about that, and the play button isn't quite in, but will follow closely after #607 so I will close this now
