### ISSUE TITLE
Shapes Layer is not renamed if polygon is added first

### ISSUE THREAD

**Issue by mirestrepo** [napari/napari#1115]
## 🐛 Bug

Shapes Layer is not renamed if polygon is added before changing the name

## To Reproduce

1. Load 3-d points and images layers. 
2. Add a new Shapes layer. By default the layer name is Shapes. 
3. Add a polygon. 
4. Rename Shapes Layer to e.g, "L1". 
5. When accessing the layers programmatically, the Layer name is still "Shapes".
6. Rename again, new name is correctly applied.

If I rename the layer right after creation, then there are no issues.

## Expected behavior

The layer name should always correspond to what the user entered in the GUI

## Environment

napari: 0.2.12+14.gdec5b99
Platform: Darwin-18.6.0-x86_64-i386-64bit
Python: 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
Qt: 5.13.2
PySide2: 5.13.2
VisPy: 0.6.4
NumPy: 1.18.1
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.11.0

GL version: 2.1 ATI-2.9.26
MAX_TEXTURE_SIZE: 16384

**Comment by sofroniewn** [comment]
@mirestrepo thanks for reporting this! It does sound like a bug - the name you see in the GUI should always match the name in the layers. I tried to reproduce this, inspecting the name in console by just doing `viewer.layers`, but they seem in sync for me. Could you maybe share a screen shot like mine but with them out of sync, just so I'm sure I understand what's going on. I'm curious do you still get the same bug if you draw a rectangle? There could be something about the way paths / polygons get drawn (and having the finish them with the `esc` key that causes this)

![image](https://user-images.githubusercontent.com/6531703/78576768-fe899d80-77e1-11ea-8b4f-c3fff76a60b5.png)

**Comment by mirestrepo** [comment]
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/1238840/78577739-854b7400-77fc-11ea-8a73-6f9c78377810.png">

**Comment by mirestrepo** [comment]
@sofroniewn It's also interesting, because in the lower left corner in you GUI, it should say `L1` instead of `Shapes`.... or that's what I see, in the cases when the renaming takes place as expected

**Comment by sofroniewn** [comment]
Hmm, most puzzling. Curious - where did the variable `review_viewer` get named, the default name we populate the console with is just `viewer`? [Also are those some nice L2/3 cells? Or am I getting a bit rusty on my cortical anatomy 😄]

**Comment by mirestrepo** [comment]
I'm working in a Jupyter notebook and I named the viewer review_viewer.

Oh.... I am a data scientist helping a neuroscience lab so my cortical anatomy is not very good - they are all just blobs to me waiting to be segmented 😂

And last, if I add a rectangle, the renaming happens as expected

**Comment by sofroniewn** [comment]
> I'm working in a Jupyter notebook and I named the viewer review_viewer.

Makes sense, just wanted to know if anything weird was going on there

> Oh.... I am a data scientist helping a neuroscience lab so my cortical anatomy is not very good - they are all just blobs to me waiting to be segmented 😂

😂😂😂😂so many blobs

> And last, if I add a rectangle, the renaming happens as expected

Ok, this is very interesting. When you finish drawing the polygon do you do so by clicking escape? What happens if you toggle focus between the viewer and another application before attempting the renaming? I'm wondering if somehow some focus somewhere isn't getting released, but I'll admit this is still a bit of a mystery to me. Maybe time to call in @tlambert03 to see if he can reproduce. [He might also know if they are L2/3 cells 😂]

**Comment by mirestrepo** [comment]
If I toggle focus to another application, then the renaming happens as expected. That's a good magic bug to find ;)!

**Comment by tlambert03** [comment]
omg. 🤪

**Comment by tlambert03** [comment]
yeah, I'm afraid I can't reproduce it either following the steps in the first post.  so we might need more specific reproduction instructions, including exactly how each step is being done.  The more you can put into code to reproduce, the better, for instance, instead of "load 3-d points and images layers", tell us exactly how you're starting napari and how you're instantiating the viewer.  include the commands that get you from the bash command line to the point of having a viewer instance.
when you say "add shapes", are you clicking on the button in the gui?  or doing it programmatically?   same with renaming, etc...

sorry for the detailed request but it's hard to debug it without being able to reproduce it

**Comment by mirestrepo** [comment]
I load a stack of images and an array of 4-d points.... 

The shapes are added interactively using the buttons in the GUI. I noticed the renaming issue, when saving my layers to file as shown in the code.

Feel free to ask for more details. Also the order of renaming and adding the polygon, is key... if I rename first and then add the polygon, there is no issue

```
review_properties = {
    'confidence': filtered_points[:, 0],
    'good_point': class_labels
}

# define the color cycle for the face_color annotation
face_color_cycle = ['blue', 'green']


review_viewer = napari.view_image(vois[roi_idx], rgb=False)


review_layer = review_viewer.add_points(filtered_points[:,1:4],
                    face_color='good_point',
                    face_color_cycle=face_color_cycle,
                    name='points',
                    size=3,
                    properties=review_properties)

# set the edge_color mode to colormap
review_layer.edge_color_mode = 'colormap'

@review_viewer.bind_key('f')
def save_polygons(review_layer):
    
    
    print("Saving labeled points to file")
    #save results to files.
    
    global polygonal_data 
    polygonal_data={}
    
    for layer in review_viewer.layers:
        print(type(layer))
        if type(layer) == napari.layers.shapes.shapes.Shapes:
            print("Found shape layer")
            print(layer.name)
            polygonal_data[layer.name] = layer.data
    
    global polygon_file
    
    polygon_file = output_path + "/roi_" + str(roi_idx) + "/polygon.npy"
    
    np.save(polygon_file, polygonal_data)
    
    print("Saved")
```

**Comment by sofroniewn** [comment]
Thanks for the details! I'll try these now. Also @mirestrepo, curious does #1051 fix this (it's not merged yet, but if you could try that branch it might be do the job - it changes some of how the mouse bindings are done for the shapes layer). [Unrelated #1051 also stops adding an extra vertex when drawing polygons, which hopefully you prefer too]

**Comment by sofroniewn** [comment]
@mirestrepo curious if this is still an issue on the current master, I'm afraid I wasn't able to reproduce before, but we've added a number fixes since then none of which were directly target at this, but which might have helped. If this is still a problem we can keep looking into it. Thanks again for flagging it

**Comment by sofroniewn** [comment]
I'm wondering @mirestrepo is this has remained a problem for you and maybe if you can try updating to the latest napari `0.3.8` and seeing if you can still reproduce this problem. We've clean up quite a bit since `0.2.12` and so this might no longer be an issue. It looks like at the time the rest of the team struggled to reproduce too. Thanks!!

**Comment by mirestrepo** [comment]
Hi. Thanks fo checking back and all the help. I'll close this and re-open if needed.
