### ISSUE TITLE
ROI 

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#112]
## 🚀 Feature
ROI that define regions; methods for accessing + displaying data from these regions. 

## Motivation
A standard method in functional imaging is to load some ND data with dimensions `(*space, t)` to a visualization tool (fiji, pyqtgraph, flika, icy, etc) and use a gui for drawing polygonal regions of interest (ROI) on the image in the two display axes. One may then generate a plot in another window that displays a summary statistic of the ROI, e.g. the time-varying spatial mean of the pixels in the ROI. This method is mandatory for rapid QC on a functional imaging dataset, but drawing ROI + visualizing timeseries can also form the basis of fancier stuff like cell segmentation, or targeting cells for photostimulation.

I'm sure the devs are thinking about this functionality :) I'm just curious here to see the current vision for ROI functionality in napari, and to provide a place for members of the bioimaging commnuity to weigh in. For my use, which might not generalize, the most important thing is that each ROI and its relevant properties + methods be accessible programmatically. Flika (via pyqtgraph) enable this, but some of the API is a little counter intuitive.

Some stuff I'd potentially like to see would be a way to programmatically register a function to act on an ROI vector before its plotted, e.g. to zscore / normalize timeseries before plotting them together. Also, and this is a long-shot because of how hard it is: good hand-drawing for 3D ROI, which would be super useful for people doing neuropil imaging in drosophila.

**Comment by sofroniewn** [comment]
@d-v-b great to open up an issue around this.

If I read correctly there are a couple things being mentioned in this issue

1. **Ability to draw and overlay 2D polygons on 2D-timeseries data.** We are actively working to support this, but it's still in its early stages. There is a PR that you can try #100 that allows you to create a `Shapes` layer and then move / rearrange the shapes - it doesn't allow drawing yet, but that will come. If you have comments on the API that would be great as it is still in development. There is also an issue discussing some of this #98, but it is slightly out of date, so probably best to look at the PR.

2. **Ability to draw / display 3D polygons (either in 3D or defined across multiple z-slices of a 3D image)**. This seems really hard to me, and I'm not sure about how to go about it. We've added support for "nD" stuff to our `Markers` layer which represents points. But extending this to lines / polygons seems challenging. I'm open to working on it in the future, but would be greatly aided by some concrete use cases and example datasets.

3. **Ability to select an roi and execute arbitrary analysis code base on the selection**. This is definitely on our road map. In addition to working on the viewer we're also thinking about how to create a plugin ecosystem that would be able to leverage the viewer, its layer types, and its interactivity to do more custom analysis routines. Something like click and run a cell segmentation based on the click would fall into the category of one of these plugins. I'd say our conversations around this are still early and exactly how we expose that to plugin developers / users is not clear but we have a fairly good idea of some of the basic use cases we want to support.

4. **Ability to select an roi and then display timeseries in a 2nd window**. This also seems like pretty basic functionality that we'd want to support, along with things like displaying 2 images side by side (currently supported), ability to show "orthogonal views" of a 3D volume (not currently supported) or "z-profiles" of a 3D volume (also not currently supported). I think the challenge here for us will be how to think about displaying a 1D plot (the timeseries) alongside the main image viewer. I think we're somewhat reticent to open up new windows and contribute to the window explosion that can happen in FIJI, but without doing that it is unclear to me how to organize it. I'm curious what your take is / what you'd like to see. As to providing hooks for you to then add your own custom transformations to the ROI to get to the timeseries that seems reasonable too - there are way to many different types of things people might want to do for us to try and "hard code" them, but we'd just need to think about what a good API looks like.


Anyway - that was a bunch of comments - the TL/DR though is - we're starting to think about this stuff. If you want to check out the very early stage work go look at the Shapes PR #100 and feel free to give some feedback!

**Comment by d-v-b** [comment]
Awesome! I'm super excited about this :)

**Comment by ambrosejcarr** [comment]
@sofroniewn we're going to start wanting to visualize these for starfish in a few months. We expect to hand off data to a segmentation working group in June. It could be an interesting group of users to pilot these features, if the times align.

> 2\. **Ability to draw / display 3D polygons (either in 3D or defined across multiple z-slices of a 3D image)**.

With respect to this, my initial research suggests that a compressed binary mask is probably the way to go from a _compute_ and _storage_ perspective. A binary mask has the nice characteristic of being cleanly n-dimensional. One could then compute a series of 2-d polygons for visualization.  Do you have any thoughts on this? 

Linking starfish research for masks in 3d as it seems relevant: https://github.com/spacetx/starfish/issues/875

cc @kne42

**Comment by sofroniewn** [comment]
Hi @ambrosejcarr 

It’s unclear to me why you’d need to switch to a polygon representation if you already have a binary mask representation? With the binary mask you could visualize an overlay with the appropriate transparency and color so it would look good, and it would tell you exactly which pixels were inside the shape. I can see if you wanted to be able to edit the shape and move the vertices then it might important to have the polygon representation - but that feature request may dictate how we want to think about the conversion.

Alternatively if you start with polygons and don’t want to make binary masks then I understand that you need to visualize polygons!

@d-v-b feel free to weigh in on the above (and below too)

I think I’d split this discussion further into a couple more parts

1. You want to do 3D rendering and seen an object in 3D with the appropriate transparencies and blending. In this case, say for simplicity you had a 3D cube, you would want to pass a list of the 8 corners and we would render them in 3D. This sort of functionality is supported by vispy, so I think we’d be able to get there, and it is on our roadmap, but right now we haven’t done any work yet to expose the vispy rendering of 3D images, let alone 3D polygons. Once we’ve got the images rendering we will address this.

2. You want to do 2D rendering but you have a 3D volume that you are scrolling through with a slider. In this case say again you have a 3D cube you could pass it just the list of 8 corners and we could calculate the slice through the cube that the current slider is at and render that to the screen (this could apply to any number of dimensions and any time of polygon) though complexity can quickly arise if the slice through for example generates two non-connected polygons we’d need to be able to handle that sort of geometry, and the whole thing would have to be really fast to still allow for reasonable interactivity (which is a concern here). One option would be to pre-compute on loading all the polygons for all possible slices (values of the z-slider, but that could be quite a lot). It would force some initial delay, but at least scrolling would be highly performant. If you switch from the XY view to the XZ view you’d have to do that again (unless you also precomputed that on loading too, which is again possible, but could be slow etc.). Finally for interactivity what vertices would we allow the user to select and drag - would it be only the original vertices at the corners of the polygon (say those 8) for the cube? Or would it be vertices on the slices? If one of the vertices on the slices then gets moved we could add it to the original list of vertices in its new location, defining a new 3D polygon which would be pretty nice but might lead to lots of recomputation as the slices all around would change too. Also how would someone move a vertex in the Z direction? I guess you’d need to switch to the XZ view or something, which would be possible.

3. You want to do 2D rendering, you have a 3D volume, and now you have a list of 2D polygons - one for each z-slice, so that cube that I mentioned above is actually a list of N squares. This sounds a little like what you described above, and could be the output if one were to manually draw polygons on each plane. We can certainly render this (wouldn’t be too hard given where we are now), but my concern is what shapes would we display if someone transitioned from an XY view to the XZ view - would we now need to do a lot of computation to determine how this list of 2D polygons really formed a 3D shape (sort of like the option above), or would we just show no polygons as there were none actually defined in the XZ plane. Finally for interactivity, here it’s maybe a little easier as each 2D polygon can be controlled independently.

**Comment by d-v-b** [comment]
Hi @sofroniewn and @ambrosejcarr 

From my own perspective, I see a strong distinction between binary masks: collections of indices / points in data coordinates, no intrinsic geometry, often produced computationally, and ROI: geometrical objects in display coordinates, often painted/drawn through human interaction with a GUI. 

As Nick notes, masks can be treated as another image layer, and Napari may be agnostic about the computation that generated a given mask. But, should Napari develop the kind of ROI drawing functionality Nick discusses in the latter portion of his comment, then Napari will be responsible for creating ROI and enabling user interaction with them. Thinking specifically about a solution for drawing ROI around the blobby 3D neuropil structures one encounters while doing functional imaging in drosophila or zebrafish, Nick's solution number 3 seems the simplest: 3D ROI accessible / modifiable slice-by-slice as 2D polygonal sections. But maybe this stuff is so domain-specific that it can be the purview of a plugin, given a basic system for creation & curation of polygons.

[ICY](http://icy.bioimageanalysis.org/) has an implementation of 3D roi drawing which might be worth looking at, but you can only draw lines in 3D (I guess for tracing neurites?), and the interface always made me a little crazy.

**Comment by sofroniewn** [comment]
With #297 we've now added support shapes including an nD mode with broadcasting and slicing, support for a rasterize functionality with `to_masks`, `to_labels`, and also `to_svg`.

Right now all our shapes must be within a 2D plane (even for the nD ones), but in the future we could support true 3D or nD shapes. I will leave that for followup issues and PRs though
