### ISSUE TITLE
Toggle current layer visibility w/keyboard shortcut

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1139]
## 🚀 Feature

I'd like to introduce a new keyboard shortcut to toggle visibility of current layer

## Motivation

When working with a few layers, I often find myself wanting to toggle the visibility of a particular layer to look clearly at one beneath. This has been coming up most recently when painting labels.

## Pitch

I'd like to propose a new keyboard shortcut to toggle the visibility of the current layer. 

This part is up for debate, but if this is very useful for people, it could be a single key, like `H`, or a combo like `Ctrl+H`, or some other key(s) entirely. 

From looking at the other key bindings, I assume this would be straightforward to do, unless there is some `Qt` issue I'm not familiar with.

## Alternatives

At the moment, I use the mouse to manually toggle the visibility.

**Comment by sofroniewn** [comment]
This seems like a pretty good feature to me @hectormz - you can look here https://github.com/napari/napari/blob/master/napari/_viewer_key_bindings.py#L83-L86 for how we use `Control-A` to select all layers, so seems pretty reasonable to add `Control-H` to toggle visibility for all selected layers (I'd probably go with all selected instead of just the active one)

I'd probably add a method like `toggle_selected_visibility` to our layers_list https://github.com/napari/napari/blob/master/napari/components/layerlist.py#L15 and then just call that from the keybinding as it's nice to keep the keybindings as short as possible.

Curious if @tlambert03 or @jni have an alternative implementation in mind or any other suggestions. 

It would be great if you could make this PR!!

**Comment by kevinyamauchi** [comment]
I think this is a great idea, @hectormz !

Do you think it would be also useful to create a "focus layer" keybinding while you're at it? This would hide (or dramatically increase the opacity) of all layers other than the selected layer.

**Comment by hectormz** [comment]
@sofroniewn thanks for the pointers, I'd be happy to put this together!

One question is what to do with homogeneous layers (eg 5 layers selected, with 2 visible and 3 not visible). 
- Should each layer be faithfully toggled?
- Or should it be assumed that the user wants all of them to be invisible/visible, and the state is determined by the majority? (In the example above, all the layers would become visible, and when toggled again, all would become invisible)

@kevinyamauchi I like that idea as well. I'm curious what others think about it, and how it should be implemented. Making all other layers invisible (and faithfully toggling the changed ones back) would be easiest. Is there a layer-level control to change opacity, or would it actually entail going down into each image or shape etc?

**Comment by GenevieveBuckley** [comment]
You can access the opacity for each layer using the `.opacity` property. Although for the issue you describe here (toggling visibility) it's probably much better to ignore opacity and use only the `.visible` property instead.

Because visibility is a boolean, you could make a "true" toggle by using `not`. I don't know if this is desirable for you, but it does seem like it could be more intuitive than the "majority rules" on/off switch described above?

Here's a short sketch that will let you play with those ideas:
```python
In [1]: import napari

In [2]: from skimage import data

In [3]: viewer = napari.Viewer()

In [4]: viewer.add_image(data.camera(), name='camera')
Out[4]: <Image layer 'camera' at 0x23251d9db50>

In [5]: viewer.add_image(data.astronaut(), name='astronaut')
Out[5]: <Image layer 'astronaut' at 0x23251e00be0>

In [6]: viewer.grid_view()  # let's see them side by side

In [7]: viewer.layers[0].visible = False  # let's manually switch off the visibility for one of these layers

In [8]: viewer.layers.select_all()

In [9]: def toggle_visibility(viewer):
    ...:     for layer in viewer.layers:
    ...:         if layer.selected:
    ...:             layer.visible = not layer.visible
    ...:

In [10]: toggle_visibility(viewer)

In [11]: toggle_visibility(viewer)
```

**Comment by sofroniewn** [comment]
> Because visibility is a boolean, you could make a "true" toggle by using not. I don't know if this is desirable for you, but it does seem like it could be more intuitive than the "majority rules" on/off switch described above?

That seems like a good place to start. I'd also probably start with a PR just focused on visibility, then there could maybe be a followup for opacity like @kevinyamauchi describes

**Comment by kevinyamauchi** [comment]
> I'd also probably start with a PR just focused on visibility, then there could maybe be a followup for opacity like @kevinyamauchi describes

Makes sense to me!

**Comment by hectormz** [comment]
@sofroniewn @kevinyamauchi I'll start with the simpler approach for now.

Thanks @GenevieveBuckley for the sample!
