### ISSUE TITLE
Docking Napari in a QT UI

### ISSUE THREAD

**Issue by dstabley** [napari/napari#1165]
### Please note that this issue tracker is not a help form and this issue will be closed.
I'm trying to develop a simulator application using Napari as the end result viewer. In PyQT5 it is possible, for example, to dock a matplotlib plot inside of an existing window. Is it possible to do this with a Napari viewer? This may be a naive question but I am new to QT development. 

Thanks!

**Comment by tlambert03** [comment]
Anything that ultimately inherits from [`QWidget`](https://doc.qt.io/qt-5/qwidget.html) can be put in any Qt application.  So just as a matplotlib `FigureCanvas` can be reused in other applications, so too can any napari widget.  Granted, the degree to which it feels "at home" in some other application will depend on a lot of other factors.  The two main widgets that you may wish to grab from napari are the main window, or the `QtViewer`.  For example:
```python
import napari

viewer = napari.Viewer()
main_window = viewer.window._qt_window
qt_viewer = viewer.window.qt_viewer
assert isinstance(qt_viewer, QWidget)  # True
assert isinstance(main_window, QWidget)  # True
```

Alternatively, since napari is also a full Qt application, you might wish to put mpl plots inside of napari itself.

```python
import napari
import numpy as np
from matplotlib.backends.backend_qt5agg import FigureCanvas
from matplotlib.figure import Figure


with napari.gui_qt():
    mpl_widget = FigureCanvas(Figure(figsize=(5, 3)))
    static_ax = mpl_widget.figure.subplots()
    t = np.linspace(0, 10, 501)
    static_ax.plot(t, np.tan(t), ".")

    viewer = napari.Viewer()
    viewer.window.add_dock_widget(mpl_widget)
```

see also: https://matplotlib.org/3.2.1/gallery/user_interfaces/embedding_in_qt_sgskip.html
https://stackoverflow.com/questions/12459811/how-to-embed-matplotlib-in-pyqt-for-dummies

**Comment by dstabley** [comment]
@tlambert03 that worked wonderfully, thanks!

**Comment by tlambert03** [comment]
not sure which one you used there... but if it was the latter, I'll just add that support for _some_ sort of plotting infrastructure inside of napari is definitely a very high priority (see #675 #823 and linked discussions), though exactly how it will be implemented is still unclear.  I'll let you close this issue if it's been addressed for you, or follow up with additional questions...

**Comment by sofroniewn** [comment]
Sounds like this is being well taken care of, but #1005 might be of interest too as it talks about matplotlib widgets in napari too

**Comment by dstabley** [comment]
@sofroniewn @tlambert03 I just needed to embed a Napari viewer for this project and it worked really well, though plotting would be really nice. For now if I need to do that I would probably make a QT subwindow with Matplotlib plots. Updating to close this as I forgot to do this previously. Thanks again!
