### ISSUE TITLE
considering down-converting float64 to float32 when saving?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1184]
## ❓ Question

Should we consider making the builtin `napari_write_image` implementation default converting 64 bit float to 32 bit float?  I wonder how many people are going to save a tiff from napari and run into an error when they try to open it in Fiji...

Of course, we need to somehow open up control to users... but just wanted to flag that potential near-term issue.

**Comment by jni** [comment]
Wait Fiji can't open a 64-bit float tiff?? Is 64-bit not generally supported or is this a Fiji quirk?

**Comment by tlambert03** [comment]
That's a good question actually... I just kinda assumed it can't, cause I've never been able to get a float64 written by tifffile to read (see screenshot)... but maybe that's just tifffile or maybe I'm doing something wrong.  @ctrueden?

<img width="258" alt="Screen Shot 2020-04-29 at 10 18 33 PM" src="https://user-images.githubusercontent.com/1609449/80665414-70fb3f80-8a67-11ea-9ca9-eeb3f02f1825.png">

**Comment by jni** [comment]
@cgohlke might also have some ideas about this...

**Comment by cgohlke** [comment]
You should be able to import the 64-bit float TIFF into Fiji using Bio-Formats.

**Comment by tlambert03** [comment]
a ha, yes indeed! see i _was_ doing something wrong! :)

**Comment by ctrueden** [comment]
The problem is that ImageJ1 does not support 64-bit floating point images. Only ImageJ2/ImgLib2 supports that. Bio-Formats can open them but it must ultimately downcast it to 32-bit (because the Bio-Formats Importer is still built on ImageJ1). If you use File > Import > Image... to invoke SCIFIO, you should get a true 64-bit floating point image. But displaying it in the legacy ImageJ UI (the default Fiji uses), it'll still say "32-bit" in the title bar because it has to lazily downcast it to 32-bit to make ImageJ1 happy.

The good news is that if you use PyImageJ and write e.g. `img = ij.io().open(my64bitTIFFfile)` you should get back a 64-bit `Dataset` object, which can be turned into a numpy (soon to be xarray) object using `ij.py.from_java(img)`. Let me know if that doesn't work!

Sorry the situation is so complicated, guys. :-(
