### ISSUE TITLE
pydata.org link in BENCHMARKS.md is 404

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1198]
## 📚 Documentation

In the first paragraph of:
https://github.com/napari/napari/blob/master/docs/developers/BENCHMARKS.md

We link to:
https://pandas.pydata.org/speed/napari/

And that's a 404 now.

Looks like there's no longer a napari page here:
https://pandas.pydata.org/speed/

**Comment by sofroniewn** [comment]
I think that line actually never existed :-( the "guide" was copied from scikit-image that does have a page up there.

Right now our benchmarks have been more one-off things we've run, rather than something we've tracked. If we do start tracking more closely we can decide if we want to have those records hosted there or somewhere else. Until then we should probably just drop that sentence and link. Thanks for catching and flagging!!

**Comment by NicolasCARPi** [comment]
Shouldn't this issue be closed now that the change has been merged to master?

**Comment by sofroniewn** [comment]
> Shouldn't this issue be closed now that the change has been merged to master?

Correct, thanks for the catch!! This was closed by #1236
