### ISSUE TITLE
channel_axis splits but layers.save doesn't merge

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1199]
## 🐛 Bug/Feature

Something to address in the future:  many readers will probably split multichannel tiffs into different layers in the viewer, but our builtin `get_writer` function doesn't yet know how to merge them again.

**Comment by sofroniewn** [comment]
Once we have #1103 implemented this will become easier

**Comment by psobolewskiPhD** [comment]
Bumping this.
If one opens an RGB layer, one can split it to the 3 channels.
It does not appear possible to reverse this -- merge to stack gives a stack of 3 channels, but that does not save as an RGB image when saved to PNG.
Would be nice to have a way to merge to RGB or convert to RGB.

**Comment by psobolewskiPhD** [comment]
So I'm thinking how to solve this...
1. Select 3 layers -> new contextual menu > merge to RGB -- there are enablements to make this work (same shape) and there is a stack_util `merge_rgb` already, but it is currently broken.
https://github.com/napari/napari/blob/c73e9d5ec0864cc9fa727cf7b147ccdab39a03/napari/layers/utils/stack_utils.py#L301

2. Select 3 layers -> existing contextual menu > Merge to Stack; new contextual menu > Convert Stack to RGB -- there are enablements to make this work, it's easier to implement.

3. Both

Both is probably the answer, because the other two options require either a split or a merge depending whether you have 3 layers or C-stack data. If not both I kinda lean to option 2, because I feel like it's the more common case, but option 1 would be the inverse of the existing Split RGB, so there is some symmetry there.

@lucyleeow @DragaDoncila any thoughts?

**Comment by DragaDoncila** [comment]
Hmm I'm leaning towards option 1 tbh. I think having `Merge to Stack` and `Merge to RGB` as options makes a lot of sense. And yes I agree ideally we'd also have a `Convert to RGB` for an already merged stack

**Comment by psobolewskiPhD** [comment]
@DragaDoncila 
Yeah, I agree, I think `Merge as RGB` is more intuitive as the inverse of `Split RGB`.
**But** in all of this, the order of the channels matters to get RGB back -- obviously.
When we do `Split RGB`, the layer list ends up `B G R`.  Then, the when doing `images_to_stack` it takes care of reversing this back. Thus, `merge_rgb` inherits this behavior, so when fixed, it would make RGB images from a `B G R` layer list, meaning `Split RGB` and `Merge RGB` would be reversible operations. 🎉 
**But** what if people have their own 3 layers? my intuition would be to have them `R G B` order, which would of course make this backwards. 

Meanwhile, I think it's reasonable to expect that if you have a (3, y, x) image the order of the 3 to get RGB would have to be `R G B` -- no reversal shenanigans needed.
But is `Merge to Stack` obvious enough as being a precursor to `Convert to RGB`? To me it is, but....

**Comment by DragaDoncila** [comment]
Ohhhhhk so @psobolewskiPhD you have given way more thought to this than I had 😆 . I will ask some questions and make some comments, but I have no solutions for you right now.

> When we do Split RGB, the layer list ends up B G R. Then, the when doing images_to_stack it takes care of reversing this back

Ok so if I have three layers B G R (going down the layerlist), I click `Merge as RGB` and my resulting stack has final dimension of length 3 and those elements are in order (r, g, b)? 

Why do we end up with B G R in the layerlist? Is this necessary? Is it expected? Is it just because we return the layers one by one? I would lean towards doing the reversal before we even add the layers, such that we end up with R G B going down the layerlist.

> what if people have their own 3 layers? my intuition would be to have them R G B order, which would of course make this backwards.

If we do the reversal when we split, then the `images_to_stack` function wouldn't need to do any reversing, and that would take care of this right?

> Meanwhile, I think it's reasonable to expect that if you have a (3, y, x) image the order of the 3 to get RGB would have to be R G B -- no reversal shenanigans needed.

Agreed here

> But is Merge to Stack obvious enough as being a precursor to Convert to RGB? To me it is, but....

Does this matter, if we directly have a `merge as rgb` option?

Also wanna say generally I think if I have layers A B C going down the layer list, I expect merge to stack to give me a stack ABC not CBA.

**Comment by psobolewskiPhD** [comment]
We talked about this at the Pac meeting and the idea was to have the user colormap the layers and go with that as the source of truth instead of layer order.
`Convert` moving from left-most to right-most seems like it would cover 90% of cases?

**Comment by psobolewskiPhD** [comment]
@DragaDoncila 
This layer action:
https://github.com/napari/napari/blob/baaf01dadcdef62bdb9a14e8a1df4ca974c84a49/napari/layers/_layer_actions.py#L105
has always had the `rgb` kwarg, but it's not been used and the `stack_utils.merge_rgb()` has been broken (also private)
Is it best to:
1.  keep the kwarg and implement the logic on color maps in `_merge_stack` (implemented, e.g. as some set comparisons with a warning if they don't match)
2. drop the kwarg and have a `_merge_stack` and `_merge_rgb` as separate actions, which seems simpler?

**Comment by DragaDoncila** [comment]
I think it's fine to keep the kwarg and fix it! Note that the same callback with different kwargs can be attached to multiple actions, we just define a new enclosing function.

Was there some other reason you think having them separate seems simpler?
