### ISSUE TITLE
Inconsistency in ordering of layers visually and in the actual list object

### ISSUE THREAD

**Issue by kne42** [napari/napari#122]
## ❓ Questions and Help

So I noticed something today that confused me a lot regarding how things in the `LayersList` are ordered.

It's easiest to provide an example – say your layers list is ordered like so: `[astronaut, camera, spots]`. On screen, the list is ordered like so:
```
spots
camera
astronaut
```
and the `spots` layer is displayed at the top of the stack.

I find this confusing since I would expect `astronaut` to appear at the top of the list and `spots` at the bottom.

So I wanted to get everyone's opinion on what ordering would make the most sense:
- should the ordering match?
- should new layers get appended or inserted to the list?
- should the topmost or the bottommost layer be displayed at the top of the stack?

**Comment by sofroniewn** [comment]
This was extensively discussed in #565 and we eventually decided it is more intuitive to have the most visible, and most recently added list on top in the viewer, even though it is the reverse order from the code. Hopefully people will be indexing into the layers list using the layer name rather than the index so it won't be too confusing
