### ISSUE TITLE
Inconsistent colormap usage between Image and Labels layers

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1245]
## 🐛 Bug

When set colormap to instance of `Labels` resulted labeling has different order than number order of colors in used colormap. 
If use `Image` layer instead of `Labels` then colors order agree with label numbers  
## To Reproduce

1. Create labeling
2. Add it with add_label and add_image
3. Overwrtte with same colormap 
4. See different labelling colors

(here my code to create colormap https://github.com/4DNucleome/PartSeg/blob/f8772b5f2d3d84bba6d0a7a4fba77bb7e5746517/package/PartSeg/common_gui/napari_image_view.py#L167

## Expected behavior

Ability to control label colors still using `Labels` layer

## Environment
vispy 0.6.4
napari 0.3.0

 - Any other relevant information:
napari as embedded viewer

**Comment by jni** [comment]
@Czaki this is by design, since labels are supposed to be arbitrary orderings. ie it's meant to be a feature, not a bug. :joy: 

Having said that, I can definitely see how in the case of a small number of labels, you would want to control the label -> colour mapping directly. Indeed this is reminiscent of #1214. Let's see what we can do here to allow that while still preserving the random mapping for those that just want contrast in their segmentation view. Thanks for pointing this out!

**Comment by sofroniewn** [comment]
This is also related to #716 where we've called out a feature request for letting the labels layer take a list of custom colors. Would that functionality meet your needs @Czaki?

**Comment by Czaki** [comment]
@sofroniewn Partially yes. But I need to change it without recreation of `Labels` instance. Like:
```
label.colormap = new_colormap
```

**Comment by psobolewskiPhD** [comment]
with all the Labels and colormap changes in 0.4.19, is this still relevant @Czaki @jni ?

**Comment by Czaki** [comment]
It is fixed even earlier
