### ISSUE TITLE
Allow marker size and color control in the annotation mode

### ISSUE THREAD

**Issue by jni** [napari/napari#125]
## 🚀 Feature
Probably we want to allow marker size and marker color control in annotation mode somehow... It feels a bit broken that marker sizes can be specified on the command line but not in the GUI.

Having said that implementation here is hard so this can wait. I guess we would need a size slider, that can optionally expand into a multidimensional size slider (ie one slider per dimension), and a color picker (this latter one probably already exists in Qt?).

**Comment by sofroniewn** [comment]
@jni to be clear you can control size and color of ALL the markers from the properties widget in the layer list (double click to expand) and you will see a size slider and color drop-down. (We might want to add a sandwhich icon to make it clear that those boxes are expandable because I've been getting feedback that it is not intuitive)

The thing you cannot to is adjust the different dimension sizes independently or adjust different marker sizes independently. For that we'd need some concept of selected markers that we don't quite have yet and I'm unsure how best to do it from a GUI standpoint. A lot of those similar issues are coming up with the in-progress work on the shapes layer #100 and we can think about how to address them in both cases.

Right now it is not possible to assign different colors to different markers when they are in the same layer or assign a scalar and colormap to the markers. This is because of how vispy creates a markers visual and it could be possible to fix, but would require changes at the vispy level. In the shapes layers in #100 this sort of behavior is possible because we use mesh visuals from vispy instead that give us extra flexibility. It is unclear though if we will ultimately want to switch the markers visual to mesh visuals, drop the markers layer entirely in favour of the shapes layer, and adapt the markers visual to support multicolor. I'm not sure about the relative performance tradeoffs of the markers vs mesh visuals but it could be something that would become significant when rendering 1M markers, which could happen

**Comment by sofroniewn** [comment]
Oh also we havn't implemented any color pickers anywhere yet, but yes Qt provides a color picker / color dialog widget - https://doc.qt.io/qt-5/qcolordialog.html

**Comment by sofroniewn** [comment]
Points (markers) can now be resized and recolored individually - this has been implemented in #371
