### ISSUE TITLE
Show path of file(s) that napari is currently viewing

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1251]
## 🚀 Feature
Somewhere in the UI it should show the filename/path of the file(s) that are currently loaded.

## Motivation

As a user I might have many datasets that look similar. It's easy to forget which dataset(s) are currently loaded in napari. I'd like to be able to see which dataset(s) are loaded.

## Additional context

Probably should show the full path? It should work with remote files:
`napari https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/4495402.zarr`
I probably want to see that full path and not just `4495402.zarr`?

This is how it looks in photoshop. They don't show the path:

<img width="661" alt="filename-photoshop" src="https://user-images.githubusercontent.com/4163446/81958952-be85b980-95dc-11ea-8a72-570fdb0e9aaa.png">

**Comment by kevinyamauchi** [comment]
I think this is a great idea! I am a little concerned that full paths might get unwieldy. What if we give the filename and then the full path is the tooltip? Or maybe it switches between the full path and the filename + full path tooltip modes based on the length of the full filepath?

**Comment by tlambert03** [comment]
Yeah, I'm not sure we want the filename for the layer itself (That was more or less re-added in #1232)... I'm assuming this would be maybe in the help message at the bottom left?   Perhaps adding `viewer.help = layer.path` to the `ViewerModel._update_active_layer` method?

**Comment by tlambert03** [comment]
copying this possible approach from zulip:
maybe a `self.path` attribute on the base Layer that defaults to `None`, and then add `new.path = filename` at around line 876 in `napari.components.add_layers_mixin`?

(also have to check whether new is a list or not)

**Comment by psobolewskiPhD** [comment]
Presently, napari does provide the filename, but not path, when hovering the data—but, ironically enough, not while mousing through the layer in the layer list:
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/c9d6952e-ac65-4f2b-84b5-6c40ff3b2097">

**Comment by joaomamede** [comment]
with the builtin napari opener it has it in: 
viewer.layers[0]._source

I believe that with napari-aicsimageio it also has it, so it must be independent of the plugin.

**Comment by thanushipeiris** [comment]
For anyone looking this is now available in napari.layers.Layer.source.path e.g. `viewer.layers[0].source.path`

**Comment by rjlopez2** [comment]
I have a custom made plugin, and when I call an image loaded with my pluging with this method it returns nothing:
```
original_img.source

Source(path=None, reader_plugin=None, sample=None, widget=None, parent=None)
```
How do I normally implement this information in my reader?

here is the _reader file of my plugin
[link](https://github.com/rjlopez2/napari-sif-reader/blob/main/src/napari_sif_reader/_reader.py)

best regards

**Comment by jni** [comment]
Hmm, that's weird. Seems like a bug. Could you open a new issue @rjlopez2? And include a sample file that we can test with your reader? 🙏

**Comment by rjlopez2** [comment]
Thanks for replying @jni.
I found out what the problem could be (or at least a work around).
It turns out that my reader take as a source not a single file but a folder containing a number of 2d binary images, which output ultimately, a numpy time stack array.
I worked around with this by explicitly taking the original folder path to my reader and add it to the metadata.

**Comment by rjlopez2** [comment]
BTW, what I meant by binary images is not two (F/T) values images but binary *\*files\** with information about the actual image.

For our reader, I am still need to implement the drag and drop functionality, before I check in more detail how to deal with this, since our reader requires multiples files format to be present in the source folder. You can see a bit more about the library I am using to read this types of files with the `sif_parser.np_spool_open()` method [here](https://github.com/rjlopez2/sif_parser/tree/multithreading_np_spool_open?tab=readme-ov-file#sif_parsernp_spool_openpathtospool_files) .

Yet, it would be interesting to learn how to gather this info in the reader when loading folders containing multiples files extensions/etc. 

I will rise an issue at the time I face the problem, but for the time being it is ok.

**Comment by jni** [comment]
> For our reader, I am still need to implement the drag and drop functionality, before I check in more detail how to deal with this, since our reader requires multiples files format to be present in the source folder.

typically what we recommend in these situations is to point to one of the files, in this case, the .sifx file. Alternatively, use `accepts_directories: true` for the reader as done [here](https://github.com/napari/napari/blob/bf157e37685228609956168d8a71166ad40e874a/napari_builtins/builtins.yaml#L132), which is how we read .zarr files.

**Comment by rjlopez2** [comment]
> Typically what we recommend in these situations is to point to one of the files, in this case, the .sifx file. 

That's exactly in the direction I was thinking to proceed on, since that's the file containing the header information of the acquisition, and other metadata information.

About the `accepts_directories: true` trick I knew there was such option but not sure where to located it 😅

thanks for the tips 👍🏾

and also thanks for the enormous contribution you guys are doing to the community with this piece of software.

**Comment by DragaDoncila** [comment]
> About the accepts_directories: true trick I knew there was such option but not sure where to located it 😅

Just in case other people get here, you can find all the reader options in the [contributions reference](https://napari.org/stable/plugins/contributions.html#contributions-readers), and some more discussion on using them in the [contributions guide](https://napari.org/stable/plugins/guides.html#readers)!
