### ISSUE TITLE
Hookspecs for layer keybindings

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1272]
## 🚀 Feature
Plugin developers are beginning to use our reader/ writer hookspecs with success, but are looking to add additional functionality like custom key bindings, mouse functions, or GUI elements (see https://github.com/hci-unihd/covid-if-annotations/issues/3).

I propose that the next hookspecs we add are for our key bindings for our layers. We can then grow to other hookspecs after.

## Motivation

I think we should continue with our functional approach, and our approach of not providing "napari" objects to plugins but instead providing things like layer data tuples, e.g. (data, meta, layer_type). The advantage of this approach is that it enforces a "loose coupling" with napari, our plugins can't just do anything like nuke the whole viewer or layer, and it gives us a lot of control over what a plugin does as napari calls the plugin code. The downsides are some reductions in flexibility, and potentially performance, but I think they are well worth it, if they are even really there.

## Pitch

It's unclear if hookspecs are the natural thing for what I have in mind, but I think each plugin should be able to provide one dictionary per layer type. The keys of that dictionary need to valid key press combinations for napari, and the values of that dictionary need to be functions with the following signature:

```python
image_key_bindings_func(data: Any, meta: dict) -> (Any, dict)
```

Note that this is different from the API of our current keybindings functions which take in a layer and can then do anything. We could keep that API around or eventually deprecate it for this one.

How these keybindings would work is that when the key was pressed we'd generate the (data, meta) tuple pass those to the function, and then get back a (new_data, new_meta) tuple. If new_data is not None we'd set `layer.data=new_data`, and then we'd go through every element of `new_meta` and update the layer property accordingly. This is a massive reduction in what keybindings can do, but I think it will actually make them much easier to understand and make this whole system more robust.

One question would be do we "copy" the data when we pass it to the keybindings function, I'm not sure if we'd want to do that as it might trigger some big delays, but it might make the whole system much more "safe" as no in place modifications would be possible.

Curious what do @jni @tlambert03 @kne42 think of this approach? and how to best integrate it with the napari_plugin_engine? We could add a special "hookspec" where people are able to provide dictionaries instead of functions.

An interesting exercise would be how many of our current layer keybindings could be rewritten to conform to this API? Unfortunately not all of them as we have keybindings do things like change `mode` (like `painting`/ `pan_zoom`) amongst other things, which aren't inside our `meta` dict, but maybe we could figure out how to fix that.

**Comment by sofroniewn** [comment]
Two quick additional thoughts

1) We'll need to leverage UI elements to make it easy to turn on/ turn off a plugins keybindings, and we wouldn't them all on by default. This probably relates to discussion in #1238

2) We'll also probably want execution of this keybinding code to be non-blocking (could relate to #845 or multithreading #1210), curious how to best think about this @tlambert03 @pwinston

**Comment by tlambert03** [comment]
Love the goal... I agree it makes a natural "next hookspec".
Not a big fan of the signature/approach however.  Happy to be overruled by general consensus here, but I think it adds a lot more complication than is necessary, restricts functionality without making things _that_ much safer, and has definite performance implications...

With the IO plugins, I think it made a lot of sense to pass `LayerData` tuples instead of napari objects: in that case the concept of "taking a path and returning some data" lent itself very well to a non-napari-centric implementation, which I _do_ think we should strive for whenever it makes sense.  In other words, I can definitely imagine developer efforts being reusable there.
But the concept of a keybinding is extremely application specific, and I find it hard to imagine these being reused outside of napari.  In light of that, the proposal here of converting a layer to pure python types, passing those to the plugin, receiving new python objects, diffing with the existing layer, then updating where necessary seems to be unnecessarily complicated, restrictive, and computationally heavy.

I see this option as very much like the [`pytest_addoption`](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_addoption) hookspec from pytest, in which they allow plugins to add new arguments to their command line argparser.  (This is, for instance, what [lets `pytest-cov` add the `--cov` option](https://github.com/pytest-dev/pytest-cov/blob/c5623ec7589051399a092f7e8d4d3de287aace96/src/pytest_cov/plugin.py#L66-L102) when calling pytest).  In that case, they pass the actual `argparse.parser` object to plugins and let them modify it.

For our keybindings hooks, I would have proposed something like this (mostly full working example)

```python
# napari/plugins/hook_specifications.py

from typing import Callable, Literal, Sequence, Tuple, Union

KeymapProvider = Literal[
    "viewer",
    "layer",
    "image",
    "labels",
    "points",
    "shapes",
    "surface",
    "vectors",
]

# https://pluggy.readthedocs.io/en/latest/index.html#historic-hooks
@napari_hook_specification(historic=True)
def napari_add_keybinding() -> Sequence[
    Tuple[KeymapProvider, str, Callable[[Union[Viewer, Layer]], None]]
]:
    """Return a list of tuples: (keymap_provider_name, key_combo, function).
    
    where the function accepts a single Layer/Viewer
    """
```

and then register that hookspec with call_historic in `napari.plugins.__init__`:
(call historic means that the implementation will be called once immediately on registration, regardless of whether it is registered before or after the hook specification)

```python
# napari/plugins/__init__.py

def register_keybinding(result):
    for binding in result:
        provider, key, function = binding
        if provider == 'viewer':
            provider = napari.viewer.Viewer
        else:
            provider = getattr(napari.layers, provider.title())
        # hook up the keybinding here!
        provider.bind_key(key)(function)

# ... after plugin_manager creation:

plugin_manager.hook.napari_add_keybinding.call_historic(
    result_callback=register_keybinding
)
```

Finally, an implementation on the plugin side looks like this:
```python
def activate_picker_mode(layer):
    """Activate the label picker."""
    layer.mode = 'pick'

@napari_hook_implementation
def napari_add_keybinding():
    return [('labels', 'L', activate_picker_mode)]
```
... and if you really wanted to be concise, you could replace most of our `_labels_key_bindings` file with one liners like this (due to using an `@mode.setter` on  `Labels`)
```python
@napari_hook_implementation
def napari_add_keybinding():
    pairs = (('P', 'paint'), ('F', 'fill'), ('Z', 'pan_zoom'), ('L', 'pick'))
    return [
        ('labels', key, lambda layer: layer.__class__.mode.fset(layer, mode))
        for key, mode in pairs
    ]
```

Lastly, if we went with this idea, I think it would be a good idea to modify the `class_keymap` [here](https://github.com/napari/napari/blob/master/napari/utils/key_bindings.py#L316) and the `instance.keymap` [here](https://github.com/napari/napari/blob/master/napari/utils/key_bindings.py#L309) into modified `dicts` that [prevent key overwrite](https://stackoverflow.com/questions/30241688/overriding-dict-update-method-in-subclass-to-prevent-overwriting-dict-keys) (or do something interesting when there is a key-combo clash).  That's probably also where I would look to put the logic that enables/disables keybindings for certain plugins.

**Comment by sofroniewn** [comment]
> Lastly, if we went with this idea, I think it would be a good idea to modify the class_keymap here and the instance.keymap here into modified dicts that prevent key overwrite (or do something interesting when there is a key-combo clash). That's probably also where I would look to put the logic that enables/disables keybindings for certain plugins.

This seems like something we'll probably want regardless, in some senses it's like adding "namespaces" to our keybindings. Worth noting for @kne42.

For the `mode` issue that I mention we can always add a kwarg to the `_get_state` to return a `full` state dictionary with more variables, in which case using the approach I proposed a few example keybindings become

```python
def activate_picker_mode(data, meta):
    """Activate the label picker."""
   return (None, {'mode': 'pick'})

def new_label(data, meta):
    """Set the currently selected label to the largest used label plus one."""
    return (None, {'selected_label': data.max() + 1})

@napari_hook_implementation
def napari_labels_key_bindings():
    return {'L': activate_picker_mode,
            'M': new_label}
```

Agree the `undo` and `pan_zoom` keybindings are harder to put in this framework, but I really do worry that the approach of passing the full napari layer will lead to all sorts of complicated behavior. It's much harder for me to think about how to make that asynchronous too, and what to do if someone kicks of multiple asynchronous processes at the same time. Using the approach I describe above, especially if we did copies of data, you could interrupt execution of a key binding function and everything would be fine, nothing would be changed. We probably want to be judicious with coping data, but an architecture like this could also pave the way for more complex protocols where the compute was running elsewhere and very async.

I think its also worth considering what the rest of the plugin architecture looks like, as I'd like us to strive for consistency across it. I do think for a long time we've said that we want "functional plugins" that don't have a knowledge of napari objects, and I could imagine reusing function signatures of our layer data tuples with magicgui, mouse functions, etc.

Curious what @royerloic @jni think about all this

**Comment by tlambert03** [comment]
> a few example keybindings become

What I'd really want to see for your example keybindings are not the implementations, but rather how you would implement the equivalent of my `register_keybinding` above (i.e. what exactly do you plan to do with those returns). That's where I think the conversion to and from types is going to be more trouble in terms of complexity and performance than it's worth.  and I guess regarding "worth" here, I'm still struggling to see exactly what we're gaining.  This might be related to my perspective on "consenting adults" that we've discussed before.  Jumping through hoops to prevent plugins from doing certain things, in python at least, still doesn't prevent them from doing those things... At the end of the day, plugins can still misbehave, and users can still uninstall them. 

I can _concieve_ of a day when we might say "ok... this is getting abused, we need to lock it down and implement complicated logic to interrupt execution, etc..."  But the flip side to doing that is having _our_ internal checking logic get so complicated that people's plugins don't work as expected, and perhaps mysterious/frustrating behavior resulting...

> what to do if someone kicks off multiple asynchronous processes at the same time

I wonder if there too maybe we're preparing for something that will never happen?  It's perhaps important to remember that, while we can offload I/O operations to other threads, and computation to other processes, we still can't really get around the fact that the main event loop (the one that has to handle those key press events) is single threaded with an event queue.  so I'm not really sure we ever _do_ make keypress events asynchronous?  even if they trigger some concurrent processing, they always have to come back to the main thread to be handled.  (and additionally, how does the conversion to and from standard python types help with asynchronicity?)

> I'd like us to strive for consistency across it. I do think for a long time we've said that we want "functional plugins" that don't have a knowledge of napari objects

absolutely, I still think that pattern makes sense for functional plugins.  I _like_ the layer-data tuples!  and I agree we should strive for consistency ... but I think each case has its nuances, and this one feels a bit forced to me (kinda like we're doing it because we did it before, less because it makes sense in this specific use case).  

just my opinions though!  as always: happy to yield to consensus!

**Comment by sofroniewn** [comment]
> What I'd really want to see for your example keybindings are not the implementations, but rather how you would implement the equivalent of my register_keybinding above (i.e. what exactly do you plan to do with those returns).

Stepping aside for the plugin functionality, and thinking just about what it would look like if we switched over to use the new API internally for our keybindings then, where right now we currently pass the layer straight to the function after a key press:

```python
my_func(layer)
```

now we'd have to do more, including generate the layer data tuple, and then update the layer attributes, I imagine at it's simplest it would be as follows:

```python
layer_data = layer.as_layer_data_tuple(full=True)

new_data, new_meta = my_func(layer_data[0], layer_data[1])

if new_data is not None:
  layer.data = new_data
for key, value in new_meta.items():
  if hasattr(layer, key):
    setattr(layer, key, value)
  else:
    print(f'Warning {key} attribute not found on layer')
```

I've added a `full=True` to allow for adding more properties to our meta dictionary then we currently just use for saving.

As to comments around async/ safety etc, my thoughts are that we could now be much more flexible with how we run the line
```python
new_data, new_meta = my_func(layer_data[0], layer_data[1])
```
as we know it won't actually be updating our layer. I'm imaging that we could be in napari, kick one of these `my_func` computations off in a new thread that might take 5 minutes, keep using napari, and then maybe even get a dialog saying "your processing is done now, would you still like to update your data" (potentially allowing you to "create a new layer with the new results" instead of just "updating in place")

**Comment by sofroniewn** [comment]
I should add, I'm also happy to be pointed out that I'm wildly and needlessly over-complicating things here too 🤣 

I appreciate the discussion though and entertaining the idea!! 😄

**Comment by tlambert03** [comment]
and I'll add that I'm definitely not totally opposed to the pattern you just proposed there :smile:

I certainly agree there are code safety concerns, and it would be nice to be able to prevent something like this:
```python
@napari_hook_implementation
def napari_add_keybinding():
    return [('labels', 'Space', lambda layer: del layer)]
```
at the same time, there'a a good percentage of our current keybindings that we wouldn't be able to implement with this pattern.

which gets me thinking, what about a proxy object?  Something that behaves very much like the original object API, passing through "approved" methods and attributes, but preventing things like deletion, or any other unapproved methods...

**Comment by jni** [comment]
I have to say I fall quite firmly on @tlambert03's side here, perhaps even more extreme: I totally *want* plugins to be able to bind "delete this layer" as a keybinding! We've already had users who have dozens of layers going at a time. I can definitely envision someone wanting to create and delete layers willy-nilly.

Always copying data sounds massively limiting in the case of even medium-sized data. Things like proofreading into a zarr-backed array become hard, maybe impossible?

Even the things that work well with this sound *painful*. I'm sure there's a lot of possibilities within this data/meta framework, but it just feels hamstrung. I wouldn't find this kind of API enticing, even with my functional-programming bent. It kind of reminds me of the first iPhone API which only let you make web-apps. It was less than a year before Apple had to admit that native apps were the way to go. I think this would be a similar story in fast forward.

I know that we have to figure out a way to make plugins play well together. But I don't think banning play altogether is the right way to do that. 😂 

@tlambert03 the API you proposed in [your first comment](https://github.com/napari/napari/issues/1272#issuecomment-633064212) I really like.

**Comment by sofroniewn** [comment]
> I totally want plugins to be able to bind "delete this layer" as a keybinding! We've already had users who have dozens of layers going at a time. I can definitely envision someone wanting to create and delete layers willy-nilly.

Any keybinding that was creating layers would need to be bound to the viewer, not an individual layer right now - so I don't really see this type of keybinding as being relevant for this discussion which is about keybindings on individual layers. Our current system doesn't allow for a self destruct keybinding like @tlambert03 mentioned to work properly anyway right now and I don't think we should change it so it does (at least `del layer` doesn't work for me). For viewer keybindings we'd definitely want the ability to create and destroy layers, and I can imagine implementations that allow this that either pass napari objects or don't.

> Always copying data sounds massively limiting in the case of even medium-sized data. Things like proofreading into a zarr-backed array become hard, maybe impossible?

I'll note that the approach that I'm proposing does not require copying data, it just becomes an option if we want to.

> Even the things that work well with this sound painful. I'm sure there's a lot of possibilities within this data/meta framework, but it just feels hamstrung. I wouldn't find this kind of API enticing, even with my functional-programming bent. 

Is there an alternative API that does not involve passing the entire napari object to the function that you would find more appealing? Maybe a proxy object that @tlambert03 mentions https://github.com/napari/napari/issues/1272#issuecomment-633118835.

Alternatively, maybe we do pass the napari layer, but then I'd like us to try and pull out everything that we don't want a plugin developer to have that is on our layer and put it elsewhere - for example some of the slicing stuff - because our layers are already very big.

Stepping back, I think for our plugin interface we have a very fundamental choice to make, do we pass around napari model objects and expect our plugin developers to go inside of them to get access to what they need, and change anything they want in-place, or do we pass around pure Python objects and get back pure Python objects and make the updates ourselves? I feel like mixing the APIs is unnecessarily confusing.

I really feel like for > 1 year we've been saying that our plugin interface would be functional and based on pure Python, and we started down this road with readers and writers, so it is surprising now to hear that @jni want's a different approach.

I guess I'm also trying to prioritize robustness, scalability, stability, and longevity for our plugin interface over "willy-nilly" because otherwise I don't think we're any different from just being a library that people can build whatever they want on top of it and there is no need to even have a "plugin-interface" at all. For people like that, they can always use napari to build their own standalone applications, but there have to be some guide rails in place if we're imaging an ecosystem of 100s of plugins that can be used interoperably.

@royerloic what is your perspective on this? As I said above, I'm still open to all the options, but I do want us to consider some of the things I'm trying to prioritize and figure out if there is a way we can achieve them while keeping a simple and intuitive API and high performance.

**Comment by sofroniewn** [comment]
I'd also appreciate any insights from @pwinston or @ttung here on what it would take for our plugin code to be executed asynchronously/ non-blocking and any design choices that might make the more feasible, as it might be really important in the long run.

**Comment by ttung** [comment]
I agree with lots of ideas that have been stated.  Due to an abundance of laziness, I won't attribute the idea to the original author (sorry!), but here's my random thoughts:

1. It would seem like keybindings are specific enough to the application that it is necessary to pass in napari-specific objects to the plugin.  The idea of proxy objects is interesting, as it significantly reduces the exposed surface and gives us something like a fixed API that we can maintain.  However, nothing really stops the plugin developer from `import napari` and going to town.  If you want a constrained plugin interface with good isolation, python is probably the wrong language[1].
1. We need to make data futures a first class concept in Napari.  It is absolutely required for managing large data sets.  It might even be prudent to force all plugins to use data futures, even if napari internals isn't ready for it.
1. Making the plugin interface use keyword-only arguments allows for much flexibility for API changes.  On the other hand, if such flexibility is not desired, then please disregard this point.
1. Meta-question: Why are plugins making keybindings?  I can't think of any plugins that set keybindings, and even if they are making keybindings, I would imagine that they ought to be doing it on an optional basis, and through an existing config interface.  "Thanks for installing Plugin XYZ™.  Would you like to add the default keybindings?" -> [Yes/No] -> "The default keybindings for Plugin XYZ™ conflict with your existing keybindings." -> [Don't set keybindings/Override keybindings/Review keybindings].

[1] It would be super fascinating to explore a plugin interface based on python multiprocessing + shared memory, as that **would** deliver the constrained plugin interface with good isolation.

**Comment by jni** [comment]
@sofroniewn 

> Any keybinding that was creating layers would need to be bound to the viewer, not an individual layer right now

Yeah, that's why I like @tlambert03's proposal of KeyMapProviders.

> I'll note that the approach that I'm proposing does not require copying data, it just becomes an option if we want to.

Ah, sorry, I misread that.

> then I'd like us to try and pull out everything that we don't want a plugin developer to have that is on our layer

Yes, and this is good practice anyway. As we discussed briefly on Zulip and I've mentioned in other PRs, I want to start thinking about slimming down the public API of our objects. The way I explore new libraries is to make an object or import a module then do `obj.<tab>` and see what's there. In cases with a big legacy API like matplotlib or numpy, this is impossible or very painful. Let's try to avoid that.

> I really feel like for > 1 year we've been saying that our plugin interface would be functional and based on pure Python, and we started down this road with readers and writers, so it is surprising now to hear that @jni want's a different approach.

I think this is 100% true for me for *functional* plugins, meaning plugins that trigger some computation on an input and produce an output. But in that case, I want napari to provide access to normal Python libraries and handle all the IO. That is, in that case, there *is* no plugin interface: we are the ones to add libraries, and library authors have zero concept of napari or even napari_plugin_engine. They go about their business and napari provides a way for users to call Python code on their napari objects. The really good thing about that is that then recording processing steps becomes the same thing as writing Python scripts, and that's extremely powerful.

When it comes to things that *interact* with napari, that's a different story, and I admit don't have a clear idea of where we want to end up. BUT, it should be somewhere pretty and fun. =D

> otherwise I don't think we're any different from just being a library that people can build whatever they want on top of it and there is no need to even have a "plugin-interface" at all. For people like that, they can always use napari to build their own standalone applications,

There's a balance, though: we also don't want everyone to feel that the best way forward is to build standalone applications based on napari. That's one form of success for sure, but we want to provide people with an API that gives them ability to easily do what they want to do. To continue with the guide rails analogy, yes, we want some, but we need to make sure they are not guides to nowhere. Otherwise people will not get on the ride at all.

One thing that's super important is that we want to be able to record every action a plugin makes on our models. For that, I think #1040 will be critical, and maybe that's a guide: our API for keybindings is that plugins should be able to bind a key to anything that maps to an event, and nothing else. Then our EventHandler will know everything and if we say "record actions" we will have a faithful record of what happened.

@ttung 

> We need to make data futures a first class concept in Napari

Yes I think that's something @pwinston will be exploring in the context of subjective performance.

> I can't think of any plugins that set keybindings

Huh? Literally every plugin in Fiji, to a first approximation, provides keybindings. Now for many/most/all (not sure) of them, the keybindings are modal and only activated when the plugin is activated. Possibly this is something we can architect. But, for example, I think it'd be useful for plugins to be able to set keyboard shortcuts for their own launch. But also 100% agree that keybinding clashes are a concern.

> It would be super fascinating to explore a plugin interface based on python multiprocessing + shared memory

One person's fascinating is another's nightmare! 😂 But there's an idea for napari 6.0 in there somewhere. =)

**Comment by royerloic** [comment]
Lots of ideas here!

For me the main argument for a more insulated interface (@sofroniewn proposal) is that we are going inevitably to have changes of the layers internals (and not so internals). Every time such a change happens, this will break plugins that rely on objects being exactly the way that they expect them to be. If instead, we pass a 'view' of the layer and viewer, and we just pass what we think should be touched, then you have the possibility to decouple the internals from the public API, and thus you reduce API trauma. You could even imagine producing different views to accommodate older plugins (plugins should declare which version of the API they are written against). I would really want to avoid seeing plugins 'dying' left right and center every time we change something. Worse, we might eventually limit ourselves because some super duper popular plugin would break, and for some reason we can't easily fix it, and nobody else can either. Strong coupling between code modules will not be future proof imho and will be a major source of headache down the line. There are quite a few example of software engineering projects that have suffered from lack of insulation. One that comes to mind is Python itself and its C extension interface, which exposes too much of the Python internals and has made it very difficult to move the whole language forward (GIL, etc). Of course, Python does not have enforceable interfacing, but there is a difference between encouraging users to put their hands in the cogwheels (ouch), and putting a fence. They know they are naughty when they go around the fence... 
I think the performance cost of copying small objects (tuples lists, etc... ) will be negligible, copying the full .data field of layers by default is out of the question imho. If a keybinding/plugin creates a new layer, fine, but you can also do modifications in-place. 
A very important benefit of copying some of the lightweight details of layers is that this will make asynchronous processing much easier, because we can trust that no other thread has access to this data. In general, giving direct access to internal objects is not a good idea when building an async ready plugin interface -- unless you are fine making all these objects thread-safe etc...
Finally, given a more 'abstracted' interface, we can imagine how the plugins code could find usefulness beyond napari-of-today, could operate with remote, web based versions of napari that we have not yet thought, designed or built. the more we tie ourselves to concrete objects, the less we are building for the future.

My own opinion on pluggins: they should be as much declarative as possible and avoid the 'imperative' style. Here this means: 'insulated functional interfaces' which is what @sofroniewn is proposing. Adding one insulation layer gives a lot of benefits in the long term, in the same way that separating views from models gave us a lot of clarity. One thing that I would like to see long term is a more declarative style that will make it easier for us to 'operate' on plugins. For example, you want to scale up the plugin on a DASK remote cluster and such? the plugin writer does not need to have ever thought of it, he just needs to declare what the function is, what the keybinding is, and napari could be configured to send the computation remotely etc... _This is easier if we constrain plugins to live in a 'bubble' of our own making._  
@jni might be the guardian of dimensions? I claim to be the guardian of modularity :-)
 
We should think very very hard on this problem because the choices we make now will come back to haunt us, or be the thing we will be the most proud in 10 years from now, Let's get it right and take our time to learn from each other and reach a consensus where each one of us has learned something and gained a better understanding of the problem. We should not solve this one easily nor fast.

**Comment by ttung** [comment]
How will you prevent a plugin writer from `import napari` and going wild?  Or is that not going to be a consideration?

**Comment by sofroniewn** [comment]
> How will you prevent a plugin writer from import napari and going wild? Or is that not going to be a consideration?

I guess I can think of 3 reasons why someone might do that

1. They don't understand/ know about the appropriate plugin interface. Here we just have to make sure that we're promoting best practices in our documentation/ tutorials.

2. There is something that our current plugin interface doesn't provide, and so they are forced to do this. Here we should really try and understand their use case and see if we can provide something through our plugin interface.

3. They are trying to do something malicious. This I am less worried about. We shouldn't ignore this possibility, but I don't think it has been an issue for FIJI.

I'd really prefer to avoid it as it makes concepts like "reproducibility" a bit harder to ensure, but I'm not sure I'd go as far to take steps to try and prevent it. Maybe there is some danger that one very prominent plugin starts to do this and then it breaks the ecosystem, but I'm inclined to agree with @tlambert03 philosophy of consenting adults here and that plugins that do weird things will not be the plugins people want to use.

Out of curiosity what would it look like to try and prevent something like this? Could it be done without putting every plugin in a sandbox.

**Comment by ttung** [comment]
> Out of curiosity what would it look like to try and prevent something like this? Could it be done without putting every plugin in a sandbox.

You could override the import command and inspect each import to see if it's reasonable?  Wrap ambiguous imports with proxy objects to trace usage.  Perf could be atrocious.  I know this is possible with python 2.7, not sure if it's possible in python 3.

Or we could build the multiprocess + shmem thing, which has some desirable properties that this project is likely to want (e.g., ability for plugins to have unresolvable dependencies).  However, it is quite likely a nightmare as @jni suggests. :)

**Comment by jni** [comment]
> I claim to be the guardian of modularity

Oh come on, surely we can do better than this! "Enforcer of the Module Borders"? "Keeper of the Inner Powers"? =P

**Comment by kne42** [comment]
I'd like to point out that we don't necessarily need a hookspec just for keybindings. I think that you could cover keybinding settings via hookspecs on startup:
```python
@napari_hook_implementation
def napari_on_startup():
    from napari import Viewer, layers

    @Viewer.add_keybinding('p')
    def hello_world(viewer):
        viewer.somethingsomethinglog('Hello World!')

    @layers.Labels.add_keybinding('z')
    def super_watershed(layer):
        ...
```

Since we own naplugi or whatever we're calling it now, we can also add a new type of hook with an easier interface:
```python
@napari_keybinding('Viewer', 'h')
def foo(viewer):
    ...
```

**Comment by 0x00b1** [comment]
> Could it be done without putting every plugin in a sandbox.

I’m particularly interested in usability and maintenance concerns so I’d propose whitelisting contracts, e.g. `Image → Image` and `Image → Labels`. I’m less concerned about security concerns since Napari will, more than likely, be sandboxed on macOS and Windows.

I admit that I have an extremely conservative view of plug-ins and wouldn’t bother exposing interfaces for “key bindings, mouse functions, or GUI elements.” 🤷‍♂️

**Comment by Carreau** [comment]
I know this hans't been commented on in a while; but one thing that has worked great in Jupyter Notebook is to associate each function with an identifier and then the keybinding to those identifiers separately.
Binding with a decorator is problematic as it makes it relatively more difficult to detect/fix conflict between keybinding and hook into configuration/preferences.

That of course depends on how much configurable you want the keybindings to be.

**Comment by sofroniewn** [comment]
> I know this hans't been commented on in a while; but one thing that has worked great in Jupyter Notebook is to associate each function with an identifier and then the keybinding to those identifiers separately.

I'm very intrigued by this idea! Definitely something we might want to explore as I think we do want to be able to detect/ fix keybinding conflicts - see discussion in #1321 too

**Comment by lucyleeow** [comment]
Lots of good discussion here but I'm going to close this as npe1 is now being deprecated. I've read most items and I think most of the items discussed have been detailed in other issues or in NAP-7 or addressed already, e.g., with the new app-model provider and processors, the new `PublicOnlyProxy`.

> We'll need to leverage UI elements to make it easy to turn on/ turn off a plugins keybindings, and we wouldn't them all on by default.

I am going to open a new issue for this, as this is something that we want post NAP-7
