### ISSUE TITLE
Better syntax for launching a GUI programmatically

### ISSUE THREAD

**Issue by jni** [napari/napari#134]
## 📚 Documentation

@royerloic pointed out that it's kinda clunky that the `QApplication` startup and shutdown logic are embedded at the start and end of each example. The whole thing certainly smells of a context manager! Suggestion:

```python
from skimage import data
from skimage.color import rgb2gray
from napari_gui import imshow, application

with application():
    image = rgb2gray(data.astronaut())
    viewer = imshow(image, {})
```

You could then nicely embed Napari within a bigger processing script:

```python
with application():
    viewer = imshow(image)
    viewer.add_markers()  # add clicks, but see #120  =P
    markers = viewer.layers[-1].markers

count = len(markers)
# ... more downstream processing...
```

If we are going for the OO API, I think the above would still work, but we might add a convenience method within the viewer?

```python
viewer = Viewer()

with viewer.start_application():
    # more good stuff

# downstream processing
```

**Comment by sofroniewn** [comment]
Just to note this intersects with discussions we are having in #120.

I guess I'm not quite sure if a context manager would behave as I expect. If I had the
```python
with application():
    image = rgb2gray(data.astronaut())
    viewer = imshow(image, {})
```
In a cell at the top of my notebook, and then in the next cell wanted to do
```python
viewer.add_markers(data)
```
Would this work? My understanding says no as viewer was only defined inside that context manager. Not being able to do this sort of multi-cell interaction inside a notebook is a complete deal breaker for me (think of what the `layers.ipynb` example used to look like)

**Comment by kne42** [comment]
Yes yes yes! I've actually wanted to implement something like this for a while :)

I was also thinking of taking a further step to leverage context managers:
```python
with gui.imshow(img) as viewer:
    viewer.add_image(img1)
    viewer.add_markers(spots)
```

Basically a viewer would include a context manager that delays window showing and application blocking until the end of the block (and I'd also like to work in update delaying into there – kinda like `layer._freeze`). I'd also like to apply the update delaying to layers as well. Actually I think now I kinda wanna open an issue to better articulate my ideas :P

@sofroniewn There are only two blocks that create their own scopes in Python: functions and classes. Allowing all other blocks to share the same scope is super useful for example when iterating in a for-loop:
```python
def index(obj, l):
    """Find the index of an object in a list."""
    for i, e in enumerate(l):
        if e == obj:
            break
    else:
        raise ValueError(f'{obj} not in {l}')

    return i
```

**Comment by sofroniewn** [comment]
Ah @kne42 so I'd still be able to do the behavior I want as `viewer` would still be accessible.

I'm definitely curious about this approach, and can see the value in blocking refreshes etc when you are adding many layers / manipulating many layers. For example in the `examples/lut.py`

```python
viewer = imshow(image, {})
layer = viewer.layers[0]
# change the clims
layer.clim = [0.25, .75]
# change the colormap
layer.colormap = 'gray'
```
It would be nice to make these sorts of changes before having everything update.

I am however very wary of adding too much complex syntax for beginner users who just want to look at an image etc. so maintaining a somewhat simple path remains important to me (as does not having too many different paths through the API such that it becomes confusing)

**Comment by kne42** [comment]
I'd also like to note that notebook users won't need to use the context manager/application anyways since they're only there to provide the Qt event loop which `%gui qt5` does for us.

So this is really just for people who are scripting.

**Comment by sofroniewn** [comment]
Ah thanks for clarifying that - I had not appreciate it. In that case I feel more comfortable with this approach and can see its value

**Comment by jni** [comment]
> I'd also like to note that notebook users won't need to use the context manager/application anyways since they're only there to provide the Qt event loop which `%gui qt5` does for us.
>
> So this is really just for people who are scripting.

:point_up: this! I think this answers all your concerns, @sofroniewn. =)

**Comment by sofroniewn** [comment]
Following our in person discussion @royerloic drew this representation of our desired architecture

![image](https://user-images.githubusercontent.com/6531703/57938567-4f686e80-787d-11e9-93dc-3ca97d22e184.png)

Here is I think where things landed (with maybe 1 minor naming revision)

On the right hand side we have our `Qt` classes - they have names like `QtWindow`, `QtViewer`, `QtDims` etc. and are constructed in a tree like fashion with no circular dependencies. The class names should correspond to the filenames of the main file containing these objects. They get passed corresponding model files during construction where needed. Those model files don't depend on anything Qt related (i.e. there is no bidirectional dependency) and each have their own test function. They have names like `Layers`, `Dims` and the class names and filenames should also match. I propose we have one naming exception which is for the viewer model file - we should name it `ModelViewer` - this allows us to reuse the name `Viewer` for the object on the lefthand side. The `Viewer` on the lefthand side is a subclass of `ModelViewer` with an additional property `_qtwindow` that contains the `QtWindow` (and in turn all the other `Qt` elements because of its tree like structure). The `ModelViewer` itself has a tree like structure containing `Dims`, `Layers` etc. with no circular referencing. It also contains the `add_*` methods that allow you to add new layers. Finally we will make judicious usage of `_` and `__` properties to ensure a clean "public" api.

There was still some debate about `launch()`, `imshow()`, and `Viewer()` as being main access point. I lean towards `Viewer()` to instantiate the object (without being able to take any input images) and `imshow(image)` as a convenience wrapper as follows

```python
def imshow(image):
    viewer  = Viewer()
    viewer.add_image(image)
    return viewer
```
I think we get the top part done without settling this bit yet though.

Are we in agreement that this seems like a reasonable place to start and @jni are you ready to implement? Now is a pretty good time as we only have the keybindings PR out. I'd also say this refactor and settling on an architecture and main API is one of the highest priority and most important things to do for the `0.1.0` milestone!

**Comment by jni** [comment]
So, to recap how we got to where we are, to the best of my recollection:

- we originally had imshow, which did the viewer + window dance and returned the viewer
- alternatively we could do the window + viewer object creation, but that was clunky
- we then had a debate about the "canonical" way of using Napari, and whether it was a good thing to have a *function* that returns a weird/nonstandard object, whether it was a good or a bad thing to shadow the name from matplotlib, etc.
- then @freeman-lab (I believe) suggested we unified the two approaches: make what became `ViewerApp` with an `__init__` that behaves as `imshow`.

Now we are proposing going back to imshow and some class that requires two steps, and I'm really not sure that it's the right way to go — I very much liked having a unified approach.

@sofroniewn although I very much sympathise with your preference for the two-step API, I still have reservations. The biggest one is that I think people will much appreciate a one-liner, especially in interactive work. A more minor one is that I'm still a bit cautious about fully endorsing the `add_to_viewer` mechanic, and without it, it becomes even more cumbersome to use the OO interface. (The two main reasons I'm still not settled on it are (1) static analysis tools can't cope with the dynamically-added methods, and (2) you lose namespaces, so if you have e.g. someone else making my_super_awesome_napari_plugin.Image, they will overwrite the built-in Image.)

I also still dislike shadowing matplotlib's imshow.

Ok on to my recommendations.

1. The class names should be:

- Viewer
- Window
- ViewerWidget
- ViewerModel (or ViewerData)

Even though ViewerWidget and Window are Qt objects, again, I think it's better not to shadow names that exist in the Qt hierarchy, or that closely resemble objects in the Qt hierarchy. 

2. The preferred interactive API should be one of the following:

(a)

```python
import napari
...
viewer = napari.view(image0, image1, ...)
viewer.add_markers(coords)  # or viewer.add(napari.Markers(coords))
```

(b)

```python
viewer = napari.Viewer(image0, image1, ...)
viewer.add_markers(coords)  # or viewer.add(napari.Markers(coords))
```

(c)

```python
viewer = napari.Viewer(images=[image0, image1],
                       markers=[coords])
```

3. The preferred programmatic API *could* be:

```python
viewer = napari.Viewer()
viewer.add_image(image0)
viewer.add_image(image1)
```

But I still find that unnecessary, and think rather that that kind of syntax should be preferred *only* for people using the ViewerWidget or ViewerModel classes.

For options (b) and (c), which are my preferred ones, I could start implementing with the args and then we can see how strongly everyone feels about ripping out that functionality. ;)

**Comment by sofroniewn** [comment]
For (1) I am fine with

- Viewer
- Window
- ViewerWidget
- ViewerModel

But would we then do
- LayersWidget
- LayersModel
- DimsWidget
- DimsModel
- etc.

and have file names like `dims_model.py` and `dims_widget.py`? Or `dims_view.py` and `DimsView`? I could go either way.

For (2) and (3) I think (c) is very limiting because you can't pass any of the additional keyword arguments, like `color` as there might be conflicts between the different layer types and it will quickly become a mess. I prefer (a) because I find the existence of both (b) and (3) slightly confusing, and I really like (3) - especially if your images all have different colormaps / clims.

**Comment by royerloic** [comment]
I like this suggestion @sofroniewn 
Consistency is key here, and will make it very easy for people
to understand how the code is organised. I also would love to
avoid having lots of view.py and model.py files... 

I also agree with @sofroniewn  on his preference on @jni 
proposals: (a) and (3). Great to see this converging...

**Comment by sofroniewn** [comment]
@royerloic do you have an opinion on `DimsWdget` or `DimsView`? I prefer `DimsView` as I think it will me more understandable to people outside the `Qt` ecosystem and the could be a day when we have views that aren't strictly widgets. I am fine with `ViewerWidget` though as that is the parent that contains all the others and `ViewerView` is a little weird, though maybe `ViewerView` is ok too

**Comment by royerloic** [comment]
All these are right now Qt based, so it is fine to have that somehow clear
in the name too -- that would suggest for `DimsWidget` or `QtDims`.
But I don't have a strong opinion except for being consistent. 
`DimsView` is fine too.
