### ISSUE TITLE
Point layer editable status changed after toggling visibility

### ISSUE THREAD

**Issue by hungyiwu** [napari/napari#1346]
## To Reproduce

1. Open napari, create a new point layer, and add a few (2~3) points
2. Open the IPython console and confirm the `editable` state is True by `viewer.layers['Points'].editable`
3. Change the editable state to False by `viewer.layers['Points'].editable = False`
4. Confirm the select/add/delete icons all grayed out and not clickable
5. Now click the eye icon of this point layer twice to toggle its visibility to off and then on
6. The select/add/delete icons are functional again, and `viewer.layers['Points'].editable` in the IPython console returns `True`

## Expected behavior

The `editable` state should be independent of the visibility state

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.3.4
Platform: Linux-5.4.0-7634-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.6 | packaged by conda-forge | (default, Jun 1 2020, 18:57:50) [GCC 7.5.0]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.17.2
VisPy: 0.6.4

GL version: 4.6 (Compatibility Profile) Mesa 20.0.4
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.5
- svg: 0.1.3
```

 - Any other relevant information:

Ubuntu 20.04
conda 4.8.3

**Comment by kevinyamauchi** [comment]
Hello @hungyiwu! Thank you for the clearly written issue. I agree that `editable` and `visible` should be independent properties. I think this likely applies to other layers (e.g., `Shapes`) as well.

We have a parallel issue for finer control over layer interactivity (#1273) and I think we can fix this one at the same time.

Thanks again and please don't hesitate to drop more issues if you find other bugs or have feature requests!

**Comment by sofroniewn** [comment]
Apologies for the lack of progress on this one, we should get to it soon!

**Comment by andy-sweet** [comment]
> Apologies for the lack of progress on this one, we should get to it soon!

Almost at the second anniversary of this one, so not so soon! But I am looking at clarifying `Layer.editable` and `Layer._set_editable` and stumbled across this bug.

I think I can/should fix this as part of a related clean up, but am considering two fixes given that we likely still want to disable the editing layer control buttons either when a layer is not visible or not editable.

1) Make the `Layer.editable` property derived from both `Layer._editable` and `Layer.visible`. In this case, `Layer._editable` is independent of `visible`, but `Layer.editable` is obviously not. This is the easiest way (i.e. fewest code changes) to disable the editing layer controls either when the layer is not visible or not editable. It means that an invisible layer would temporarily change the value returned by `Layer.editable`, but would return to that actually set by the user (or caused by a reset) after the layer becomes visible again.

2) Make `Layer.editable` and `Layer.visible` entirely independent. This way, we'd have to make the layer controls listen for changes to both `visible` and `editable` and disable the editing layer controls if either of them are false.

Any thoughts on these?
