### ISSUE TITLE
Docs version is incorrect, and is missing pages

### ISSUE THREAD

**Issue by jni** [napari/napari#1365]
## 📚 Documentation

The current documentation shows napari version 0.1.dev742+g0adb11c:

<img width="849" alt="Screen Shot 2020-06-16 at 1 50 53 pm" src="https://user-images.githubusercontent.com/492549/84730044-822ceb00-afd8-11ea-9445-eadcd82155cd.png">

I suspect this might be an issue with #1324 interacting badly with how we build docs.

Additionally, the pages under [`docs/explanations`](https://github.com/napari/napari/tree/0adb11c53dbd29ae82fbf46b68c61bda63128775/docs/explanations) don't appear in the docs. I think the fix is to add `explanations` to the toctree here:

https://github.com/napari/napari/blob/0adb11c53dbd29ae82fbf46b68c61bda63128775/docs/source/index.rst

**Comment by tlambert03** [comment]
I can reproduce this locally if I use `git clone` with a `--depth` less than the number of commits from the last tagged commit.  So it seems like the `CIRRUS_CLONE_DEPTH: 0` flag isn't working.  I'll see what I can do to fix it

**Comment by tlambert03** [comment]
I have the version working, and am adding the explanations now.  Reconciling the markdown and rst is problematic in some places, so we have some choices to make.

we can use [recommonmark](https://github.com/readthedocs/recommonmark) (as we're already doing), to convert the markdown to rst for sphinx/docutils, but there are some trouble areas.  In particular, the tables used in the explanations. I can use recommonmark [AutoStructify](https://recommonmark.readthedocs.io/en/latest/auto_structify.html) and an `eval_rst` block to make those tables work for our sphinx docs:

![Screen Shot 2020-06-16 at 3 57 02 PM](https://user-images.githubusercontent.com/1609449/84822017-0a67bc00-afea-11ea-95c4-5eeae759bacc.png)

but that will come at the expense of their formatting if someone reads them in the github repo.

![Screen Shot 2020-06-16 at 3 58 09 PM](https://user-images.githubusercontent.com/1609449/84822133-371bd380-afea-11ea-8fd1-708fb952ec66.png)

how would you like to handle that?  Prioritize how they look in sphinx docs?  or how they look as markdown docs?

Also, I'd vote for moving both "developers" and "explanations" folders inside of docs/source ... where the rest of the docs source lives.  Otherwise, we have to continue taking special measures inside of our docs makefile to copy those folders into the source directory when building our docs. 
any objections?

**Comment by sofroniewn** [comment]
> Also, I'd vote for moving both "developers" and "explanations" folders inside of docs/source ... where the rest of the docs source lives.

This sounds like a good idea

> Prioritize how they look in sphinx docs?

I guess for now.

Have you seen https://twitter.com/choldgraf/status/1272633413132943360, could be something we want to use in the future?

I'd say though if we can get something ok for now then I'd do that, and then I can update #1364 and we can make the 0.3.5 release tonight which would be nice!

Thanks @tlambert03 for digging into this!!

**Comment by tlambert03** [comment]
I hadn’t seen MyST... promising!

**Comment by jni** [comment]
@tlambert03 go for your life! =) long term I’d definitely like for us to explore MyST but now is not that term. =P

**Comment by jni** [comment]
An extra comment on MyST:

https://twitter.com/asmeurer/status/1272951514890301440

**Comment by tlambert03** [comment]
that is true... but I think having support for both around can be confusing at times too, since it's easy to get in the habit of thinking "I can use whichever one I want now".  For instance, in our docstrings, you still have to use rst format for it to be rendered properly with sphinx-napoleon... and we have a lot of places where a single backtick is used to demarcate "code" instead of double backticks ... but it renders as italics in rst.  (like in [most of our layer API docs](https://napari.org/docs/api/napari.layers.shapes.html#module-napari.layers.shapes.shapes))

so the progressive conversion requires context-dependent attention by all contributors.

**Comment by sofroniewn** [comment]
Just linking to #1049 where can continue this discussion if this immediate issue gets closed
