### ISSUE TITLE
Executed examples in the docs

### ISSUE THREAD

**Issue by jni** [napari/napari#1387]
## 📚 Documentation
It would be great to be able to use sphinx-gallery together with `nbscreenshot` to run our examples for our documentation and embed screenshots.

The tutorials would also be great to run automatically, although that might be not be feasible since some use large datasets, or demonstrate interactivity.

**Comment by sofroniewn** [comment]
Indeed, see discussion here from @GenevieveBuckley for considerations for our tutorials https://github.com/napari/tutorials/issues/70. I think a good first step though it just getting all our examples in this repo run and included

**Comment by GenevieveBuckley** [comment]
Continuing the discussion from https://github.com/napari/napari/issues/1568 (it seems better placed here, since this issue is not specific to the nbclient library):

https://github.com/napari/napari/issues/1568#issuecomment-716382897
> Exciting news! If we use [runipy](https://github.com/paulgb/runipy)* to execute jupyter notebooks we can finally run them with the `%gui qt` magic. (See the discussion [here](https://github.com/jupyter/nbclient/issues/97#issuecomment-716366259) for more details) 🚀 🚀 🚀
> 
> *Note: runipy is no longer maintained, but it's very small so we could potentially maintain a fork of it in the napari org. I'd say the benefits would be worth it.
> 
> ```
> pip install runipy
> runipy example-notebook.ipynb
> ```
> 
> ```python
> # cell 1
> %gui qt
> 
> # cell 2 - this MUST be in a separate cell after the qt magic above, you can't combine these two into one cell
> import time
> time.sleep(5)
> 
> # cell 3
> import napari
> viewer = napari.Viewer()
> ```

**Comment by GenevieveBuckley** [comment]
Followup from @jni's suggestion at the dev meeting:
I can use `runipy` to run a notebook with napari and then save the executed notebook with outputs (and especially `nbscreenshot` outputs) to a separate file. Yay!

One slight hiccup with this is that it saves an older notebook json format, not the current notebook version 4 format. When you open the output with jupyter it's clever enough to detect and convert this for you, but I'm not sure if sphinx will be able to handle this. So we might need to tweak how the output json is written to file.

**Comment by GenevieveBuckley** [comment]
Interestingly, sometimes I get a strange error (but it's very inconsistent). It doesn't happen every time, but it happens quite a bit. If you re-run the command enough times it ends up working.

Here is me finding this problem, then re-running with exactly the same command and having it work fine.
```
(napari-dev) C:\Users\Genevieve\Documents\GitHub\napari-notebook-testing>runipy napari-notebook.ipynb output2.ipynb
10/30/2020 02:59:27 PM INFO: Reading notebook napari-notebook.ipynb
10/30/2020 02:59:29 PM INFO: Running cell:
%gui qt

10/30/2020 02:59:29 PM INFO: Cell returned
Traceback (most recent call last):
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Genevieve\anaconda3\envs\napari-dev\Scripts\runipy.exe\__main__.py", line 7, in <module>
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\runipy\main.py", line 158, in main
    nb_runner.run_notebook(skip_exceptions=args.skip_exceptions)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\runipy\notebook_runner.py", line 232, in run_notebook
    self.run_cell(cell)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\runipy\notebook_runner.py", line 151, in run_cell
    msg = self.kc.get_iopub_msg(timeout=1)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\jupyter_client\client.py", line 82, in get_iopub_msg
    return self.iopub_channel.get_msg(*args, **kwargs)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\jupyter_client\blocking\channels.py", line 54, in get_msg
    raise Empty
_queue.Empty
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

(napari-dev) C:\Users\Genevieve\Documents\GitHub\napari-notebook-testing>runipy napari-notebook.ipynb output2.ipynb
10/30/2020 02:59:43 PM INFO: Reading notebook napari-notebook.ipynb
10/30/2020 02:59:45 PM INFO: Running cell:
%gui qt

10/30/2020 02:59:45 PM INFO: Cell returned
10/30/2020 02:59:45 PM INFO: Running cell:
import time
time.sleep(5)

10/30/2020 02:59:50 PM INFO: Cell returned
10/30/2020 02:59:50 PM INFO: Running cell:
print('hi')

10/30/2020 02:59:50 PM INFO: Cell returned
10/30/2020 02:59:50 PM INFO: Running cell:
import napari

viewer = napari.Viewer()

10/30/2020 02:59:54 PM INFO: Cell returned
10/30/2020 02:59:54 PM INFO: Running cell:
napari.utils.nbscreenshot(viewer)

10/30/2020 02:59:55 PM INFO: Cell returned
10/30/2020 02:59:55 PM INFO: Running cell:
print('hooray!')

10/30/2020 02:59:55 PM INFO: Cell returned
10/30/2020 02:59:55 PM INFO: Running cell:
viewer.close()

10/30/2020 02:59:55 PM INFO: Cell returned
10/30/2020 02:59:55 PM INFO: Saving to output2.ipynb
10/30/2020 02:59:55 PM INFO: Shutdown kernel

(napari-dev) C:\Users\Genevieve\Documents\GitHub\napari-notebook-testing>
```

**Comment by GenevieveBuckley** [comment]
It also seems like there's a problem if I try and write the output directly to html

I suspect that the packages in my environment are too new, and maybe I should try this again with older dependency versions.

```
(napari-dev) C:\Users\Genevieve\Documents\GitHub\napari-notebook-testing>runipy napari-notebook.ipynb --html
10/30/2020 04:13:56 PM INFO: Reading notebook napari-notebook.ipynb
10/30/2020 04:13:58 PM INFO: Running cell:
%gui qt

10/30/2020 04:13:58 PM INFO: Cell returned
10/30/2020 04:13:58 PM INFO: Running cell:
import time
time.sleep(5)

10/30/2020 04:14:03 PM INFO: Cell returned
10/30/2020 04:14:03 PM INFO: Running cell:
print('hi')

10/30/2020 04:14:03 PM INFO: Cell returned
10/30/2020 04:14:03 PM INFO: Running cell:
import napari

viewer = napari.Viewer()

10/30/2020 04:14:08 PM INFO: Cell returned
10/30/2020 04:14:08 PM INFO: Running cell:
napari.utils.nbscreenshot(viewer)

10/30/2020 04:14:08 PM INFO: Cell returned
10/30/2020 04:14:08 PM INFO: Running cell:
print('hooray!')

10/30/2020 04:14:08 PM INFO: Cell returned
10/30/2020 04:14:08 PM INFO: Running cell:
viewer.close()

10/30/2020 04:14:09 PM INFO: Cell returned
10/30/2020 04:14:09 PM INFO: Saving HTML snapshot to napari-notebook.html
Traceback (most recent call last):
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\ipython_genutils\ipstruct.py", line 132, in __getattr__
    result = self[key]
KeyError: 'cells'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Genevieve\anaconda3\envs\napari-dev\Scripts\runipy.exe\__main__.py", line 7, in <module>
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\runipy\main.py", line 204, in main
    output, resources = exporter.from_notebook_node(nb_runner.nb)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\nbconvert\exporters\html.py", line 95, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\nbconvert\exporters\templateexporter.py", line 307, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\nbconvert\preprocessors\coalescestreams.py", line 29, in wrappedfunc
    for index, cell in enumerate(nb.cells):
  File "c:\users\genevieve\anaconda3\envs\napari-dev\lib\site-packages\ipython_genutils\ipstruct.py", line 134, in __getattr__
    raise AttributeError(key)
AttributeError: cells
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

(napari-dev) C:\Users\Genevieve\Documents\GitHub\napari-notebook-testing>IOStream.flush timed out
IOStream.flush timed out
```

No output html file is written to disk.

**Comment by ianhi** [comment]
I would love it if the examples were available on the docs. 

One thing to consider with sphinx-gallery is the possibility of writing a [custom image scraper](https://sphinx-gallery.github.io/stable/advanced.html#write-a-custom-image-scraper) that calls `viewer.screenshot` to generate the images.

I also like the idea of including GIFs of user interaction with the GUI as I think this really increases the understanding of what's happening. If that's desirable then I'd note that Sphinx-gallery supports gifs, so gifs could be manually recorded and included in the repo.

However, that comes with the downside of repo size bloat due to the gifs and the need to re-record the gifs anytime the styling of napari changes. So here is a more robust (but also more complex) proposal. I also proposed this on https://github.com/matplotlib/matplotlib/issues/19222

1. Run the example manually
2. Programmatically record all user interaction events  (mouse_move, click, etc...)

Then at docs build time

3. Use a custom sphinx-gallery scraper that plays back the recorded events and use vispy to draw a mouse cursor onto the canvas
4. Record these and generate a gif and then embed that gif

At first blush this sounds overly complicated but I have implemented this for matplotlib and found that it was relatively simple to achieve. Although I may have played some unsafe shenanigans with `exec`. That repo is here: https://github.com/ianhi/mpl-playback and generates galleries like this: https://mpl-playback.readthedocs.io/en/latest/gallery/index.html

If there's an appetite for this then I'd be happy to help translate `mpl-playback` to something like `napari-playback`

**Comment by tlambert03** [comment]
Hi @ianhi,

It's not that well "advertised" here, but our docs are undergoing a big rennovation led by @kne42, using jupyter-book, which will definitely assist in generating images from code.

We are interested in all ways to autogenerate visual demos including gifs (currently, most of those "bloated" gifs are in the [napari-tutorials repo](https://github.com/napari/tutorials/tree/master/assets/gallery), and in this process we'd like to unify all these resources).  I'll also point out the [`napari-animation` repo](https://github.com/sofroniewn/napari-animation), that @sofroniewn  and @alisterburt  are working on. 
 That will store keyframes and generate animations that will also likely be useful for autogenerating these sorts of gifs.

Anyway, just pinging @kne42 here so that she sees this idea and offer of help. 

thanks!

**Comment by sofroniewn** [comment]
Hi @ianhi I love this vision and just to echo @tlambert03 point, I think some of the machinery will be in place for autogenerating gifs in napari-animation and we'd welcome any of your input over there (it's in early development right now).

I read through the matplotlib linked issue, and one thing that stands out is tracking the `mouse position` - we don't really have that sort of functionality in napari-animation, which is much more of a keyframe + interpolation based approach vs an "event recording" approach. I've created https://github.com/sofroniewn/napari-animation/issues/21 to discuss this more on the animation repo.

We've had some informal discussions about adding support for macrogeneration which I think would be more along the lines of "event recording" - though so far I'd mainly been thinking of that in the context of generating analysis scripts and undo/ redo (see #474 for some old ideas around that) and focusing on tracking function calls and data changes rather than tracking the mouse/ button presses (which would require us doing the tracking more at the Qt level).

We might want to start a new issue focused just on macrogeneration / event recording to continue this part of the discussion there.

**Comment by jni** [comment]
I love this discussion, and @ianhi that mpl-playback gallery is so friggin cool! 😍 

@sofroniewn in my view macro recording and event recording are two separate things, with relatively little overlap. I might be way off base here but wouldn't mouse event recording be a matter of adding a mouse_drag_callback to the viewer that stores all of the event positions and clicks to some global list? The only question then is how to relate those events to viewer events. But maybe that can also be done by having the recorder subscribe to ~all events being emitted by the viewer models?

More immediately though, I think we should take baby steps, and aim for a screenshots gallery first, then plain old animations, then finally interactive animations. But certainly @ianhi your demos show the full range of what's possible and I'm super excited about where we can go with this. We can even use large downloads together with the [`cache` GitHub Action](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action) to show napari working with larger datasets.
