### ISSUE TITLE
Better Qt tests for mouse move/ drag events

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1411]
## 🐛 Bug

We have custom mouse move/ drag events on some of our qt objects like the `QtLayerList`, but we don't have any good testing yet of these functions - see https://codecov.io/gh/napari/napari/compare/e43f730170aab1e011c42060c65ba44133f6f18f...87910700153881903401c4f1d3f58285c94a674b/src/napari/_qt/qt_layerlist.py?before=napari/_qt/qt_layerlist.py from #1391. We should add dedicated tests for these lines and other similar ones that simulate Qt mouse moves.

**Comment by dalthviz** [comment]
Hi, I gave this a try, started checking and seems like is not so straight forward to create a test for the drag and drop functionality using `pytest-qt` alone. Seems like due to a bug with the `QtTest` module the helper functions you would use for this (`qtbot.mouseMove` specifically) don't trigger the events for the widgets to "enter the drag and drop mode" (some details on the QT bug and alternatives to create such a drag and drop test can be found in this SO post: https://stackoverflow.com/a/59080886/15954282).

Following that finding, I tried implementing a test using the `pyautogui` package. To check how that works you can check this branch (you will need to install `pyautogui` to run the test): https://github.com/napari/napari/compare/main...dalthviz:napari:issue_1411

However, I'm not sure if to have such a test is worthy to add another test dependency such as `pyautogui` 🤔

Sharing the findings here just in case :)
