### ISSUE TITLE
Use the `experimental` namespace to allow us to try out new features

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1564]
## 🚀 Feature
There have been a couple of convos recently in different places in the project where we have wanted to get functionality in for advanced users and developers to try out, but where we might want to make breaking changes more frequently and ultimately might not end up supporting all the functionality that we try out. This could apply to hookspecs, like discussed in #1327, new layer types, new interactivity, or things we havn't even thought of yet. 

One suggestion from @freeman-lab that I really like is we learn from the tensorflow project who use the `experimental` namespace. See [tf.experimental](https://www.tensorflow.org/api_docs/python/tf/experimental?version=nightly) and [tf.data.experimental](https://www.tensorflow.org/api_docs/python/tf/data/experimental?version=nightly) which are clearly indicated as such in the docs.

As noted by @pwinston in discussion in the euro dev meeting, this would now give us a third namespace option, separate from public and the private `_`.

Scikit-image uses the `future` namespace (just one top level instead of individual at every sublevel), see [skimage.future](https://scikit-image.org/docs/stable/api/skimage.future.html) and with the following documentation 

> Functionality with an experimental API. Although you can count on the functions in this package being around in the future, the API may change with any version update and will not follow the skimage two-version deprecation path. Therefore, use the functions herein with care, and do not use them in production code that will depend on updated skimage versions.

I personally prefer the word `experimental` to `future` and I think it describes the napari needs a bit more that `future`, for example we might add an `experimental` hook spec that allows plugin developers lots of freedom but that actually then causes things to frequently crash. We'd then probably want to remove that hook spec entirely rather than preserve it.

These are just early thoughts right now, but curious the opinions of others and any ideas for how we might use this concept both with our plugins and more generally in napari. cc @jni @royerloic

**Comment by kevinyamauchi** [comment]
I am a big fan of adding an "experimental" namespace. A few quick thoughts:
- I think the intention is much more clear than then `_` convention - especially to those that don't spend a lot of time with python.
- I think having an explicitly experimental section gives contributors a lot more freedom to implement and importantly get community feedback on new features much more quickly.
- I also think this ties into the discussions in #1556 , as features in the "experimental" namespace can have a lower bar for test coverage/quality, which again I think helps get things moving more quickly.

In terms of the actual name, I like "experimental", as I think it conveys the right things (i.e., these are things we are trying, they aren't totally solid, and they may change drastically in the future). Of course, I am open to other suggestions.

In terms of implementation, I am curious what everyone's thoughts are. I think for experimental things that are discrete components (e.g., layers), I think it's fairly straightforward to put them under an experimental names space (e.g., `napari.experimental.layers` or `napari.layers.experimental`). However, for a feature that is a part of a larger component (e.g., when we added colors that are settable by properties), I think it is a bit less clear. Do we then duplicate the full component, add the new feature and put that under experimental (e.g., `from napari.layers import Points` would be the "stable" points layer and `from napari.experimental.layers import Points` would be the experimental one)?

I think there is also a hybrid approach where we have an experimental module for fully experimental components (e.g., new layers) and also experimental features in existing components that are activated via a flag  (I think @pwinston has advocated for flags for "opt-in experimental features"). One example of this that I am aware of in tensorflow is their `TFLiteConverter` ([see the `experimental_new_converter` flag)](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter). My recollection is when they first added it, the default value for the flag was `False` (i.e., one has to opt in). Then after a bit of time, the default value became `True` as it is now (i.e., it is default on, but one can opt out). I assume sometime in the future it will no longer be a flag and the "experimental new converter" just becomes `TFLiteConverter` (or doesn't). While these flags add new code branches, I think the added complexity is worth it for the feedback we can get on new features and because they clearly communicate what is experimental and what is solid (or at least should be 😛 ),

@ziyangczi was this partially why you were expressing a slight preference for an experimental build as opposed to an experimental namespace (i.e., it's just cleaner to have a separate build)?

**Comment by pwinston** [comment]
I like the sound of "experimental" and particularly think it might resonate with Napari's science-oriented users? I also think an `experimental` namespace could itself be considered an experiment. For instance "we are going to experiment with four week sprints" will generally be better received than "we are switching to four week sprints". And really it's more truthful.

But "experiment" should not just be a weasel word or a universal hedge. I would not say "we are going to experiment with dropping support for Python 3.6" I would just drop support. If people complain maybe you reverse the decision, but to me an experiment means "a big part of the reason we are doing this thing is to learn from it". Other examples might be "we are going to experiment with requiring ascii UML diagrams for new features" or "we are going to experiment with storing example data in the git repo" (bad idea!).

As for @kevinyamauchi's comments above, having features be opt-in in the stable distro but opt-out in a beta or canary build makes a lot of sense.  In the web world feature toggles are so common there are fancy [services to manage them](https://launchdarkly.com/). Big websites will almost always gradually roll out new features to ever larger cohorts (1%, 10%, 30%....) and immediately back off if they see any problems. Hitting a switch and letting 100 million users use the new code in the next 5 minutes is a recipe for disaster. As for Napari, rolling out a feature like async to wider and wider audiences is a good way to get feedback and testing while minimizing possible negative impact or disruption.

See also [Feature Toggles](https://martinfowler.com/articles/feature-toggles.html) and the semi-related [Blue Green Deployment](https://martinfowler.com/bliki/BlueGreenDeployment.html).

**Comment by liu-ziyang** [comment]
for experimental packages, I am a little concerned that people would then lack the motivation to push the last mile to make them official, the use case is satisfied and therefore can be perceived to left as is. Looking at some of the packages you would have experimental packages for ages, with others potentially want to use it wondering when would they be admitted.

If we also dedicate some engineering resources to these packages and help push them out of the experimental phase, then I would have no concern on these

**Comment by pwinston** [comment]
This is a very legitimate concern @ziyangczi. I could imagine "permanent experiments" that people depend on, but no one is interested in finishing. One approach there is a create a new plugin API and punt the person's code to a plugin. Basically eject the sub-standard code from the product. And then other people can write different plugins that hit that API.

It's a concern, but I would call ongoing management of `experimental.*` a cost of doing business. Banning all experiments because some might end badly I think is throwing the baby out with the bathwater. If napari is successful overall, if it's thriving even, I suspect the good outcomes will far outstrip the occasional bad ones. Most people are good and well intentioned. Although not everyone.

The nightmare scenario would be everyone just writes experiments because the bar for "real features" is too high. I think that's unlikely though, and it would indicate many things were wrong with the project that went far beyond this one issue. But certainly that would be a very bad situation, really it would sink the project.

I mentioned "portfolio theory". Actually it's similar Kanban's [WIP limits](https://getnave.com/blog/kanban-wip-limits/), you could say only X experiments can be going at once. To add more, an older one must be finished or removed. It would require discipline. But it would cap what percent of napari could be experimental at any one time, which might be good.

If someone complains about having their experiment shut down they can just fork napari. You generally don't want forks. But if someone is essentially a bad actor, best let them go off on their own.

**Comment by AhmetCanSolak** [comment]
I am happy to see this issue and I love to see us having `experimental` namespace. As @kevinyamauchi said makes the intention super clear. Possibly this is also our best bet to address test coverage/merge requirements discussed in #1556 . 

Also as a person who left some WIP pieces in the past, I take @ziyangczi 's concern serious and maybe we can try to adjust our milestones/project management in a way to push the desired experimental features to standard API on master. Or maybe having a rule like only X experiments can be going at once as @pwinston said, can help. I love to hear alternative ideas!

**Comment by neuromusic** [comment]
Could also force a "self-destruct" of `experimental`, by purging it for all major releases. The assumption here is that experiments that aren't ready for core by key release milestones probably need to die, especially since there will likely be breaking changes.

It also might be worth adding some friction to letting users access `experimental`... maybe they need to set an environment variable to turn on experimental features? or do a `pip install napari-experimental`? 

I'm also curious... how do you handle it if a change in "core" breaks an experimental feature (and its associated tests)? does that PR get to land? who is responsible for fixing the experimental feature?

**Comment by sofroniewn** [comment]
Loving this discussion everyone, lot's of great ideas and questions being raised.

I'm curious how some of our early plugin developers and advanced users view this proposal and the discussion. Any and all input welcome cc @adamltyson, @constantinpape, @Czaki, @GenevieveBuckley, @guiwitz, @hectormz, @JacksonMaxfield, @joshmoore, @manzt, @quantumjot, @will-moore

**Comment by pwinston** [comment]
I definitely imaged `experimental` was opt-in, probably opt-in per experiment. I was thinking of it like "early access" or Gmail's [labs](https://zapier.com/blog/gmail-labs-missing/) features, which is now just **Advanced**.  Like Chrome's 200+ `chrome:://flags`. You don't want newbies stumbling into them, that could lead to a bad first impression of Napari. I love the idea of generating some urgency with "the bus is leaving now!" for major releases, could be very motivating. Fly or get kicked out of the nest.

Breakages is a good question. Accepting the PR and saying "we are going to disable your experiment until you update it" is clearly an option. Whereas a PR that breaks core functionality would never be accepted ever. I think whether Napari disables the experiment or delays the PR is case-by-case. Good to have the flexibility though, the options.

We we have disable someone's experiment it should just say: Experiment Failed.

**Comment by Czaki** [comment]
My first think is "great idea`, but then questions appear "What should be placed here". 
Most PR which I participate rebuild `napari` core parts. 
  
I think `experiment` namespace should be place for utills which need more feedback from users. But in how many cases it is better place than plug-in? 

I think that all such things should be placed in `napari.experimental.feature_name` sub package. Because most of them may need modify more than one place. For example for new layers there  should be also some modification of interface. 
This should also simplify enabling/disabling such feature.
Such interface simplify also creating plug-ins which modify interface.

Some ideas which could be placed  in `experimental`

- multiprocessing interface similar to qthreading #1559 
- methods for extrapolate labelling along axis
- some part of multi camera view (Like in SimpleITK)

**Comment by adamltyson** [comment]
I also think it's a good idea. `tf.experimental` has always been clear to me (without ever really thinking about it).

(To me) early access to new features, and lowering the barrier of entry for contributions is always good. Agree that functionality shouldn't live in `napari.experimental` forever, and @neuromusic's idea for wiping the slate clean at every major release is a good one. It feels less arbitrary than a time limit.

While I understand the reasoning behind adding friction to use these features, I'd vote against anything that could add friction for users testing these features.

**Comment by quantumjot** [comment]
I think this is a great idea. Agree with @adamltyson that if we want feedback on experimental features, we should allow users to try them with minimal effort.

**Comment by goanpeca** [comment]
It seems some part of this ideas has been already implemented. Could we close this @sofroniewn ?

**Comment by sofroniewn** [comment]
Yes, we've decided to go with this approach in places, I will close now
