### ISSUE TITLE
Sanity checks for input arrays delayed in async code

### ISSUE THREAD

**Issue by jni** [napari/napari#1576]
In #1565, a sanity check for the rgb flag was added to the `on_chunk_loaded` method of the Image layer, see:

https://github.com/napari/napari/blob/67eb6908f77d93d064a69a6b4f6b48034ac60a90/napari/layers/image/image.py#L628-L633

In other words, this check is not done on layer creation, but rather every time that a chunk loads, which seems like overkill — it only needs to happen once, on the first load.

One idea would be to have single "verify correct load" method that is called asynchronously at layer creation time. This method would *not* be cancellable, it would always execute before the first actual "show". This gives us a chance to catch errors gracefully (rather than e.g. having NumPy broadcasting errors in random places), without cluttering the chunk loading code.

See [this discussion](https://github.com/napari/napari/pull/1565#discussion_r474665243) for details.

**Comment by pwinston** [comment]
Yes, there must be a much better way to do this. I just threw that in because without the error was very confusing. The error gave no indication the problem was RGB related, at least by my memory. It was a while ago.

Reproducing the error is probably the first step. And attaching it here. I think with async the "guess RGB" is not run on load. So you have to trust the user to set the "rgb" flag correctly. But they can set it incorrectly.

This is semi-related to something I've been ignoring. Which probably should be a separate issue. Sometimes on start Napari will access/load a bunch of slices right away. Maybe to determine the contrast limit? Like RGB this is maybe something that we might need to change for async. Maybe do it more on-the-fly as the data comes in to avoid the up front hit?

Both issues are sort of dealing with the fallout of async. Rather than async loads itself. But certainly both need to be addressed. And I suspect there's much more "fallout" once people start using it.

**Comment by sofroniewn** [comment]
> In other words, this check is not done on layer creation, but rather every time that a chunk loads, which seems like overkill — it only needs to happen once, on the first load.

@jni, see might comment here though about the fact that data can change dimensionality after the layer has been created, so this might actually be a little more complex, and we might need to keep checking more frequently. Comment posted below.

> I agree, something feels funny here, but it could represent something deeper than rgb/ async that we want to consider even more now. We do have it so that you can change the dimensionality of the image data by modifying the data property, similarly the multiscale/ rgb too, but I'm not sure if we should allow that - i.e. once you create a layer should the dimensionality/ rgb/ multiscale be fixed, this could dramatically simplify lots of things, while being a reasonable restriction in functionality. In the absence of this restriction, I think the checks that @pwinston has here might be critical and we might need more for "dimensionality changes" too.

**Comment by sofroniewn** [comment]
This `rgb` check was removed in #1659 and so this can be closed. If we need to revisit this topic we can reopen this issue or create a new one
