### ISSUE TITLE
Paint not showing until 3d mode activated

### ISSUE THREAD

**Issue by averypennington** [napari/napari#1631]
## 🐛 Bug

After updating to 0.37 (dev56) the paint tool isn't working. Paint doesn't show up when painting onto an image volume (99,256,256). However, if the '3d mode' (number of displayed dimensions) is activated, the paint is there.

## To Reproduce

1. Run examples/nD_labels.py
2. Select label layer, select paint brush, paint. Try to switch number of displayed dimensions.

## Expected behavior

The paint should appear under the brush as it is painted, with the expected paint colour and brush size.

## Environment

napari: 0.3.7.dev56+g4e954d3
Platform: Windows-10-10.0.17763-SP0
Python: 3.7.6 | packaged by conda-forge | (default, Jun 1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.5
SciPy: 1.4.1
Dask: 2.18.1
VisPy: 0.6.4

GL version: 4.4.0 - Build 21.20.16.4574
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.6
- svg: 0.1.4
 - Any other relevant information:

**Comment by jni** [comment]
I can reproduce this behaviour in master. Dang! Thanks for reporting @penningav! This is a bad regression so I hope we can fix it before 0.3.8!

**Comment by averypennington** [comment]
Not a problem, glad you guys are looking at it. That would be great. Cheers

**Comment by jni** [comment]
Looks like this is caused by #1607, based on git bisect.

**Comment by sofroniewn** [comment]
Yikes! I should be able to look into this tomorrow, thanks for reporting!! Sounds like it's not in the `0.3.7` release itself, just the latest version on master.

**Comment by sofroniewn** [comment]
Ok, I looked into this a little more. It is caused by these lines in #1607 https://github.com/napari/napari/pull/1607/files#diff-3ff6125a4ff917291bee7185ab645021R91-R94, 

```python
        if self.current_key is not None and self.current_key == request.key:
            # We are already showing this slice, or its being loaded
            # asynchronously.
            return None
```
Where we no longer update the image if the key hasn't changed. Unfortunately this update scheme doesn't take into consideration that the data itself may have changed. There maybe other ways to trigger the update in this case, and I'll leave it to @pwinston to suggest a fix and a test to prevent this from happening again.
