### ISSUE TITLE
pre-commit error

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1642]
## 🐛 Bug

Running into some problems with pre-commit, looks like it might be looking for python 3.8 but i'm on 3.7, will look into more later today

```python-traceback
(base) czirwc1macos2701:napari nsofroniew$ git commit -a -m "test_paint"
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/nsofroniew/opt/anaconda3/bin/python', '-mvirtualenv', '/Users/nsofroniew/.cache/pre-commit/repo4d9hx89r/py_env-python3.8', '-p', 'python3.8')
return code: 3
expected return code: 0
stdout:
    The path python3.8 (from --python=python3.8) does not exist

stderr: (none)
Check the log at /Users/nsofroniew/.cache/pre-commit/pre-commit.log
```

**Comment by sofroniewn** [comment]
@jni this may have been added in #1617, see https://github.com/napari/napari/pull/1617/files#diff-82c3b36709926de3a1b27bea0d8258ccR1-R2, we should fix asap

**Comment by jni** [comment]
Sorry about this. I somehow needed it when developing on Linux, where it was finding python 3.6, which had an old version of pip, which couldn't install isort (because it doesn't ship with a setup.py). It *also* wouldn't let me commit without committing the changes to pre-commit config. It was absolutely infuriating. Feel free to remove it. I could try some other solution.

BUT, the whole thing with pre-commit is that it creates a new environment to install stuff into, so maybe you can nuke your existing pre-commit env and try again?

**Comment by sofroniewn** [comment]
i had to change to 3.7 but then all my commits have that change!!

**Comment by jni** [comment]
Yeah it was the same for me — I didn't *want* to commit it, but I had no choice. It didn't occur to me to edit in the GitHub API, that was clever/sneaky of you. 😂
