### ISSUE TITLE
Ability to average over multiple slices along the viewing axis

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#1744]
## 🚀 Feature
The ability to average multiple slices along viewing direction in 2d viewer

## Motivation
Interpretation of 3D images with low signal to noise ratio often benefits from the on-the-fly projection of multiple slices along the viewing direction. This is often performed in popular cryo-electron tomography software such as 3dmod from the IMOD suite.

## Pitch
A small integer field or integer slider which would allow playing with the projected thickness of a 3D image viewed in 2D.

## Alternatives
Filters applied on 3D images can remove the requirement for this sort of visualisation trickery but tend to be expensive to compute when volumes get large

## Additional context
I see that in the `ChunkKey` object (`napari.components.chunk._request.ChunkKey`) associated with the `ImageSlice` (`napari.layers.image._image_slice.ImageSlice`) indices are already an attribute and that they default to `slice(None, None, None, None)` for x and y in 3d data. I guess this implies that the functionality for slicing the data is already there and just not exposed?

If someone can point me in the right direction I'd be happy to try to get this working with a small example dataset, I'm just not sure where the best place to start would be

**Comment by sofroniewn** [comment]
Welcome @alisterburt! Yes, this would be a very useful feature. If I understand your request correctly, there was some discussion of it here https://github.com/napari/napari/issues/7, which is one of the oldest napari issues still open!

The idea was to use a range slider with two independently movable endpoints (like our current contrast limits slider) to allow people to define a range for a slice instead of just a single point. You could then do a max projection on that slice.

In all we actually imagined 3 modes for the sliders:
- point slice (which is what we have now)
- range (which would do the max project as mentioned above)
- clip (which would clip the data, also possibly useful for 3D viewing).

Probably the biggest question is whether we want to try and leverage the graphics card and do this in a shader or just do it in the cpu (curious what @royerloic and @jni think about this, this has been @royerloic most requested feature for quite some time). Depending on what we choose here the implementation could end up being a little different.

We might also want to consider how to support things like the mixed 2D and 3D rendering that was prototyped in #839 and also non-orthogonal slicing as we decide how to support this. We could also start with a simple cpu approach and move to a gpu approach in time.

The key place in the code where the slice indices are determined right now is https://github.com/napari/napari/blob/master/napari/layers/base/base.py#L760-L816 and https://github.com/napari/napari/blob/master/napari/layers/base/base.py#L551-L583, these would need to be adjusted to handle a range of data.

**Comment by alisterburt** [comment]
Thank you!

This is great - lots to think about and I appreciate the links.

I hadn't considered a range slider as proposed and I can imagine it being extremely useful for certain tasks

In the context of what you've mentioned, I guess what I'm proposing is actually a "point slice" mode with an adjustable thickness parameter - for my main use cases I see two advantages over the range slider:
1.  requires the setting of only one parameter (slice thickness)
This makes "exploring" the data easier, in the case of the range slider this requires the shifting of the two ends of the slider (although this could equivalently be achieved by click-dragging the center of the slider...) 

2. natural extension to the hybrid 2D/3D mode
The slice would be shown in 3D at the point slice position but would be shown as the max projection over a range (defined by the thickness) around the point

Off topic from here:
Really happy to see the hybrid mode and hear that orthogonal slicing is being discussed! I'm not sure if you've ever come across the Dynamo software package for ET work but one of my favourite things about it is the [dynamo_tomoslice viewer](https://wiki.dynamo.biozentrum.unibas.ch/w/index.php/Dtmslice) which is a 2d-in-3d slicer type gui.

Two cool features in there which I'd love to see in napari some day are...
1. the ability to click and drag the slices to move them along the direction normal to the slice
2. the ability to save copies of current slices in the viewer then continue interacting with the image slice itself

**Comment by sofroniewn** [comment]
I wasn't familiar with the Dynamo software package, my background is more fluorescence imaging - so great to see some of the cryoET tools out there, thanks for sharing. I'd love us to be able to serve that community too!!

> in the case of the range slider this requires the shifting of the two ends of the slider (although this could equivalently be achieved by click-dragging the center of the slider...)

We have that center drag functionality in our contrast limits range slider right now and I think it works quite well, but we can see what's easiest to implement first.

You can actually see that we used to have something in our dims model called `interval` and a slicing mode, that was pulled out in https://github.com/napari/napari/pull/1539/files#diff-ab5508adaadc17d3bbef66e87273ee36aadc1f0ed993bb749c0280851fafd03bL35-L39 as they we're implemented on the Qt side or supported on the slicing side.

To get things going again, I could see the following:

- We might want to add back in the `interval` and slicing mode enum for our dims model
- Then on the Qt side have it swap between the scroll bar and the range slider when the slicing mode changed
- Then in the base layer rather than just use the point, use the point/ interval depending on the dims mode to do the slicing.
- Then maybe easiest in the vispy_image_visual we can do a cpu based max intensity projection, and send that to the graphics card. Doing the max intensity projection on the gpu would be possible if projecting in one dimension, but not more due to the current vispy API (the library we use for rendering). Maybe that's ok though.
- We'd probably want to roll back to point based slicing for all non-image layers at first, though it might be nice to support for our other layers later.

There's definitely some complexity hidden here though, so worth continuing to discuss!!

**Comment by alisterburt** [comment]
The point by point makes it all sound so manageable, thanks! - I'll have a play with reintroducing the interval and slicing mode first and see how many things I manage to break in the process... 

There are definitely lots of things Napari can be useful for in cryo-ET, looking forward to delving deeper!

**Comment by alisterburt** [comment]
Hmm, I got started on this (better late than never) and got stuck pretty quickly on how to properly initialise interval - it seems like now that range is in world coordinates there's no obvious way to initialise it to the full range of the image using properties of the dims model itself? 

My very minimal progress is here, for now it just initialises to point mode in all cases https://github.com/alisterburt/napari/commit/e8184247cd0d5979bd404e4c04095dbc4914848a

**Comment by sofroniewn** [comment]
> Hmm, I got started on this (better late than never) and got stuck pretty quickly on how to properly initialise interval - it seems like now that range is in world coordinates there's no obvious way to initialise it to the full range of the image using properties of the dims model itself?

Why not just initialize the interval to the full extent of the world coordinate range so it behaves like a full max projection?

**Comment by alisterburt** [comment]
doh - of course. For some reason I thought I had to be tightly bound to the
bounds of the data itself

**Comment by alisterburt** [comment]
Played with the Qt side a little bit - adding a `_create_interval_slider_widget` method to the `QtDimSliderWidget`. I reused the `QHRangeSlider` that you guys use for the contrast limits - I thought I'd ask for a bit of help before I get too lost in connecting this up and having it swap between the scroll bar and the range slider

What's the best way to get a review/help with what I've done so far, should I make a work-in-progress PR like #1817 ?

Current progress is here https://github.com/alisterburt/napari/commit/b0ff2e093e6be5af0d8b4a332bcd26783dc5d9f5

**Comment by sofroniewn** [comment]
Nice! Yes, a work-in-progress PR is a good way to start, that way we can continue to conversation over code. Agreed also it's best not to get too lost in the Qt stuff until confident everything else has the right shape. Looks like you're off to a good start on the dims side of things though.

**Comment by alisterburt** [comment]
I mean, reimplementing what had already been there with a step by step guide most definitely helped - I'll make a PR now, cheers!
