### ISSUE TITLE
Examples should only have dependencies that are in the requirements

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#179]
## 📚 Documentation
I think the scripts in the examples directory should be guaranteed to run immediately after a fresh installation (i.e., they should only have dependencies that are in the requirements). It's a little frustrating to do the installation, go to try out napari and then get a `ModuleNotFoundError`. What do you all think?

**Comment by kne42** [comment]
please

**Comment by kne42** [comment]
this is largely due to our dependency on scikit-image for images

if we get our own data module this should be easy

**Comment by kevinyamauchi** [comment]
I took a look and I think you're right - we would just need to have our own data module. In any case, I ran into this while checking out the shapes PR and the wait was worth it!

**Comment by jni** [comment]
I propose that we depend on scikit-image and we spend our energy improving the scikit-image data module rather than rolling our own. ;)

Another, probably better option is to add metapackages. `napari[core]` would contain only the bare requirements, `napari[full]` would contain bare requirements plus some extra convenience packages, ie stuff in `requirements/docs.txt`, such as skimage.
