### ISSUE TITLE
inconsistencies with `add_points` and `Points` signature for `text`

### ISSUE THREAD

**Issue by brisvag** [napari/napari#1833]
## 🐛 Bug

When while `add_points` accepts a dictionary for its `text` argument, setting a `Points` object's `text` attribute to a dictionary is impossible.

## To Reproduce

```python
import napari
import numpy as np

p = np.random.rand(5,3) * 100
pr = np.random.choice([True, False], (5,))
v = napari.Viewer(ndisplay=3)
text = {'text': 'pr', 'color': 'black'}

v.add_points(p, properties={'pr': pr}, text=text)   # this works fine
v.layers[0].text = text    # this raises an exception
```

the expection raised is:
```python
~/.local/lib/python3.8/site-packages/napari/layers/utils/_text_utils.py in format_text_properties(text, n_text, properties)
    150 
    151     # If the text value is a property key, the text is the property values
--> 152     if text in properties:
    153         formatted_text = np.array([str(v) for v in properties[text]])
    154         text_mode = TextMode.PROPERTY

TypeError: unhashable type: 'dict'
```

## Expected behavior

`text` attribute should be settable directly to a dictionary

## Environment

```
napari: 0.3.8
Platform: Linux-5.9.2-arch1-1-x86_64-with-glibc2.2.5
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.2
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6.0 NVIDIA 455.28
MAX_TEXTURE_SIZE: 16384

Plugins:
- mrcfile-reader: 0.1.2
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

**Comment by sofroniewn** [comment]
Thanks for the detailed bug report @brisvag, sounds like this should be fixed. Maybe @kevinyamauchi has additional thoughts.

**Comment by kevinyamauchi** [comment]
Hello @brisvag , thank you for this report! I agree that this was an oversight and we should allow text and associated properties to be set via a dictionary as one can with the `add_*()` and `view_*()` methods. I am a bit slammed at the moment, but I can take a crack at this in the coming weeks. Alternatively, a PR would be most welcome and I would be happy to coach you or anybody interested through it!

**Comment by kevinyamauchi** [comment]
@brisvag, I am following up on your [zuplip post ](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/text.20bug.20.231833/near/220089885)(easier to link code snippets here):

Your intuition is correct. To allow the user to update multiple text properties with a dictionary, we need to be able to pass a set of new property values through the `layer.text` setter. On the `TextManger` side, we would need to add a method to update a set of properties (ideally from a dictionary).

Converting `TextManager` to a dataclass has recently become more of a priority. Also, @Czaki added a nice `update_from_dict()` method to our `evented_dataclass` (#1966). Given those two things, I think the most efficient path forward is to convert the `TextManager` to an `evented_dataclass`. It would be great if you wanted to work on that!

I would recommend the following:
1. Check out @tlambert03 's awesome `evented_dataclass` docs in #1965.
2. @tlambert03 has made a PR (#1485) starting to convert `TextManager` to an `evented_dataclass` (see [this file](https://github.com/napari/napari/blob/3ea0fc7a9bac5682c75595f874773dac8a4d8c10/napari/layers/utils/text.py)). I think it is worth starting a new PR since there are changes there we won't need (e.g., implemented in other PRs). However, it is a great starting point. Just note there are a couple of syntax changes (e.g., we have renamed the decorator from `@dataclass` to `@evented_dataclass`)
3. Convert `TextManger` to an `evented_dataclass`. We may need to overload the `update()` method, as setting text requires passing in variables that aren't attributes  of the class in order to update the text (e.g., the layer properties).
4. Add a conditional to the `layer.text` setters that pass a dictionary to the `TextManager.update()` method.

How does this sound? Getting this started was on my to-do list for the week, but I have a few other things on my plate, so I think this will go a lot faster if you take this over (happy to help as much/little as you like)! Alternatively, if converting `TextManager` to an `evented_dataclass` is more work than you had in mind (totally understandable), I can get the conversion started in a PR over the next day or two and you can take over, adding the update method. Please let me know what you prefer!

**Comment by Czaki** [comment]
> Converting `TextManager` to a dataclass has recently become more of a priority. Also, @Czaki added a nice `update_from_dict()` method to our `evented_dataclass` (#1966). Given those two things, I think the most efficient path forward is to convert the `TextManager` to an `evented_dataclass`. It would be great if you wanted to work on that!

this method is `update`, not `update_from_dict`. It was changed during the discussion. Implementation still named `update_from_dict`. But for evented dataclass it is set `setattr(cls, 'update', update_from_dict)`

**Comment by kevinyamauchi** [comment]
Good catch, thanks @Czaki !

**Comment by brisvag** [comment]
I took a look at some of the code, you linked: converting `TextManager` to a an evented dataclass seems indeed a bit too much for me at the moment! but I would definitely like to follow up if you lead the way, @kevinyamauchi.

**Comment by kevinyamauchi** [comment]
Sounds good! I will ping you when I've started the PR.

**Comment by sofroniewn** [comment]
I think this is no longer an issue as add_points now just calls to Points, but maybe @brisvag or @andy-sweet could take a look/ give this a thought before we close. Thanks!!

**Comment by brisvag** [comment]
No, this problem still exist. It's not about the inconsistency between `Points` and `add_points`, but the one between these two when passed a `text` argument and `Points.text = something`!

**Comment by andy-sweet** [comment]
The idea in [PR 3277](https://github.com/napari/napari/pull/3327) is to recreate the `TextManager` in the `Points.text` setter, and to call that setter in the `Points` constructor. And to do the same with `Shapes`, and with whatever else has text.

That solves this inconsistency problem, but does require us to reconnect some signals (i.e. in the corresponding vispy layer) when recreation happens.

**Comment by andy-sweet** [comment]
Assigned to myself, because I'm hoping to fix this with [PR 3277](https://github.com/napari/napari/pull/3327).
