### ISSUE TITLE
Plugin system currently makes it impossible for plugins to receive multiple files (with drag-and-drop)

### ISSUE THREAD

**Issue by jni** [napari/napari#1883]
## 🐛 Bug

We always envisioned that reader plugins should be able to receive a *list* of paths, see the hookspec [here](https://napari.org/docs/dev/plugins/hook_specifications.html#napari.plugins.hook_specifications.napari_get_reader). This would allow us to read formats that depend on multiple files being present (e.g. shape files together with projection files).

However, @DragaDoncila and I found that napari currently does **not** allow plugins to receive more than one path, ever! That's because [`viewer.open`](https://github.com/napari/napari/blob/53b54e010bd8947904b62afb07640faabeb1ddf0/napari/components/add_layers_mixin.py#L276-L340) [calls `viewer._add_layers_with_plugins`](https://github.com/napari/napari/blob/53b54e010bd8947904b62afb07640faabeb1ddf0/napari/components/add_layers_mixin.py#L333-L338) separately for each given path! (Unless `stack=True` from the command-line.)

In my opinion, we should *first* try to find a plugin that will happily read the full list, and if *that* fails, then we call a plugin separately for each file.

**Comment by Tomaubier** [comment]
Hi, Is there any temporary fix to get around this issue?

**Comment by tlambert03** [comment]
Hi @Tomaubier, from the looks of it, I'm afraid there's nothing that a plugin can do to get multiple files with drag and drop.  that would need to be fixed in napari core.

@jni, I _think_ this was actually the original intention based on this text in the hookspec docs:

> path may be either a str or a list of str. If a list, then each path in the list can be assumed to be one part of a larger multi-dimensional stack (for instance: a list of 2D image files that should be stacked along a third axis). Implementations should do their own checking for list or str, and handle each case as desired.

In other words, plugins were always only ever going to get a list of paths if the user had indicated the desire that they be stacked.  

I can definitely see the limitation though, so perhaps we should change the default behavior here, or allow a keyboard modifier to indicated "stack" when dropping files into the napari viewer?

**Comment by psobolewskiPhD** [comment]
@DragaDoncila is this still relevant with npe2? 

> allow a keyboard modifier to indicated "stack" when dropping files into the napari viewer?

This is implemented, `Shift` will do that. Not sure how this works with plugins though.

**Comment by DragaDoncila** [comment]
@psobolewskiPhD I have confirmed that readers do indeed get the full list of paths, whether this is by holding `Shift` with drag'n'drop or from `Open Files as Stack` in the GUI. When neither of these things is true, they get each file one by one. So I think that's desired/expected behaviour and we can close this. 

I think the final thing we might want to do w.r.t. plugins and multiple files is formalize passing through the `stack` keyword all the way to plugin readers. Right now receiving a list implicitly means "please stack these", but it might be nice to actually pass the keyword and add it to the manifest as well, so that plugins can declare whether or not they stack files (or if they do both depending on the keyword). I could've sworn we had issues tracking this but couldn't find one just then on quick search...
