### ISSUE TITLE
Python 3.9, macOS Big Sur napari will not run from command line

### ISSUE THREAD

**Issue by harripj** [napari/napari#1889]
## 🐛 Bug

On MacOS Big Sur napari will run from an inline interpreter but not directly from the terminal as 'napari' or 'python -m napari'. python.app will bounce in the dock.

This can be solved by ```export QT_MAC_WANTS_LAYER=1``` in the terminal or, by adding it in within ```_run_pythonw``` as ```env['QT_MAC_WANTS_LAYER'] = '1'``` before calling subprocess. [Credit.](https://forums.macrumors.com/threads/pyqt5-and-big-sur.2260773/post-29243620)

## To Reproduce

1. Python 3.9, MacOS Big Sur in terminal run:
2. napari
3. python -m napari

## Expected behavior

napari will run.

**Comment by sofroniewn** [comment]
Thanks for this report @harripj and that proposed solution! I think @Czaki and @tlambert03 have seen something similar too.

I wonder if we should make a PR to set that by default before in the appropriate case before our `0.4.1` release? I can just imagine a lot more people running into this. Thoughts @Czaki @tlambert03 @jni?

I'm linking to #1393 too as we've been discussing Big Sur issues there too

**Comment by tlambert03** [comment]
for those who find this thread... do look at https://github.com/napari/napari/issues/1393#issuecomment-727261662 too, as it also explains that,  in order to use BigSur:
- python 3.9 is _non-optional_ ... (until a backport is issued to 3.8)
- vispy (version 0.6.5), one of our main dependencies currently doesn't import on python 3.9... and until  vispy/vispy#1914 is released, a manual patch is required.

**Comment by Czaki** [comment]
As I read about Big Sur I could expect multiple bug reports connected with it. I do not have plans to upgrade to this system (I have only access to one MacOS device). Maybe someone know a good method to run the new release in a virtual machine? 

Not all python distributions contain `pythonw` (for example one installed with `pyenv` does not). So bugfix should be more general. 

As I understand @tlambert03 is currently the best person to ask because he has access to a machine with BigSur system.

**Comment by sofroniewn** [comment]
Closed by #1894
