### ISSUE TITLE
Large multiscale zarrs slow on pan/zoom when clipped

### ISSUE THREAD

**Issue by ahnsws** [napari/napari#1942]
## 🐛 Bug

Hello, I'm very excited to incorporate napari into our histology workflow, but we are encountering an issue that degrades UX. Passing a list of dask arrays from an image pyramid makes pan and zoom very slow (several seconds per frame), getting worse with larger images. If I pass only the base level of the pyramid, then interactions are **silky smooth**.

## To Reproduce

1. Create a moderately sized zarr pyramid:

```python
import numpy
import skimage.data as data
import zarr
from skimage.transform import pyramid_gaussian


def create_zarr(path: str, image: numpy.ndarray, chunk_size: int = 512) -> None:
    pyramid = pyramid_gaussian(image, downscale=4, max_layer=4, multichannel=True)

    store = zarr.DirectoryStore(path)
    with zarr.group(store, overwrite=True) as group:
        series = []
        for i, layer in enumerate(pyramid):
            path = "base" if i == 0 else f"L{i}"
            group.create_dataset(path, data=layer, chunks=(chunk_size, chunk_size, 3))
            series.append({"path": path})

        multiscales = [{"name": "pyramid", "datasets": series, "type": "pyramid"}]
        group.attrs["multiscales"] = multiscales


create_zarr("./image.zarr", numpy.tile(data.astronaut(), reps=(10, 10, 1)))
```

2. Load the zarr into napari

```python
import os
from typing import List

import dask.array as da
import napari


def get_pyramid(path: str) -> List[da.Array]:
    levels = ["base"] + sorted(
        [s for s in os.listdir(path) if (not s.startswith(".")) and (s != "base")]
    )
    return [da.from_zarr(f"{str(path)}/{level}").rechunk() for level in levels]


pyramid = get_pyramid("image.zarr")

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_image(pyramid)  # [0])  # add this in to load only the base layer

```

## Expected behavior

Buttery smooth UI when a pyramid is passed in, not just for a single image.

## Environment

```
napari: 0.4.0
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.6 | packaged by conda-forge | (default, Oct 7 2020, 18:22:52) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.18.5
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6.0 NVIDIA 452.57
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

## Performance traces

See `multiscale.txt` for the trace when panning with a pyramid. See `single.txt` for the trace when panning with a single image. (Renamed from json to txt for upload purposes)

[single.txt](https://github.com/napari/napari/files/5598784/single.txt)
[multiscale.txt](https://github.com/napari/napari/files/5598785/multiscale.txt)

**Comment by sofroniewn** [comment]
Hi @wooahn, sorry about this! I havn't had a chance to try and replicate yet, so don't know if there is a big regression lately that might be making things but worse, but I will say that `512x512x3` is fairly modest in size for chunks, especially if you occasionally have to load four of them to fill one field of view.

Curious how performance feels for you if you drop down to `128x128x3` say.

I'm also not sure about the `rechunk` call to dask. It shouldn't be needed and I wonder if it might be slowing things down.

I'll try and look into this more soon. We've also got some exciting experimental work on asynchronous and tiled rendering that will be much faster and should be ready for testing soon!

**Comment by ahnsws** [comment]
Hi @sofroniewn, thanks for responding so quickly!

I've just tried creating the zarr with a chunksize of 128 and removed the call to `rechunk`, but the image is still very slow to pan and zoom. I only had the rechunk in there because I was working with some large SVS and SCN files and I noticed that rechunking improved performance for those kinds of files.

I have also tried to use the following `async.json` file using `NAPARI_ASYNC`, but the performance improves only slightly, at least from what I can tell using the performance widget (`NAPARI_PERFMON`).

```
{
  "synchronous": false,
  "num_workers": 8,
  "use_processes": false,
  "force_delay_seconds": 0
}
```

When I have some spare time I'd be happy to provide call graphs from pstat, like #1885 .

**Comment by ahnsws** [comment]
When the image is fully within the view, pan and zoom is silky smooth, but as soon as the pyramid is clipped, the performance degrades substantially. I don't notice any impact whatsoever on clipping for single images. Upgrading from numpy 1.18.5 to 1.19.4 didn't change anything either.

**Comment by sofroniewn** [comment]
Hi @wooahn, I just gave this a try and your example as given above is slow for me too. Performance got better if I used `preserve_range=True` on the `pyramid_gaussian` and then `dtype='uint8'` when making the zarr (instead of `float64` which things are now), but I'm not sure if that is an acceptable temporary solution for you.

It'll really be `NAPARI_OCTREE=1` that improves the performance for our multiscale datasets, but we're not quite there yet. Still it might be good for @pwinston to do some testing with a toy datasets like the one above you mention, and when the octree is ready for further testing we'll let you know!! Should be in the next week or two.

**Comment by ahnsws** [comment]
Oh interesting. Yeah those adjustments definitely help, but even though our images are already in uint8, they're quite large so they get pretty sluggish anyway. Also, if I pass in the full pyramid and the napari window itself is small, I can interact with the image just fine, but as soon as I maximize the window to my screen (2560x1440) and the image starts clipping that's when it gets slow (a few frames per second).

Thanks again for looking into this!

**Comment by jni** [comment]
> Also, if I pass in the full pyramid and the napari window itself is small, I can interact with the image just fine, but as soon as I maximize the window to my screen (2560x1440) and the image starts clipping that's when it gets slow (a few frames per second).

This is expected. Currently with pyramids, with every small pan we create a new "view" of the underlying array (potentially requiring IO if there is no caching implemented), *and* we send that view to the GPU. The size of said view is controlled by the canvas size, so for a big display, you are sending a huge array over to the GPU every single time you reveal a new pixel, which, we know, is ridiculous. 😂 For a small window size, the array that you are sending is much smaller, so performance is acceptable.

We are working on this! Thank you for your patience! 😬

**Comment by ahnsws** [comment]
Great! Looking forward to you guys' work on incorporating octrees.

**Comment by ahnsws** [comment]
Correction: using `NAPARI_ASYNC` actually improves performance by a fair bit, although not quite silky smooth (panning a moderately sized image of 13000x6000 on 1440p). I must not have set it properly earlier.

**Comment by pwinston** [comment]
Is the PR description verbatim what you are using to test @wooahn?

I can test with `NAPARI_OCTREE=1` and see how it compares. It's less done than `NAPARI_ASYNC`. But if this is a good test case, I can try to make it work.

Ultimately octree should result in the best performance. But it might not be there today.

**Comment by ahnsws** [comment]
Yep, I am using that exact code, except for changes in what I pass to `reps` when making the zarr. For the below, I used `reps=(20, 10, 1)`. Edit: sorry, `reps=(10, 10, 1)`

I was able to get the master branch set up (after setting `NAPARI_OCTREE`, `NAPARI_MON`, and fixing line 140 in `qt_test_image.py`), but then I get the following stacktrace:

```
Octree input data has 5 levels:
    Level 0: 5120 x 5120 = 26.2 million pixels -> 20 x 20 = 400 tiles
    Level 1: 2560 x 2560 = 6.6 million pixels -> 10 x 10 = 100 tiles
    Level 2: 1280 x 1280 = 1.6 million pixels -> 5 x 5 = 25 tiles
    Level 3: 640 x 640 = 409600 pixels -> 3 x 3 = 9 tiles
    Level 4: 320 x 320 = 102400 pixels -> 2 x 2 = 4 tiles
In 0.078ms created 0 levels:
Tree now has 5 total levels.
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/_qt/event_loop.py", line 79, in gui_qt
    yield app
  File "/home/sebastian/PycharmProjects/sandbox/napari-issues/view.py", line 23, in <module>
    viewer.add_image(pyramid)  # [0])  # add this in to load only the base layer
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/components/viewer_model.py", line 771, in add_image
    return self.add_layer(image_class(data, **kwargs))
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/image/experimental/octree_image.py", line 58, in __init__
    super().__init__(*args, **kwargs)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/image/image.py", line 278, in __init__
    self._update_dims()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/base/base.py", line 518, in _update_dims
    self.refresh()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/base/base.py", line 896, in refresh
    self.set_view_slice()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/base/base.py", line 791, in set_view_slice
    self._set_view_slice()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/image/experimental/octree_image.py", line 444, in _set_view_slice
    self._slice = OctreeMultiscaleSlice(
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/image/experimental/_octree_multiscale_slice.py", line 37, in __init__
    self._octree = Octree(slice_id, data, slice_config)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/napari/layers/image/experimental/octree.py", line 69, in __init__
    assert self.levels[-1].info.num_tiles == 1
AssertionError

```

**Comment by ahnsws** [comment]
It seems like `NAPARI_OCTREE` is sensitive to the downscale parameter from layer to layer in the pyramid. If I change `downscale` from 4 to 2 in the call to `pyramid_gaussian`, I get the following stacktrace:

```
Octree input data has 5 levels:
    Level 0: 5120 x 5120 = 26.2 million pixels -> 20 x 20 = 400 tiles
    Level 1: 2560 x 2560 = 6.6 million pixels -> 10 x 10 = 100 tiles
    Level 2: 1280 x 1280 = 1.6 million pixels -> 5 x 5 = 25 tiles
    Level 3: 640 x 640 = 409600 pixels -> 3 x 3 = 9 tiles
    Level 4: 320 x 320 = 102400 pixels -> 2 x 2 = 4 tiles
In 5.535ms created 1 levels:
    Level 5: 160 x 160 = 25600 pixels -> 1 x 1 = 1 tiles
Tree now has 5 total levels.
tiles: 0 -> 4 create: 4 delete: 0 time: 33.774ms
WARNING: Error drawing visual <TiledImage at 0x7f17f44c5f40>
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/home/sebastian/miniconda3/envs/sandbox/lib/python3.9/site-packages/vispy/gloo/glir.py", line 1537, in set_data
    raise ValueError("Type %r not allowed for texture" % data.dtype)
ValueError: Type dtype('float64') not allowed for texture

```

and I can't see the pyramid I passed in, but I can see the red grid overlay.

**Comment by pwinston** [comment]
Your first case the error is saying your root level had more than one tile. Real data does not always build the pyramid down until there is a single tile. Of course not, it doesn't know what size tile were are using.

But I added a pretty lengthy feature so it will take your pyramid and extend it until it does the root does contain a single tile. Looks like in your case that code is not running. I wonder if it's not in your version or something? Or it's just not running it?

For the second case it seems pretty clear we don't support `float64` yet. That's an easy fix I can try to put it in tomorrow. Basically it's something `Image` did that's not yet in `TiledImageVisual` but not hard to add.

**Comment by pwinston** [comment]
At the top of `TextureAtlas2D.add_tile()`  under the line `data = octree_chunk.data` I'll probably try adding these lines from `Image._build_texture()`:

    if data.dtype == np.float64:
        data = data.astype(np.float32)

At least as a starting point. I can look at that tomorrow.

**Comment by pwinston** [comment]
As for the levels I see in your second case it did create an extra level. So I think that's a bug. I think the "create extra levels until you end up with a single tile" feature is not working in your case. If you file a separate issue with a repro case that leads to that `AssertionError` I can take a look at it.

A "this valid input leads to an assert" issue, which is different from this general slowness issue.

**Comment by pwinston** [comment]
@wooahn I created a PR to fix the `float64` issue: https://github.com/napari/napari/pull/1976

Also, that will report a nice exception if the downscale ratio is not 2.

In your case the exception is now:

    ValueError: Multiscale data has downscale ratio of 4.0, expected 2

It never occurred to me anyone would use anything but 2, so that's an assumption that's baked in pretty deeply. However, with effort, we could support other ratios. One way might be to create "virtual levels" that have no data themselves, but kind of reference another level's data. Or just fully break the assumption.

With the fix, it works but not super smooth. It's blocking on something. Not sure what. That should not happen, if it's slow the chunks might come in slow but it shouldn't chug the frame rate. I'll have to look into it. Hopefully, it's not the `float64` to `float32` conversion. I can't imagine it would be.

Probably GPU/texture related. I haven't yet put in the thing that amortizes the RAM->VRAM loads over a number of frames. That's something we planned to do on day 1 but just has not been a problem yet.

So today if you pop to a new quadtree level you might load 10 tiles in one frame. We can easily do one per frame and it will only take 300ms if you are going 60Hz. So might be time for that. One quirk of that is we need a timer because it needs to happen even if you stop moving the mouse. Right now we only draw on camera movement. But in this case, there'd be a little queue, and you have to keep drawing until the queue is empty, even if there is no movement.

Most games just draw constantly all the time. But for napari we are trying to keep it so it goes fully idle. Which I think is a good goal for napari/desktop type programs.

**Comment by ahnsws** [comment]
Got it, thanks. I'm not quite familiar with the innards of napari and the GPU yet so thanks for bearing with me.

With some brightfield images that I am working with, the downscale parameter is 4, which was why I had set the repro code to that value. I'll see how that PR does from my end in a bit.

**Comment by pwinston** [comment]
Great. I think supporting any downscale, even varied between levels, would be nice. But I could see that feature being pushed out for a while since using 2 is pretty common and does work well for most uses.

**Comment by pwinston** [comment]
<img width="1084" alt="Screen Shot 2020-12-02 at 2 24 25 PM" src="https://user-images.githubusercontent.com/4163446/100921209-38628f00-34aa-11eb-9a0a-7d45a30bc2ca.png">

Yeah it goes along pretty well then a really slow frame, than gets slowly faster. Not sure what, whatever is I'm not timing it explicitly. I'll look into it.

**Comment by pwinston** [comment]
<img width="795" alt="Screen Shot 2020-12-02 at 2 35 54 PM" src="https://user-images.githubusercontent.com/4163446/100922292-b7a49280-34ab-11eb-9a0a-f2d273b2fb70.png">

Yeah, when it pops to this level it needs to load 36 256x256 tiles from RAM to the GPU. Each takes like 50ms which is way too long. But I think the first step is to amortize it down to one load per frame. So that would take 36 frames if it's doing 20Hz it's almost 2 seconds. For now, it will go black and then you see them popping in.

The next step is to keep rendering the old tiles, even though they are "too big". Basically, you draw each parent tile until its 4 children are ready, then you swap. That will give you the standard tiled rendering thing where things just get a bit blurry then tile by tile they can clearer. All within 2 seconds.

So those are two separate steps neither totally simple, but neither requires invention it's just wiring it up. So I can look at those this week hopefully.

Then I would circle by to why 50ms to load one tile... In a game you might load hundreds of textures in 5ms, just going from RAM to VRAM is fast. So 50ms for one 256x256 texture is slower than we'd like.

<img width="663" alt="Screen Shot 2020-12-02 at 2 40 59 PM" src="https://user-images.githubusercontent.com/4163446/100923247-ec651980-34ac-11eb-946f-deecb05a4be6.png">

**Comment by sofroniewn** [comment]
> The next step is to keep rendering the old tiles, even though they are "too big". Basically, you draw each parent tile until its 4 children are ready, then you swap. That will give you the standard tiled rendering thing where things just get a bit blurry then tile by tile they can clearer. All within 2 seconds.

Yeah, this would be beautiful, also if we got that working on the edges too, so that when you panned it didn't pop to black, but to something blurry, would be great too

**Comment by pwinston** [comment]
Yeah, panning is similar. You can help panning a lot just by loading more same-level tiles, like expand the intersected frustum a bit on all sides. So no multi-level required. But then loading coarser levels should be in the mix somewhere, since that gets you more coverage faster.

In general, we need two systems that don't exist yet. One is a priority queue of things to load, from various locations and various levels. On-screen, nearly on screen, next/prev slices, one level up, two levels up, etc. With some "policy" that we can tweak and tune. And offer some config options, mostly how aggressive to pre-cache stuff.

The second system is during rendering a way to render the "best available" data, wherever it is. This is just like a very fast search process. Mostly it's drawing the current level. But in some cases, it might have to hunt around. Maybe we load at the root tile (one 256x256 texture) up front, as the worst-case fallback. We might be inside a single pixel of that, but at least it's something.

Really it should be easy to make it look good once we have the machinery/vocabulary to describe what we want to happen. All of this was planned since day one. We are just getting there now.

**Comment by pwinston** [comment]
We might be able to do some of this inside `TiledImageVisual`. Which would be totally different from Raveller. `TiledImageVisual` does not know anything about an octree or even a grid. It just has "tiles" which can be a rectangle anywhere in space, even in 3D space ultimately, like a billboard along a highway, but let's say 2D for now. So the tiles can be overlapping. We don't overlap them today, we do in fact feed it a grid, but the tiles could overlap and be different sizes.

Suppose you do have a grid of tiles, and you are zooming in. Now suppose you just start throwing in new smaller tiles. If using draw order or z-buffer you make sure that smaller tiles draw after the bigger ones, it would do the right thing. Then you just need a way to evict tiles that are totally covered up.

It would work for same-level tiles offscreen too, just fine. And even the root tile catch-all, although you wouldn't want to evict that in case it became uncovered. That could be a policy, "add this perma-tile" and then "add this tile, but evict it when covered", etc.

That's not a crazy idea. The nice thing is `TiledImageVisual` knows nothing about octrees or grids. So it's complicated because it can handle this soup of overlapping tiles. But it's simpler because it just has a list of tiles: x, y, width, height. No notion of levels or grids or edges or corners.

This is good because intersections are still handled at the Octree level where non-rendering users can get at them. But this mixed-level stuff is really a rendering thing. I don't think anyone else needs that. Who wants to deal with a mixed-level patchwork of data at various resolutions, changing over time? Rendering does, but this keeps all that in the visuals.

Although zooming OUT you want the big tiles to be drawn on top, and evict the smaller tiles. Maybe you always want newer tiles to take precedence... I think so, because why would you ever feed the visuals worse data than you previously gave it? There's a recency bias. New data should always come from the latest viewpoint, so by definition data from that viewpoint should supplant older data. Once enough new data is available.

The draw-order and the eviction are the interesting part. But juggling a bunch of 2D rectangles seems pretty easy and fast. Is this tile fully covered by newer tiles? If so kick it out, unless it's locked in there. Have to think about that. Worth trying though. It seems better than juggling all that inside the octree code, which is how Raveller did it.

**Comment by pwinston** [comment]
With the above PR we now incrementally load the tiles which prevents the big hang, if the tiles are in RAM and just need to go to VRAM. Loading off disk is still a hang which we need to investigate, so the first time it will hiccup, but after that, you can zoom in/out pretty well.

A follow-on PR will be continuing the draw the old tiles until the new ones replace them.

**Comment by pwinston** [comment]
With #2010 merged this is improved. Please give it a try @wooahn. Let me know. I created a `uint8` version of the image instead of `float64`. Although `float64` is a valid torture test, the `uint8` version contains all the same information and is much smaller.

However, it's still not nearly as smooth as the pre-octree version. To achieve that we'd need to add a special "small multiscale image" mode. We would need to detect the image is small enough to fit in VRAM and just load the whole thing into VRAM. Either before it's even displayed, or every quickly within the first few seconds.

We've been 100% focused on large multi-scale images that don't fit in RAM. For those, we purposely only want to load in what is currently being viewed. However this image is so small (5k, 5k) we could easily load the whole thing.

I think special support for "small multiscale images" is on the road map. But not sure when it will happen.

Long term I'm hoping the `OctreeImage` class will replace the `Image` class. For that to happen it will have to support degenerate octrees with only one level, potentially with only one tile. The max texture size is (16k, 16k) on my laptop. So you could create a pretty large image as a single tile. Although then transferring to VRAM is a hiccup, but if you do it once on load? Have to experiment.

For `OctreeImage` to replace `Image` it must efficiently render every time of image: small/big, single-scale/multi-scale. We are definitely not there yet.

Feel free to leave this open until that support is added. Or close it as "good enough for now", either way.

**Comment by pwinston** [comment]
There might other stuff we can do to speed it up besides just loading it all. For instance, bring back synchronous loading. Pre-octree we would auto-detect if a layer was loading very quickly and switch to synchronous. We've disabled that for now, because for octree we'd need to meter the number of loads. That is, each load might be fast, but we can't afford to load 40 chunks in one frame. We should only load N per frame.

**Comment by pwinston** [comment]
Oh and one more thing that would help. We only transfer one tile into VRAM per frame. Because transferring them all was a huge hiccup. But one is probably too few for some data. Ideally set can set a budget like 20ms and transfer as many as we can in that time period.

The difficulty is we can't just time them. Because the cost of the transfer is not felt until you call `glFlush()` and the card takes over. It will do the transfer. So we have to anticipate that cost. We have to decide "let's transfer four because that will fit in our budget".

More we can do long term to make things faster.

**Comment by ahnsws** [comment]
Great! Let me take a look.

**Comment by psobolewskiPhD** [comment]
Updating the OP code example:
```
import numpy
import skimage.data as data
import zarr
from skimage.transform import pyramid_gaussian


def create_zarr(path: str, image: numpy.ndarray, chunk_size: int = 512) -> None:
    pyramid = pyramid_gaussian(image, downscale=4, max_layer=4, channel_axis=2)

    store = zarr.DirectoryStore(path)
    with zarr.group(store, overwrite=True) as group:
        series = []
        for i, layer in enumerate(pyramid):
            path = "base" if i == 0 else f"L{i}"
            group.create_dataset(path, data=layer, chunks=(chunk_size, chunk_size, 3))
            series.append({"path": path})

        multiscales = [{"name": "pyramid", "datasets": series, "type": "pyramid"}]
        group.attrs["multiscales"] = multiscales


create_zarr("./image.zarr", numpy.tile(data.astronaut(), reps=(10, 10, 1)))
```
and
```
import os
from typing import List

import dask.array as da
import napari


def get_pyramid(path: str) -> List[da.Array]:
    levels = ["base"] + sorted(
        [s for s in os.listdir(path) if (not s.startswith(".")) and (s != "base")]
    )
    return [da.from_zarr(f"{str(path)}/{level}").rechunk() for level in levels]


pyramid = get_pyramid("image.zarr")

viewer = napari.Viewer()
viewer.add_image(pyramid)  # [0])  # add this in to load only the base layer
```
I cannot reproduce seconds per frame of choppiness.
When zooming in or out there is a brief hiccup when the level changes, but panning is always smooth.

**Comment by psobolewskiPhD** [comment]
I retested this and everything seems fine with the script above.
Also tested with the new experimental async on the example from above post is even better on zoom but you do see tiles loading at the edges when panning a zoomed in view.
Still, no "several seconds" delays. 
I think this issue can be closed, even is other performance issues may remain.
