### ISSUE TITLE
AttributeError in dataclass.py with Python 3.9

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1954]
## 🐛 Bug

Running latest master under Python 3.9 I get this error:

```
  File "/Users/pbw/dev/napari/napari/utils/events/dataclass.py", line 318, in <dictcomp>
    n: _te._strip_annotations(t) for n, t in original_annotations.items()
AttributeError: module 'typing_extensions' has no attribute '_strip_annotations'
```

## To Reproduce

1. Just start napari.

## Environment

napari: not-installed
Platform: macOS-10.15.6-x86_64-i386-64bit
Python: 3.9.0 (default, Nov 15 2020, 06:25:35) [Clang 10.0.0 ]
Qt: 5.15.2
PySide2: 5.15.2
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2.30.0
VisPy: 0.6.5.dev279+g74d9461d

GL version: 2.1 ATI-3.10.15
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4

**Comment by jni** [comment]
Thanks for raising, @pwinston!

Reference to conversation on Zulip:

https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Our.20dataclass.2Epy.20with.203.2E9/near/218056588

I *think* that probably the purpose of this function was to remove `Annotated[]` in versions of Python prior to 3.9, since some typing tools might not have understood it. See [PEP-593](https://www.python.org/dev/peps/pep-0593/) for details about the Annotated mark.

As such, I expect that the function has been removed altogether in 3.9. My proposed solution is to grab the code from the 3.8 version of `typing_extensions` and vendor it somewhere in napari.

**Comment by sofroniewn** [comment]
> As such, I expect that the function has been removed altogether in 3.9. My proposed solution is to grab the code from the 3.8 version of typing_extensions and vendor it somewhere in napari.

That sounds good to me. Do you think @jni that we should also start testing 3.9, especially once the new vispy release comes out? See https://github.com/conda-forge/napari-feedstock/pull/17#issuecomment-734896344
