### ISSUE TITLE
min req test failing, numpy/ pandas

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2045]
## 🐛 Bug

Starting in #2044 (though unrelated to that PR) our min requirements tests is failing. It looks like something to do with pandas/ numpy https://cirrus-ci.com/task/6267832738512896

**Comment by alisterburt** [comment]
Had a quick look, pandas updated to 1.2.0 and with that came an increase their minimum version of numpy

Here are a few milestones
- pandas 1.0.0 released Jan 29 2020 -> numpy 1.13.3
- pandas 1.1.0 released July 28 2020 -> numpy 1.15.4
- pandas 1.2.0 released Dec 26 2020 -> numpy 1.16.5

I had a quick look at `setup.cfg` and napari doesn't directly depend on pandas

A solution could be to force a lower pandas version in the testing requirements (https://github.com/napari/napari/blob/master/requirements/test.txt). I can see the downsides to doing that, but because pandas isn't a direct dependency it can't be updated in `minreq.py` (https://github.com/napari/napari/blob/master/tools/minreq.py) like it's done for the others.

I could add a similar script `minreq_tests.py` or similar which pins the version of pandas in `requirements/test.txt` and add that to the CI config for the minimum requirements tetsts?

**Comment by sofroniewn** [comment]
Closed by #2050
