### ISSUE TITLE
How to properly setup napari on windows?

### ISSUE THREAD

**Issue by colinmarcus** [napari/napari#2057]
OK, I have been trying for 2 days now to get Napari properly set up, with only partial success. I can launch Napari from the terminal but not from inside a python script. The README instructions specify `pip install napari[all]` - this does not work.

I am on Win10, operating in the conda environment. I am happy to create a new conda env if someone can post a **tested** and **complete** set of commands that leads to a fully working Napari installation.

BTW, one of the main issues I have noticed is that `pip install napari[all]` does not install a sufficiently updated version of QT. I tried doing `conda update -c conda-forge qt`, which updated the QT version to 5.12.9 but somehow broke Napari completely.

I suspect that many people would benefit from a very **complete** and well-written guide to installing Napari. Please keep in mind, many of us are scientists trying to view 3D data - we are not computer science experts who understand all the ins and outs of setting up environments etc etc.

Ideally, setting up Napari should be as easy as setting up commonly used libraries like matplotlib. I feel Napari occupies a position of high importance as it seems to be the only really good 3D visualization tool for python right now (though feel free to prove me wrong).

**Comment by jni** [comment]
Hi @colinmarcus, and happy new year! May 2021 bring you a working napari installation. 😜

More seriously, I'm sorry for the installation issues you're having. We'll try to help you out! We've tried to balance being comprehensive and being overwhelming in our [installation tutorial](https://napari.org/tutorials/fundamentals/installation). In your case, since you are already working with conda-forge, I would definitely suggest trying `conda install -c conda-forge napari`, rather than going the pip route.

Obviously we agree that we are the "only really good 3D visualization tool for Python" which is why we started the project! 😊 So thanks for saying that! But we are still a young project with limited resources and a very platform-dependent tool chain, which makes it hard to cover all the installation bases. In particular, there's about a million ways to install and run Python, especially on Windows. (See [this Twitter poll and responses](https://twitter.com/jnuneziglesias/status/1338331202231529473), for example!) But, we are always happy to try to help you out, learn from your experience, and hopefully improve our guidance in response.

Can you try a new environment with `conda create -y -n napari-cf -c conda-forge python=3.8 napari` followed by `conda activate napari-cf` and see if that works for you? If it doesn't, could you report your script and the specific error you're seeing? (For sharing complete scripts, I recommend posting to gist.github.com.)

**Comment by tlambert03** [comment]
for anyone stumbling on this issue:

>  I tried doing `conda update -c conda-forge qt`, which updated the QT version to 5.12.9 but somehow broke Napari completely.

"`qt`" is not something we suggest installing anywhere (`pyqt` or `pyside` perhaps... but not `qt` directly).  Trying `conda create -y -n napari-cf -c conda-forge python=3.8 napari` as @jni suggested is great.  But if you did try the (exact) installation method that we recommend in the readme [here](https://github.com/napari/napari#from-pip-with-batteries-included) or in our tutorials [here](https://napari.org/#installation):
```
conda create -y -n napari-env python=3.8
conda activate napari-env
pip install napari[all]
```

and you still have problems, then we'd like to know about it. Please tell us (more specifically) what's not working and post the output of `conda list`

**Comment by liu-ziyang** [comment]
going to close this issue, for anyone having trouble installing napari on windows, please see https://napari.org/#installation
