### ISSUE TITLE
pytest --pyargs is broken by test_examples.py

### ISSUE THREAD

**Issue by jni** [napari/napari#2108]
## To Reproduce

1. `pip install --pre napari[pyqt5,testing]` in a fresh environment
2. run `pytest --pyargs napari`

Error:

```pytb
 $ NAPARI_POPUP_TESTS=1 pytest --pyargs napari
============================= test session starts ==============================
platform darwin -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
PyQt5 5.15.2 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
rootdir: /Users/jni
plugins: napari-plugin-engine-0.1.9, timeout-1.4.2, qt-3.3.0
collected 1610 items / 1 error / 1609 selected

==================================== ERRORS ====================================
_ ERROR collecting conda/envs/napari-043rc/lib/python3.8/site-packages/napari/_tests/test_examples.py _
conda/envs/napari-043rc/lib/python3.8/site-packages/_pytest/python.py:1309: in _idval
    generated_id = idfn(val)
conda/envs/napari-043rc/lib/python3.8/site-packages/napari/_tests/test_examples.py:39: in <lambda>
    ???
conda/envs/napari-043rc/lib/python3.8/pathlib.py:1038: in __new__
    self = cls._from_parts(args, init=False)
conda/envs/napari-043rc/lib/python3.8/pathlib.py:679: in _from_parts
    drv, root, parts = self._parse_args(args)
conda/envs/napari-043rc/lib/python3.8/pathlib.py:663: in _parse_args
    a = os.fspath(a)
E   TypeError: expected str, bytes or os.PathLike object, not NotSetType
```

I'm not sure what the best fix is... The *quick* fix is to remove `test_examples.py` from the distribution. I don't think the examples themselves are even packaged?

We should also create an element in the test matrix to test in this way, to make sure we catch this in the future. I think we had one but I guess it was lost in the move to GitHub Actions. I'm not quite sure how to do this with tox, though. My guess is to add an entry `pyargs` [here](https://github.com/napari/napari/blob/6beb6153d10c13d9b52161ee4dae65068959c649/tox.ini#L89) that does `cd; pytest --pyargs napari`, and then add an entry to the test matrix that adds that tox setting? CC @tlambert03

**Comment by tlambert03** [comment]
good catch, sorry about that.
for fixing the test itself, we could either exclude `test_examples.py` in MANIFEST.in as you say ... or we can add a `pytest.skip` marker to the test if it doesn't find the examples folder.  preference @jni?

I'm working on the best way to test it.  This is made kind of tricky at the moment, because we are temporarily [skipping `test_examples` on CI](https://github.com/napari/napari/blob/6beb6153d10c13d9b52161ee4dae65068959c649/napari/_tests/test_examples.py#L7-L10) due to segfault issues that need to be figured out (#2094).  So, we need to make that skip a little more refined, otherwise `pytest --pyargs napari` will work no matter what we do.  options include:
1) have a github actions test where we skip the checkout step, and simply pip install directly from github, specifying the commit sha: `pip install git+git://github.com/${{ github.repository }}.git@${{ github.sha }}#egg=napari[all,testing]` ([here](https://github.com/tlambert03/napari/actions/runs/485387708/workflow) is an example of that ... currently passing because of the CI skip mentioned above)
2) do something with tox.  I don't think the `cd` strategy is going to work (tested locally, still passed)... Interestingly, this is an argument for having a `src` directory in the repo (ugly though it may be).  There is a very good blog post (and links) on this exact issue [here](https://hynek.me/articles/testing-packaging/), and [advice from pytest here](https://docs.pytest.org/en/stable/goodpractices.html#tests-outside-application-code) (these have led me to adopt the `src` layout in other packages with more complicated builds).
3) we could go ahead and include the examples as a separate package in the sdist!  rename them to `napari_examples` (so they are next to napari in the `site-packages` folder)... we could also modify our cli so that someone could do `napari demo add_image`

thoughts @jni?

**Comment by sofroniewn** [comment]
> we could go ahead and include the examples as a separate package in the sdist! rename them to napari_examples (so they are next to napari in the site-packages folder)... we could also modify our cli so that someone could do napari demo add_image

I like this idea, or something similar, I think shipping the examples is nice and a good way to get someone started with napari.
