### ISSUE TITLE
Text is not shown for initially empty point layers

### ISSUE THREAD

**Issue by jwindhager** [napari/napari#2115]
## 🐛 Bug

When working with initially empty point layers, the text labels of points added by the user are not displayed.

## To Reproduce

```py
import napari
import numpy as np

from PIL import Image

# fix DecompressionBombErrors
Image.MAX_IMAGE_PIXELS = None


def on_click(layer, event):
    if layer.mode == 'add':
        # assign the next ID to the current point
        layer.current_properties['id'][0] = max(layer.properties['id'], default=-1) + 1
    elif layer.mode == 'select':
        # print properties (for debugging purposes only)
        print(layer.properties)


with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.open('/path/to/file.png')
    # Note: the necessity to specify **potential** property values here is limiting!
    points_layer = viewer.add_points(properties={'id': np.arange(1000)}, text='id')
    points_layer.mouse_drag_callbacks.append(on_click)
```

## Expected behavior

The IDs are displayed next to the points added by the user

## Environment

napari: 0.4.2
Platform: Linux-5.4.0-60-generic-x86_64-with-glibc2.31
Python: 3.9.1 (default, Dec 11 2020, 14:32:07) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2020.12.0
VisPy: 0.6.6

GL version: 4.6.0 NVIDIA 460.32.03
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.9
- svg: 0.1.4

## Additional context

Use case: selecting control points in two images for image registration

**Comment by jwindhager** [comment]
My current workaround is adding the following to the example code above:
```py
    @points_layer.events.current_properties.connect
    def text_workaround(event):
        points_layer.text = 'id'
```

However, this workaround does not (directly) allow for using dictionary definitions of `text`, see https://github.com/napari/napari/issues/1833

**Comment by kevinyamauchi** [comment]
Hello @jwindhager ! Thank you for making this issue! I agree that this is not the ideal behavior. One should be able to create an empty `Points` layer with the text property already specified and then when a point is added, the corresponding text element gets added. I think this shouldn't be too difficult to add, but I have a few things in the queue right now.

A bit of context about requiring potential properties to be specified when creating an empty layer with properties: We did it this way because we wanted it so if the user created an empty layer with properties and then through the GUI they added a point, that new point would be assigned property values. However, I can see how this would be annoying. We are happy to hear any suggestions you may have about improving the behavior!

**Comment by jwindhager** [comment]
Thank you for the insight and for handling this, @kevinyamauchi !

> A bit of context about requiring potential properties to be specified when creating an empty layer with properties: We did it this way because we wanted it so if the user created an empty layer with properties and then through the GUI they added a point, that new point would be assigned property values. However, I can see how this would be annoying. We are happy to hear any suggestions you may have about improving the behavior!

I'd suggest to change the signature to `properties: Union[None, list[str], dict[str, Optional[list]]] = None`:
- `list[str]` for simply specifying a list of property names
- `dict[str, Optional[list]]` for specifying property names together with potential values
