### ISSUE TITLE
[multithreading] Passing args/kwargs to a worker callback function

### ISSUE THREAD

**Issue by sumanthratna** [napari/napari#2136]
## 🚀 Feature
I'd like to be able to pass arguments to a callback function that I've connected to. This should work for at least the following APIs:
- `worker.{signal}.connect(callback)`
- `@thread_worker(connect={signal: callback})`
(since the above two APIs seem to be the most high-level + easy-to-use)

## Motivation

e.g., if my callback is `viewer.add_image` and I want to pass `blending='additive'` to the callack call

## Alternatives

an easy way to implement this is to simply add `*args` and `**kwargs` where appropriate and pass these when calling the callback. I haven't thought about this much so I'm not yet sure if I would actually like this API (I'm a little hesitant about the `*args` part; it might cause confusion/decrease code readability)

## Additional context

n/a

**Comment by tlambert03** [comment]
hi @sumanthratna!  do you happen to have a code example of what you're trying to do?  I looked through viewmask to see where you might be trying to apply this, but couldn't find it.

Currently the `thread_worker` API has a [fixed set of callbacks](https://napari.org/docs/0.3.7/events/threading.html#responding-to-feedback-from-threads), like `returned` or `yielded` which are called with the value returned or yielded by the decorated function.  By definition, these things will _always_ be a single value (since functions can only return/yield a single value... though it can be a complex one, like a dict or a tuple).  So generally, the best way to accomplish what you're trying to do here is to have your worker yield or return a dict or a tuple, and then make a simple callback function that will unwrap those into the "real" callback that you want.  As an example:

```python
# this works fine if you only have a single argument
@thread_worker(connect={'returned': viewer.add_image})
def make_image():
    return np.random.rand(512,512)

# but if you want something more complex
def my_callback(value):
    viewer.add_image(**value)

@thread_worker(connect={'returned': my_callback})
def make_image_with_parameters():
    return {'data': np.random.rand(512,512), 'blending': additive}
```

does that accomplish what you're looking to do?

**Comment by sumanthratna** [comment]
> hi @sumanthratna! do you happen to have a code example of what you're trying to do? I looked through viewmask to see where you might be trying to apply this, but couldn't find it.

I haven't yet started implementing async or multithreading, but out of my own interest I wanted to experiment with it by using multithreading to add multiple objects to the napari viewer concurrently. e.g., adding a shapes layer, a points layer, and an image layer in viewmask

> does that accomplish what you're looking to do?

it does! When I thought of this issue I was thinking of `functools.partial` but it seems very verbose. If you see the "Alternatives" section in my original post, that would look something like this:
```python
make_image_with_parameters = thread_worker(
    make_image, 
    connect={'returned': viewer.add_image}, 
    blending='additive',
)
```

I admit, the more I think about this, the more ugly it looks. I'll close this issue since I think it's safe to stick with verbosity, so I'll go with what you suggested. Thank you @tlambert03!

**Comment by tlambert03** [comment]
> something like this:
> ```
> make_image_with_parameters = thread_worker(
>    make_image, 
>    connect={'returned': viewer.add_image}, 
>    blending='additive',
> )
> ```

ahh, I see. yes in that case (if you _always_ wanted your callback called with `blending=additive`) then I'd say partial is a very good solution there:  `connect={'returned': partial(viewer.add_image, blending='additive')}`
