### ISSUE TITLE
Discussion: Intended use of `experimental_provide_function...` hookspec

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2150]
Just want to bring a few scattered conversations into one location:
- https://github.com/jni/affinder/pull/12#issuecomment-763871037 (and the following discussion)
- https://github.com/napari/napari/pull/2143

The question is about the current `experimental_provide_function_widget` hookspec that was conceived in #1816 and implemented in #2080.  I think everyone is in agreement that we want an entry point for plugins to provide pure functions that could be assembled and chained in some sort of computational graph, ideally with a node-based gui front end.  I think @sofroniewn (and it sounds like @jni too?) envisioned `experimental_provide_function_widget` to _be_ that hookspec. 

Perhaps missing the point, _I_ was actually the one that added the `_widget` suffix, because as I saw it A) the only concrete internal use of that spec at the moment is adding a widget to the viewer with `window.add_function_widget`... and B) the hookspec docstring itself takes a set of `magic_kwargs` that are used to build a widget.  I think if I had known that others saw this hookspec as the start of the functional analysis plugins, I would have raised some more concerns at the time.  In addition to the fact that we really don't know how it's going to be used internally yet (which I think is sufficient reason to hold off on adding it), I also feel like we don't yet have enough of a type inference infrastructure to make much use of functions that may or may not be annotated at all.  Basically, I'm not sure we should start offering a hookspec that we know we _want_ to use someday, but aren't quite sure how yet.

With #2143 and with https://github.com/napari/magicgui/pull/117, users can _still_ build widgets from functions, but with those two PRs, the pattern changes from _us_ using `magicgui` internally, using the function and kwargs they provided to `provide_function_widget`, to _plugin developers_ using `@magic_factory` in their own repository (if they want to), and everyone being able to use a single hookspec `provide_dock_widget` inasmuch as they'd like to offer up a widget for the viewer.  Together, that lets us delay the decision of whether we even need to use or depend on `magicgui` directly, and it would let us (for now) drop the `provide_function_widget` hookspec until we have a clearer idea as to how it's going to be used.  It arguably becomes less confusing which hookspec you're supposed to use (now you just make a widget class-like however you want, and give it to us in `provide_dock_widget`).

I'm personally slightly in favor of dropping `provide_function_widget` for now... along with all the machinery in `plugins.__init__` and `qt_main_window.py`

**Comment by sofroniewn** [comment]
Thanks for making this issue for dedicated discussion @tlambert03, I think you capture the prior context nicely.

> I'm personally slightly in favor of dropping provide_function_widget for now... along with all the machinery in plugins.__init__ and qt_main_window.py

I share your concerns about the possibility of greater confusion now #2143, but I think I'd prefer to press on with `provide_function_widget`, restricting it's API, rather than drop it entirely. I think the fact that I'm now able to update my toy-segmentation plugin to not depend on napari or magicgui or qt is pretty cool and still valuable - even if the only thing we do right now with the that plugin is generate a magicgui widget.

> that lets us delay the decision of whether we even need to use or depend on magicgui directly

I don't mind us depending on magicgui, I don't think the development process is that much more painful, and I think it's ok that people are now have to use the latest magicgui, but curious if you see bigger negatives that I'm missing. I love magicgui :-)

> I also feel like we don't yet have enough of a type inference infrastructure to make much use of functions that may or may not be annotated at all. Basically, I'm not sure we should start offering a hookspec that we know we want to use someday, but aren't quite sure how yet.

The point about the types is fair very fair, but I think having this hookspec is how we'll learn a lot of what those needs are. It might be that in 6 months from now we make a new hookspec called `napari_provide_analysis_function` and `napari_experimental_provide_function_widget` ceases to exist, but I think we'll be much better developing and iterating on `napari_experimental_provide_function_widget` in the main repo rather than in branches/ PRs to get there. I'm already using it quite a bit and having fun!

One option for `0.4.4` though might be to rollback some of the API complexity / possibilities for that hookspec. So no more `magic_kwargs` dict, no more `dock_widget_kwargs` dict. Just a callable or a list of callables, that we treat in the same way as we treat now. We'll handle decisions like `layout`, and `auto_call` etc. using defaults or more introspection. If we can't recognize a type or something isn't annotated properly we'll throw an error.

I'd also suggest that we switch to passing ReadOnly versions of napari objects to the functions - so possibly using this great snippet you send me back on zulip the other week.

```python
import napari
import wrapt


class ReadOnly(wrapt.ObjectProxy):
    def __getattr__(self, name):
        return ReadOnly(getattr(self.__wrapped__, name))

    def __setattr__(self, name, value):
        print("Cannot set read only view")

    def __repr__(self):
        return repr(self.__wrapped__)


viewer = napari.Viewer()
roviewer = ReadOnly(viewer)
```

When functions are registered we can look for napari types and convert them to be `ReadOnly` types and then leverage the magicgui stuff as before, so that we won't break the normal work flow for magicgui users.

I think if we make these changes for `0.4.4` and if everything with the hookspec goes horribly wrong we can say - it's ok, use our other hookspec `provide_dock_widget`, we know that will work, and we'll just learn so so much that I don't think we'd get from more discussions alone.

How does this sound? I could work on a PR to make this conversion this weekend, but I might need some help from you along the way :-)

**Comment by tlambert03** [comment]
> I think the fact that I'm now able to update my toy-segmentation plugin to not depend on napari or magicgui or qt is pretty cool and still valuable - even if the only thing we do right now with the that plugin is generate a magicgui widget.

If you want to keep it and use it, that's certainly a very strong reason to do so! :) 

> but curious if you see bigger negatives that I'm missing. I love magicgui :-)

nope, no big negatives... just always being mindful of dependencies we can drop :).  i like it too! 😄 

> The point about the types is fair very fair, but I think having this hookspec is how we'll learn a lot of what those needs are.

I agree with that sentiment. (particularly if we make a conscious effort to actually hook this up to something other than widget generation)

> One option for 0.4.4 though might be to rollback some of the API complexity / possibilities for that hookspec. So no more magic_kwargs dict, no more dock_widget_kwargs dict.

fine with me, would you still be able to do what you needed with segmentation plugin without those though?  (or would the answer to that just be in the introspection and/or sane defaults you proposed?)

> I'd also suggest that we switch to passing ReadOnly versions of napari objects to the functions

I ... I'm honestly not sure how i feel 😄 !  with the dock widgets allowed to stay powerful, i think I'm ok with that? curious if @jni wants to make a case here.  Would you want this to apply to people who use `viewer.window.add_dock_widget` with a `@magicgui` instance that they manually added?  Or just the `function_widgets` plugins?

> How does this sound? I could work on a PR to make this conversion this weekend, but I might need some help from you along the way :-)

sounding pretty good to me so far.

**Comment by sofroniewn** [comment]
> fine with me, would you still be able to do what you needed with segmentation plugin without those though? (or would the answer to that just be in the introspection and/or sane defaults you proposed?)

I think so, but that will be the first test!!! [Note i'll try this asap, before working on PR :-)]

>  Would you want this to apply to people who use viewer.window.add_dock_widget with a @magicgui instance that they manually added? Or just the function_widgets plugins?

I'd want to leave all the `viewer.window.add_dock_widget` + `@magicgui` behavior as is, and just change `viewer.window.add_function_widget` and thereby getting `provide_function_widget` hookspec for free. Might be challenging technically, but I think we could do it.

> I agree with that sentiment. (particularly if we make a conscious effort to actually hook this up to something other than widget generation)

I'm also thinking it could be a place for us to experiment more with multithreading for plugins in a "safe" more constrained way (thinking about your comment https://github.com/chanzuckerberg/napari-plugin-alfa-cohort/issues/21#issuecomment-765800513 for example).

**Comment by sofroniewn** [comment]
I'm going to close this now that #2158 has merged, but we should definitely have further discussions about the functional hookspec on new issues!
