### ISSUE TITLE
Passing a large Xarray as a Labels layer can cause memory explosions

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2190]
## 🐛 Bug

If you have a moderately large (e.g. `(5, 10, 1024, 1024)`)  `xarray.DataArray` then drawing on the labels layer becomes very slow, or napari will crash due to out of memory.

## To Reproduce

```python
import napari
import numpy as np
import xarray as xr

img = xr.DataArray(np.random.rand(2, 5, 1024, 1024))
mask = xr.DataArray(np.zeros_like(img,dtype=np.int))

# uncomment these to use numpy and all is fine
# img = np.random.rand(2, 5, 1024, 1024)
# mask = np.zeros_like(img, dtype=np.int)

with napari.gui_qt():
    viewer = napari.view_image(img, name='img')
    labels = viewer.add_labels(mask, name='mask')
```

## Expected behavior
I'd expect the labels layer to work fine with either Xarray or numpy, the same as the image layer.

## Reason
This is due to this line:
https://github.com/napari/napari/blob/88ef14e4a97a24491a8e3de15df1c0ed3b4da167/napari/layers/labels/labels.py#L843

and differences between xarray and numpy when doing fancy indexing. For a full explanation of the differences read http://xarray.pydata.org/en/stable/indexing.html#vectorized-indexing. The short of it is:

```python
import xarray as xr
import numpy as np

da = xr.DataArray(
    np.arange(24).reshape((2, 3, 4)),
)
slice_coords = (
    [0, 0, 0],
    [0, 0, 0],
    [0, 1, 3],
)
print(da[slice_coords].shape)
```
gives
`(3, 3, 3)`
which can end up attempting to allocate a massive amount of memory.

whereas:
```python
slice_coords = (
    xr.DataArray([0, 0, 0]),
    xr.DataArray([0, 0, 0]),
    xr.DataArray([0, 1, 3]),
)
print(da[slice_coords].shape)
```
gives the same results as when indexing a numpy array: `(3,)` which is a reasonable amount of memory.

## Environment
napari: 0.4.5.dev1+g58677b5
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.31
System: Pop!_OS 20.04 LTS
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 1920x1080, scale 1.0

Plugins:
- svg: 0.1.4

**Comment by ianhi** [comment]
This also generalizes a little in that it seems that other non-numpy arrays are not well supported by the labels layer.
dask : doesn't support assignment so doesn't work
zarr : fails with what seems like a bug (xref https://github.com/napari/napari/issues/470) 

```python
import napari
import numpy as np
import zarr

img = np.random.rand(2, 5, 1024, 1024)
mask = zarr.zeros_like(img, dtype=np.int)

with napari.gui_qt():
    viewer = napari.view_image(img, name='img')
    labels = viewer.add_labels(mask, name='mask')
    labels.mode = 'paint'
```

```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 443, in mousePressEvent
    self._vispy_mouse_press(
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/vispy/app/base.py", line 181, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/ian/Documents/oss/napari/napari/_qt/qt_viewer.py", line 673, in on_mouse_press
    mouse_press_callbacks(layer, event)
  File "/home/ian/Documents/oss/napari/napari/utils/interactions.py", line 101, in mouse_press_callbacks
    next(gen)
  File "/home/ian/Documents/oss/napari/napari/layers/labels/_labels_mouse_bindings.py", line 33, in draw
    layer.paint(layer.coordinates, new_label)
  File "/home/ian/Documents/oss/napari/napari/layers/labels/labels.py", line 856, in paint
    self.data[slice_coord] = new_label
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/zarr/core.py", line 1122, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/zarr/core.py", line 1217, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/zarr/core.py", line 1506, in _set_basic_selection_nd
    indexer = BasicIndexer(selection, self)
  File "/home/ian/mambaforge/envs/napari-dev/lib/python3.9/site-packages/zarr/indexing.py", line 283, in __init__
    raise IndexError('unsupported selection item for basic indexing; '
IndexError: unsupported selection item for basic indexing; expected integer or slice, got <class 'numpy.ndarray'>
```

**Comment by jni** [comment]
Thanks for raising this @ianhi, and for #2191!

tbh, I'm not super in love with the solution though, which leads down the road of a gigantic try/except if/else cascade for each array type.

Other relevant links:
- zarr-developers/zarr-python#657
- https://numpy.org/neps/nep-0021-advanced-indexing.html

(Note that the NEP has been in draft for years, and is essentially abandoned due to lack of interest...)

My own personal view is that other array libraries should match NumPy's indexing behaviour. That doesn't solve the problem for a very long time though. =\

Not sure what the best course of action is, then. We could make an exception here to get you unstuck, we could adopt xarray internally (we've been discussing that for a while), or something else I'm not seeing right now.

Note that all of the failing examples fail *only at write time*, right? In general, I would never expect painting into a dask array to work, but we should probably fail gracefully in these cases.

**Comment by ianhi** [comment]
> (Note that the NEP has been in draft for years, and is essentially abandoned due to lack of interest...)

:cry: :cry: :cry: 

> tbh, I'm not super in love with the solution though, which leads down the road of a gigantic try/except if/else cascade for each array type.

I understand now that xarray/zarr etc are not fully supported everywhere, but I think the issue was that all my experience with napari up till this bug led me to believe that they were as supported internally as numpy. This was both through my experience with the Image layer and from this part of the [labels docs](https://napari.org/tutorials/fundamentals/labels):
![image](https://user-images.githubusercontent.com/10111092/106303853-a5836e00-6228-11eb-80d5-7f87c12fd991.png)


> Not sure what the best course of action is, then. We could make an exception here to get you unstuck, we could adopt xarray internally (we've been discussing that for a while), or something else I'm not seeing right now.

I don't an exception for my sake makes sense, but I also may be just be the first xarray user to bring this up and more people will run into this in the future. I don't have a good sense of how xarrray vs others are trending but if people are trending towards xarray then maybe an exception makes sense? Also, is there a clear policy on what array-likes napari fully supports? Is it just numpy?

Big :+1: to xarray internally I really enjoy using it. It docs still have a strong meterology bent, but when I filled out their [user survey](https://forum.image.sc/t/xarray-2021-user-survey/47259) there seemed to be a real awareness that it could be made more general and in particular useful for biosciences etc.

Finally, would it be more appealing if this kind of indexing fixing for arrays got thrown into a util functions somewhere that could be called wherever this sort of indexing happens? Then at least the try/except cascade could be contained.



> Note that all of the failing examples fail only at write time, right? In general, I would never expect painting into a dask array to work, but we should probably fail gracefully in these cases.

Yeah this alone would have saved me a lot of time debugging the code that came prior to napari. Perhaps raising a dialog / raise an exception if you try to draw on a non-numpy array? It may also be worth adding some comments to docstring. In particular I took `array-like` to include `lists, numpy, xarray, dask, pytorch, etc...` . So if not all of those work a line saying something like "writing to the labels will only work for a numpy array"

**Comment by sofroniewn** [comment]
> > (Note that the NEP has been in draft for years, and is essentially abandoned due to lack of interest...)
>
> 😢 😢 😢

There are some efforts to keep this standardization going from quansight - see https://data-apis.org/blog/array_api_standard_release/ and I think napari will want to benefit from that as much as possible! I havn't looked at their latest progress, but maybe we should check it out. In the meantime I'll try and answer some of your questions and think about how we can move forward.

> I understand now that xarray/zarr etc are not fully supported everywhere, but I think the issue was that all my experience with napari up till this bug led me to believe that they were as supported internally as numpy.

Yeah, we should update the docs to make it clear that those other array types are only supported right now for viewing and not editing labels until this is fixed. Apologies the docs are misleading!

> Yeah this alone would have saved me a lot of time debugging the code that came prior to napari. Perhaps raising a dialog / raise an exception if you try to draw on a non-numpy array? It may also be worth adding some comments to docstring. In particular I took array-like to include lists, numpy, xarray, dask, pytorch, etc... . So if not all of those work a line saying something like "writing to the labels will only work for a numpy array"

This is also a good idea until we have everything working!

> Also, is there a clear policy on what array-likes napari fully supports? Is it just numpy?

For viewing arrays we support anything where `np.asarray` returns a numpy array on and basic indexing works, for editing arrays it's more complex as you have noted and I think it's just numpy that fully works now. We have a test for array-like viewing here https://github.com/napari/napari/blob/v0.4.4/napari/_tests/test_numpy_like.py, which covers some basic viewing for the Image layer, but nothing for Labels and editing. If we get this working (like in #2191) we should add tests there for that use case.

I'll take a more detailed look at #2191 when I get the chance and will comment on possible implementations/ things we can do now over there.

**Comment by jni** [comment]
> Also, is there a clear policy on what array-likes napari fully supports? Is it just numpy?


I don't think we have a clear policy, but I would state it as: we support NumPy and other arrays that support the NumPy API. The NumPy API, though, is massive, so that was never a clear target. Different array libraries have implemented different parts of the API. The data APIs blog post that @sofroniewn linked to shows an attempt to remedy the situation, and [here is the draft spec](https://data-apis.github.io/array-api/latest/API_specification/array_object.html). The [indexing](https://data-apis.github.io/array-api/latest/API_specification/array_object.html#getitem-x-key) and [indexing + assignment](https://data-apis.github.io/array-api/latest/API_specification/array_object.html#setitem-x-key-value) are still TODO, though there is a draft spec [here](https://data-apis.github.io/array-api/latest/API_specification/indexing.html), but it does not mention fancy indexing, which is absolutely necessary for labels painting.

> "writing to the labels will only work for a numpy array"

That particular line isn't quite accurate — @AbigailMcGovern has got zarr painting working using [tensorstore](https://google.github.io/tensorstore/). The code is still a bit raw but you can check it out [here](https://github.com/jni/pia-tracking/blob/fa3fcb14f3afc14ea62213ae5ecb8188954931d8/correct_labels.py).

Other arrays such as zarr *would* be supported if they added fancy indexing to their `__getitem__` and `__setitem__` methods. I think it's more an issue of community effort than of technical difficulty.

As to xarray... Well, since they went a different way with fancy indexing, it would be a harder sell for them. 🤦 

I'm not closed to the idea of special-casing xarray, though, especially if it gives us yet another way to write to on-disk stores — would it?

**Comment by tlambert03** [comment]
> I'm not closed to the idea of special-casing xarray, though, especially if it gives us yet another way to write to on-disk stores — would it?

fwiw, I would support special-casing xarray in this case.  It's super-dreamy to imagine a day when every array library uses the same interface, but if there are use cases that have very clear benefit and might take years to support otherwise, I think a rare exception or two could be made.  given how often we discuss potentially using xarray internally, and how napari it appears to be used with napari, it seems like a fine candidate for special casing.

**Comment by ianhi** [comment]
> I'm not closed to the idea of special-casing xarray, though, especially if it gives us yet another way to write to on-disk stores — would it?

I think it might provide the ability to work with zarr. See http://xarray.pydata.org/en/stable/io.html#appending-to-existing-zarr-stores although it's all very `xarray.DataSet` focused rather than `xarray.DataArray`. Though I think it is currently workable, and will likely improve.

> That particular line isn't quite accurate — @AbigailMcGovern has got zarr painting working using tensorstore. The code is still a bit raw but you can check it out here.

Nice! That's pretty slick.

> fwiw, I would support special-casing xarray in this case. It's super-dreamy to imagine a day when every array library uses the same interface, but if there are use cases that have very clear benefit and might take years to support otherwise, I think a rare exception or two could be made. given how often we discuss potentially using xarray internally, and how napari it appears to be used with napari, it seems like a fine candidate for special casing.

Big :+1:  from me obviously. I found it hard to go back now that I've started working with labelled dimensions. Would this also imply that special casing would be ok for https://github.com/napari/napari/issues/14?

**Comment by tlambert03** [comment]
> Would this also imply that special casing would be ok for #14?

yeah ... I was specifically thinking about things like #14 (and, indirectly, things like https://github.com/napari/napari/issues/2229 ... where xarray would provide at least one form of metadata that we could leverage)

**Comment by sofroniewn** [comment]
> Big 👍 from me obviously. I found it hard to go back now that I've started working with labelled dimensions. Would this also imply that special casing would be ok for #14?

Yeah, let's give it a try. I'm not ready to depend on xarray or use it internally as our data model, but if at a few key places in the repo we check if given an xarray that's ok. It looks like dask does that using `type(a).__module__.startswith("xarray.")` which means we don't even need to import xarray, see https://github.com/dask/dask/blob/d096fdeecc3dc0bdf1afa3ba6ce53cedae59dd7d/dask/array/core.py#L4092

[Edit: in #2191 we actually need the import for a reason, but otherwise we could just do the above]
