### ISSUE TITLE
Add some qt helpers for qactions, menus and shortcuts

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2196]
## 🚀 Feature

With the need for configurable shortcuts and allowing plugins to extend the Napari interface it would help to create some helpers to assist in the creation of actions, menus and assigning shortcuts to these actions.

## Motivation

Simplify the creation of actions. Locate the shortcut definition in a single place, instead that directly in parts of the code.

## Pitch

A common pattern found in the codebase:

```python
open_images = QAction('Open File(s)...', self._qt_window)
open_images.setShortcut('Ctrl+O')
open_images.setStatusTip('Open file(s)')
open_images.triggered.connect(self.qt_viewer._open_files_dialog)
```

We could replace this by something like:

```python
open_images = create_action(
    id_='some_unique_action_identifier',
    text='Open File(s)...',
    parent=self._qt_window,
    tip='Open file(s)',
    triggered=self.qt_viewer._open_files_dialog,
)

# Shortcut definition
shortcuts = {
    'some_unique_action_identifier': 'Ctrl+O',
}

```

This allows to define the global shortcut configuration in a single place, or per plugin and tie the shortcuts to actions by using some unique ID that can then match the shortcut to the action, when things are updated.

#### Menus

We can also add some helper to menu creation so that we can define sections on menus that would include separators as needed:

```python
add_item_to_menu(menu, actions, section="Edit options")

add_items_to_menu(menu, actions, section="Edit options")
```

## Alternatives

N.A.

## Additional context

`create_action` would keep a reference to all the defined actions when created.

**Comment by sofroniewn** [comment]
Yes, I love this idea! You'll notice now there are a number of different ways we do this, and standardizing it by using some helper functions would be much appreciated.

Going one step further, you may have noticed already that we have two different ways that keybindings can be added - one is with a decorator that goes on our individual layers/ viewer and is largely Qt independent - see for example things in this [_viewer_key_bindings.py](https://github.com/napari/napari/blob/v0.4.4/napari/components/_viewer_key_bindings.py) or [_labels_key_bindings.py](https://github.com/napari/napari/blob/v0.4.4/napari/layers/labels/_labels_key_bindings.py) - AND - inside [qt_main_window.py](https://github.com/napari/napari/blob/v0.4.4/napari/_qt/qt_main_window.py) when we add a shortcut next to a menubar item.

We might also want to eventually use this opportunity to bring these together so that there is only one way to register a keybinding and if you register that keybinding then you'll also get a menubar option (I'm not sure if that is normal in most software, i.e. if you have a keybinding is there also a menubar option, but it seems like reasonable practice to me). We've got a number of threads like #1321 and https://github.com/napari/napari/issues/1272#issuecomment-767163381 already about keybindings so I don't want to hijack this one, but thought i'd put it out there for consideration.

**Comment by sofroniewn** [comment]
Now that #2612 has merged should we close this?

**Comment by goanpeca** [comment]
Lets
