### ISSUE TITLE
Unable to find an executable to build Qt resources (icons). Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.

### ISSUE THREAD

**Issue by XareniGalindo** [napari/napari#2199]
Dear all

I was trying to run a notebook developed by @Varun Kapoor 
https://github.com/kapoorlab/TheNextMLExpert/blob/9773c9830da69924beed78d39b6c8870d6b9f6d8/NucleiSegmentation/NucleiSegmentations.ipynb

That uses @napari to visualize grand truth images and prediction images obtained with StarDist, I did run the notebook last week and it work but now that I want to re-run it the next error is appearing 

FileNotFoundError: Unable to find an executable to build Qt resources (icons).
Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.
Please open issue at https://github.com/napari/napari/issues/.

I hope someone can help me to solve this issue. Thanks in advance

**Comment by tlambert03** [comment]
Hi @XareniGalindo, please tell us a little more about how you've created your python environment.  Did you create a conda environment or other sort of virtual environment? How did you install napari?  pip?  conda?  (If you can provide the exact command line arguments you used to install, that would be helpful)

**Comment by tlambert03** [comment]
Hi @XareniGalindo, would you still like help with this?

**Comment by Wellidontcare** [comment]
This happened to me too. 
I think you need a PyQt Ressource compiler binary in your path, not sure if this should be installed with the napari packet itself.

I fixed it by installing the pyqt5-dev-tools.

**Comment by tlambert03** [comment]
Those programs come with the default installation of pyqt and pyside on both pip and conda.  You shouldn't need to install anything else.  In most cases in the past, this has been due to idiosyncrasies in the local environment... hence my curiosity.  We can likely prevent it with more information

**Comment by jni** [comment]
Just to summarise a short conversation between Talley and I on Zulip: one idea for preventing these issues going forward is to keep the dynamic generation code for local editable installs, but to pre-build the resources for bundles, wheels, and conda-forge packages. That should free us from trying to make these things work in 99%+ of user installs.

**Comment by Wellidontcare** [comment]
Now after reading the installation instructions again, I see my fault was installing via `pip install napari` without specifying the preferred qt-bindings.

**Comment by jaimergp** [comment]
> Just to summarise a short conversation between Talley and I on Zulip: one idea for preventing these issues going forward is to keep the dynamic generation code for local editable installs, but to pre-build the resources for bundles, wheels, and conda-forge packages. That should free us from trying to make these things work in 99%+ of user installs.

Is this being done for wheels already? If that's not the case, the conda packages are not doign that either, nor the installers. Let me know if you want me to open an issue/PR to tackle this @jni!

**Comment by tlambert03** [comment]
Hi @jaimergp, a lot has changed since this issue.  we really can't build _everything_ we need up front, because part of the point is that themes/icons can be dynamically declared.

The bigger issue here wasn't as much about dynamic code generation as it was about finding qt executables in the environment.  I'll add two notes:
- since #2285 (which added even more fallbacks here) we haven't had any issues with this
- as soon as https://github.com/napari/napari/pull/3707 is merged, we won't be using `pyrcc` for runtime compilation of resources at all, so this will be moot

the only ancillary issues here are those of potential write permission limitations, as I mentioned in that issue: https://github.com/napari/napari/pull/3707#issuecomment-1153005744

closing this issue since the initial question was solved
