### ISSUE TITLE
Default points layer is 2D rather than current viewer dimension

### ISSUE THREAD

**Issue by jni** [napari/napari#2273]
## 🐛 Bug

In prior versions of napari (0.3.4), adding points with no data would default to the dimensionality of the existing layers, if any, or 2D if the viewer was empty. Today, it defaults to 2D in any case. This might have been done consciously to minimise complexity (since layers don't know about the viewer, and much of `add_*` is auto-generated), but I wasn't sure so I thought I'd raise an issue to discuss. If we decide not to fix, it would be good to add documentation about this, or at least a usage example.

See more details in this image.sc thread:

https://forum.image.sc/t/napari-timepoints-not-detected/48756/4

## To Reproduce

This script prints "3" in version 0.3.4 and "2" on napari master:

```python
import numpy as np
import napari

image = np.random.random((10, 1024, 1024))

with napari.gui_qt():
    viewer = napari.Viewer()
    _ = viewer.add_image(image)
    pts_layer = viewer.add_points()
    print(pts_layer.ndim)
```

**Comment by sofroniewn** [comment]
Ah - I disagree that this is a bug, it maybe should be been a better documented or more widely discussed breaking change, but it was quite intentional at the level of the `viewer.add_points()` method. Clicking the new points button in the UI still uses the dimensionality of all the data, but the `add_points` method does not as it not is autogenerated from the `Points` layer.

I think that the `add_points` method from the API should be stateless, in that it should not depend on the rest of the viewer. I think it would be very magical if `add_points` depends on what else is present, and it moves away from the parity between the `viewer.layers.append(Points())` and `viewer.add_points()` API.

Note it is also very easy from the API to do
```python
viewer.add_points(ndim=3)
# or
viewer.add_points(ndim=viewer.dims.ndim)
```

rather than us magically guess what dims the users wants and leave `viewer.add_points` with no stable default.

I think clicking the new points button in the UI right now will use the full dims of the data present, which I think is reasonable default for a GUI button (in the future I could imaging right clicking to allow creating new layers with custom ndim). https://github.com/napari/napari/blob/d409d3573e15dd1b21b008201608ebd2f2dc2dc2/napari/_qt/widgets/qt_viewer_buttons.py#L36-L38

[EDIT:]

>  I wasn't sure so I thought I'd raise an issue to discuss. If we decide not to fix, it would be good to add documentation about this, or at least a usage example.

Improving documentation or adding an example makes a lot of sense to me!!

**Comment by jni** [comment]
@sofroniewn on the one hand, as you know I love functional programming and stateless APIs. On the other hand:

- we already break parity between the layer `__init__` and the `add_` method for Image,
- `viewer.add_points` is a method on the viewer instance, so one would probably expect some state there anyway,
- `ndim=` might actually be autogenerated as well, if we decide to go that route (check whether the init takes that argument, check whether it's been provided, if it hasn't, default to the viewer ndim).

I'm 50/50 on this one... But at any rate we can make a start on auditing/creating our examples. 👍

**Comment by psobolewskiPhD** [comment]
I tend to agree with Nick here.
@jni have you any new thoughts on this? If not, I'd lean towards `wont fix` and close.

**Comment by jni** [comment]
yup happy to close!
