### ISSUE TITLE
If napari closed with undocked windows, they never work on next launch

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2365]
## 🐛 Bug
Now that settings saves various window states, a couple new bugs may appear. I just noticed that if you undock the layer list or the layer controls and quit napari, then on the next launch, even if you reshow those windows (since they will be hidden on launch), then they never work properly.  They are just blank rectangles...

**Comment by goanpeca** [comment]
A quick solution for this would be to redock floating docks on close. Not sure if you can get the floating docks to appear correctly on startup.

**Comment by tlambert03** [comment]
if there's a crash, we'd still be lost in the next session though right?  i guess I'd prefer this to be solved during initialization rather than shutdown if possible

**Comment by goanpeca** [comment]
Ok, I will take a look :)

**Comment by tlambert03** [comment]
if it's easier... maybe we don't even need to save docked/floating state at all?  It might be generally hard to recover parent-chain of an undocked widget (currently, they show as un-styled), so I'd be fine with just making everything docked at startup, and not saving it.  is that easy?

**Comment by goanpeca** [comment]
>if there's a crash, we'd still be lost in the next session though right? i guess I'd prefer this to be solved during initialization rather than shutdown if possible

If there is a crash, close event would have never been called, so it would restore to the last state (that had all dockwidgets docked because we enforce this on close)

>if it's easier... maybe we don't even need to save docked/floating state at all? It might be generally hard to recover parent-chain of an undocked widget (currently, they show as un-styled), so I'd be fine with just making everything docked at startup, and not saving it. is that easy?

It is not possible to save state of some things and not others AFAICT

And it should be working, not sure why we are getting this empty windows.

So still my suggestion for now would be to dock all floating widgets on close (that is what we had to do in Spyder AFAICR). Now we could actually make this work with some extra logic, and we would need to save all these extra docks pos and size to be able to restore them properly, but I need to do a simple test with a dummy application to see if it might be something different on how Napari is adding those widgets.

**Comment by tlambert03** [comment]
sounds good, if it's the only or easiest way... let's do it and figure it out later

**Comment by jeffkimbrel** [comment]
How does one go about getting one of these closed docks back? I closed the main layers control dock (the dock with opacity, colormap, etc...) and I can't get it back. I have a feeling I undocked it and closed, similar to this issue. Re-running the code (just trying the `parameter_sweep.py`) and restarting the terminal doesn't bring it back.

Or, is there a hidden file or something that is saving this window state between sessions that I can just delete?

Thanks.
