### ISSUE TITLE
Pad colors when not all control points specified

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2400]
## To Reproduce

```python
import numpy as np

import napari

colormap = napari.utils.Colormap(colors=[[0,0,0,1], [1, 1, 1, 1]], name="test", controls=[0.1, 0.9] )

print(colormap.colorbar)

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_image(np.random.random(size=(100, 100)), colormap=colormap)
```

end of stacktrace
```
~/.pyenv/versions/3.8.3/envs/napari/lib/python3.8/site-packages/vispy/color/colormap.py in _glsl_mix(controls=array([0.1, 0.9], dtype=float32), colors=array([[0., 0., 0., 1.],
    143 
    144     """
--> 145     assert (controls[0], controls[-1]) == (0., 1.)
```

## Expected behavior

If Colormap is properly constructed (and `colorbar` works) then it should not raise an exception when applying to layer. 

## Possible solutions

1. Fix controls and colors before passing to vispy (napari/napari/_vispy/vispy_image_layer.py line 128) by adding a copy of first and last color with respectively coordinate 0 and 1 if absent.
2. Raise an exception if trying to create a colormap with first and last coordinate different to (0, 1)

I prefer the first solution.

## Environment
last master (42d48e3d63aa850ec18a3a6167e7441275c94303)

**Comment by sofroniewn** [comment]
> Fix controls and colors before passing to vispy (napari/napari/_vispy/vispy_image_layer.py line 128) by adding a copy of first and last color with respectively coordinate 0 and 1 if absent.

We can do this, we should then just update doc string to make it clear that is what is happening. I see this as a "user convenience" type of functionality, as you could just type it all out below and it would work as expected, right? 

```python
colormap = napari.utils.Colormap(colors=[[0, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 1], [1, 1, 1, 1]], name="test",
                                 controls=[0.0, 0.1, 0.9, 1.0])
```

**Comment by Czaki** [comment]
I do this way. But I still think that this is unexpected behavior. You construct the proper object and try pf its usage ends with an exception.

**Comment by sofroniewn** [comment]
yeah we should fix - either with option 1 or option 2 you mention above. PR would be welcome if you want to make one

**Comment by goanpeca** [comment]
>Raise an exception if trying to create a colormap with first and last coordinate different to (0, 1)

Fixing things magically for users (option 1) can be great, but if we want to convey a "correctness" concept to users in colormaps then I would favor option 2.

**Comment by Czaki** [comment]
The option 1 represent this what produce current function colorbar.

**Comment by sofroniewn** [comment]
Personally I'd probably prefer option 2 as I think it was an oversight to not check that `0` and `1` were provided. I agree that guessing what the user intended can backfire. The fact that we don't error now I don't really see this as an intend piece of functionality, I see it as a missing validation, and this was just something untested and unspecified. For example right now if someone gave a value of `-2` or `4.7`, or a decreasing list of control points we actually wouldn't error either but we probably should.

**Comment by Czaki** [comment]
It depends. If we define colormap as interpolation of given colors on section `[0, 1]` it still perfectly works for me. But I agree that it should emit at least a warning.

But I agree that it will also end with an exception if pass it to vispy.

**Comment by sofroniewn** [comment]
@GenevieveBuckley, reading your comment here https://github.com/napari/napari/pull/2406#issuecomment-801537007 

> I feel like magical behaviour that changes/affects the data is more the thing to focus on. I'd file this more under "napari chooses sensible defaults for us".

makes me think of this current request - curious how you think we should handle this - should we fix the controls or raise an error. There is a WIP PR to fix at #2422

**Comment by GenevieveBuckley** [comment]
The current situation is clearly not ok. It shouldn't look fine up until the point you actually try and use the colormap.

I think it's probably simpler overall to add a check to the validation step and raise an informative error if it's not met. That error might suggest adding `0` and `1` if it looks like that might be the problem, or re-iterate the rules for `control` Nick mentions above. 

I lean this way for a couple of reasons:
* It seems like a user error caused more by lack of documentation, so I think that should be improved instead. That seems like the root cause.
* Nick is right, there aren't validation checks for a lot of things that should be checked here. So if you magically fix some things, but check and error on other things it feels like the logic gets split up and convoluted.
* It is unlikely to disproportionately affect new users, who might give up on napari after trying it once or twice.
* I think there is only marginal benefit in magically fixing this particular user error. Because the user has to generate the colormap before they try to use it, they kinda know they've done a thing that didn't work instead of "napari doesn't work". The fix is also very quick, you just rerun the last line and update the values in `control`, it doesn't cause the whole viewer to crash or anything.
* I wanted to comment that if we did auto-magically fix things it should produce a user warning then... but wanting to say that is probably a sign it should just be an error instead.

**Comment by sofroniewn** [comment]
Ok, thanks for weighing in with the detailed thoughts @GenevieveBuckley - personally I agree with all your points. @Czaki has now made an implementation in #2422 that is quite clean using a single root validator. Given the simplicity of the fix and his desire for it, I think adding it, but taking your the part of your suggestion to add a warning and improving the documentation seems like the best compromise for now.

**Comment by GenevieveBuckley** [comment]
Great, maybe we can add those other validation checks you suggest above too.

> For example right now if someone gave a value of -2 or 4.7, or a decreasing list of control points we actually wouldn't error either but we probably should.
