### ISSUE TITLE
Remove toggle theme option

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2450]
## 🐛 Bug

Since there can be more than 2 themes, this option should be removed.

<img width="255" alt="Screen Shot 2021-03-22 at 10 54 03 AM" src="https://user-images.githubusercontent.com/3627835/112018841-eb5c0480-8afc-11eb-8fbc-4f392d431ecb.png">

## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

@liaprins-czi your advice is greatly appreciated :)

**Comment by tlambert03** [comment]
fwiw, the behavior there is currently more of a "cycle" theme, and it does work with multiple themes:

https://github.com/napari/napari/blob/80f8ef18d9645c52601a8c1fd1125601f4b3dac0/napari/components/viewer_model.py#L255-L259

maybe we could just change the misleading wording of the menu?

**Comment by goanpeca** [comment]
>fwiw, the behavior there is currently more of a "cycle" theme, and it does work with multiple themes:

For anything more than 2 themes, cycling might not be the best UI. In that case, if we want to expose that, we should probably use a submenu.

**Comment by tlambert03** [comment]
that's fine too (but I do also kinda like the hot key that lets me cycle).

**Comment by ppwadhwa** [comment]
@goanpeca can the hot key still cycle through them even if we add a new submenu for the themes?

**Comment by goanpeca** [comment]
>can the hot key still cycle through them even if we add a new submenu for the themes?

It could but it would be very hard to have discoverability of such a feature.

Now the real UX question is, even if toggling and cycling is convenient with a shortcut, a theme is not something you are toggling every minute, it is something you select and then move on, so the quick access feature and ability to toggle it quickly with a shortcut does not seems to sync with the actual usage.

**Comment by sofroniewn** [comment]
At a bare minimum it should be renamed `cycle theme` instead of toggle theme. I could see reasons for having a submenu, but probably wouldn't as it is now possible to set the theme in the preferences, and having the submenu then seems highly redundant.

> Now the real UX question is, even if toggling and cycling is convenient with a shortcut, a theme is not something you are toggling every minute, it is something you select and then move on, so the quick access feature and ability to toggle it quickly with a shortcut does not seems to sync with the actual usage.

I agree that most users are unlikely to do this, but I can see how it is useful for a GUI developer :-) Maybe we shouldn't be adding menu items/ keybindings like this just for developers though.

One question is would our custom keybindings dialog and keybindings preferences ever become so expressive that we could add a custom keybinding for this and store it in the preferences?

My current vote would probably be to drop the menu item (as redundant with preferences), but keep the keybinding, at least for now (as convenient). We do have a number of other keybindings that don't have menu items, but maybe it's not the best practice ...

Curious what others think

**Comment by ppwadhwa** [comment]
FYI: I submitted a PR to drop the menu item.  In order to still cycle through themes with the keybinding, I had to add the keybinding to `_viewer_key_bindings` because the keyboard shortcut was attached to the QAction included in the menu.

**Comment by liaprins-czi** [comment]
> One question is would our custom keybindings dialog and keybindings preferences ever become so expressive that we could add a custom keybinding for this and store it in the preferences?

Myabe not for the first version of customizeable keybindings, but I think we could have it eventually.

I agree with removing this option from the menubar, as it should be consistent with other Preferences settings in how it is accessed; keeping it available through the preferences dialog exclusively will help the user build a mental model that that is where to go to make changes of this sort.

I do not know about keeping the keybinding for cycling through, but if it's already been created, I don't think it will be harmful to keep it.
