### ISSUE TITLE
Use zarr.open() if napari is trying to open a filename ending in `.zarr`

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#2475]
## 🚀 Feature
If you try to open a filename ending in `.zarr` then napari should use the `zarr.open()` method instead of its default open method.

## Motivation
Juan shared a `.zarr` dataset with me yesterday (the `AO-LLSM` dataset), but gave specific instructions that I could not just drag and drop it into napari and instead I should open it with `zarr.open()` and then show that result in the napari viewer.

## Pitch
It seems to us that if a filename ends with `.zarr` then napari should be smart enough to work out that it should use `zarr.open()` to avoid this problem.

## Alternatives
We could keep the current napari behaviour, which is not ideal.

We could change the napari `open()` behaviour in a way that doesn't directly use `zarr.open()` but fixes whatever weirdness is causing napari not to be able to view the data properly. Since zarr is already a dependency (I think?), it does seem simpler just to use it instead.

## Additional context
This discussion with Juan was about the `AO-LLSM` dataset Gokul gave to Nick.

**Comment by sofroniewn** [comment]
> Juan shared a .zarr dataset with me yesterday (the AO-LLSM dataset), but gave specific instructions that I could not just drag and drop it into napari and instead I should open it with zarr.open() and then show that result in the napari viewer.

@jni can you provide some more detail on this. Here is our current zarr read function

https://github.com/napari/napari/blob/102a7e8f845893c874d2b86f9371d41130100b89/napari/utils/io.py#L265-L293

It uses `image = da.from_zarr(path)`, should that line just be `image = zarr.open(path)`?

Can you explain why?

**Comment by jni** [comment]
Oh no, sorry I missed this. I don't think zarr.open would solve this specific issue. Several things were happening with this data,

(1) it's multiscale but doesn't have the right ome-zarr metadata for multiscale
(2) *for some reason I don't understand*, when dragging and dropping, it would open the slices as layers instead of opening it as a stack
(3) (this is really very specific to this data) Two of the scales have the same shape but different chunking, see #2224 

Only the second problem is actually something that we can fix in napari. I thought I'd made an issues that open-as-stack should be the default but I can't find it...

**Comment by GenevieveBuckley** [comment]
> Only the second problem is actually something that we can fix in napari. I thought I'd made an issues that open-as-stack should be the default but I can't find it...

Ok, if you can't find it maybe you can open a new issue. I'll close this, since the problem here appears to be specific to quirks in this particular dataset.

**Comment by jni** [comment]
Great, see #2603
