### ISSUE TITLE
Allow option to save only window geometry, not geometry + panel state

### ISSUE THREAD

**Issue by jni** [napari/napari#2583]
## 🚀 Feature

Motivated by [this user question](https://forum.image.sc/t/reset-napari-gui-default-settings-between-runs/51711) and a short conversation with @tlambert03, it might be desirable to save window geometry only without saving panel state/layout. These would either become two separate preferences, or we would drop the ability to save panel state altogether. (Though I think panel state will become more important as people start to use their favourite plugins in combination with one another.)

**Comment by sofroniewn** [comment]
Makes sense to me, agreed I see this coming up more and more in the context of plugins when someone might have many dockwidgets added, but it also makes sense if someone wants to say always have the layer list on the right because they have many images. I don't think they should be forced to drag it over there every time, so I think we should have two separate preferences. I'd rather everything get saved by default, and you can then unselect an option if you want to not have things saved.
