### ISSUE TITLE
Location of progress bar/ qt imports in repo

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2661]
I want to pick up the discussion here https://github.com/napari/napari/pull/2580#issuecomment-832096273 about where the progress bar lives in the repo and how it gets imported.

In general we've tried to separate out our qt imports and non qt imports into different parts of the package to maintain a loose coupling between the two. They need to come together at some place, which is currently our `Viewer`.

The progress bar is currently implemented in such a way that it can either display with Qt or default to a console view without qt (using a try/ catch), and so could in theory be imported either as `from napari.qt import progress` or `from napari.utils import progress`.

I currently favor starting with `from napari.qt` as it keeps our qt stuff together, but we can discuss further on this issue

**Comment by DragaDoncila** [comment]
In my view there's three aspects to consider here (maybe there's some I'm missing though):

1. **Usability** - where will it be easier for users to find, where will it be less likely to confuse/mislead users
In some respects putting it in `qt` might lead users to believe that they can't use it in scripts they also run headless, though we could document this more clearly to avoid this confusion. Otherwise either seems just as usable to me.

2. **Code Smells/API Leaks** - is this poor design, are we potentially exposing more code than we should
I'm not sure I understand the concerns here and what we're worried might happen if we take it out of `qt` into `utils`. 

3. **Semantics** - is this at its core a GUI interface or not, separation of concerns
At its core this is a `tqdm` wrapper, but the only functionality it provides on top of `qt` is the ability to add a widget to the viewer. If it was extending the functionality of `tqdm` to provide other features besides the progress bar in the viewer, then I would be more likely to favour moving it into `utils`. But really, any time you're using this in the terminal it's just `tqdm` and provides basically nothing. Given this, I think it should stay in `qt` but still keep the `try/catch` for the import so that if people are running a processing script without the viewer, they can still see their progress bars.
