### ISSUE TITLE
Using a formatter

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#270]
## 🚀 Feature

I am proposing to use `black` python formatter to decrease number of convention decisions to make and sustain consistency on code convention over repository. To me defaults of black seems great and i think you guys might like it as well.
Black formatter: https://github.com/python/black

## Motivation
Using a strong formatter decrease number of convention decisions to make. Reduces frustration on newcomers.

## Pitch
Black formatter is so cool. I compare it with `yapf` from google and autopep8 formatter.
Definitely black has an edge.

## Alternatives
Strongest alternatives: `yapf` from google: https://github.com/google/yapf 
and autopep8: https://github.com/hhatto/autopep8

**Comment by jni** [comment]
I like the idea of formatters in general, but I dislike the rigidity of black (as I understand it it is not very configurable).

The number one concern is whether code formatted with black is actually nice and readable. Do you know any scientific packages that use it? Only the web-world appears to have taken it on.

I guess another way to propose this is to submit a PR with all the code formatted. Then we can see if we like its changes. =)

**Comment by sofroniewn** [comment]
I'm open to a formatter, and `black` has come up at CZI recently, but I'm not sure any of our projects actually started using it. @kne42 might know more and I can follow-up.

A PR seeing what the new code would look like would be helpful and might be a good next step if it is not too much work to make. If the new code appears more readable and understandable then I'd be all for it, if we are constantly having to use `# fmt: off` and `# fmt: on` to make the code look nice then I'd probably want to pass

**Comment by kne42** [comment]
Summarizing my comments from a different thread, I'm open but not thrilled to having an autoformatter. While it'll be great to finally have our codebase cleanly formatted, I don't think it's a proper substitution for people just actually writing well-formatted code.

At the end of the day, readability is something that a simple program cannot quantify; all it's doing is following a strict set of rules. Except styling doesn't consist of rules, it consists of guidelines, which means that following style guides to the letter does not necessarily make your code more readable, sometimes it can make your code _less_ readable.

Ideally, contributors should be following a style guide (*cough cough* PEP8) and otherwise format sensibly (which, if it isn't clear enough, we can make a guide for too).

However, given the current state of the codebase, I will admit that I have my doubts of letting contributors just go around willy-nilly without some sort of enforcement since I'd prefer not to have to leave 1000 comments on every PR about styling.

What I would most prefer to see is something similar to the @pep8speaks bot that suggests formatting automatically without necessarily forcing it on someone, which IMO would be the best compromise between having some sort of sanity check while letting humans ultimately decide what looks cleanest.

As far as actual autoformatters go, here's my take on them:
- `black` is a hard no from me – I strongly disagree with its formatting conventions
- `yapf` seems very promising in its customizability so I'd definitely be on-board with it
- `autopep8` is classic and minimalistic but doesn't provide as nice formatting as the other two – it just fixes PEP8 errors, which is fine by me

**Comment by AhmetCanSolak** [comment]
Thanks to all @jni @sofroniewn @kne42 for your comments. 

I like idea of discussing the formatters on a small PR over code. 
I will be opening a showcase PR.

Also, i understand the frustration/hesitation against a strong formatter.
`black` style may not be the most pythonic collection of conventions, however, IMO it increases readability and takes care convention decisions for us. 
Its default conventions are also compatible with many many industry-grade conventions.

`yapf` is really good IMO and on most cases default style is same with `black`.
I know you guys liked that it is also configurable, i see it as a possible drawback.
Again we might need to make decisions.

Stay tuned till my formatter PR.

**Comment by jni** [comment]
just btw I'm super in favour of changing the default line length to 80, like God intended. =P

The problem of review definitely pushes me in favour of the formatter. I have to admit that I have come to regard PEP8speaks as noise, and rarely read it. This is the problem with all auto-suggest tools, including e.g. the github issue template.

**Comment by sofroniewn** [comment]
@jni I personally find the PEP8speaks very helpful (though I often run `pycodestyle` because it's faster) as a beginner. I'd say our problem now is that there are many things that it doesn't catch and that I get consistently wrong. The manual approach does mean I'm learning more (and will hopefully get better), but I recognize it's a lot more burden on our reviewers.

I'd say reducing reviewer burden and time would also be a major reason to adopt a formatter, but I'm open to the details

**Comment by AhmetCanSolak** [comment]
I opened the #282 . Please check details and let me know about your comments.

**Comment by sofroniewn** [comment]
That's great, thanks @AhmetCanSolak I will check it out. If easy maybe you or @kne42 wants to open a similar PR using the same three files with `yapf` using some of the configurations that @kne42 likes so we can do side-by-side comparisons.

**Comment by AhmetCanSolak** [comment]
@sofroniewn it is easy. `yapf` default is pretty much same with black except putting " for strings for the files in PR. So side-by-side comparison could make more sense if we have specific configuration in mind.

**Comment by sofroniewn** [comment]
Looking now at `black -S` #282 and `yapf` #283 side-by-side I think a couple of us, (@jni, @AhmetCanSolak, and myself) are leaning towards `black -S`. @kne42 and @royerloic what are your opinions? 

One more thing we'd need to decide is how to enforce the autoformatter. If it is possible, I'd favor an approach where we add a seventh test (like our current 6 cross platform tests) that checked for compliance. If the test fails it will be obvious - there will be a red X - but it would still be possible for us to merge (in the same way that we continue to merge despite the windows / macOSX builds failing). If we wanted to move to a world where you could not merge at all with any failing tests we could also do that in the future. We'd also disable the pep8 bot and its suggestions, but add a description of how to use the autoformatter to our contributing guidelines

**Comment by jni** [comment]
I just saw that JupyterHub uses black and uses git pre-commit hooks to ensure that it runs. 

https://github.com/jupyterhub/jupyterhub/issues/2416

Their [solution](https://github.com/jupyterhub/jupyterhub/pull/2418/files) involves the package [pre-commit](https://pre-commit.com/) to manage git hooks, but we could equally well do it [manually](https://githooks.com/). But I think using pre-commit is probably the way to go.

Whatever we do, automating it pre-merge or post-merge is the right way to go. The user should not have to manually run black, and should never be bugged about black. It should Just Work:tm:.

**Comment by sofroniewn** [comment]
I like the user not having to manually run it, and I have a strong preference towards a pre-commit solution - which if I understand correctly would allow us to see the already formatted code during PR review. If a goal is to streamline PR review I think running the formatting before the review seems very important.

I have no problem with the `pre-commit` package and don't see any reason to role our own, especially if JupyterHub has been using this for the past few months.

I also don't have a problem with one massive reformatting PR to get us going. People have raised concerns about `git blame` in this context, but some reading of the black docs leads to a solution involving `git hyper-blame`.

I'm pretty excited about all this!!

**Comment by jni** [comment]
> I think running the formatting before the review seems very important.

:100: spot-on point.

I also think that we are early enough in the history of this project that git blame is not a concern. I also think we can generally place the blame on @sofroniewn and have a good chance of being correct. =P

@AhmetCanSolak how do you feel about writing a PR that uses `black -S` on the whole code base *and* installs pre-commit hooks as described above?

**Comment by AhmetCanSolak** [comment]
Hi @jni , yes i can make a PR for `black -S`

**Comment by AhmetCanSolak** [comment]
now integrated formatter successfully, im closing this issue.
