### ISSUE TITLE
Dragging shapes drags canvas (sometimes)

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2713]
## To Reproduce

(will edit later am in a meeting and just want to have areminder) 

$ python examples/add_image_transformed.py
create label layer, 
create shapes layer
create multiple ellipses
copy one ellipse, 
past it
go to select mode, 
drag past ellipse.

Canvas drags with it: 

![flash](https://user-images.githubusercontent.com/335567/118198666-352ee000-b406-11eb-8df4-5221a25a262a.gif)

I can't always reproduce it (am on 336772a7d) 

## Expected behavior

Drag only ellipse

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by Carreau** [comment]
Bisected to #2441 

Seem like `viewer.camera.interactive` is reset to True on Ctrl-C/Ctrl-V

**Comment by jni** [comment]
A little bit more background from the interactive discussion after the meeting: the labels layer has a bunch of extra "modifier shortcuts", including "temporarily switch to fill mode while holding Ctrl". Somehow, hitting Ctrl while in the shapes layer is getting passed through to the labels layer as the modifier (bad point 1), and then the on-release shortcut is switching `viewer.camera.interactive` back on, rather than switching the mode back to pan_zoom. (which would anyway also do the `viewer.camera.interactive` bit.)

So the bit that broke is that somehow updating the selection model let the Ctrl modifier through to the labels layer.

**Comment by jni** [comment]
A shorter reproducer:

```python
import napari
import numpy as np


image = np.random.random((5, 5))
labels = np.zeros((5, 5), dtype=int)

viewer = napari.Viewer()
viewer.add_image(image)
viewer.add_labels(labels)
pts = viewer.add_points()
pts.mode = 'select'


napari.run()
```

Then:
- drag (nothing bad happens, just get the selection box)
- press and release Ctrl
- drag again — now dragging moves the camera.

**Comment by sofroniewn** [comment]
Ok if you look at 
```python
[type(a) for a in viewer.window.qt_viewer._key_map_handler.keymap_providers]
```
you can see that right now it looks like we're accumulating layers inside our `keymap_providers` but we should be adding/ removing the active one each time it is changing, see https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L382-L399

I would have expected that list to always be length 2, just the viewer and active layer. Now it has all the layers. This is evidently quite fragile now and broken. It even has layers that should have been deleted, which could be causing bad leaks! Maybe we should overhaul this entirely. I know that was already planned.

@tlambert03 what are your thoughts on fixing here?

**Comment by sofroniewn** [comment]
Ok the problem is #2441 also removed `QtViewer._active_layer` here which was needed. I can fix now. It's probably a bad pattern that should change, but I think I can fix bug

**Comment by tlambert03** [comment]
away from computer for the next day or so.  Will look when back
