### ISSUE TITLE
Label layer, Cmd/Ctrl to toggle eraser does not toggle back when layer list in focus.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2714]
## 🐛 Bug

See attached gif, where I :
- Select Canvas
- press and release Cmd
- (tools briefly goes to eraser while cmd pressed)
- Select Layer list
- press and release Cmd
- Tools select erase and _stay_ on eraser.

(maybe hard to see because of how the gif loops) 

![toggle](https://user-images.githubusercontent.com/335567/118203954-fef75d80-b411-11eb-8119-f11ed01515f5.gif)

Bug exists since at least 0.4.6

**Comment by sofroniewn** [comment]
Following up on https://github.com/napari/napari/pull/3072#issuecomment-893199773 I think we should drop the use of modifier keys to change labels mode - cc @jni

**Comment by jni** [comment]
We agree on that, @sofroniewn, but that doesn't get to the root cause here — this problem happens with *any* "hold to toggle" behaviour, including hold space for pan-zoom. Actually it's worse with hold-space: the other modes get disabled!


https://user-images.githubusercontent.com/492549/128447443-e7383496-4a83-410f-a1e4-f9f6b4731d47.mov

**Comment by psobolewskiPhD** [comment]
@Carreau @jni 
the keybinds have changed a lot since this, but also the press-hold behavior has been changed: https://github.com/napari/napari/pull/4814
I can't replicate the issue with the new keybind system. Can y'all check if it's still an issue on your end?
