### ISSUE TITLE
import-linter blocking commit 

### ISSUE THREAD

**Issue by ppwadhwa** [napari/napari#2772]
## 🐛 Bug

I am not able to commit to my branch because the import-linter is failing on code that I didn't touch.   See here:

```
import-linter............................................................Failed
- hook id: import-linter
- exit code: 1
=============
Import Linter
=============
---------
Contracts
---------
Analyzed 553 files, 2248 dependencies.
--------------------------------------
"Forbid import PyQt and PySide" KEPT
"Block import from qt module in abstract ones" KEPT
"Block import from qt module in abstract ones" KEPT
"Block import from qt to _qt" BROKEN
Contracts: 3 kept, 1 broken.
----------------
Broken contracts
----------------
"Block import from qt to _qt"
-----------------------------
napari._qt is not allowed to import napari.qt:
- napari._qt._tests.test_progress -> napari.qt.progress (l.11)
- napari._qt._tests.test_progress -> napari.qt (l.11)
```

## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by goanpeca** [comment]
@Czaki could you give us a hand :) ?

**Comment by sofroniewn** [comment]
See solution https://github.com/napari/napari/pull/2659/files#r638327401, let's just remove that block - it's not as important as the other ones

**Comment by Czaki** [comment]
in #2659 there were introduced import linting with 4 contracts. One of them is "Block import from qt to _qt" 
https://github.com/napari/napari/blob/01c24e320dc3d8daaae80a383f95fc0587c98ee4/setup.cfg#L182-L191

I add this contract to ensure that noting in `napar._qt` depends on `napari.qt`.  

The only case which is acceptable is test imports.

I see 3 options:
1) remove contract
2) add next ignore rules to ignore import in `test_progress` 
3) move this few test cases to `napari.qt._tests` module

**Comment by sofroniewn** [comment]
> I add this contract to ensure that noting in napari._qt depends on napari.qt.

is this just stylistically a good idea or is it absolutely critical - i.e. code will crash if this is true?

I'd probably just drop right now (option 1), make sure that people can commit code again, and then we can have a longer discussion if this thing is really critical.

**Comment by Czaki** [comment]
> is this just stylistically a good idea or is it absolutely critical - i.e. code will crash if this is true?

could crash because of circular import. 

I already meet something similar (not napari) when crash depends on order of import so when GUI is starting everything works, but when usin nongui parts of code (readers, writers, calculation backend) there exist orders of imports which ends with crash.

But I agree that fast drop could be a good idea to not block development process.

**Comment by goanpeca** [comment]
I am now getting this locally
```bash
(napari) gpenacastellanos@CZIMACOS3405 napari % pre-commit run -a
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
pyupgrade................................................................Passed
import-linter............................................................Failed
- hook id: import-linter
- exit code: 1

Could not find module napari._qt.qt_resources._qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7.
```

**Comment by sofroniewn** [comment]
> But I agree that fast drop could be a good idea to not block development process.

Ok, let's drop now then. Can you open a PR @Czaki.

We should also check that @goanpeca issue is then fixed too

**Comment by Czaki** [comment]
@sofroniewn @goanpeca #2774

**Comment by tlambert03** [comment]
> Could not find module napari._qt.qt_resources._qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7.

is this thing keeping a database or something?

**Comment by Czaki** [comment]
> > Could not find module napari._qt.qt_resources._qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7.
> 
> is this thing keeping a database or something?

This are old files with icons if I good remember

**Comment by sofroniewn** [comment]
We also had quite a lot of fails in our main CI - more than normal https://github.com/napari/napari/runs/2658509551, we should make sure they aren't still present after #2774

**Comment by tlambert03** [comment]
> > > Could not find module napari._qt.qt_resources._qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7.
> > 
> > 
> > is this thing keeping a database or something?
> 
> This are old files with icons if I good remember

correct ....  is this thing keeping a database or something? :joy:
(in other words... why would it care about a missing temp file)?

**Comment by Czaki** [comment]
> We also had quite a lot of fails in our main CI - more than normal [napari/napari/runs/2658509551](https://github.com/napari/napari/runs/2658509551), we should make sure they aren't still present after #2774

@sofroniewn 

they will be present because they are connected with NumPy RC release `numpy==1.21.0rc1`:
```
  E           FutureWarning: Promotion of numbers and bools to strings is deprecated. In the future, code such as `np.concatenate((['string'], [0]))` will raise an error, while `np.asarray(['string', 0])` will return an array with `dtype=object`.  To avoid the warning while retaining a string result use `dtype='U'` (or 'S').  To get an array of Python objects use `dtype=object`. (Warning added in NumPy 1.21)
```

So this warning should be ignored or numpy should be pinned. 


@tlambert03 
I do not found any database. Also, there is no import linter earlier. But I think that it is connected with the presence of this file on the disc. 

I think that it may be connected with additional dot in name of file.

**Comment by sofroniewn** [comment]
I have now merged #2774, hopefully that should improve the situation, we can see and then decide if we can close this

**Comment by ppwadhwa** [comment]
FYI: I have been able to commit since #2774  was merged.   :)

**Comment by jni** [comment]
>  (in other words... why would it care about a missing temp file)?

It appears to be the other way around... This complaint happens *if it finds these files*. I had a whole bunch of old ones that I had to delete in order to be able to commit again. @Czaki can you comment on why it checks that? And why the error message is so obtuse? I wonder if we should remove another condition, too... It's common to have multiple versions of generated files in these folders.

**Comment by Czaki** [comment]
> @Czaki can you comment on why it checks that?

because it checks every `*.py` file to check what it import 


> And why the error message is so obtuse?

because it try to import `napari._qt.qt_resources._qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7` 
and `_qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7` is not a valid module name in python. 
During generation such file should be `file_name.replace('.', '_')`

**Comment by tlambert03** [comment]
> I wonder if we should remove another condition, too... 

that would be my preference

**Comment by tlambert03** [comment]
to my understanding, this pre-commit step was introduced because @Czaki was frustrated by the time it took to notice in a CI test that he had auto-imported from PyQt5 instead of qtpy.  As I mentioned in the original PR, I understand that desire, (though I also don't think it's _that_ hard of a thing to figure out from the test logs) ... but in general I'd prefer to keep our pre-commit steps to the minimum essentials.  I'd support reverting this one altogether, but short of that, would prefer to keep it to the original intention of preventing direct PyQt5/PySide2 imports

**Comment by Czaki** [comment]
any usage of import linter will end with an error if wiles like `_qt_resources_0.4.5.dev9+g577de77_pyqt5_5.9.7.py` will be in the codebase. I mean any python file which name is not a valid Python module name. 

 
As far as I know, the current version of napari does not contain such files.

**Comment by tlambert03** [comment]
those files are autogenerated at runtime, and are part of our gitignore... so it's a bit strange that this precommit hook is not also ignoring them

**Comment by Czaki** [comment]
> those files are autogenerated at runtime, and are part of our gitignore... so it's a bit strange that this precommit hook is not also ignoring them

I do not know why these files are tested. But currently, these files have different name schema:
`_qt_resources_PySide2_5_13_2_9fb95879ef4c41b7750c685ae3465e22.py` so the problem could be solved by cleaning old files.

**Comment by goanpeca** [comment]
>so the problem could be solved by cleaning old files.

Is there a pre-commit that deletes old files?

**Comment by goanpeca** [comment]
So should we3 close this @sofroniewn ?
