### ISSUE TITLE
Scaling images shifts displayed origin

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#2778]
## 🐛 Bug

This is either a bug or I need clarification on the intended behavior of `scale`, the other layer transform parameters, and more generally the coordinate system of napari.

![scale_bug](https://user-images.githubusercontent.com/2608297/119422935-f119c600-bcb6-11eb-91ae-f7a78c226ae1.png)

## To Reproduce

Run the following example.

```python
import numpy as np
import napari


viewer = napari.Viewer()

viewer.add_image(np.ones((4, 3)), colormap='red', blending='additive', opacity=0.5)
viewer.add_image(np.ones((2, 3)), colormap='green', blending='additive', opacity=0.5, scale=[2, 1])

napari.run()
```

## Expected behavior

The image layers should be aligned so that I see a completely yellow (red + green) image. I roughly interpret the `scale` parameter as a pixel size / sample spacing, but maybe that's incorrect.

## Environment

Running in the dev napari conda environment at git commit: 8775a19bcecb8a5b4b8f2470a0a52ccb8a06f250

## Additional context

If I call `viewer.axes.visible = True`, then I can see that the origin is located at the center of both pixels, which explains why the second scaled image appears offset. This could be intended, but I'm struggling to justify why. I found some maybe related issues (e.g. #1118), but couldn't find any clarifying documentation. As this has potentially caused some confusion before, is it worth considering writing a developer guide around coordinates? I'd be happy to take that task on.

I stumbled across this potential bug while writing some tests for #2163, so any help would be appreciated and should help move those issues along.

**Comment by sofroniewn** [comment]
> If I call viewer.axes.visible = True, then I can see that the origin is located at the center of both pixels, which explains why the second scaled image appears offset. This could be intended, but I'm struggling to justify why. I found some maybe related issues (e.g. #1118), but couldn't find any clarifying documentation. As this has potentially caused some confusion before, is it worth considering writing a developer guide around coordinates? I'd be happy to take that task on.

Well observed! This was intentional (see #1660 for implementation, I'm also looking for issue with the background discussion but can't find it). 

I know other software can take the top left of the pixel as `(0, 0)`, but we felt that when doing imaging pixels can be thought of as samples from a particular point in space so it's natural to think of the center of the pixel as that point, and so put the center at `(0, 0)`. I believe ITK also takes this view. You can see this notebook for a nice explanation https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb (and photo there within)

![image](https://user-images.githubusercontent.com/6531703/119430342-75734580-bcc5-11eb-9988-d4ff1aa0fd3d.png)

I know @jni has a great article that he shares whenever this discussion comes up that maybe he can link to in this issue too.

We should definitely write this all up in a guide on our transforms, though and that would be much appreciated if you could take that on! I'm not sure if you've seen `python examples/affine_transforms.py` yet, but that has some toy data cases which hopefully make all this more clear and could be used in a docs guide.

**Comment by sofroniewn** [comment]
Here was original issue https://github.com/napari/napari/issues/310#issuecomment-506002559

**Comment by andy-sweet** [comment]
Thanks for the quick clarification @sofroniewn.

This is clear and logical, and agreed with @jni that treating pixels as point samples (not little squares!) is typically the best way of handling image operations in general. It does mean that image downsampling is not as simple as just changing the size and spacing because the point sample associated with the 0-index needs to shift its location, but that's fine.

**Comment by andy-sweet** [comment]
I'll close this issue, and will attempt to write some docs as I work on the other transform issues.

**Comment by jni** [comment]
> I know @jni has a great article that he shares whenever this discussion comes up that maybe he can link to in this issue too.

Here's the article:

http://alvyray.com/Memos/CG/Microsoft/6_pixel.pdf

I actually never really realised who the author was. Turns out to be one of the pioneers of digital image processing and digital graphics, inventor of the alpha channel (!), Lucasfilm employee, and cofounder of Pixar (!). He recently published an autobiography and Wired did a fascinating profile on him:

https://www.wired.com/story/pixar-animation-alvy-ray-smith-pixel/

All this to say, the "not a little square" article holds even more weight with me than it used to 😂.

**Comment by matham** [comment]
For other people, because I was running into the same issue. If you have two layers with arbitrarily different scales, and you want both layers to start visually at the same location, you have to use a translation of the following:

```py
import numpy as np
import napari


viewer = napari.Viewer()

base_scale = 1.5
larger_scale = 5
viewer.add_image(
    np.ones((4, 3)), colormap='red', blending='additive', opacity=0.5,
    scale=[base_scale, 1],
)
viewer.add_image(
    np.ones((2, 3)), colormap='green', blending='additive', opacity=0.5,
    scale=[larger_scale, 1],
    translate=[(larger_scale - base_scale) / 2, 0],
)

napari.run()
```

It was a bit confusing tbh especially after the comment that pixels are not "little squares" and the paper. But then for this calculation it turns out that it is little squares indeed 😅 I tried changing the interpolation to see if that changes anything, but it looks the same in terms of being little squares. Perhaps the point is that we shouldn't think of them as only little squares, even if they do largely get treated as little squares?

An overall observation, the `scale` docs just say `"Scale factors for the layer."`. It would be nice if it was clarified whether `translate` and other location parameters are applied after, or before scaling. Because that is always a question when there's scaling - how it affects other location based parameters.
