### ISSUE TITLE
Uninstallation feedback

### ISSUE THREAD

**Issue by joshmoore** [napari/napari#2786]
#### Description

I was surprised that "Removing" a plugin from napari uninstalled it from my environment.

#### Steps/Code to Reproduce

 * Start napari
 * open "Plugins" > "Install/Uninstall Packages"
 * find ome-zarr under "Installed Plugins"
 * click on "remove"

#### Expected Results

I perhaps naively assumed this would just remove the plugin from the current context.

#### Actual Results

The package was _uninstalled_.

**Comment by tlambert03** [comment]
that window is a gui-based interface for pip (which is why we named the menu "Install/Uninstall Packages").  If you want to have napari ignore a plugin (but not uninstall it) then use the checkbox next to the name (rather than the remove button):

![Screen Shot 2021-05-27 at 10 05 27 AM](https://user-images.githubusercontent.com/1609449/119840544-17b44880-bed3-11eb-82c8-bdda72b6d801.png)

(this requires #2565)

**Comment by tlambert03** [comment]
would changing the button text from "remove" to "uninstall" make this clearer?

**Comment by joshmoore** [comment]
Understood, and definitely no suggestion that that be changed. Just a datapoint that someone who understands these things quite well was *still* surprised. Minimally, I'd suggest renaming "remove" to "uninstall" to match the menu item. I'll leave people who understand UI/UX to say whether or not some other form of feedback ("package uninstalled", etc.) would prevent confusion.
