### ISSUE TITLE
Napari does not allow painting zarr arrays with Label layer

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#2806]
## 🐛 Bug

Napari doesn't allow painting when the Label layer was created from a Zarr array buffer because the default Zarr array indexing does not support NumPy arrays, it only accepts slices and integers.

## To Reproduce

- Run the following code:
```python3
import zarr
import napari


if __name__ == '__main__':
    zarray = zarr.zeros((100, 100, 100), dtype=int)

    viewer = napari.Viewer()
    viewer.add_labels(zarray)
    
    napari.run()
```
- Try painting the `zarray` layer.

## Expected behavior

To paint as usual.

## Environment

```
napari: 0.4.8rc7.dev3+ge035ffc6
Platform: Linux-5.8.0-53-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.2 LTS
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- console: 0.0.3
- napari-cell-segm: 0.1.dev1+gddf0eb0.d20210528
- napari-dexp: 0.1.dev4+g453bbc2.d20210528
- napari-ibacktracker: 0.1.dev2+gbecb212.d20210531
- napari-segm-annotation: 0.1.dev1+g7fbf135.d20210518
- scikit-image: 0.4.8rc7.dev3+ge035ffc6
- svg: 0.1.5
```

## Additional context

This could be solved by using `.vindex` method instead of `__getitem__`/`__setitem__` or `set/get_coordinates_selection`[[1]](https://zarr.readthedocs.io/en/stable/api/core.html#zarr.core.Array.set_coordinate_selection) for zarr arrays when the slicing is not using an integer or a slice object, but I don't think this is the best solutions. 

Any suggestion?

**Comment by sofroniewn** [comment]
Yes, this is a know issue. We might want to add a better error message/ warning cc @jni. @jni also has some work arounds involving tensorstore I believe -  maybe he can add more details

**Comment by jni** [comment]
@JoOkuma this is what @AbigailMcGovern achieved by opening the zarr arrays using tensorstore instead.  This answer on image.sc contains all the details you need to open the zarr with tensorstore and paint into it: https://forum.image.sc/t/automatically-saving-intermediate-results-while-annotating-in-napari/53256/2 tldr: use [this function](https://github.com/jni/zarpaint/blob/e76c89fd5beb6252cec941092dba70a71b9a58b6/zarpaint/_zarpaint.py#L58-L86) from zarpaint.

The "real" solution is for zarr itself to allow fancy indexing with `[]` to match NumPy's. (We don't want to have to special-case every array library that does things "just so", but rather to target a [common API](https://data-apis.org/array-api/latest/API_specification/array_object.html) shared by array libraries.) I [have a PR open on zarr-python to do this](https://github.com/zarr-developers/zarr-python/pull/725) that is almost at the finish line. 🤞

I will close this since I think the solutions are external to napari itself. Hopefully tensorstore will get you unstuck and that zarr PR gets merged so that future users can just use zarr normally!

**Comment by JoOkuma** [comment]
> @JoOkuma this is what @AbigailMcGovern achieved by opening the zarr arrays using tensorstore instead. This answer on image.sc contains all the details you need to open the zarr with tensorstore and paint into it: https://forum.image.sc/t/automatically-saving-intermediate-results-while-annotating-in-napari/53256/2 tldr: use [this function](https://github.com/jni/zarpaint/blob/e76c89fd5beb6252cec941092dba70a71b9a58b6/zarpaint/_zarpaint.py#L58-L86) from zarpaint.
> 
> The "real" solution is for zarr itself to allow fancy indexing with `[]` to match NumPy's. (We don't want to have to special-case every array library that does things "just so", but rather to target a [common API](https://data-apis.org/array-api/latest/API_specification/array_object.html) shared by array libraries.) I [have a PR open on zarr-python to do this](https://github.com/zarr-developers/zarr-python/pull/725) that is almost at the finish line. crossed_fingers
> 
> I will close this since I think the solutions are external to napari itself. Hopefully tensorstore will get you unstuck and that zarr PR gets merged so that future users can just use zarr normally!

Oh, I remember you guys telling me about about tensorstore. Thanks, looking forward to the merge of your zarr PR.
