### ISSUE TITLE
Weird points layer behavior when using the scale parameter.

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#2858]
## 🐛 Bug

The `world_to_data` method results in weird coordinates mapping when used with a scaled points layer.

## To Reproduce

1. Execute this code.
```python3
import numpy as np
import napari
from magicgui import magicgui


if __name__ == '__main__':
    viewer = napari.Viewer()
    
    # see additional context and try this
    # viewer.add_image(np.zeros((6, 10, 10)), name='Image', scale=(5.0, 1.0, 1.0))
    viewer.add_image(np.zeros((6, 10, 10)), name='Image', scale=(1.0, 1.0, 1.0))

    pt_layer = viewer.add_points(name='Points', ndim=3, scale=(5.0, 1.0, 1.0))

    @magicgui(call_button='Print points')
    def widget():
        # print(pt_layer.data)
        for row in pt_layer.data:
            print(pt_layer.world_to_data(row))
        print('---------------------')

    viewer.window.add_dock_widget(widget, area='left')
    napari.run()
```
2. Add some points in some z-slice that is not the first one.
3. Press the "Print points" button on the bottom left corner.
4. Check the output.

## Expected behavior

I expected the z-coordinates from these points to be scaled by 0.2 (1/5) but they are rescaled by 0.04 / (1/25).

## Environment

```
napari: not-installed
Platform: Linux-5.8.0-55-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.2 LTS
Python: 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- animation: 0.0.1
- console: 0.0.3
- napari-plugin-debug: 0.1.dev1+g7c4d7bd.d20210608
- scikit-image
- svg: 0.1.4
```

## Additional context

This doesn't happen when the layers have the same scale.
I found this trying to reproduce another bug related to `world_to_data` and the points layer.

**Comment by jni** [comment]
@JoOkuma I think this is actually expected behaviour: `pts_layer.data` is already in "data" coordinates, as the name indicates. 😂 So it makes no sense to run it through `world_to_data`. If you look at `pts_data * scale`, you get the coordinate of the point in world coordinates, and it matches up with the pixel coordinates of the image (with scale (1, 1, 1)). It looks like `layer.data_to_world` is not a thing, but it should be. Probably we need some attention to our transform models to make all these computations easier.

**Comment by JoOkuma** [comment]
Ow, I was using it backward 🤦. 

But why do the points' `world_to_data` results change when I change the image layer scale?

I thought the world be some fixed standardize space, with unitary scale, localized at the origin, etc. 
So it does change with the data?

**Comment by jni** [comment]
> But why do the points' world_to_data results change when I change the image layer scale?

Because the slider moves a different amount of world space based on the image layer.

**Comment by JoOkuma** [comment]
I'm having similar issues again, the world changes as new layers are added and I'm not able to keep track of the mapping between a points layer to world so I can query the values from a labels layer using its `world_to_data` from the points' coordinates.

@jni @andy-sweet Should I implement a `data_to_world` function analogous to the `world_to_data`? Is there any expected change to the transform models?

**Comment by andy-sweet** [comment]
@JoOkuma are you able to share a small code example that demonstrates the issue that you're having? I'm a little confused about what the issue is and I suspect there is some confusion about definitions.

Before that, here are some other comments/thoughts that might be useful.

Agreed that I think of the world coordinate system as one that should not change as new layers are added. Each layer defines a data-to-world transform (by composing its values of `translate`, `scale`, `rotate`, `shear`, `affine`), which takes a coordinate defined in that layer's local data coordinate system to the shared/fixed world coordinate system. That transform is accessible through a hidden/protected `_data_to_world` property on `Layer`. The reason its hidden is because it's not exactly the inverse of the older `world_to_data` which also includes the "grid" transform (which I'm assuming you're not using here), and because it's a property instead of a method.

The local data coordinate system is fairly clear to define for a rectilinear image, because the 0-vector tells us where the center of first pixel is (e.g. for a 2D image, this is typically the top-left pixel) and number of pixels in each dimension of data tells us where the center of the last pixel is (e.g. the bottom-right pixel).

It's less clear (to me at least) how to define a local data coordinate system for something like a `Points` layer because it's not a rectilinear grid of samples (it's a collection of coordinates). I suspect that `Points` is often intended to be an annotation of an `Image`, so the implication is that the local data coordinate system is shared between them, which I can see being useful when you can work in that local coordinate system - it may work for your usage too, in which case you may be able to forget about world coordinates.

If it's easier to talk over a video chat, I may be able do one later today.

**Comment by JoOkuma** [comment]
I'm using macOS and a different napari version and I can't reproduce the issue.
I need to check if it still happens in Linux with the most recent napari version, otherwise, I will close this issue.

I get your point that `Points` coordinates should be "attached" to an `Image` or `Labels` layer. I will keep this in my mind.

Thanks a lot of @andy-sweet

**Comment by andy-sweet** [comment]
> I get your point that `Points` coordinates should be "attached" to an `Image` or `Labels` layer. I will keep this in my mind.

Just to clarify, I don't think that a `Points` layer should always be attached to another layer (like `Image`, `Label`, and maybe `Surface`), but my guess is that it often will be. Also note that adding a `Points` layer after adding an `Image` layer causes the `Points` layer to inherit the same `scale` as the `Image` layer - that's also something worth knowing.

**Comment by andy-sweet** [comment]
Hey @JoOkuma, it looks like #3754 exposed `Layer.data_to_world` as the inverse of `Layer.world_to_data`, so do you think it's worth closing this issue now?

I think we could definitely improve our transforms model and documentation of it, but maybe this isn't the best issue to track that effort (see #3783 instead?).

**Comment by JoOkuma** [comment]
I agree it should be closed. Thank you.
