### ISSUE TITLE
Return key in preferences doesn't correspond to "ok"

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2993]
## 🐛 Bug

Right now when I have the preferences dialog open and press the return key it doesn't correspond to "ok" instead it asks me if i want to return to the default settings. I'd expected it to correspond to ok. We might also want the shading of the "ok" button to be slightly different to indicate that it is "in focus" when the dialog opens.

cc @ppwadhwa @goanpeca

**Comment by goanpeca** [comment]
>We might also want the shading of the "ok" button to be slightly different to indicate that it is "in focus" when the dialog opens.

Agreed, but this is a more general issues, Mac by default disables tab navigation and focussing but we can force that with Qt. 

Since we have color for hover, a different shade for in focus might not be that noticeable/accessible. Then this will depend on the OS, Mac usually put a blue outline to indicate focus. But Win might put a dashed outline to indicate the same. In general I like that it is clear if a button is hovered AND it has focus.

@liaprins would love to hear your thoughts on this and suggestions :)

**Comment by sofroniewn** [comment]
> Agreed, but this is a more general issues, Mac by default disables tab navigation and focussing but we can force that with Qt.

Yup ok, happy to punt on the styling/ focus/ tab issues - but i think we should fix the return => ok instead of revert to default

**Comment by goanpeca** [comment]
>but i think we should fix the return => ok instead of revert to default

Agreed, working on a fix :)

**Comment by liaprins-czi** [comment]
Yes, I agree that showing an in-focus state would be helpful, ideally if it can align with the OS's default design ... is it possible to do this with QT @goanpeca ? If we cannot call on the existing OS's focus design, then I think in general using a blue outline (similar to Mac OS treatment for in-focus) would communicate the idea.

Lastly, I was not sure what you meant by this @goanpeca :
> Mac by default disables tab navigation and focussing

Do you mean that happens in certain cicrumstance that happens to the Preferences dialog? If so, what causes that? Ideally it would not be disabling tab navigating and focus states (for a11y purposes)?
