### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#302]
## 🚀 Feature
Before our `0.1` and SciPy how would everyone feel about adding a code of conduct?

Github has good resources on different codes of conduct, and why they are valuable [here](https://opensource.guide/code-of-conduct/). 

> A code of conduct is a document that establishes expectations for behavior for your project’s participants. Adopting, and enforcing, a code of conduct can help create a positive social atmosphere for your community.

I'd recommend we go with the [Contributor Covenant](https://www.contributor-covenant.org/) which is fairly standard and widely used. Github makes is super easy to add it from the [community](https://github.com/napari/napari/community) tab. We could also then add a Contributor Covenant Badge to our README (details on their site).

**Comment by jni** [comment]
I'm in favour of adding a CoC, I've heard from several women in the SciPy community (and others) that they bristle at the overly-strict language on the Contributor Covenant. They have pointed me instead to the [PSF's](https://www.python.org/psf/codeofconduct/) and [Ruby's](https://www.ruby-lang.org/en/conduct/).

**Comment by kevinyamauchi** [comment]
I am also in favor of adding a Code of Conduct. Of the examples posted thus far, I like the PSF's for its simplicity and clarity.

**Comment by sofroniewn** [comment]
@jni looking at how the Contributor Covenant is used in practice, various projects slightly modify the "scope" and "enforcement" sections to better explain and meet their needs, for example [TensorFlow here](https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md), so if the concerns are just in those section then we might be able to address them pretty easily.

[Scipy](https://docs.scipy.org/doc/scipy/reference/dev/conduct/code_of_conduct.html) and [numpy](https://www.numpy.org/devdocs/dev/conduct/code_of_conduct.html) have pretty similar codes of conducts, which I prefer to the one from the `PSF` as they have more detail and structure, and also include a Diversity statement. I think `napari` further aligning itself with the values and practices of the scientific python ecosystem also make sense.

**Comment by kne42** [comment]
> I'm in favour of adding a CoC, I've heard from several women in the SciPy community (and others) that they bristle at the overly-strict language on the Contributor Covenant. They have pointed me instead to the [PSF's](https://www.python.org/psf/codeofconduct/) and [Ruby's](https://www.ruby-lang.org/en/conduct/).

Could you elaborate as to why this "overly-strict language" is a bad thing? Conversely, I find the PSF and Ruby CoC to be way too general and not enforceable. I like the Contributor Covenant because it leaves no room for interpretation, is explicit, and fairly comprehensive.

**Comment by jni** [comment]
Well, I don't have a strong opinion about these things. But if the idea is to make things "welcoming", then a bunch of legalese/corporate-sounding language with many clauses about enforcement might achieve that on some level, but on a "how does this document make me feel" level, it's the complete opposite.

I think the idea behind the PSF, Ruby, and other more "minimal" statements (such as scikit-learn's) is to lead by positive example, rather than by threat of punishment. I generally like that philosophy.

With regards to enforceability, I don't think it's a *big* problem: ultimately human judgement is required in all hairy situations, and you just need a document that says what is expected of people, and if someone does something against that spirit, the powers that be (ie everyone in this discussion) have to come to some agreement about what to do. I'm remembering an example of pretty aggressive behaviour in the Software Carpentry mailing list, and there is disagreement to this day about whether that person violated the CoC, whether banning was the right thing to do, etc. Heck, even with a complete legal system, Supreme Court Justices can't agree on outcomes. What I take from this is that what matters most in a CoC is, as @sofroniewn mentioned, that it sends a welcoming signal to the wider community. There's an argument that the Ruby and PSF documents are better at that than Contributor Covenant.

But to reiterate my starting position above: I don't have a lot of skin in the game. I'm lucky that I have never had to report or act on a CoC violation ([this](https://github.com/scikit-image/scikit-image/pull/3645#issuecomment-452952953) is as close as I've come), and work with a great group of people ;) so everything about this feels academic, and I would defer to more experienced people in any decision. But even they disagree. =)

**Comment by sofroniewn** [comment]
To me a strong code of conduct serves as both a real and signaled protection to those most vulnerable to harassment, and unfortunately, I think is needed in the context of an internet at large (think twitter and beyond) that can be hostile.

For this reason, I, like @kne42, prefer the more explicit codes of conduct, like the [Contributor Covenant v1.4](https://www.contributor-covenant.org/) or how it was adapted by [SciPy](https://docs.scipy.org/doc/scipy/reference/dev/conduct/code_of_conduct.html) and [numpy](https://www.numpy.org/devdocs/dev/conduct/code_of_conduct.html).

I agree with @jni though, around “enforcement”. Ultimately it will be up to us to interpret any CoC and try our best to make the right decisions. I’m not worried that by having a stronger code of conduct we’ll have to deal with frivolous complaints, or be forced to sanction people unnecessarily. There will always be gray zones though and as @jni notes, human judgement will always be required.

I noticed that @stefanv is on the committee for SciPy dealing with their CoC reports, and I wonder if he would have any other guidance for us or if he would recommend that we also adopt the SciPy CoC?

I feel pretty strongly about this topic, but we should only adopt a CoC that we actually stand behind and are willing to enforce when necessary. So I suggest we continue to reflect on this, and give some of the other members of the community who missed yesterdays meeting an opportunity to catch up on the discussion too.

**Comment by freeman-lab** [comment]
Much appreciate the discussion here! I'll just add that of the options above, something similar to the [scipy](https://docs.scipy.org/doc/scipy/reference/dev/conduct/code_of_conduct.html) version seems both appropriate in tone and approach and maintains consistency with core parts of the Python ecosystem, which is a theme of this project as a whole. I absolutely second @kne42 's point that there's value in being more explicit, and am also really curious to hear @stefanv's perspective.

**Comment by stefanv** [comment]
We worked on the SciPy Code of Conduct for a long time.  The goal was to write a document that shows clear and serious intent, without frightening people with policing language.  Code of conducts are contentious partly because cultures differ in how much tolerance they have for control vs safeguarding of freedoms.

The way the SciPy CoC tries to address the issue is by having a layered document: the first part is positive, and deals with desired outcomes.  We'd like to have people participate in the following way, so that the following goals can be achieved.  Most people will hopefully read this, nod their heads, agree to participate, and move on.  But, of course, the document cannot stop there, because you have to be clear about the consequences of breaches, especially to reassure people who have been in difficult situations before.  So the document then dives deeper into the rules, and ultimately explains the consequences of breaking those rules.  We also have a [separate document detailing follow-up procedures](https://docs.scipy.org/doc/scipy/reference/dev/conduct/report_handling_manual.html#coc-reporting-manual).

One could argue that even more language is needed around enforcement, but I think the assessment above is correct: in case of a breach, human interaction will be required—and the humans responsible for the transgression will have to judge how to best handle the situation.  You cannot (and probably don't want to) write a document that covers every single type of transgression and exactly how that transgression will be handled; we leave some freedom for humans to mediate in a kind and thoughtful way.

I don't think there is anything wrong with the contributor covenant, but personally I find that document a bit clinical.  The SciPy CoC spends time to describe higher level intent and outcomes, and I find that helpful in calibrating the mind of the reader / community participant.

**Comment by sofroniewn** [comment]
Thanks @stefanv for that very helpful context.

At the meeting today those present came to agreement that we should adopt the `scipy` code of conduct. I will make a PR adding the CoC and followup procedures.

We will need to add a contact email, name individuals that will be on the committee dealing with reports, provide an alternate contact for reports involving the members of the committee or where there might be COI, and make sure we have resources to privately document and maintain any records relating to a report.

For those that were not present at the meeting today but want to weigh in here feel free to do so. Once there is a PR we can have further discussion about the details there too.

**Comment by sofroniewn** [comment]
This is closed by #374
