### ISSUE TITLE
Index error when processing points properties with no content

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3054]
## 🐛 Bug

`layer_utils.get_current_properties` makes assumptions about the length of data in the properties array, which leads to an index error if the properties are empty.

While I doubt anyone would intentionally create  an empty properties array, this sort of thing could come up in batch processing (as it did for me) where you don't know ahead of time the content of the data

## To Reproduce

```py
import napari
import numpy as np

points = []  # some unknown
napari.view_points(points, properties={'index': np.arange(len(points))})
```

```py
  File "<string>", line 4, in add_points
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/points/points.py", line 387, in __init__
    self.current_properties = get_current_properties(
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/utils/layer_utils.py", line 319, in get_current_properties
    current_properties = {
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/utils/layer_utils.py", line 320, in <dictcomp>
    k: np.asarray([v[0]]) for k, v in choices.items()
IndexError: index 0 is out of bounds for axis 0 with size 0
```

## Expected behavior

it should fail gracefully in the case of an empty list

# Related

I was making `properties['index']` as a workaround for providing text:  #3053

**Comment by sofroniewn** [comment]
@andy-sweet just flagging for you - not sure if you've seen, but something you might want to know about

**Comment by andy-sweet** [comment]
@tlambert03 : the error is gone now due to the change in implementation here (i.e. from properties to features).

As you add points, they will get nan values because `pd.DataFrame({'index': []})` will use a default dtype of float64 for the index column, and without an explicit `feature_default` for `'index'` we'll use `None` which will be coerced to `nan` for the float64 column.

I think that seems pretty reasonable and the behavior could be altered by updating `feature_defaults` or setting the dtype of the column explicitly.

If you can't reproduce this and the above sounds good, please close this.

**Comment by tlambert03** [comment]
hooray!
