### ISSUE TITLE
Deleting points raises IndexError (MacOS)

### ISSUE THREAD

**Issue by maweigert** [napari/napari#3078]
## 🐛 Bug

Removing points from a points layer via "Delete selected points" sometimes results in an`IndexError: index is out of bounds`. This happens only for certain points and in specific situations - git bisects indicates commit 5dd37eccb84e3291123 to be the culprit (maybe some events race condition?)

## To Reproduce

The following script generates 3 points `P1--P2--P3`. Directly selecting the middle one (P2) and quickly deleting it via the keyboard results in the above error in ~30% of all cases
 
```python
import numpy as np
import napari
w = napari.Viewer()
points=np.stack([np.ones(3), 10*np.arange(3)], axis=-1)
points_layer = w.add_points(points, size=2)
points_layer.mode="select"
napari.run()
```

```python
IndexError: index 2 is out of bounds for axis 0 with size 2
```
## Expected behavior

Point being removed without throwing a tantrum

## Environment

```
napari: 0.4.10 (3bd58bde6858eb4d9f)
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.8 (default, Feb 24 2021, 13:46:16) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.7.0
Dask: 2021.04.1
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 ATI-3.10.18
- MAX_TEXTURE_SIZE: 16384

```

**Comment by jni** [comment]
Maybe there should be a limit on the number of terrible bugs one person can report in a 24h period hey @maweigert? 😂 

(Joking, just thought it was funny that I literally *just* finished responding to your other bug, hit "archive" on the GH notification, and this was the next top notification! 😂)

Thanks for the git-bisect! Should really help narrow down what is happening!

**Comment by jni** [comment]
Ok so this one I can't seem to reproduce... Perhaps it has to do with mouse sensitivity and whether the point thinks it's moving while it's being deleted, and my mouse is on a less sensitive setting than yours... (Tried with both trackpad and mouse.) Would you mind copy-pasting the full traceback @maweigert? You might want to use a gist.github.com to paste into if it's too long. Thank you!

**Comment by maweigert** [comment]
> Would you mind copy-pasting the full traceback @maweigert?

Sure, here it is https://gist.github.com/maweigert/034ecccab08b02cf4aface706f5fb732

**Comment by DragaDoncila** [comment]
@maweigert thanks for the report. I couldn't reproduce on ubuntu but I've managed to reproduce now on Mac and am looking into it.

**Comment by DragaDoncila** [comment]
Finally managed to figure out exactly what's happening here.

@jni was right that this happens when a slight mouse drag is detected on click. Since #2992 this point move also emits a `data` event, causing `_on_layers_change` to fire [on the viewer](https://github.com/napari/napari/blob/9dd9fa6390ad4dfe9a08194de8c84e7e87bfeaa0/napari/components/viewer_model.py#L335). This resets the cursor position to 0 (not sure that this is strictly necessary?), which eventually causes `get_value` to be called on the `points` layer and [this line](https://github.com/napari/napari/blob/9dd9fa6390ad4dfe9a08194de8c84e7e87bfeaa0/napari/layers/base/base.py#L1007) sets `self._value` to 0 (the new cursor position). 

Because previously we weren't emitting the `data` event, `self._value` was always holding the point being selected for deletion, which was causing `self._value` to be reset to `None` on the points layer [here](https://github.com/napari/napari/blob/9dd9fa6390ad4dfe9a08194de8c84e7e87bfeaa0/napari/layers/points/points.py#L1398). Now that `self._value` isn't `None` but a real point index, we run into issues with setting the highlight on the point (we still try to highlight a point that may not exist) and from then on with any cursor position change because we're still trying to access a point whose properties have been deleted - errors fire as you move the cursor around.

It looks like the comment on [this line](https://github.com/napari/napari/blob/9dd9fa6390ad4dfe9a08194de8c84e7e87bfeaa0/napari/layers/base/base.py#L1005) has come of age and maybe now is the time to consider decoupling `base.get_value` and `points._set_value`, although this would be a much larger change than just fixing this one bug and seems like it would also affect `shapes`.

Two quick alternatives if we wanted to fix this ASAP and then look at the `self._value` issue separately would be
- not setting cursor position to 0 `on_layers_change` [here](https://github.com/napari/napari/blob/9dd9fa6390ad4dfe9a08194de8c84e7e87bfeaa0/napari/components/viewer_model.py#L347) - not sure exactly what the implications of that would be. I've tried to discern changes in Viewer behaviour without it but couldn't really, and I've also run tests without it and all seems okay, but probably someone else should weigh in here.
- always setting `self._value` to `None` in `remove_selected` [here](https://github.com/napari/napari/blob/9dd9fa6390ad4dfe9a08194de8c84e7e87bfeaa0/napari/layers/points/points.py#L1398) which I think should be a minimal impact change for users because as soon as they move their cursor they will still get valid information in their status bar.

The last option would be my preferred solution if we want to look at `self._value` separately after this bug is fixed, but not sure if that's what we want @sofroniewn @jni?

**Comment by jni** [comment]
@DragaDoncila Honestly I like *both* options, and think we should probably do both. I don't think it should make any difference setting the cursor position to (0, 0, ...) when changing the layer list, as it's not a particularly special value. But I agree with you that setting `self._value` to None feels more "proximal" to the fix. 😅 So if @sofroniewn agrees I would suggest make both changes in a PR.

A bigger structural fix can come later, this is a pretty significant bug so I'd like the fix in the next release.

**Comment by sofroniewn** [comment]
> not setting cursor position to 0 on_layers_change

I think you might need to either pad/ drop dimensions so that cursor.position has correct dimensionality - i.e. the significance is not about it going to `0` but going to the right `n` in our `nD` representation. That's a shame no test is currently catching that behaviour, but you might be able to write a test which changes dimensionality of layers and moves cursor to find bug

> always setting self._value to None in remove_selected

seems like a good idea

**Comment by maweigert** [comment]
Thanks!! Points are getting deleted without complaining for me again :)
