### ISSUE TITLE
Consider making "ok" the default when closing the preferences window

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3144]
## 🧰 Task
Currently, if you change a preference in the preferences and then close the window, the new preferences will be reverted _unless_ you click the OK button.

This is different from the standard behavior (on mac at least) where if you open preferences and change something and close it, the preference "sticks", even if you close the window with the "x" button at the top left.  I get tripped up by this a lot.

I'd propose that we make "accept" the default behavior of that dialog.  (Honestly, I feel like it would even be ok to remove the OK and cancel buttons... I can't find many other examples in my apps of preferences that have those options.  They just make changes immediately and persist them.

**Comment by brisvag** [comment]
If (or when?) preferences changes are completely tracked by the action manager and can be easily undone, I'd say this is great. Before then, I had experiences with big software with a lot of settings where you click something by mistake and then you'll never know what you messed up because it was saved automatically...

**Comment by tlambert03** [comment]
I don't think preference changes are slated to be added to the undo/redo architecture... so let's chat about it assuming that that won't happen for the moment.  I _still_ think changing (and then losing) intentional changes is a more common and equally frustrating experience than changing something accidentally and not noticing/forgetting what you changed.
In any case, even with the current system, if you accidentally changed something and then clicked ok, you're still in the same boat (it's been "applied").  So this issue really pertains to whether one should have to click "OK" to apply their changes or not.  I suspect in most cases, the "accidental" change will only have been noticed after you clicked ok anyway, in which case it's too late.

**Comment by brisvag** [comment]
True, I'm convinced!

**Comment by LCObus** [comment]
From a UX front, I totally agree with you Talley! Systems preference "stickyness" is expected behavior and thus eliminating the extra click "ok" would be ideal. @brisvag isn't without merit, but speaks more to ensuring the preference dialog is well designed in the first place to avoid mistaken clicks, and perhaps adding a "are you sure, this will change XYZ" if there's a given preference that has breaking changes impact. But, generally preferences are just that- preferences- and shouldn't require heavy weight.

**Comment by tlambert03** [comment]
Thanks @LCObus.  sorry, this should be closed 😂  it was implemented in #3178

**Comment by LCObus** [comment]
glad to hear it!
