### ISSUE TITLE
Slider GUIs look like elements are missing with Qt 5.12

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3221]
## 🐛 Bug

I'm just testing napari 0.4.11rc0. It appears like some GUI changes were not finished in the points layer GUI.

This is how it looks in 0.4.10:
![image](https://user-images.githubusercontent.com/12660498/130476930-fa350c96-6339-454b-9970-2a7f1de5f9cf.png)

And this is the 0.4.11 version:
![image](https://user-images.githubusercontent.com/12660498/130476820-a44d35b8-15c7-48a9-bae3-a63db3e61806.png)

Behind opacity and point size is something missing. It appears.

## To Reproduce

1. Start napari
2. Add a points layer

## Expected behavior

Revert to the old GUI or add labels and display numbers

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.11rc0
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.1
SciPy: 1.7.1
Dask: 2021.05.1
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 466.77
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- Measurements (Plot profile): 0.1.3
- Measurements (skimage regionprops): 0.1.6
- Search (Plugin): 0.1.0
- Segmentation (OCLRFC): 0.4.4
- Segmentation (split/merge): 0.1.2
- Utilities (skimage regionprops): 0.1.6
- Visualization(B/C): 0.1.1
- aicsimageio-in-memory: 0.3.5
- cellpose-napari: 0.1.3
- clEsperanto: 0.10.0
- console: 0.0.3
- napari-yapic-prediction: 0.1.dev99
- ome-types: 0.2.7
- omero: 0.1.1
- scikit-image: 0.4.11rc0
- svg: 0.1.5

 - Any other relevant information:

**Comment by tlambert03** [comment]
oooh, no... can you run `pip install -U superqt` and retry?

**Comment by haesleinhuepf** [comment]
> oooh, no... can you run `pip install -U superqt` and retry?

Sure! It said:
```
Requirement already satisfied: superqt in c:\users\rober\miniconda3\envs\bio1\lib\site-packages (0.2.2)
```

And the issue remains :-)

**Comment by tlambert03** [comment]
bummer... must be a styles difference on windows.  It's amazing that we apparently have so few devs working on master on windows that this hasn't been seen before! 😖  i'll log into a windows computer later today and see if I can reproduce

**Comment by tlambert03** [comment]
(btw, this is what it should look like, and what it looks like on mac):
<img width="254" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/130478421-76b2e7d4-3155-4748-99d4-aa1fec84f041.png">

**Comment by tlambert03** [comment]
ugh... even more of a bummer: it apparently varies across PCs.  Here's the first one I tried (not perfect, but much better):

<img width="259" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/130479276-f3b0f318-5ce3-45aa-8dd6-7862ad16a010.png">

@haesleinhuepf ... can you remind me about your display?  pixel pitch, and scaling, etc...

**Comment by haesleinhuepf** [comment]
> @haesleinhuepf ... can you remind me about your display? pixel pitch, and scaling, etc...

Napari info says this:
> Screens:
> 
> * screen 1: resolution 1920x1200, scale 1.0

And I'm working on an FullHD screen recently:
![image](https://user-images.githubusercontent.com/12660498/130479604-a8bc4d07-6b7a-4254-abf0-cf88686e3939.png)

**Comment by tlambert03** [comment]
thanks

**Comment by haesleinhuepf** [comment]
I see a similar issue on the labels layer GUI:
![image](https://user-images.githubusercontent.com/12660498/130481616-45ebf9df-51c3-489d-b6de-3480d41ae730.png)

**Comment by tlambert03** [comment]
> I see a similar issue on the labels layer GUI:

yes, this is not points specific... I would expect you to see this on all sliders now

**Comment by haesleinhuepf** [comment]
Correct :-)
![image](https://user-images.githubusercontent.com/12660498/130482643-87b632cf-4bbe-47a2-b283-075e60eef1bd.png)

**Comment by tlambert03** [comment]
I'm really kind of at a loss here.  maybe @goanpeca knows something about strategies for debugging cross-platform font rendering issues?

**Comment by goanpeca** [comment]
I do not have a windows machine handy :-\ , but we could try to add some automated screenshot taking and have some base images to run as benchmarks on different operating systems to at least get some failsafes on CI

**Comment by tlambert03** [comment]
even that wouldn't have necessarily caught this, since I see most of the text on sliders on my windows machines, but @haesleinhuepf  doesn't see it on his :/

**Comment by goanpeca** [comment]
@haesleinhuepf do you see any (qt) warnings on the console when running napari from it ?

**Comment by haesleinhuepf** [comment]
> @haesleinhuepf do you see any (qt) warnings on the console when running napari from it ?

No, I don't see any qt-related warnings.

**Comment by nclack** [comment]
fwiw, mine looks ok w 0.4.11rc1

![image](https://user-images.githubusercontent.com/98295/130705510-939be1c2-4032-4bd8-b3eb-f4ebbb993870.png)

It looks like my opacity is only printed with one digit past the decimal.  I tried changing display scaling from 100 to 125 to 150 and nothing seemed out-of-place (except that the "layer controls" title for the dock widget is clipped).

**Comment by nclack** [comment]
Dragging between monitors w different scaling produces interesting behavior.  I get a slightly different layout on the other screen.

![image](https://user-images.githubusercontent.com/98295/130706219-ed1a7cd9-d42a-464c-b0be-c0fa46e354b9.png)

**Comment by sofroniewn** [comment]
Ok sounds like this may end up being very machine specific. We can give it one more day, but right now I'm leaning towards releasing tomorrow without this fixed. We can release a patch maybe when it is fixed

**Comment by haesleinhuepf** [comment]
@goanpeca @sofroniewn I can trace this issue down to specific pyqt5 versions. 

I just set up a new conda environment and installed everything from scratch and there the bug is more or less gone:
![image](https://user-images.githubusercontent.com/12660498/130828580-8b66a6d5-7436-40c4-886f-719d33a30326.png)

If I then downgrade in this environment my pyqt5 to 5.12.3, I can reproduce the bug again:
![image](https://user-images.githubusercontent.com/12660498/130829754-7b9322ba-a094-4457-b06d-d5f52e4105b7.png)

Would it be possible to make sure that napari 0.4.11 comes with an updated pyqt (5.15.4)?

**Comment by tlambert03** [comment]
> If I then downgrade in this environment my pyqt5 to 5.12.3, I can reproduce the bug again:

thanks, that's really helpful ... we should have tested that from your original info.

> Would it be possible to make sure that napari 0.4.11 comes with an updated pyqt (5.15.4)?

Unfortunately, since qt is such a ubiquitous dependency, and because 5.12 is still the most recent version available from conda-forge, pinning napari to a later version (which is how we would ensure that someone always had a more recent version) would basically break our conda distribution, and a lot of environments using napari on 5.12... so we'll have to fix this for 5.12

**Comment by tlambert03** [comment]
I opened #3243, which effectively reverts #2753 if someone is on 5.12 or 5.13 ... that will give us a little more time to dig into this without totally mangling the UI for users on those versions

**Comment by sofroniewn** [comment]
> 5.12 is still the most recent version available from conda-forge

indeed - maybe @goanpeca this is something we can help move forward too - i think tania from quansight mentioned it might be something they were looking into - if some resources are needed to help maybe i can get some from CZI. would make a big difference for us i think

**Comment by goanpeca** [comment]
Indeed, I think we can help move this forward :) pinging @jaimergp @trallard

**Comment by jaimergp** [comment]
Hi 👋 !

I looked into the conda-forge pinnings because `qt` is a central piece of many packages, so I guessed they would be strict about bumping its version. Indeed, [it has been pinned to 5.12 for two years](https://github.com/conda-forge/conda-forge-pinning-feedstock/blame/ce8a3979cc805c9d2a3a96527c56ad089ebc4cd8/recipe/conda_build_config.yaml#L644), so that tells us that `qt` is not updated very often there, and probably for good reasons. Changing this pin would involve rebuilding quite some packages. Also note that `qt` needs to be built off-CI because Azure times out before it finishes, which involves somebody building and uploading manually.

If you do want to ask about it, an issue would need to be opened [here](https://github.com/conda-forge/qt-feedstock/issues).

I am afraid that `qt` will still be pinned to `5.12` for a bit, but I'll ask around.

**Comment by jaimergp** [comment]
Oh, 5.12 is LTS with EOL at 2021-12-05, so I guess that's why that's the one pinned.

Do the patch releases help with the bug? CF has 5.12.9, but I see 5.12.11 was released (providing this in CF is feasible-ish). Maybe that one ships some of the needed bugfixes for this?

**Comment by jaimergp** [comment]
5.12.10 is being prepared [here](https://github.com/conda-forge/qt-feedstock/pull/189). Somebody needs to build the packages for Windows.

**Comment by goanpeca** [comment]
Hi @jaimergp, thanks for the information and digging it up.

Just wanted to point out that Qt 5.15 is also LTS (and [will be the last long term support version](https://www.qt.io/blog/qt-5.15-released) BTW).

It has been around since May 2020, so besides the hurdles of having to build Qt offline, and any other complications in building such a complex package, I do not see a "strong" reason to *not* update those packages to 5.15 anyway beyond 2021-12-05.

>Changing this pin would involve rebuilding quite some packages.

Could you elaborate on this?

>If you do want to ask about it, an issue would need to be opened here.

Could you open an issue?

Thanks!

**Comment by jaimergp** [comment]
> Could you elaborate on this?

To maintain ABI compatibility within the conda-forge ecosystem, they pin most of the libraries packages can link to (C/C++ `host` dependencies, mainly). This way, they ensure several packages linking to, let's say, Qt, can coexist in the same process. That's why `qt` is pinned to `2.12` now; otherwise each feedstock would be able to pick their own (or accidentally use a more recent one), thus destroying all the ABI efforts.

Every time the pinning file is updated, a "migration" needs to happen. This involves a bot submitting PRs to all the packages that depended on `qt` in a binary/host way, "rerendering" the contents of the feedstock so the new version is used for linking. Since `qt` is quite popular, this might involve a few of them. 

That said, 5.12 is EOL this December, so maybe it's time to start thinking of 5.15. OTOH, if this is accepted, it will be a matter of some weeks at least, so I'd say we cannot rely on that to fix this present issue.

**Comment by tlambert03** [comment]
thanks for the background @jaimergp!  very helpful to understand.

> so I'd say we cannot rely on that to fix this present issue.

That's fine, I suspect there's a reasonable workaround to this issue, and in any case, it's not as urgent after #3243.  Hopefully there will be a transition to 5.15 after the EOL at the end of the year.  That would be "fast enough" for most of the things we need i think

**Comment by jaimergp** [comment]
> Hopefully there will be a transition to 5.15 after the EOL at the end of the year

Yes, this is a reasonable expectation. I am going to open an issue now.

-- edit: see here https://github.com/conda-forge/qt-feedstock/issues/200

**Comment by jaimergp** [comment]
Hm, looks like Qt 5.15 is only LTS for [commercial](https://lists.qt-project.org/pipermail/development/2021-January/040798.html) license holders and the next LTS, 6.2 (planned), is going to fall under the same criterion: once 6.3 is released, LTS is only for commercial users.

**Comment by andfoy** [comment]
Hi, just for everyone's information, there is an ongoing update of Qt (5.15) on conda-forge in PR https://github.com/conda-forge/qt-feedstock/pull/198, all packages were built and tested on https://github.com/andfoy/qt-recipe, right now I'm adjusting the recipe so that the conda-forge maintainers accept the changes.

**Comment by trallard** [comment]
Hey folks - thanks for the ping. As Edgar mentioned he is currently working on the Qt update so hopefully within a few weeks/ couple of months (?) we will be able to have an update

**Comment by sofroniewn** [comment]
Love this discussion

> As Edgar mentioned he is currently working on the Qt update so hopefully within a few weeks/ couple of months (?) we will be able to have an update

Ok thanks - good to know

**Comment by psobolewskiPhD** [comment]
Slightly tangential: It would be *sick* if updating pyqt5 on conda-forge could include arm64 binary for macOS (Apple Silicon). That's the only 'hoop' making napari a smidge harder to install native.
At the moment `homebrew` has arm64 binaries available (both pyqt5 and pyqt6):
https://formulae.brew.sh/formula/pyqt#default
but native pyqt is not on conda/pip, and getting homebrew binaries into a conda env is kludgy.

**Comment by jaimergp** [comment]
Both Qt and PyQt are [part of the migration process](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt#L120-L121), but Qt is still [pending](https://github.com/conda-forge/qt-feedstock/pull/185). See the [graph here](https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/armosxaddition.svg?sanitize=true) and this [other issue](https://github.com/conda-forge/pyqt-feedstock/issues/101). It will probably require a native build.

**Comment by andfoy** [comment]
I'm also working on providing packages for aarch64 and arm64 as well. See: https://anaconda.org/andfoy/qt, https://anaconda.org/andfoy/qtwebengine, https://anaconda.org/andfoy/pyqt and https://anaconda.org/andfoy/pyqtwebengine

**Comment by jaimergp** [comment]
Qt and PyQt 5.15 are available on conda-forge now.

**Comment by sofroniewn** [comment]
> Qt and PyQt 5.15 are available on conda-forge now.

Yay! I think this can then be closed. If not someone can please reopen - thanks!!
