### ISSUE TITLE
✨ Brush cursor is too small to notice when zoomed out

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#3287]
### Overview of design need
- **Is there an existing GitHub issue this design work pertains to?** 
[Cursor should be a crosshairs cursor for points 'add' mode #2142](https://github.com/napari/napari/issues/2142)

- **Also link to any specific comments or threads where the problem to be solved by design is mentioned**
[Comment explaining the current issue with brush cursor](https://github.com/napari/napari/issues/2142#issuecomment-780375973)

- **In a sentence or two, describe the problem to be solved for users**
The brush size can be selected to be very small, and when an image is zoomed out this makes it very easy to lose track of. There may be different ways to solve for this: can we indicate that the brush size is small, but still make (surrounding design elements of the) cursor larger or stand out better? Or what about the ["loupe" concept suggested by emilmelnikov](https://github.com/napari/napari/issues/2142#issuecomment-780375973)? We should investigate how other tools handle this and also consider other possible ideas.

### What level of design is needed? (Choose all that apply)
- [X] **User experience research:**  high-level recommendation/exploration of user needs, design heuristics, and / or best practices to inform a design experience  
(Use this option when you feel there’s a challenge to be solved, but you’re curious about what the experience should be — may involve research studies to understand challenges/opportunities for design)
- [ ] **Information flow / conceptual:** organizing and structuring of information flow and content, including layout on screen or across multiple steps
- [X] **Visual:** creating mockups, icons, etc
(If choosing this level alone, it means that the content to be mocked up and its organization is already known and specified)

### Is design a blocker?
- [ ] **Yes:** engineering cannot proceed without a design first
- [X] **No:** engineering can create a first version, and design can come in later to iterate and refine

If selecting **Yes**, how much design input is needed to unblock engineering? For example, is a full, final visual design needed, or just a recommendation of which conceptual direction to go?

### T-shirt size
- [ ] ●○○○○ XS: able to be done in a typical workday or two
- [X] ●●○○○ S: able to do within one sprint, if also working on other things in the sprint
- [ ] ●●●○○ M: able to do within one sprint, if it is the sole focus
- [ ] ●●●●○ L: will likely take more than one sprint to complete, but less than two
- [ ] ●●●●● XL: a very large experience to be determined or overhauled, will need to be broken down further

**Comment by isabela-pf** [comment]
Addressing the 
> We should investigate how other tools handle this and also consider other possible ideas

point, I've tried this out with color pickers on some software I had around (mostly creative tools) since that is a commonly used pixel-perfect behavior like we might need for napari. Below are my notes and photos (when applicable)

Looking at these also gave me some ideas on questions that could help us choose a direction.
- Is pixel-perfect precision of the cursor selection needed or not?
- Is this a problem where specific cursors per type of interaction would be helpful, or is there a kind of one-size-fits-all solution that would be better for a consistent interaction?

Here's some examples (please excuse the weird photos of a screen because sometimes screen shots don't capture cursors)! In no particular order.

### Adobe Photoshop, Illustrator, and InDesign

These all have the same pattern. When the user initiates a tool, in this case the eydropper, the cursor shape changes. If users have the "precise cursor" setting selected in their global settings, they see a cross with no center cutout and the cursor will not change based on tool selection.

![Photoshop with the eyedropper tool changing the shape of the cursor](https://user-images.githubusercontent.com/50221806/139349479-f32fc9a8-2590-40d8-acdf-a8cb37161af1.JPG)

### Inkscape

I don't spend a lot of time in Inkscape nowadays, so I was surprised to find a different approach to the eyedropper cursor here. Yes, the cursor changes to that typical eyedropper shape, but it also gains a crosshair for more precise selection and a small square sampling the selection for easier viewing. All these pieces move together as one cursor.

![Inkscape's eyedropper tool with changed cursor](https://user-images.githubusercontent.com/50221806/139351108-a549c0d9-22f4-471a-be82-0a036cf336d9.JPG)

### [Colour Contrast Analyser](https://www.tpgi.com/color-contrast-checker/) 

I use this tool often to grab colors across my screen, a case where it is important to know specifically which pixel I am selecting. The cursor does follow the center square, but the magnification follows around it so overall it feels like a larger cursor.

![Colour Contrast Analyser's combined cursor and magnification](https://user-images.githubusercontent.com/50221806/139349641-ef9f4a5f-4270-4d57-95db-44f009ea387c.png)

### Figma 

Figma has one of the most elaborate systems for selection. The cursor changes to a standard eyedropper illustration (not shown below), a magnifier circle appears fixed in the upper right with the currently selected hex code, and the center square of the magnifier reflects the current place of the cursor.

<img width="1410" alt="Figma's eyedropper tool with changed cursor and extra magnifier" src="https://user-images.githubusercontent.com/50221806/139350261-c6715831-50f0-40b5-9d8e-fd4f36261f5b.png">

### Preview (mac)

In preview, there's not a selection-focused tool of this source that I could find. I did include the magnifier because it similarly changes the cursor. The whole cursor becomes this imitation magnifying glass.

<img width="664" alt="Preview's magnifier tool." src="https://user-images.githubusercontent.com/50221806/139350774-5d030fcd-0187-4f18-981b-e34b74624478.png">

### Autodesk Sketchbook

This one has interesting interactions because the UX is definitely optimized for a non-mouse set up. If the eyedropper tool is selected but not in use, it changes to the standard eyedropper illustration. If a user clicks an area to select a color, the cursor appearance does not change.

![Autodesk Sketchbook's eyedropper tool with a cursor not in use](https://user-images.githubusercontent.com/50221806/139351307-d80e12f6-1667-461d-9433-e15500b4bb34.JPG)

But when the tool is actively being used, say holding down the mouse (but more than a quick click), then it uses the magnification surrounded a square cursor like some of the other approaches.

![Autodesk Sketchbook's eyedropper tool with a cursor magnified when in use](https://user-images.githubusercontent.com/50221806/139351328-54bcd830-a66c-4f06-9f48-0a3bd9f98bff.JPG)


### General observations
On a separate note, I did find it interesting that there appears to be pretty consistent cursor sizes. The larger sizes are some kind of addition to the cursor in almost every case. This does seem like it gives us a good idea of what might be a good size for napari proportionally to address the initial problem.

I could also see the emphasis on interactions changing appearances working well for napari. When you are exploring an image with a tool, having an unobtrusive, normal-sized cursor could be ideal. But once you need to make a pixel-perfect selection, that larger cursor seems like the best way to ensure the selection is the desired one.

These are just some explorative thoughts! As always, thoughts and feedback are welcome.

**Comment by Czaki** [comment]
Is this solved by #5141?

**Comment by psobolewskiPhD** [comment]
> Is this solved by #5141?

I think so. The color picker also uses a crosshair now—loupe mode would be cool, but not sure it's really needed?— nd sm. brush is crosshair.

**Comment by isabela-pf** [comment]
I agree this has been solved in one of the listed options, so I think it can be closed. If we find the core problem of a small or imprecise cursor persists, we can always reopen this issue.
