### ISSUE TITLE
Add a docs dependency list

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3289]
## 🧰 Task

See comment in https://github.com/napari/napari/pull/3265#discussion_r698247029 from @jni

> @sofroniewn I actually think we should add a docs dependency list that includes everything needed for our examples and documentation. Then all should reference that also, yes. All should mean all. 😂

**Comment by tlambert03** [comment]
hmmm... that could get hairy pretty quickly?  I'm fine with `all` meaning "all" in some sense ... but then I'm not sure we should encourage people to use `all` for our standard install just so that they can run the examples (which, I'll note, don't even ship with napari)?  We need something that means "the bare minimum you need to be able to run the command `napari` and have it work", and I think that should be the thing that we encourage people to install

**Comment by tlambert03** [comment]
also: the docs dependencies are at `docs/requirements.txt`

**Comment by goanpeca** [comment]
We could have a test to make sure those two files remain in sync :-p

**Comment by tlambert03** [comment]
which two files?

**Comment by goanpeca** [comment]
Requirements and the other file where the [all] requirements are defined? The setup.cfg one?

**Comment by tlambert03** [comment]
ah, you mean in the future yes?  currently there's no syncing to be checked.  (There's no overlap between `docs/requirements.txt` and `setup.cfg` ... if we put docs requirements in setup.cfg, it'd be ideal to remove docs/requirements.txt instead?)

**Comment by goanpeca** [comment]
>docs/requirements.txt

I guess :)

**Comment by melissawm** [comment]
I think there is nothing left to do here since the docs requirements now live at napari/docs, but we may want to re-think the `napari[docs]` suggestion at some point. cc @psobolewskiPhD
