### ISSUE TITLE
Problem showing multi-D image with small last dimension

### ISSUE THREAD

**Issue by henrypinkard** [napari/napari#332]
## 🐛 Bug

Making and showing a multiD image with a last axis <= 4 leads to a bug in the viewer: the extra scrollbar doesn't appear to move through the 0th axis, and the contrast controls don't do anything. Making the size >= 5 leads to expected behavior

## To Reproduce

#this works
with app_context():
    img = np.random.rand(128, 128, 5)
    viewer = napari.view(img.astype(float))

#this doesn't
with app_context():
    img = np.random.rand(128, 128, 4)
    viewer = napari.view(img.astype(float))

## Expected behavior

Same behavior between both of these two cases

## Environment

 - napari Version:  0.0.8+43.g382ca7b
 - OS (e.g., Linux): OSX 10.14.5
 - Python version: Python 3.6.8

**Comment by kne42** [comment]
Hi @henrypinkard, thanks for the report!

By default, image layers guess whether an image is multichannel or not based upon the length of its last dimension: 3 for rgb and 4 for rgba, else grayscale. To achieve expected behaviour, please specify `multichannel=False`.

Modification of the brightness and contrast controls are not supported via the GUI at the moment.

**Comment by jni** [comment]
I actually ran into this problem as well and decided to not report it, but maybe that was a mistake. Perhaps we should remove the magic, and default to `multichannel=False`. The "we don't do magic" policy of scikit-image was the result of many similar bug reports.

**Comment by sofroniewn** [comment]
This has now been much better documented on our Image layer tutorial - see here http://napari.org/tutorials/image.html
