### ISSUE TITLE
Discussion: organization of documentation

### ISSUE THREAD

**Issue by melissawm** [napari/napari#3390]
## 📚 Documentation

Hello folks,

After some initial discussion with the documentation working group, and checking the current state of the documentation for napari (including the content in this repo, and on [napari.github.io](https://github.com/napari/napari.github.io)), I am proposing to re-think the organization and presentation of the docs as follows. (A few suggestions for new docs appear in italics)

This reorganization tries to follow the ideas from the [Diátaxis Framework](https://diataxis.fr/), splitting document types into Tutorials (learning-oriented), How-tos (task-oriented), Reference (API documentation) and Explanations (understanding-oriented, usually aimed at experienced developers).

Another consideration for splitting the docs this way is to give visitors to the web page a clearer path of where they need to go to complete a certain task, without being overwhelmed by complicated documentation before being familiar with the basics.

Any feedback is highly appreciated, and this is only the beginning of the discussion, so feel free to add any suggestions or comments. Also, please let me know if I missed any relevant issues. 

### Proposed organization of current documentation

- Getting started/first steps
   - Installation
   - (**NEW**) *Intro for non-Python users* (title to be decided)
   - Getting started
   - Finding and installing a napari plugin
   - Napari viewer tutorial

- Learn (tutorials)
   - Annotating segmentation with text and bounding boxes
   - Annotating videos with napari
   - Using Dask and napari to process & view large datasets
   - Single cell tracking with napari
   - Tracks layer tutorial (napari/napari.github.io#88)

- Tasks (How-tos)
   - Using layers
      - _Layers at a glance: key differences and what each is used for_
      - Image, labels, points, shapes, surface, vectors
   - Napari ImageJ How-to guide
   - Performance monitoring
   - _Napari in Docker_
   - Hooking up your own events
   - _How to run [scripts in example folder from main repo](https://github.com/napari/napari/tree/master/examples)_
   - _How to run napari on remote/browser based desktops_ (#3387)

- Explanations
   - _Layers_
   - Layer transform parameters (#2941)
   - Properties (#3025)
   - An Introduction to the Event Loop in napari
   - Multithreading in napari
   - Rendering
   - Asynchronous Rendering
   - Napari Performance
   - _Glossary_ (#3231)

- (**NEW**) Plugins
   - _Customizing napari's interface_ (napari/napari.github.io#68)
   - Creating a napari plugin
   - napari hook specification reference
   - napari plugin architecture

- Videos about napari (napari/napari.github.io#135)

- Contributing guide
   - (Current content)
   - Translations

- Roadmap 

- Release notes

### Relevant issues
- napari/napari#3231 
- napari/docs#29 
- napari/napari#1049
- napari/napari#764
- napari/napari#3085
- napari/napari.github.io#43

**Comment by codemonkey800** [comment]
Awesome work on this @melissawm! My only question is will the organization here also correspond to how the file structure / [table of contents](https://github.com/napari/napari.github.io/blob/main/_toc.yml) will be organized?

**Comment by melissawm** [comment]
I think the organization should map as closely as possible to the file structure, because it makes it easier for contributors to understand where things are. But I do understand that we have different sources for the material (for example, tutorials). As for the table of contents, yes, ideally it would match this organization.

**Comment by codemonkey800** [comment]
Sounds good, thank you! That makes me wonder how this will play with the design, specifically these sections:

> - Tasks (How-tos)
>   - Using layers
>     - Layers at a glance: key differences and what each is used for
>     - Image, labels, points, shapes, surface, vectors
>   - Napari ImageJ How-to guide
>   - Performance monitoring
>   - ...

Reviewing the designs for the napari theme, levels 1, 2, and 3 TOC sections look like this:
<img width="500" src="https://user-images.githubusercontent.com/2176050/133710640-a2aa30d8-fc4a-4403-9ae7-2ebacb253894.png">

@liaprins-czi Given the current designs, how should we handle the use case of differentiating between TOC links that:

1. Belong to a specific section .
2. Is _not_ within a subsection.
3. A subsection precedes it.

For example, what if `Learning the napari viewer` and `Customizing the napari interface` were not part of the subsection `Getting Started`. There's no way to discern that they're not related:

<img width="500" src="https://user-images.githubusercontent.com/2176050/133711224-f02f3858-8259-4494-a2d0-0e22e28a6e33.png">

**Comment by GenevieveBuckley** [comment]
I'd say customizing the napari viewer is not a "getting started" topic, that's a little more advanced. I'd put it together with content about developing your own napari plugins, since that's most often when people want to do things with dock widgets.

**Comment by jni** [comment]
Thanks @melissawm! 👋 It's so nice to have you on the team! 😊 

I'll point out a couple of challenging places where the diataxis framework didn't quite fit with our existing map, or where we didn't quite know where on the framework to put particular pages.

## plugins

<img width="233" alt="Screen Shot 2021-09-17 at 5 09 04 pm" src="https://user-images.githubusercontent.com/492549/133739882-dd83c86d-05f3-40e9-bda6-31749aefc228.png">

Currently, all of our documentation about plugins is in one place: how to find and install one, how to make one, the reference, and an explanation of the architecture. I guess that each of these actually belongs in a different quadrant! 😂 But, at the same time, it's kinda cool to know that if I want to know *anything* about plugins, I can go to:

https://napari.org/plugins/stable/index.html

and get started there. How do you reconcile the quadrant with broad "topics" like this one? Is there a place for page "tags" or "keywords" and some kind of master page for each keyword that automatically compiles links to tagged documents?

## Community

<img width="234" alt="Screen Shot 2021-09-17 at 5 11 51 pm" src="https://user-images.githubusercontent.com/492549/133740247-0bcf37c6-23ad-4221-b2d7-3ad043510882.png">

This doesn't really fall within the four quadrants, does it? Is it just a separate section in the repo? When we were discussing the current layout we really wanted this stuff to be front and centre. I think one of napari's strengths is its broad community and I'd like the docs to reflect and foster that.

What about the roadmaps? I guess they fall into "community" also?

Other than that, pretty happy with how you are thinking of things, godspeed! 😃 🚀

**Comment by melissawm** [comment]
@jni I agree - I didn't even touch the plugin section because I think it is very natural for that to stay grouped together. Same goes for the Community section. I like to think of the Diátaxis framework as a guide, but not a rule - it is totally fine to do something different. The ultimate rule is to help readers find what they are looking for easily :)

Thanks for the suggestions, I'll update the summary with those comments. Cheers!

**Comment by melissawm** [comment]
Other thoughts:

The Roadmap I think can either go into community, or stay as a top level item (I tend to like the second option best, same for the release notes). 

One thing we talked about in the docs working group (@chili-chiu ) is having videos for highlights of each release, so this could go under the release notes, as the top of each release notes page.
      
@codemonkey800 if the nesting is too complicated, we could not expose the inner level of the toc in the sidebar, just inside the Using Layers page; would that help?

**Comment by goanpeca** [comment]
Thanks @melissawm, this looks pretty cool :) 

I have mentioned this on other threads or issues but cannot recall now where so here it goes :) 

I think it is important to have a distinction in the documentation in terms of:

1. UI Users: Users that do not know about python and maybe will never care
2. Power Users: Users that do know about python and want to use it to take their work to the next level
3. Plugin Developers: Powers users that want to develop a plugin for their specific needs.

The current docs first example shows:

https://napari.org/#simple-example

<img width="778" alt="Screen Shot 2021-09-17 at 10 09 54 AM" src="https://user-images.githubusercontent.com/3627835/133806152-1faa0503-2cdd-4bb6-bcf7-18925effc5c3.png">

So I feel we are completely neglecting users `1.` and that could potentially be a huge user case! It can also force us to focus in providing the minimum things needed to be able to compete with other platforms/programs, as currently some things "can only be done in code"

**Comment by psobolewskiPhD** [comment]
> So I feel we are completely neglecting users `1.`

I feel seen! When i first saw napari mentioned on twitter while back and went to check it out and saw that as the **simple** example, I said: ah, python, which I don't know. Never mind. And moved on.
Of course, this was a very stupid thing to do because napari is awesome, python isn't so bad, and there is a GUI app you can interact with by drag-n-drop or normal menus.

How to get that across? No idea!

**Comment by liaprins-czi** [comment]
> For example, what if Learning the napari viewer and Customizing the napari interface were not part of the subsection Getting Started.

@codemonkey800 Ideally if a section has any of its pages within a group, all of the pages would have a group, that is the most consistent way to organize the content and most understandable, in my knowledge of UX at least! But I am curious what @melissawm thinks? Is it feasible for all documentation pages to have a group _if they belong to a section wherein other docuemtnation pages have a group_? For some sections that are smaller, there may be no groups.
If this does not always make sense, and there are cases where some pages belong to a group and some don't, I can work on a way to design the sidebar menu and the ToC page to distinguish this!

Also 
> if the nesting is too complicated, we could not expose the inner level of the toc in the sidebar, just inside the Using Layers page; would that help?

I had this same thought when I saw the proposed organization from @melissawm ! Or more ideally I think we'd still show the full hierarchy on the [parent ToC page](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=1616%3A2), but not in the sidebar menu. Does that make sense?

**Comment by tlambert03** [comment]
and look at your python chops now @psobolewskiPhD! 😂   you've been doing amazing stuff in just a couple months

I do agree that users `1` need a little more love. but I don't think it's a foregone conclusion that that user base is the "real"  or "biggest" eventual target of all of this (i.e. that teaching people how to access it all programmatically is just a stop gap until we eventually make it all accessible via the GUI).

I know that at least part of @jni's core motivation for starting napari in the first place was to create a "gateway drug" for python.  That part of napari is also extremely important to me.  I _do_ want people who don't know anything about code to eventually get something out of napari, but I would also be more than happy if, for the next few years, napari played an important role in helping users who know perhaps just a little bit of code to visualize their data analysis, or perhaps to create little workflows for their colleagues who don't know python.  I think there's a huge population of scientists that lie somewhere between power-users and UI-only users (user 1.5 ?).

While we generally refactor our docs to improve clarity (desperately needed in general), and gradually help out UI-only users, I hope we can also keep in mind the original mission of napari, that at least a couple of the core devs are very much still dedicated to.

**Comment by psobolewskiPhD** [comment]
It's all thanks to y'all for all the help and patience and your users on twitter that make napari look so awesome!
❤️‍🔥 
I really wish I woulda dove in earlier, like in December when I started doing more ImageJ stuff, but I just wasn't comfortable with the python idea. Then working with ImageJ macros and having some git issues, hitting some walls, and *bam* I was ready. The mental model clicked—I've used R for a long time, so python actually isn't so different.
I totally agree with @tlambert03, I think there's a lot of people in a similar state, where they're fully capable of using some python, but don't know it.
Ironically, I've lately been using napari a lot with just drag-n-drop to just quickly visualize something. No code. It's also quicker to type `napari` and go—<2s launch—than launch Fiji (4s with my universal binary launcher).

**Comment by melissawm** [comment]
I think there are two important visions here:
- We want to acknowledge some of the newcomers to napari that have zero Python experience;
- We want to give them a path forward and potentially use napari as an excuse to teach them Python.

I do believe this can be achieved with a smoother introduction - maybe starting from completing a GUI task to give them the confidence and familiarity with napari, and then showing how to do the same operations using python. Would this be feasible as a "first contact with napari" document?

**Comment by tlambert03** [comment]
yep! it would be great to have a "start here if you have zero python experience" portal visible somewhere on the first page.

**Comment by psobolewskiPhD** [comment]
> yep! it would be great to have a "start here if you have zero python experience" portal visible somewhere on the first page.

This!
The homepage does mention the GUI app install, but it's sort of in passing while diving into `pip` (BTW, I think conda/mamba works now too). I think there at the start one could try to fork the path for the incoming user, maybe with a graphic/iconic link to a GUI path, which would also show—vid? animated GIF?—some basic GUI only operations.

**Comment by melissawm** [comment]
> @codemonkey800 Ideally if a section has any of its pages within a group, all of the pages would have a group, that is the most consistent way to organize the content and most understandable, in my knowledge of UX at least! But I am curious what @melissawm thinks?

If I understand correctly, all pages would have a group (which is the top-level header). All H2 titles will be under exactly one H1 title, for example. So I don't see the issue, but maybe I am missing something.

> I had this same thought when I saw the proposed organization from @melissawm ! Or more ideally I think we'd still show the full hierarchy on the [parent ToC page](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=1616%3A2), but not in the sidebar menu. Does that make sense?

It does, and I also think this would be the best solution!

**Comment by codemonkey800** [comment]
> > @codemonkey800 Ideally if a section has any of its pages within a group, all of the pages would have a group, that is the most consistent way to organize the content and most understandable, in my knowledge of UX at least! But I am curious what @melissawm thinks?
> 
> If I understand correctly, all pages would have a group (which is the top-level header). All H2 titles will be under exactly one H1 title, for example. So I don't see the issue, but maybe I am missing something.
> 
> > I had this same thought when I saw the proposed organization from @melissawm ! Or more ideally I think we'd still show the full hierarchy on the [parent ToC page](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=1616%3A2), but not in the sidebar menu. Does that make sense?
> 
> It does, and I also think this would be the best solution!

@melissawm What about H3 titles under H2 titles? For example, you have the following listed here:

> - Tasks (How-tos)
>  - Using layers
>    - Layers at a glance: key differences and what each is used for
>    - Image, labels, points, shapes, surface, vectors

I'm assuming `Layers at a glance` and `Image, labels, ...` will be H3 titles under the H2 title `Using Layer`?

**Comment by melissawm** [comment]
Ah yes, but that's not a hard requirement. If that complicates things for the toc we can re-think how that is displayed.

**Comment by codemonkey800** [comment]
It does complicate things a little, because the UI assumes that an H1 title will either be:

1. All H2 titles without H3 titles.
2. All H2 titles with H3 titles

But the use case of some H2 titles having H3 titles mixed with some H2 titles not having H3 titles make it tricky since we don't use indentation for separation of levels.

If it's possible to organize it using one of the two approaches I mentioned above, that would be great! otherwise if it makes more sense to leave it where it is now, @liaprins-czi it might be something we'll need to rethink for the UI. maybe we can push all groups within a section to the bottom and have all ungrouped items above.

**Comment by liaprins-czi** [comment]
Maybe I was confused in my initial response; when I said "I had this same thought when I saw the proposed organization from @melissawm ! Or more ideally I think we'd still show the full hierarchy on the parent ToC page, but not in the sidebar menu. Does that make sense?" I was actually thinking of the "Layers at a glance and Image, labels, ... " example. So the way I was envisioning it (and I can mock up if needed, let me know) is:
- Getting started/first steps
- Learn (tutorials)
- Tasks (How-tos)
- Explanations
- (**NEW**) Plugins
- Videos about napari (napari/napari.github.io#135)
- Contributing guide
- Roadmap 
- Release notes

are new sections. So they get listed in the sidebar by default (we should also still have the GH source code link and link to the hub I think in the list (but they are external links), @melissawm what do you think?). If you click on any of them _except_ for **Videos about napari**, **Roadmap**, or **Release notes**, you go to its [ToC page](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=1616%3A2). 

If you click **Videos about napari**, **Roadmap**, or **Release notes** you go to that documentation page directly.

On the [ToC page](https://www.figma.com/file/NmdYwtpKfMzLnNLYYWrbTw/napari.org-final-designs?node-id=1616%3A2) for the other sections, their subpages are listed. None of them have groups accoridng to how @melissawm showed teh new propsed organization (although this could easily be changed if needed, but in my mind it'd be best if all sub-pages per section, that are listed on the section's ToC page, belong to a group for consistency, but if this is not possible I can design a way to distinguish grouped vs non-grouped if needed).

for the case of "Using layers" and its children "Layers at a glance: key differences and what each is used for" and "Image, labels, points, shapes, surface, vectors", the only difference is that its children will be indented bullets on the ToC page below "Usng layers". But these two will not show on the expanded version of the side nav, only "Using layers" and its peers under "Tasks".

What do you think @codemonkey800 and @melissawm ? Does this make sense how I described it? If so, do you agree? Or is it too confusing and I should mock it up?

**Comment by GenevieveBuckley** [comment]
> One thing we talked about in the docs working group (@chili-chiu ) is having videos for highlights of each release, so this could go under the release notes, as the top of each release notes page.

Re: the mechanics of this idea - are we going to make a napari youtube channel to host this type of content, and then embed those short videos in the HTML? (I think this makes the most sense)

Also, a youtube channel would give us the option of making playlists of napari content from elsewhere (eg: can link to all the napari tutorials previously given, making them easier to find, [like these](https://github.com/napari/napari.github.io/issues/135))

**Comment by goanpeca** [comment]
>I know that at least part of @jni's core motivation for starting napari in the first place was to create a "gateway drug" for python. 

I completely agree with this vision!

>While we generally refactor our docs to improve clarity (desperately needed in general), and gradually help out UI-only users, I hope we can also keep in mind the original mission of napari, that at least a couple of the core devs are very much still dedicated to.

Absolutely, I don't think of this is a cater to `1` users at the cost of the `2,3` users. As mentioned during the meeting, "we" are probably not a representative sample of users out there since we are power users (closer to `3`, than to `2` I would say), so we are inevitably biased to ignore `1` users. Unless we "force" ourselves to make sure UI users get the most out of it, we will not improve the situation.

Also I believe that catering to the needs of UI users will have the biggest impact overall in the "gateway drug" objective and hence on improving 2 and 3 adoption in the long run.

---

Just to put a very "weird" example, is like Excel documentation (assuming it was good...) started with macros.

We really need to showcase the power of napari, but to do that we really need to start with UI users first, and then "hey now that you are here... check THIS out!"

I am pretty insistent with this topic, as I really think napari's potential for expansion in usage is on `1` 


---

**Update:** Thanks @psobolewskiPhD for sharing your experience.

I would say you are one happy case of how things can go right. 

BUT it does make me wonder:

- It would have been much better if you were not put down from the beginning. You should have had a friendlier experience. That is on us!
- How many not so happy cases are out there?

I am definitely flexing the survivorship bias analogy here:

![image](https://user-images.githubusercontent.com/3627835/134037404-38eb9450-bc89-407d-8e64-f056ebec7af0.png)

>and look at your python chops now @psobolewskiPhD! 😂 you've been doing amazing stuff in just a couple months

Maybe @psobolewskiPhD survived and we are happy to keep reinforcing those spots with white dots, but we should be reinforcing the rest, for those users that never looked back at napari....

And I can not echo @tlambert03's comment enough. You have been doing really awesome work in the past months @psobolewskiPhD. Thanks a lot for helping make this project better!

**Comment by goanpeca** [comment]
On another note, it seems this thread is now mixing a lot of different topics around the original one, maybe we could do the convo around H2/H3 and display technicalities in another issue dedicated to that :)

**Comment by codemonkey800** [comment]
> On another note, it seems this thread is now mixing a lot of different topics around the original one, maybe we could do the convo around H2/H3 and display technicalities in another issue dedicated to that :)

Agreed, it also would be cool if we could enable the Discussions tab on the napari repo so we could have the separate discussions in different threads 🤔

**Comment by melissawm** [comment]
> What do you think @codemonkey800 and @melissawm ? Does this make sense how I described it? If so, do you agree? Or is it too confusing and I should mock it up?

This makes perfect sense and I agree. 

My plan is the following:
- Make a draft PR with the new reorganization without touching any of the docs for now
- After that first PR is approved and merged, start refactoring docs themselves 

With the draft and rendering of the first PR, we will see concretely how that looks with the TOC and theme and can make better decisions. Let me know if this is reasonable or if you all prefer some other plan.

**Comment by GenevieveBuckley** [comment]
Good plan @melissawm

**Comment by jni** [comment]
@goanpeca as you have no doubt gathered by now I am somewhat apprehensive about going all in on the "UI docs first" approach. I think the Excel analogy is somewhat appropriate *if* Excel was instead called pandas (the bundled app), and going to pandas.pydata.org gave you the Excel docs and you had to dig around if you wanted to find the pandas API docs. If that was the case I doubt I would ever pick up pandas to do a thing and would just muddle around with NumPy.

In short I think napari is rather unique in targeting *both* app users *and* a large "scientific programmer" user base. This tension between the bundle and the API will always be there, and we need to watch out for both audiences, and we should not bury all of the *simple Python API* docs (ie this is not advanced stuff if you are already in the Python ecosystem — which a [huge](https://stackoverflow.blog/2017/09/14/python-growing-quickly/) and [growing](https://github.com/jni/programming-languages-in-astronomy/blob/master/programming-languages-in-ADS.ipynb) number of scientists are) under a "friendly" "Download us on the App Store!" bunch of screenshots/stuff. Instead, we should *open* with an "audience selector" that points people to different parts of the documentation. I confirmed with @neuromusic that CZI owns both napari.app and napari.dev (thanks, folks!!! :blush:), so we can put different parts of the docs in different places, with cross links, and a guide up top in all cases. "Are you looking for the documentation for the standalone app? Click here to go to napari.app!". Or, "I am a: - Python user looking to visualise my data; - scientist with no programming experience looking to visualise my data".

Of course I agree with you that the non-Python audience will eventually grow much bigger than the Pythonistas. But @sofroniewn also made the point a couple of meetings ago that we've *consciously* not put the bundled app front and centre because napari isn't stable or feature-ready for that type of user yet — other than those showing extreme dedication like @psobolewskiPhD :joy:. I think the same holds for docs, especially since this issue is about the *current* efforts of docs reorg. Ultimately, we can potentially have an entirely separate site at napari.app that contains all kinds of UI goodness.

How does that sound?

**Comment by melissawm** [comment]
> Instead, we should open with an "audience selector" that points people to different parts of the documentation

I like this, but I'd even argue that you could go with actions instead of profiles

- Do you want to learn about how to use the napari app for data visualization?
- Do you want to learn about how to use Python to explore data with napari?

**Comment by jni** [comment]
Love it, way better @melissawm! :clap:

**Comment by sofroniewn** [comment]
Yes, I much prefer actions over profiles too - great suggestion @melissawm - we could do

- Do you want to learn about how to use the napari app for data visualization?
- Do you want to learn about how to use Python to interactively explore data within napari?
- Do you want to learn about how to build and share a napari plugin?

As three core actions. The could also be

- Do you want to learn about how to contribute to the napari codebase?

All to be determined, but I love this direction 🚀

**Comment by GenevieveBuckley** [comment]
This week we discussed how to make content related to previous napari workshops visible to new & existing users. This is very important, because there is a lot of great information conveyed in those workshops, and workshops also tend to have an overarching learning plan.

The best idea we came up with was:
* Let's make a list and link to workshop videos & materials, see https://github.com/napari/napari.github.io/pull/183
* Maybe later we can consider having an "official workshop" under the napari namespace

@melissawm if you have a better idea than "let's make a list and put it ...somewhere?", let us know!

**Comment by GenevieveBuckley** [comment]
I would like to add another pet peeve of mine to this reorganization discussion: it's confusing to me that "Developer Guides" comes before "Developer resources" in the left hand sidebar of napari.org. 

I can never figure out from the names why those two things are supposed to be different, and I am constantly clicking on the top one while looking for the developer contribution guide, but that's actually found under the second developer section instead.

I'm pretty sure you already have plans to make this less confusing, but I did want to highlight it here - it's a real usability problem.

**Comment by tlambert03** [comment]
agreed.  i still just generally "click everything" looking for what I want 😂

**Comment by sofroniewn** [comment]
yes, i agree i have a hard time remembering what is in "Developer Guides" and in "Developer resources", especially as I think our "Core Developer Guide" is in "Developer resources".

Hopefully this will get addressed by the docs working group, i'm really very very open to ideas for improvement here. Please let me know if there are more proposals to review.

**Comment by liaprins-czi** [comment]
@codemonkey800 brought an issue to my attention about the current UI design: it limits the depth of content within the left sidebar navigation to two levels, but the "API references" section (and also the new "Tasks (How-tos)" section (within the "Using layers" subsection / page) content requires three levels deep:

per @codemonkey800 "all of the index pages for the API references have information that is unique to that page, but the current theme prevents access to those pages.
for example, the index page for napari.view_layers has info about the method view_image() : https://napari.org/api/stable/napari.view_layers.html
however, this page is inaccessible with the current theme since the sub-page titles can't be clicked on"

![Screen Shot 2021-09-30 at 8 57 56 AM](https://user-images.githubusercontent.com/53277128/138757990-3f32ba0f-dc37-4688-bd25-d9e35dee7b69.png)

I started working on finding a solution for this; here are what I am identifying as the user needs / problems to solve / criteria that the design must fit:
• the docs design must accommodate another level of hierarchical depth to match the content
• the current “page level” must now be able to function as both a parent to other pages, and as a page itself
• this means that since it is not just a parent, but also a page, it is different in concept from the current “group heading” which is just a label and not selectable as a page itself
• user must be able to select all pages from the left sidebar menu when they are within a given section (not only the parent pages, the children pages too)

After initial brainstorming and sketching, I built out the two most promising directions using the API reference section:

1. **Tertiary level is always shown, but indented relative to secondary page level**
<img width="142" alt="Screen Shot 2021-10-25 at 12 23 04 PM" src="https://user-images.githubusercontent.com/53277128/138758243-fa64f669-b439-4893-b7c5-65da7685336c.png">

2. **Grouping header can double as link to page (styled with underline to indicate it's clickable, as normally it's not clickable as it is usally just a grouping heading, not a page name**
<img width="143" alt="Screen Shot 2021-10-25 at 12 23 12 PM" src="https://user-images.githubusercontent.com/53277128/138758448-0fc4f956-6ede-4f1e-a02a-853312db747a.png">

I think the first works best as it maintains the page-styling pattern: everything that is a page is shown in the same style in the left sidebar. The second could work but may not be as clear to users.

Curious what others think, especially @codemonkey800 and @melissawm !

**Comment by codemonkey800** [comment]
@liaprins-czi I remember expressing preference for the second for consistency, but after seeing the mockup for the first one, I now prefer having that one because I like how it conveys the nested structure of the links 😄 

Will the TOC page still be the same or will there also be a redesign?
![image](https://user-images.githubusercontent.com/2176050/138770215-f82fbdee-4c7a-4809-994e-3e0ceeb7e528.png)

**Comment by liaprins-czi** [comment]
Great, thanks for the feedback @codemonkey800 ! And yes, the ToC page should remain the same (also with nesting / indenting, which also makes me like the first design for consistency in that way)

**Comment by melissawm** [comment]
Posting this here as well for the record:

Next actions are to 
- Write a plan for how to merge this reorganization, as I will need to close napari/napari.github.io#176 and split it into two: one for the parts that need to change on napari/napari.github.io, another for the parts in napari/napari. 
- Write a plan for where contents should live in the future.

I will do that today, and share here. Once we agree, I can do the initial changes, *including documentation on where each document lives and how to make changes* so folks can contribute their own suggestions and refinements.

**Comment by melissawm** [comment]
> @liaprins-czi I remember expressing preference for the second for consistency, but after seeing the mockup for the first one, I now prefer having that one because I like how it conveys the nested structure of the links smile

I agree, I like that one too :) Although I think that is critical for the API reference docs, for the how-to section I don't think we necessarily need to expose the sub-documents in the left sidebar toc, though. They could live under the "Using layers" page, and be reachable from there.

**Comment by chili-chiu** [comment]
@melissawm do you see this issue as still ongoing, or should we close the issue?

**Comment by melissawm** [comment]
I'll close, and if there any pending issues we can open a new issue. Thanks!
