### ISSUE TITLE
Broken ndimensional points

### ISSUE THREAD

**Issue by brisvag** [napari/napari#3428]
## 🐛 Bug

due to #3381, n-dimensional points appear to be broken. Also, the dims slider seems to be broken with a singleton dimension.

## To Reproduce
With this code, you won't see the point. However, it will appear if you enable `n_dimensional`. Moreover, I would expect the dims slider to either not appear, or to show a range of (0, 0), not (-1, -1).

```python
import napari
import numpy as np


points = np.zeros(4)

v = napari.Viewer(ndisplay=3)
v.add_points(points)

napari.run()
```

## Expected behavior

The point should be visible in the zeroth slice.

## Environment

```yaml
napari: 0.4.12.dev27+g5c3c1ae7.d20210920
Platform: Linux-5.14.7-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2020.12.0
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 NVIDIA 470.74
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-properties-plotter: 0.2.0
- ndtiffs: 0.1.1
- scikit-image: 0.4.9
- svg: 0.1.5
```

**Comment by grlee77** [comment]
Ouch, I will take a look and see about adding a new test case to catch this! I think I only tested overlaying points on an image when working on #3428 and that was looking okay.

For, example adding an image layer as in the modified example below, does get the point to show up.

```Python
import napari
import numpy as np

one_pixel = np.ones((1, 1, 1, 1))
points = np.zeros(4)

v = napari.Viewer(ndisplay=3)
v.add_image(one_pixel)
v.add_points(points, size=0.1, face_color='red')

napari.run()
```

**Comment by grlee77** [comment]
Sorry it took me awhile to get back to this. The issue is the following change to adding  `+ 0.5 * ss[i]` offsets in viewer model calls to `set_range` in #3428:
https://github.com/napari/napari/blob/315e2bf256f2e70fe96202beadeb8fb1458aca2b/napari/components/viewer_model.py#L339-L346

That change is correct for Image and Label layers, but I think we need the following instead for points:
```Python
 self.dims.set_range( 
     i, 
     ( 
         world[0, i], 
         world[1, i] + ss[i], 
         ss[i], 
     ), 
 ) 
```
where the +1 is because we changed the upper range of the Dims slider to be "exclusive" rather than "inclusive" now. I need to consider the cleanest way to implement a fix since the Viewer model deals with a LayerList that mixes these types of layers.
