### ISSUE TITLE
Fix headings on "Hooking up your own events"

### ISSUE THREAD

**Issue by neuromusic** [napari/napari#3530]
*from October 2021 pre-launch bug bash*

**Created by**: @liaprins-czi

## Description 

On Developer Guides > "Hooking up your own events", the last header on the page ("Long-running, blocking functions") is H1 but should be H2.

## Info

**Bug source**: *unknown*

**Browser**: *unknown*

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/5270674c647dfe78cfec44ff801a728d/4dfa0e3a/ScreenShot2021-09-22at3_14_08PM.png

**Comment by GenevieveBuckley** [comment]
I don't think this is true, though? 

I think it just looks like it, because the very first heading on that page is H2 instead of H1...
Currently we have:
- H2: Hooking up your own events
- H3: Listening for keypress events
- H3: Listening for mouse events
- H3: Connection functions to native napari events
- H2: Long-running, blocking functions

I think the more sensible fix would be to upgrade the first four headings, and leave the last one alone.

**Comment by GenevieveBuckley** [comment]
I opened this earlier https://github.com/napari/napari.github.io/pull/265, but Melissa says this actually needs fixing in the napari/napari repository. This issue is currently available for anyone who wants to do that.

**Comment by Mishrasubha** [comment]
Can I take up this issue?

**Comment by GenevieveBuckley** [comment]
Sure!

**Comment by melissawm** [comment]
I am closing as this was fixed in #3563.
