### ISSUE TITLE
More informative alt text for images

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#3540]
I've noticed that the alt text for all of the images included with markdown in this repository appears to say the same thing: "image". This seems less than helpful.

I'd like if we replaced the alt text with something better, probably along the lines of "image: a more informative of the image content here"

**Comment by GenevieveBuckley** [comment]
I've added the "bug" label because this is an accessibility issue - a major part of our documentation isn't available if you're using a screen reader.

**Comment by GenevieveBuckley** [comment]
@tonyfast says Quansight have been running some "low code sprints", centered around things like adding alt-text to documentation. Apparently they've been quite successful, so maybe we'd like to look into doing something similar here too @sofroniewn 
 
See https://github.com/dask/community/issues/193 and https://labs.quansight.org/blog/2021/09/low-code-contributions-through-GitHub/

**Comment by sofroniewn** [comment]
> Apparently they've been quite successful, so maybe we'd like to look into doing something similar here too @sofroniewn

Yes, i love the idea! Maybe we discuss coordination/ timing/ logistics in zulip and then post here

**Comment by GenevieveBuckley** [comment]
[Link to the zulip chat](https://napari.zulipchat.com/)

**Comment by isabela-pf** [comment]
I'm not sure if my zulip skills are failing me (likely), but I'm not seeing a thread for this in zulip yet. If this is the case, I'm happy to start a thread (in #sprints maybe?).

This just came across my path via the [Dask community issue linked above](https://github.com/dask/community/issues/193) and I wanted to weigh in because I'd be happy to help make this happen if there's interest. I've run a few of these with other people at Quansight Labs so I'm familiar with the format and alt text more generally.

**Comment by GenevieveBuckley** [comment]
@isabela-pf I don't think there's any reason we need to wait for other people - if you're happy to take the lead and organise something that would be great.

**Comment by goanpeca** [comment]
Happy to help @isabela-pf if you need a helping hand :) !
