### ISSUE TITLE
Add ability to "slab" 2D slices from 3D data

### ISSUE THREAD

**Issue by graeme-winter** [napari/napari#3600]
## 🚀 Feature

At the moment a 2D view of a 3D data set is limited to slices of thickness 1: I would like to be able to look at the (sum/average/max/min) of a slab of data e.g. in place of 

```
image = data[n,:,:]
```

have

```
image = sum(data[j,:,:] for j in range(n,n+m))
```

The current viewer structure delegates much of the interaction to dask which does not give a window to allow this, e.g. using 

```
import bitshuffle.h5
import dask.array as da
import numpy as np
import napari
import h5py
import sys

f = h5py.File(sys.argv[1])
d = f["/entry/data/data"]
s = d.shape

i = d[0]

a = da.from_array(d, chunks=(1, s[1], s[2]))

viewer = napari.view_image(a, title="DIALS Image Viewer",
                        contrast_limits=[0, 10])

napari.run()
```

## Motivation

We in the DIALS team are looking to replace our image viewer with something a little more maintainable to fix numerous issues with performance etc. (e.g. https://github.com/dials/dials/issues/1776). A survey of the `napari` API suggested that this was the last missing feature. Discussion in community meeting yesterday indicated that this feature is indeed absent. 

## Pitch

Perfect world would have someone in `napari` work with us to get this done - am very happy that we contribute to the code base to get this done, but will need some guidance as there did not seem to be a simple way to do this. 

## Alternatives

This is likely to be a blocker for adopting `napari` for us, which would be a shame as it is otherwise perfect. 

## Additional context

We raised this in the community meeting yesterday and core developers there seemed pretty keen on this as a use case. Example from our existing viewer:

![Screenshot 2021-11-11 at 06 38 13](https://user-images.githubusercontent.com/1241716/141250077-b4323827-4a0c-4703-90e2-2b7c4db04e83.png)

![Screenshot 2021-11-11 at 06 38 29](https://user-images.githubusercontent.com/1241716/141250096-31d02d2c-b4c4-4a4a-8dd3-f5db7905a887.png)

Appreciate anyone helping us our here.

**Comment by kevinyamauchi** [comment]
Hey @graeme-winter ! Thanks for coming to the community meeting and for making the issue. As we discussed in the meeting, one option is to use plane rendering for things that fit in GPU memory (cc @alisterburt ). For doing the "slabbing" on the CPU, the "data source" refactor that is under discussion would probably be the way to go, but is not yet implemented. However, there may be some workarounds for now.

As I understand it, you have images that are (time, x, y) and you want to view your image time slice by time slice such that each slice is the average of +/- n adjacent time slices. Is that correct?

For now, i am curious if there is a way to do this with dask and/or dask-image. If my understanding is correct, it seems like what you are after is a 1D sliding window filter along your "time" axis. I believe @grlee77 mentioned in the meeting chat that there is a 1D filter in dask-image, but I can't remember what it is called. Maybe it was in [`dask_image.ndfilters`](http://image.dask.org/en/latest/dask_image.ndfilters.html)?

Since the filter can be evaluated lazily, I am wondering if you can do something like the following:
1. When you load your image as a dask array (datea and dask array likely should be chunked along time), apply the 1D sliding window averaging filter before passing it to napari .
2. load the filtered image as an image layer in napari
3. I _think_ if the image is chunked along time and the filter is set up correctly it should calculate the average lazily with the dim slider
3. Add a GUI for setting the window size and when the user changes the window size, the image layer data gets updated with an image with the new filter size applied.

For some resources on performing lazy computations with dask/napari, here is a [tutorial](https://napari.org/tutorials/applications/dask.html) and an [image.sc thread](https://forum.image.sc/t/failing-to-implement-lazy-dask-delayed-image-processing-pipeline-from-tutorial/54007/5) that may be of interest.

I am far from an expert on dask, so perhaps @GenevieveBuckley has some better ideas.

**Comment by kevinyamauchi** [comment]
Ah, maybe what you are looking for is the [uniform filter](https://dask-image.readthedocs.io/en/latest/dask_image.ndfilters.html#dask_image.ndfilters.uniform_filter) with shape `(10, 1, 1)` (~~or is it `(10, 0, 0)`?~~)for images that are ordered (time, y, x)

**Comment by kevinyamauchi** [comment]
I was curious, so I gave it a go and I think it is working for the `(10000, 100, 100)` image I tried (see the script below). You can toggle the visibility of the filtered and raw image layers to see the difference. As I mentioned, I am not a dask expert, so others may have better ways to implement it.

```python
import napari

import dask
import dask_image.ndfilters

slice_width = 100
n_t = 10000

# set the width of the averaging window
window_width = 10

# make a fake image
# note the chunk size is 1 along the 0th dimension
raw_im = dask.array.random.random(
    size=(n_t, slice_width, slice_width),
    chunks=(1, slice_width, slice_width)
)

# filter the image along the 0th dimension
# (evaluated lazily)
filtered_im = dask_image.ndfilters.uniform_filter(
    raw_im, size=[window_width, 1, 1]
)

# add the images to the viewer
# note that the contrast limits are set. this is to
# prevent napari from trying to auto calculate the clims,
# which could require reading a lot of chunks
# (not sure this is strictly necessary)
viewer = napari.view_image(raw_im, contrast_limits=(0, 1), visible=False)
viewer.add_image(filtered_im, contrast_limits=(0, 1))

napari.run()
```

Do you think this would work for you, @graeme-winter ?

edit: you might need to adjust the x/y chunking and enable async loading and octree if your images are bigger (I am less familar with those parts of the code base): https://napari.org/guides/stable/rendering.html

**Comment by alisterburt** [comment]
@kevinyamauchi I love it! We should definitely consider trying to add this to core napari. Possible routes to this have been discussed/half implemented before at #1744 #1820 (there's a whole rabbit hole to go down here if you choose, this is clearly something people have wanted for a while.

I like the idea of exposing this with a 'thickness' parameter associated with the point slicing that we do currently in 2D (it fits well with how things are described in the GPU arbitrary plane stuff in #3023) but could also be convinced by a range slider with movable endpoints to set a 'slice range' for each dimension.

I'm not sure whether it makes sense to charge forwards on this with respect to the slice/chunk discussions going on around async/data source - maybe @perlman could add his thoughts here, does it make sense for us to implement something here which may be clobbered by your work in the near future?

**Comment by graeme-winter** [comment]
@kevinyamauchi nailed it thank you

added:

```
a = dask_image.ndfilters.uniform_filter(a, size=[10, 1, 1])
```

now we have a stack of 10 images. So: time to start looking at this as a UI toolkit. 

I suspect that the average user would find a "thickness" parameter as suggested by @alisterburt pretty useful, but from here I think we can get what we need doing done. Totally appreciate the fast feedback! ++ kudos

**Comment by kevinyamauchi** [comment]
> I'm not sure whether it makes sense to charge forwards on this with respect to the slice/chunk discussions going on around async/data source - maybe @perlman could add his thoughts here, does it make sense for us to implement something here which may be clobbered by your work in the near future?

Given the planned changes to the data model, I would lean towards keeping this outside of core napari if there is a reasonable way to do so. Also, depending on the image size and filter type, I could imagine that there is some tuning (e.g., chunk size, tile size) to get reasonable performance, so it might be too "fiddly" to make a core feature. That being said, I think it would be awesome to see something like this as a core feature in the future!

Related to chunking, I just remembered that @GenevieveBuckley made a nice blog post on choosing chunk sizes that may be useful here: https://blog.dask.org/2021/11/02/choosing-dask-chunk-sizes

**Comment by alisterburt** [comment]
makes sense @kevinyamauchi ! Let's leave for now. I might turn your example into something for the docs over the weekend, it's super powerful and I'll definitely be using it too 🙂 

Glad that should get you going @graeme-winter - I'll close this now but don't hesitate to reach out if you run into more issues!

**Comment by kevinyamauchi** [comment]
> @kevinyamauchi nailed it thank you
> 
> added:
> 
> ```
> a = dask_image.ndfilters.uniform_filter(a, size=[10, 1, 1])
> ```
> 
> now we have a stack of 10 images. So: time to start looking at this as a UI toolkit.
> 
> I suspect that the average user would find a "thickness" parameter as suggested by @alisterburt pretty useful, but from here I think we can get what we need doing done. Totally appreciate the fast feedback! ++ kudos

Great! I am happy you're able to move forward @graeme-winter ! Happy to chat about adding GUI elements, etc.  In case you haven't seen it, we have a "zulip" (kind of like slack) that is a great place to get more "realtime" feedback/discussion:  https://napari.zulipchat.com

Also, in case the uniform filter is too slow for your data, you could try the "coarsen" function. I haven't tried it, but I think it should be faster. You could use this to bin the data long the "time" axis (e.g., 100 time slices binned 20x would become 5 time slices). You can choose the bin size and the function used to do the binning (e.g., mean, sum, etc.)
https://docs.dask.org/en/latest/generated/dask.array.coarsen.html

**Comment by jni** [comment]
@graeme-winter thanks for the issue!

> I would lean towards keeping this outside of core napari if there is a reasonable way to do so.

Actually I want to say that this is in fact something we've wanted to have in napari pretty much since its inception, though the only mention I can find for it is the top item in [this list on #420](https://github.com/napari/napari/issues/420)! As you can see the item remains unticked :sweat_smile:, but we'll get there! So @kevinyamauchi @alisterburt I think I'll reopen this issue since as far as I can tell this is not written down in any specific issue!

The UI here would look like the contrast limits slider: changing the "mode" on a slider from "slice" to "projection" would separate the slider to two components, and napari would do whatever projection the user selected (e.g. dropdown arrow next to axis name) in the selected range of slices.

I also wanted to add dask-image is a powerful library but so is plain dask! I actually got the sum working by itself with NumPy/dask slice tricks:

```python
import napari
from dask import array as da
from dask.array.lib.stride_tricks import sliding_window_view
from skimage import data

blobs = data.binary_blobs(length=64, n_dim=3)
blobs_dask = da.from_array(blobs, chunks=(1, 64, 64))
blobs_dask_windows = sliding_window_view(
    blobs_dask, window_shape=(5, 64, 64)
)[:, 0, 0, ...]  # original shape [60, 1, 1, 5, 64, 64], slice out singleton axes
blobs_sum = da.sum(blobs_dask_windows, axis=1)
viewer = napari.view_image(blobs_sum)

napari.run()
```

**Comment by alisterburt** [comment]
I had come across `stride_tricks.as_strided` but not sliding window view, you just blew my mind @jni 🤯

**Comment by jni** [comment]
Recently ported to NumPy from scikit-image. :smiley:

**Comment by jni** [comment]
@graeme-winter et al, check #3604 for an example using magicgui to change the window size dynamically from the UI. :heart: :snake: + Dask.
