### ISSUE TITLE
Setting .affine attribute of image layers resets contrast_limits

### ISSUE THREAD

**Issue by jojoelfe** [napari/napari#3688]
## 🐛 Bug

Changing the affine attribute of the image layer resets the displayed contrast_limit ( image looks like default, the .contrast_limits attribute of the layer is unchanged).

## To Reproduce

1. Change contrast limits of an image
2. Set .affine property `viewer.layers.selection.active.affine = napari.utils.transforms.Affine()`
3. Image will look like before contrast limit change

## Expected behavior

Changing affine matrix should not reset contrast_limits

**Comment by jni** [comment]
Hmm, it doesn't reset it for me (using `examples/add_grayscale_image.py`), but it definitely messes with it! Thanks for the report @jojoelfe.

**Comment by jojoelfe** [comment]
I have tested it with `examples/add_image.py` and there the effect is much stronger. Not sure if it's because of RGB or 8bit vs 16bit.

**Comment by andy-sweet** [comment]
I could reproduce this on v0.4.12 at least using the RGB image example (`examples/add_image.py`), though `Image.contrast_limits` did not change only the appearance of the image.

I cannot reproduce it on v0.4.15 or on main, so I think this has been fixed now. I'm struggling to understand the bug or a simple test to check it, so I'm not curious enough right now to `git bisect` this to find what fixed it, but maybe it would be enough for @jojoelfe to confirm that this is fixed in v0.4.15 or the main branch? If so, please close the issue!

**Comment by jojoelfe** [comment]
Yes, seems to be fixed.
