### ISSUE TITLE
Choose coordinate convention for docs

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#37]
@jni made a comment about coordinate conventions in the docs at the end of #21 that didn't get addressed. I thought I'd make an issue, as I'm sure people have thoughts they'd like to discuss.

@jni:
> As a minor quibble, in examples documentation etc, can we use the coordinate convertions from scikit-image? ie tprc,ch instead of xyzct. (I did just realise that columns conflicts with channels. Oh well.)

**Comment by AhmetCanSolak** [comment]
I love to hear about scikit-image convertions first, if possible @jni

**Comment by royerloic** [comment]
I would rather not impose any strict channel order semantics, this should be provided by the data source via metadata. We have dimension with indices 0, 1, 2, etc... metadata can provide labwls for it, what we choose to display and in which permutation on the screen is completely configurable.
There should be no labels to these dimensions in the docs, just think how numpy does it.

**Comment by jni** [comment]
@AhmetCanSolak there is a link in my original comments:

http://scikit-image.org/docs/dev/user_guide/numpy_images.html#coordinate-conventions

@royerloic I of course want to be general in how we treat dimensions, but what I am trying to avoid is that we get locked into thinking about xyzct without realising, since that is the worst possible ordering, performance-wise, for NumPy (C-order) arrays.

**Comment by royerloic** [comment]
Great, you know how important performance is for me, (and you will soon realise for @AhmetCanSolak ). I like the idea to keep in mind the tczyx order as 'what should be done' while retaining full generalilty.
(Actually you answered a quwstion I had which was what is theb order that numpy 'likes' )

**Comment by sofroniewn** [comment]
With the merging of the dims refactor #171 we have now moved to a more pythonic ordering that supports `tczyx`
