### ISSUE TITLE
Upgraded Napari and now the GIL is released

### ISSUE THREAD

**Issue by JulesScholler** [napari/napari#3770]
## 🐛 Bug

In the previous version of Napari you could use the following:

```python
        viewer = napari.Viewer()
        viewer.add_layer(image_layer)
        viewer.add_labels(labels_manual)
        napari.run()
```

to manually label image area and then when closing the Napari window the rest of the code would execute, e.g. using labels_manual for segmentation purpose. Now it seems that the GIL is released upon calling napari.run() and the rest of the code will execute. This is making most of my applications bugging. 

## To Reproduce

```python
        viewer = napari.Viewer()
        viewer.add_layer(image_layer)
        viewer.add_labels(labels_manual)
        napari.run()
        print('This message will be displayed before closing Napari window')

```

## Expected behavior

'This message will be displayed before closing Napari window' should be displayed after closing the Napari window.

Is there a way of getting the old behavior?

Thanks a lot!

**Comment by JulesScholler** [comment]
I tried the following method proposed in the documentation:

```python
from napari.utils import get_settings

get_settings().application.ipy_interactive = False
```

and got the following error:

> ImportError: cannot import name 'get_settings' from 'napari.utils' (/home/hbm/miniconda3/envs/LibAPR/lib/python3.8/site-packages/napari/utils/__init__.py)

**Comment by JulesScholler** [comment]
I found the proper way to import `get_settings`:

```python
from napari.settings import get_settings
get_settings().application.ipy_interactive = False
```
But it is still executing and locking the interpreter.

**Comment by tlambert03** [comment]
> 'This message will be displayed before closing Napari window' should be displayed after closing the Napari window.

Hi @JulesScholler, this behavior will depend on the execution context:

1. **in a script**
    
    if you are running a script (e.g. `python my_script.py`) then the following _will_ print the message only after closing the napari window, as you desired:
    
    ```py
    # my_script.py
    import napari
    viewer = napari.Viewer()
    viewer.add_points(None)
    napari.run()
    print("after close")
    ```
2. If you are working in IPython, or in Jupyter, then `napari.run()` is essentially a no-op, since the Qt application is controlled by IPython/Jupyter there.  In that context please use `viewer.show(block=True)` if you'd like to stop the flow of execution until a particular viewer is closed:

    ```py
    # in IPython
    viewer = napari.Viewer()
    viewer.add_points(None)
    viewer.show(block=True)
    print("after close")
    ```

As a side note on nomenclature, this isn't related to python's global interpreter lock (GIL), but rather has to do with the Qt Event loop that (synchronously) blocks the flow of execution and waits for user input.  A bit more detail can be found in the docs here: https://napari.org/guides/stable/event_loop.html

**Comment by tlambert03** [comment]
> ImportError: cannot import name 'get_settings' from 'napari.utils'

thanks, will update the docs!

**Comment by JulesScholler** [comment]
Wow this community is really amazing! 

Thanks for your quick answer and sorry for the confusion with the GIL. I could not find this block method in the doc (should we add it somewhere?) and was naively looking into the viewer instantiation rather than the viewer methods.

Cheers,
Jules

**Comment by tlambert03** [comment]
> was naively looking into the viewer instantiation rather than the viewer methods

yep it's an understandable confusion!  

>  (should we add it somewhere?)

sure! anything that would help prevent the confusion in the future would be great. I guess  that page on the event loop might be one place? (it would also be a decent place to discuss why you'd need it in interactive ipython, but not in a script.)  But also, it looks like that particular parameter is not documented in the [docstring of `viewer.show`](https://github.com/napari/napari/blob/e6ce01d9d43b5204cea9c84a6b08db97a2d23148/napari/viewer.py#L111)  so that would be a great place to add it too.

**Comment by JulesScholler** [comment]
I agree that the event loop is probably the best place with an added docstring of the viewer.

In my case I develop my apps using PyCharm and I execute scripts using iPython to allow for an easier debugging. It might be an edge case but I am sure some folks would end up doing similar workflow with jupyter.

Thanks again.

**Comment by tlambert03** [comment]
definitely not an edge case!  first class use case:  I also use napari primarily through ipython, and I know @jni  does too.
