### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.pyrcc_main'

### ISSUE THREAD

**Issue by keredson** [napari/napari#3792]
## 🐛 Bug

`ModuleNotFoundError: No module named 'PyQt5.pyrcc_main'` thrown when calling `napari.Viewer()` on a fresh Ubuntu install.

## Fix
Run:  `sudo apt install pyqt5-dev-tools`

Which installs `/usr/lib/python3/dist-packages/PyQt5/pyrcc_main.py`

So:
```
$ python
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.pyrcc_main
>>> 
```

### TL;DR

The common prereq instructions of installing `python3-pyqt5`is insufficient on Ubuntu and the dep on `pyqt5-dev-tools` is non-obvious.

Not sure there's a specific ask here.  (Maybe a better error message?)  Mostly I'm logging this for future google searchers to find (since nothing really comes up ATM).

## To Reproduce

Call `napari.Viewer()`...

```
~/.local/lib/python3.9/site-packages/napari/viewer.py in __init__(self, title, ndisplay, order, axis_labels, show)
     52         from .window import Window
     53 
---> 54         self._window = Window(self, show=show)
     55 
     56     # Expose private window publically. This is needed to keep window off pydantic model

~/.local/lib/python3.9/site-packages/napari/_qt/qt_main_window.py in __init__(self, viewer, show)
    402     def __init__(self, viewer: 'Viewer', *, show: bool = True):
    403         # create QApplication if it doesn't already exist
--> 404         get_app()
    405 
    406         # Dictionary holding dock widgets

~/.local/lib/python3.9/site-packages/napari/_qt/qt_event_loop.py in get_app(app_name, app_version, icon, org_name, org_domain, app_id, ipy_interactive)
    183         # this will register all of our resources (icons) with Qt, so that they
    184         # can be used in qss files and elsewhere.
--> 185         _register_napari_resources()
    186 
    187     _app_ref = app  # prevent garbage collection

~/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py in _register_napari_resources(persist, force_rebuild)
    386         _clear_resources = getattr(mod, "qCleanupResources")
    387     else:
--> 388         resources = _compile_napari_resources(save_path=persist and save_path)
    389         exec(resources, globals())
    390         _clear_resources = globals()["qCleanupResources"]

~/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py in _compile_napari_resources(save_path)
    323 
    324     with _temporary_qrc_file(svgs, prefix='themes') as qrc:
--> 325         output = compile_qrc(qrc)
    326         if save_path:
    327             try:

~/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py in compile_qrc(qrc)
    227     """Compile a qrc file into a resources.py bytes"""
    228     if qtpy.API_NAME == 'PyQt5':
--> 229         return _compile_qrc_pyqt5(qrc).replace(b'PyQt5', b'qtpy')
    230     elif qtpy.API_NAME == 'PySide2':
    231         return _compile_qrc_pyside2(qrc).replace(b'PySide2', b'qtpy')

~/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py in _compile_qrc_pyqt5(qrc)
    176     PyQt5.pyrcc.  They provide access via a helper function in `pyrcc_main`.
    177     """
--> 178     from PyQt5.pyrcc_main import processResourceFile
    179 
    180     # could not capture stdout no matter what I tried, so using a temp file.

ModuleNotFoundError: No module named 'PyQt5.pyrcc_main'
```

## Expected behavior

A UI to appear.

## Environment

- Ubuntu 21.10
- `apt install python3-pyqt5`
- `pip install napari`
- `napari.__version__ == '0.4.12'`

**Comment by tlambert03** [comment]
thanks @keredson ... 

> The common prereq instructions of installing python3-pyqt5is insufficient on Ubuntu and the dep on pyqt5-dev-tools is non-obvious.

curious, did you already try the instructions [in our readme](https://github.com/napari/napari#from-pip-with-batteries-included) and have them fail? (or are they unuseable for some reason)?

```bash
# conda part optional, but the most commonly tested approach
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
pip install "napari[all]"
```

specifically, did you try `pip install "napari[all]"` before resorting to `python3-pyqt5` or `pyqt5-dev-tools`
`ModuleNotFoundError: No module named 'PyQt5.pyrcc_main'` is often cause by PATH issues, such that perhaps your apt install isn't available to the python env at runtime?  

also, I haven't tested ubuntu 21 yet, fwiw, so it's possible this is unique to that?

**Comment by keredson** [comment]
it wasn't a path issue - confirmed the deb didn't contain the file at all.  (it's definitely a weird split the pkg maintainers did.)

reproducing is a bit tricky since `_register_napari_resources` caches `/home/derek/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_qt_resources_PyQt5_5_15_2_5bab406e8e80e6013f59ab193ce5fd9a.py` if it succeeds.  (at which point `PyQt5.pyrcc_main` becomes unnecessary.)  but can just manually delete to reproduce the original error.

`pip install "napari[all]"` instead of `pip install napari` did not materially change things.  (`pooch>=1.3.0` was the only difference at the time i ran it.)   was still able to reproduce after installing w/ `[all]`.

created a PR for the readme.

**Comment by keredson** [comment]
> also, I haven't tested ubuntu 21 yet, fwiw, so it's possible this is unique to that?

probably not.  looks like [pyqt5-dev-tools](https://packages.ubuntu.com/bionic/pyqt5-dev-tools) has been around since 18.04, and if you download the bionic version of the deb it references `pyrcc_main.py`:

```
$ grep -R pyrcc_main pyqt5_5.10.1+dfsg-1ubuntu2.debian
pyqt5_5.10.1+dfsg-1ubuntu2.debian/debian/pyqt5-dev-tools.install:usr/lib/python3*/dist-packages/PyQt5/pyrcc_main.py
```

**Comment by keredson** [comment]
did a code comment PR for you all as well if you prefer that instead, or can take both, dealer's choice.  :)

**Comment by tlambert03** [comment]
to be honest, I'm a bit hesitant to merge that PR, since we really prefer advising people to use virtual environments, and by using `sudo apt install pyqt5-dev-tools`, you're mixing global libraries with conda.  It's still unclear to me.... _are_ you using conda or some virtual environment?  Or are you trying to install napari as a global python library?  (It sort of looks like the latter, based on `/home/derek/.local/lib/python3.9/site-packages/napari/`, which I'd generally recommend against, and that's why I'd prefer not encouraging others to use it).

So, just to be explicit.  here's what we generally encourage someone to do from a fresh ubuntu installation (the first step installing xcb libraries is necessary if you get the error "Failed to load platform plugin xcb"... [see this SO post](https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without) for details)

```sh 
# this is the one system-wide linux-specific thing you'll need to do once after installation
sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 \
    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
    libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
```
then, [install miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html#regular-installation), and proceed by creating a virtual environment (that is, _don't_ use your global python/pip to install).

```
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
pip install "napari[all]"

# run napari 
napari
```

Sorry to have you try more things, but before we encourage people to use `apt install pyqt5-dev-tools`, I'd really like for you to try that and let us know if it doesn't work for you.  That's what all of us have been using for a couple years now and it's a pretty well-tested (and system isolated!) solution.

**Comment by keredson** [comment]
> are you using conda or some virtual environment?

ah, no, i'm not using conda (or any other venv) ATM.  (nor looking to install just for this lib, esp. since they install via the "download and run this untrusted 50mb shell script" technique.)

> Or are you trying to install napari as a global python library?

no, not as global.  installed as user-local.

**Comment by tlambert03** [comment]
> nor looking to install just for this lib

fair enough!  i do think that virtual environments are advisable though, and I know from fielding many of the questions that we get here that a non-negligible portion of our users might get themselves into trouble if they start installing things like this (even the pip "user-local" install is difficult to isolate from other dependencies... it may not literally go into `/usr/lib`, but it's still quite possible to run into some binary incompatibilities if they later install other things into that same environment, and then extracting themselves from that situation takes some know-how)

I'll let other devs also weigh in though as well,  cc @jni

**Comment by keredson** [comment]
FWIW, totally fine closing this if i'm using it outside a recommended or supported manner. =D

**Comment by keredson** [comment]
found the [article](https://towardsdatascience.com/creating-and-training-a-u-net-model-with-pytorch-for-2d-3d-semantic-segmentation-dataset-fb1f7f80fe55) that orignially lead me to you all, which does recommend conda in the [linked repo's readme](https://github.com/johschmidt42/PyTorch-2D-3D-UNet-Tutorial/blob/master/README.md).

**Comment by jni** [comment]
I agree generally with @tlambert03's comments. I don't think we want to encourage this installation path as supported, as it's very uncommon in Python circles. In short, *one day*, I hope you can do `sudo apt install python-napari` and stuff will Just Work, but until then, I think mixing pip and apt is a recipe for broken Python installs.

> (nor looking to install just for this lib, esp. since they install via the "download and run this untrusted 50mb shell script" technique.)

tbh I find this to be a red herring argument. At the very least it overestimates the security practices of napari, scikit-image, and any number of related libraries that you install via pip. Literally anything you install with pip can execute arbitrary code on install or import, *including its dependencies*, *including proprietary binary blobs*. Pillow, an image reader library that we depend on, has seen plenty of security issues, and of course, anything that did logging in Java was massively compromised — including stuff installed with apt.

conda btw installs in user space (no sudo required), and fully open implementations such as [mamba](https://mamba.readthedocs.io/en/latest/installation.html) exist to do the same thing. btw for the open alternatives of miniforge and mamba-forge, you can see the recipe for making the installers [here](https://github.com/conda-forge/miniforge/blob/master/scripts/build.sh), though it's not very illuminating unless you go fish around to see what constructor does. I haven't, I just trust the members of that community to do a decent job (especially since the whole stack is open source), just as you trust the members of the Ubuntu community to do theirs.

Anyway, that's all a big aside, for now I will suggest that we close this issue and recommend use of conda or virtualenv to install both napari and its dependencies. If anyone objects to this I'm happy to reopen and consider ways forward. Thank you @keredson!

**Comment by boegel** [comment]
For anyone else hitting this when using a `PyQt5` installation from source, make sure that was not configured with `--no-tools`, see also https://github.com/easybuilders/easybuild-easyconfigs/pull/16469/files...
