### ISSUE TITLE
New `canvas_axis=True` parameter, when making a screenshot.

### ISSUE THREAD

**Issue by kolibril13** [napari/napari#3827]
## 🚀 Feature

`screenshot` should have a parameter `canvas_axis=True`
Right now, when making a screenshot with `canvas_only=True`, it automatically adds an axis to the plot.
Sometimes, that could not be wanted, therefore this new parameter.

## Motivation

Right now, the screenshot function has the following signature:
`def screenshot(self, path=None, *, canvas_only=True, flash: bool = True):`
it could get changed to:
`def screenshot(self, path=None, *, canvas_only=True, canvas_axis: bool=True, flash: bool = True):`

## Additional context

![image](https://user-images.githubusercontent.com/44469195/146351241-f1f866d8-0bea-4a49-9486-75fb168e7414.png)
Interstingly, when having:
```py
img = viewer.screenshot(canvas_only=True, path= "hello1.png")
plt.rcParams['figure.dpi'] = 150
plt.imshow(img)
plt.savefig('hello2.png')
```
the file hello1.png will not have the axis, the file hello2.png will have the axis

**Comment by tlambert03** [comment]
> Right now, when making a screenshot with canvas_only=True, it automatically adds an axis to the plot.

Hi @kolibril13, that axis is getting added by matplotlib (not napari) when you use `plt.imshow()`.  (this is why when you provide path to screenshot, you don't see it, because it's saving the (axis-free) screenshot to disk without going through matplotlib.

If you'd like to use `plt.imshow()` to show an image without axes, see this tip: https://stackoverflow.com/questions/9295026/matplotlib-plots-removing-axis-legends-and-white-spaces

**Comment by kolibril13** [comment]
Thanks a lot, that was an error in thinking from my side.
Really appreciate that you took the time to link me to this side :)
