### ISSUE TITLE
Shapes Layer example in Readme

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#387]
## 📚 Documentation
 python3 examples/add_shapes.py

The figure generated after running this command that has a layer of shapes and the photographer as below.

Although on the shape layer, opacity, face_color, edge_color sliders seem ineffective. They don't change anything in the shape layer overlaid on the image, although interestingly the thumbnail changes

<img width="624" alt="Screen Shot 2019-07-02 at 4 35 51 PM" src="https://user-images.githubusercontent.com/10284094/60553296-82f54000-9ce7-11e9-8e1f-7bc645840eaa.png">

**Comment by sofroniewn** [comment]
In order to edit those properties you have to select a shape first, which you can do with the select tool that becomes available on the left-hand side panel when you select the shapes layer. This is fairly unintuitive and confusing though so we definitely have to work on documenting it / we might also want to revisit how this is done

**Comment by pranathivemuri** [comment]
gotcha, yeah documentation would be great

**Comment by sofroniewn** [comment]
This has now been explained in depth in our shapes layer tutorial - http://napari.org/tutorials/shapes.html
