### ISSUE TITLE
Tracking Qt6 support

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3880]
## 🧰 Task
We have a few open issues surrounding supporting Qt6, so I wanted to open a meta issue where updates can be posted.

qtpy 2.0.0 is now released, with support for pyside6 and pyqt6 (yay).
Unfortunately, qtpy 2.0.0 only supports >= Qt 6.2, and it looks like a couple of troublesome bugs got introduced in PySide6.2
1. they are now doing some slot inspection upon `signal.connect(slot)`, but make some assumptions about the slot being connected (specifically, that it has a `__code__` attribute, which isn't always true).  This breaks the ability to test signals using `unittest.mock.MagicMock`, which is a pretty big deal :/  (bug report [PYSIDE-1755](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-1755))
2. whether consciously or not, they removed the ability to override signal *types* (i.e. make `widget.valueChanged` emit a tuple instead of the base class type, like `int`).  This breaks all the range sliders in superqt, and as far as I can tell will require a breaking API change in superqt to fix it :/ (bug report [PYSIDE-1751](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-1751))

so, while I was very much looking forward to supporting Qt6 via qtpy 2.0.0 and PySide6, it looks like that isn't going to happen until we deal with these upstream issues.

**Comment by tlambert03** [comment]
as for pyqt6,  we can't use it until we deal with the removal of pyrcc... there's a workaround stared in https://github.com/napari/napari/pull/3254, but it will require more work since the theme hookspec used rcc compilation quite a bit.

**Comment by psobolewskiPhD** [comment]
I've been playing with qtpy2.0dev and now live plus plyside6 on my Apple M1, because pyside6 is native arm64 on pypi and doesn't have the pyrcc issue mentioned above. (So, if pyside6 worked then simple pip napari install would be possible on M1). 
I made a fork of napari and simply proceeded with fixing errors as they popped up one at a time till napari worked.
https://github.com/psobolewskiPhD/napari/tree/pyside6-compat
So after the simple changes, there's a few outstanding issues:
1) napari runs fine from the command line, but not when launched from python REPL using a simple script from the tutorial
```
from skimage import data
import napari
viewer = napari.view_image(data.astronaut(), rgb=True)
```
On my Mac (macOS 12, M1, python 3.9.7) I get a napari python icon launching but no window.
There is no error in the console or anywhere else, there's just no window, so I've not been able to try to fix that.

2) More minor: when launching from the command line napari runs fine and even some plugins I've tried work, but there are warnings:
```
15:28:18 WARNING delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x60000303db60, name="_QtMainWindowClassWindow")
WARNING: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=901.777,469.707 gbl=901.777,469.707 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-901.777,-469.707 last=-901.777,-469.707 Δ 901.777,469.707) : no target window
```
I don't see anything related to this in the napari codebase, so it could be from vispy which has more touch support. The warnings don't seem to block or mess anything up, but they are a bit ominous.

**Comment by Tomaubier** [comment]
> as for pyqt6, we can't use it until we deal with the removal of pyrcc... there's a workaround stared in #3254, but it will require more work since the theme hookspec used rcc compilation quite a bit.

Do you have any updates on this? Best regards

**Comment by tlambert03** [comment]
nope, nothing recently, sorry :/

**Comment by tlambert03** [comment]
Qt6 is now 'supported' as of https://github.com/napari/napari/pull/3707 ... but with the unfortunate aesthetic issue shown in https://github.com/napari/napari/pull/3707#issuecomment-1152997251


![](https://user-images.githubusercontent.com/1609449/173204591-f3bdd9dc-e280-4d2e-b222-c014284f3725.png)


it seems to be something rather low level in Qt6, regarding how the background of Dockwidgets gets rendered.  might  be fixable in our stylesheets, but I haven't been able to isolate the issue yet.

**Comment by Czaki** [comment]
in my case I do not see this bug but I found that PyQt6 version is not reported:

```
napari: 0.4.16rc2.dev188+g37ab725df.d20220723
Platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.35
System: Ubuntu 22.04 LTS
Python: 3.10.4 (main, May 2 2022, 12:34:46) [GCC 11.2.0]
Qt: 6.3.1
PyQt6: 
NumPy: 1.23.1
SciPy: 1.8.1
Dask: 2022.7.1
VisPy: 0.10.0
```

**Comment by tlambert03** [comment]
ok thanks, might be a mac thing then

**Comment by Czaki** [comment]
The visibility of the layer is not properly indicated. 
![obraz](https://user-images.githubusercontent.com/3826210/180622045-66e693dd-2494-4221-bad2-467381b66a5d.png)

**Comment by tlambert03** [comment]
thanks.  please create issues with Qt6 in the title if you'd like to report stuff

**Comment by Tomaubier** [comment]
> Qt6 is now 'supported' as of #3707 ... but with the unfortunate aesthetic issue shown in [#3707 (comment)](https://github.com/napari/napari/pull/3707#issuecomment-1152997251)
> 
> ![](https://user-images.githubusercontent.com/1609449/173204591-f3bdd9dc-e280-4d2e-b222-c014284f3725.png)
> 
> it seems to be something rather low level in Qt6, regarding how the background of Dockwidgets gets rendered. might be fixable in our stylesheets, but I haven't been able to isolate the issue yet.

Could you detail how you managed to install it? Thanks!

**Comment by Czaki** [comment]
install from the repository using pip. Then install `PyQt6` or `PySide6` (ensure that PySide2 and PyQt5 are not installed). 

The latest version (0.4.16) does not contain patches for Qt6 backends.

**Comment by Tomaubier** [comment]
Thanks for the help, the install went smoothly.
To the extent of my testing, Napari runs fine when called within a script or in Python terminal prompt, however the viewer crashes when used within a Jupiter kernel.

Steps to reproduce in a terminal:
Launch a Jupiter kernel (I used `jupyter console`)
`In [1]: import napari`
`In [2]: viewer = napari.Viewer()` -> the viewer opens and behaves as expected (other than the graphical bug mentioned by @tlambert03)
`In [3]: <run any python command> (print('foo') for example)` -> the viewer window closes but the `viewer` object remains accessible (calling `viewer.dims` works, however adding a layer (eg `viewer.add_shapes()`) throughs an error).

Did anyone experienced that before?

Also here is the state of my environnement:
```
napari: 0.4.16rc2.dev300+gbeaa98ef
Platform: macOS-12.5.1-arm64-arm-64bit
Python: 3.10.3
PyQt6: 6.3.1
numpy: 1.21.6
scipy: 1.8.0
dask: 2022.9.0
vispy: 0.11.0
jupyter: 1.0.0
jupyter-client: 7.3.5
jupyter-console: 6.4.3
jupyter-core: 4.11.1
```

**Comment by psobolewskiPhD** [comment]
> `In [3]: <run any python command> (print('foo') for example)` -> the viewer window closes but the `viewer` object remains accessible (calling `viewer.dims` works, however adding a layer (eg `viewer.add_shapes()`) throughs an error).
> 
> Did anyone experienced that before?

I can confirm this on rc4, python 3.10, pyqt6 6.3.1 arm64 macOS 12.6
`jupyter qtconsole`
then launch napari `viewer = napari.Viewer()`
and then it's sufficient to click back to the console for the viewer to disappear.
This only happens when launching from `jupyter qtconsole` or jupyter notebook (VS Code) using ipython instead is fine.

**Comment by Tomaubier** [comment]
That's weird, both VS Code and Atom Hydrogen show the same issue as `jupyter console` for me..

**Comment by psobolewskiPhD** [comment]
Maybe I wasn't clear, but I got the bug in:
jupyter console and jupyter notebook (VS Code)
but not in ipython.
Anyhow, at this point I think this specific thing should become an issue.

**Comment by Tomaubier** [comment]
> Maybe I wasn't clear, but I got the bug in:
> jupyter console and jupyter notebook (VS Code)
> but not in ipython.
> Anyhow, at this point I think this specific thing should become an issue.

Ok that makes sense, thanks for the feedback, I've just created the issue.

**Comment by psobolewskiPhD** [comment]
With recently merged:
https://github.com/napari/napari/pull/5480
and 
https://github.com/napari/napari/pull/5492

Plus the upstream fixes mentioned in the OP and one in ipykernel, I think it's best to close this issue, because Qt6 support in napari works. It's best to have new issues for any specific bugs to get more visibility on them and allow easier discussion.
I think we're close to considering an experimental `napari[pyqt6]` or `napari[pyside6]` (this would enable pip installs on macOS arm64 for example).
