### ISSUE TITLE
Bug: cmd-click no longer filling in labels

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3926]
## 🐛 Bug

Just realized that holding command is no longer switching the labels mode to "fill" and command-click to fill in a label hasn't been working for the last couple versions.  bisect puts it at #3072

**Comment by tlambert03** [comment]
ahh sorry, I just saw @sofroniewn's [comment](https://github.com/napari/napari/pull/3072#issuecomment-884439192)

> I really don't like that pressing a modifier key changes the mode even if temporarily.

I actually _loved_ that 😢 ... @sofroniewn what's the opposition to modifier-clicks doing stuff?

**Comment by psobolewskiPhD** [comment]
LOL, I had the same reaction on zulip:
https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Labels.20layer.20info.2Fkeybinds

**Comment by tlambert03** [comment]
Ok, reading more in that link, and what @psobolewskiPhD linked above, looks like the opposition was:

> the problem is that modifiers are used in other shortcuts, so we don't want modifier keys to temporarily switch modes, because e.g. typing Ctrl-C would see the mode flicker on and off when the user had no intention to deal with the mode. Instead the modifiers could either be read by the mouse event directly and the layer behaviour would be modified, or, we could use different hold keys.

I can see that potentially being troublesome (e.g. https://github.com/napari/napari/issues/2714), but I think it deserves a proper refactor, such that the _behavior_ stays the same (i.e. cmd-click should fill in a label) even if the implementation changes (i.e. no longer changes mode on pressing command, but rather waits for the click).  But it looks like it was just removed and forgotten.  Can we bring this back temporarily until someone is actually tasked with fixing it?

**Comment by tlambert03** [comment]
(and minimally the help text needs to change to no longer state that holding ctrl does anything)

**Comment by sofroniewn** [comment]
> I can see that potentially being troublesome (e.g. #2714), but I think it deserves a proper refactor, such that the behavior stays the same (i.e. cmd-click should fill in a label) even if the implementation changes (i.e. no longer changes mode on pressing command, but rather waits for the click). But it looks like it was just removed and forgotten. Can we bring this back temporarily until someone is actually tasked with fixing it?

yeah, that's fair. Maybe it was just myself - with possibly some support from @jni that felt that way. I just found it really jarring that when I would do cmd-C for example the mode button would flicker. Making the implementation such that it waited for click would avoid that, but it is more complicated - and someone else could argue that they would like to see the button change highlight when the cmd is being held down. I wonder if @isabela-pf has thoughts.

Also would shift-click work? I guess we want to keep control-click maybe for opening a dialog?

I think though if both @tlambert03 and @psobolewskiPhD agree on a preferred behavior and feel strongly then we should revert / fix it. Would be nice to maybe ask a few more folks once the PR is made just to make sure we don't bounce back and forth though

**Comment by isabela-pf** [comment]
In trying similar behaviors on other image-y applications, I’m finding some cases where users are required to _hold_ a modifier key to change an action.
- The space bar for pan/zoom is the most common (and [Wikipedia is on @sofroniewn’s side about it not being a modifier key](https://en.wikipedia.org/wiki/Modifier_key) 😆). 
- Photoshop and Inkscape use all of them to initiate different selection or editing modes. 
- Adobe Illustrator and Figma only use some modifier keys to change modes only if a selection is currently being made.
- Several applications don’t use any of these hold-key behaviors at all.

Basically this behavior isn’t an unknown pattern, just not ubiquitous.

There’s also an accessibility argument to be made against requiring a key to be held in order to change a mode (though it could be one of multiple options). Pressing a key to initiate a certain mode (and esc to leave it) or using the key as a kind of toggle doesn’t rely so much on the physical ability to hold a key for an unknown amount of time, so it is preferable. 

In this case, it sounds like the user isn’t likely to hold command and stay in the mode indefinitely, only to use the command-click combo. Is that correct?

In terms of WCAG guidelines, I’d personally interpret having a key held to be a kind of “specific timing” that isn’t allowed ([criterion 2.1.1](https://www.w3.org/TR/WCAG22/#keyboard)). So I can’t recommend that if it is the only means of accessing this feature; if it can be accessed another way it’s okay, but not fantastic.

**What I think might work:**
Activating on a certain focus (for example, switching modes is only triggered by command when users are focused on the canvas) is a reasonable behavior and one that is a little more accessible. I’d consider that an option if there is a focus that seems relevant (similar to the Adobe Illustrator and Figma behavior I mentioned above).

> Making the implementation such that it waited for click would avoid that, but it is more complicated - and someone else could argue that they would like to see the button change highlight when the cmd is being held down.

I was thinking the same thing. Is there a benefit to this mode being so transient, or do the people in favor of it consider this an option?

---

Related note: Is there a full list of commands in napari to reference this sort of thing and know what would have to be changed for more consistent behavior everywhere?

**Comment by tlambert03** [comment]
> So I can’t recommend that if it is the only means of accessing this feature; if it can be accessed another way it’s okay, but not fantastic

it's definitely accessible otherwise.  the other way is to 1) click on the paint can icon, 2) click on the canvas... OR 1) press the `3` key 2) click the region 3) press the `2` key to return top the other mode.

The cmd-click is just a convenience that allows you to not move your mouse all the way to the top left.  Probably a ~0.2 second  key hold.  It's *very* common when annotating images to circle a region an then want to fill it in, so lacking a key command, it necessitates moving your mouse a lot more than previously.

**Comment by isabela-pf** [comment]
That makes sense @tlambert03. Since I’ve found similar behavior on other software (particularly Photoshop), this “flicker” doesn’t seem like a bad pattern. I agree with that @sofroniewn 

> Would be nice to maybe ask a few more folks once the PR is made just to make sure we don't bounce back and forth though

Figma avoids this flicker by not using the held command key to trigger the mode since its the basis for many shortcuts. When I click through napari, it seems like holding option or control doesn’t do anything. Would those be better options to preserve the transient shortcut and avoid a flicker?

**Comment by jni** [comment]
@sofroniewn not sure if you're overstating my support. =P Maybe not: I agree that the mode flicker with unrelated shortcuts was bad, and there were some bugs related to its implementation (under some circumstances, the mode would not switch back), but like @tlambert03 says I would have preferred to only remove this behaviour once an alternative was implemented.

Anyway, we're here now. Two alternatives:

- special-case Ctrl-click, shift-click, etc so that they work but don't switch modes
- implement a special casing of the mode shortcuts so that *holding* the mode shortcut (3) would temporarily change it, and releasing it would change it back. This could be implemented either with timing *or* with hold+click (ie if there was a click between button down and button up, revert back to the previous mode.)

These are not mutually exclusive, and the modifiers are probably much easier to implement currently, so we could do both. Opinions?

@tlambert03 in the meantime, I propose you keep your fingers over the number buttons while labelling. :stuck_out_tongue_winking_eye: quickly switching between 2 and 3 is *almost* as ergonomic as ctrl-click?

**Comment by tlambert03** [comment]
> @tlambert03 in the meantime, I propose you keep your fingers over the number buttons while labelling. 😜 quickly switching between 2 and 3 is almost as ergonomic as ctrl-click?

there already :joy:

**Comment by sofroniewn** [comment]
Another option could just be to use another set of keys for "temporary" enable (i.e. as modifiers), `qwert` or something? Holding one will change mode, but releasing returns to previous mode?

**Comment by jni** [comment]
@sofroniewn do you see this being easier than having the toggles doing double duty? I find that more intuitive, e.g. holding on a Mac's menubar vs clicking on it.

**Comment by sofroniewn** [comment]
The nice thing about `qwert` is that the mode button can change when you're holding so you do get that good visual input in the cases where you want it, but ultimately here I will defer to the ergonomics of what people who are doing this all the time prefer

**Comment by jni** [comment]
@sofroniewn but that can happen also with 1, 2, 3, ...? It's just whether it flips back after holding.

**Comment by tlambert03** [comment]
Are we avoiding modifiers because it's harder to implement?  We don't _have_ to change the mode immediately upon pressing the command key right?  It could be in the mouse click event

**Comment by jni** [comment]
@tlambert03 yes that's option 1. The nice thing about option 2 is that you *do* get the nice visual feedback. The issue with modifiers is that if you do the visual feedback then you can get it when not intended — when activating other shortcuts.

**Comment by sofroniewn** [comment]
> @sofroniewn but that can happen also with 1, 2, 3, ...? It's just whether it flips back after holding.

1, 2, 3, ... would be permanent flips that happen on press (or release?, shouldn't matter)
q, w, e, .... would be temporary holds that return on release

**Comment by jni** [comment]
Yes, I understand that. I'm saying, we can have:
- 1, 2, 3 change mode on press
- on release, depending on how long we've pressed or whether there were any clicks during the press, we flip back to the original mode, or not.

I really like this pattern in general.

**Comment by tlambert03** [comment]
I like this too, if we can reliably pull it off in code.  Meaning, if it "behaviorally" works well, and the user never has to try twice.

**Comment by sofroniewn** [comment]
> I like this too, if we can reliably pull it off in code. Meaning, if it "behaviorally" works well, and the user never has to try twice.

Yup, we can try this - we could first just say if hold is longer than 1 second revert (probably hard to get a click off and have hold be less than 1 second), but we can fine tune details - overall i like the idea a lot, good fix that addresses all concerns

**Comment by lucyleeow** [comment]
> implement a special casing of the mode shortcuts so that holding the mode shortcut (3) would temporarily change it, and releasing it would change it back. This could be implemented either with timing or with hold+click (ie if there was a click between button down and button up, revert back to the previous mode.)

With regard to the above, this closed PR is relevant: https://github.com/napari/napari/pull/2854
Some work will be required for ActionManager to handle 'short press' and 'long press' - and if we do want to add this...
