### ISSUE TITLE
Add layerlist events to docs

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3984]
## 🧰 Task
Note to self (or anyone who'd like to take it up), we need to add `LayerList` events to the events reference at https://napari.org/guides/stable/events_reference.html

**Comment by grlee77** [comment]
I am taking a look at this. 

Also there is a related issue in that all events corresponding to `_ImageBase` get listed twice since they are present for both Image and Labels classes. As a concrete example, `layer.events.contrast_limits` is listed twice [here](https://napari.org/guides/stable/events_reference.html).

I think in general, it is helpful to have a column listing the layer class that each event type corresponds to (with a note to indicate to readers that "Layer" refers to events that are present on all layer types). We can then merge some of the `Image` and `Labels` events under the name `Image, Labels` as illustrated in a subset of table entries shown below. 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
|  Class              |  Event                                           |  Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |  Event.value type  |
|---------------------|--------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|
|  `Layer`            |  `layer.events.source`                           |  source of the layer (such as a plugin or widget)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                    |
|  `Layer`            |  `layer.events.refresh`                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                    |
|  `Layer`            |  `layer.events.set_data`                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                    |
|                    |
|  `Image`, `Labels`  |  `layer.events.contrast_limits`                  |  Color limits to be used for determining the colormap bounds for luminance images. If not passed is calculated as the min and max of the image.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                    |
|  `Image`, `Labels`  |  `layer.events.gamma`                            |  Gamma correction for determining colormap linearity. Defaults to 1.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                    |
|  `Image`, `Labels`  |  `layer.events.colormap`                         |  Colormap to use for luminance images. If a string must be the name of a supported colormap from vispy or matplotlib. If a tuple the first value must be a string to assign as a name to a colormap and the second item must be a Colormap. If a dict the key must be a string to assign as a name to a colormap and the value must be a Colormap.                                                                                                                                                                                                                                                                                 |                    |
|  `Image`, `Labels`  |  `layer.events.mode`                             |  Interactive mode. The normal, default mode is PAN_ZOOM, which allows for normal interactivity with the canvas.  In TRANSFORM mode the image can be transformed interactively.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                    |
|  `Image`, `Labels`  |  `layer.events.interpolation`                    |  Interpolation mode used by vispy. Must be one of our supported modes.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                    |
|  `Labels`           |  `layer.events.preserve_labels`                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                    |
|  `Labels`           |  `layer.events.properties`                       |  Properties for each label. Each property should be an array of length N, where N is the number of labels, and the first property corresponds to background.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                    |
|  `Labels`           |  `layer.events.brush_size`                       |  Size of the paint brush in data coordinates.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                    |
|  `Labels`           |  `layer.events.selected_label`                   |  Index of selected label. Can be greater than the current maximum label.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                    |

**Comment by tlambert03** [comment]
> I think in general, it is helpful to have a column listing the layer class that each event type corresponds to

wow, 100%, I can't believe that slipped by me!

feel free to ping if I can help
