### ISSUE TITLE
icons do not show up when starting napari with plugin from command line

### ISSUE THREAD

**Issue by ptbrown1729** [napari/napari#4004]
## 🐛 Bug

When I try and start napari from the command line with a plugin using the `-w` option the icons for the various buttons  (e.g. layers buttons, toggle n-display, etc) are not shown. Instead there are blank square placeholders. also do not show any icons. On the other hand, if I first launch napari, and then launch the plugin from the GUI the icons show up as expected.

## To Reproduce

1. install [napari-micromanager plugin](https://github.com/tlambert03/napari-micromanager) or naparij plugin (these are the only two I've tested).
2. Go to the command line, activate conda python environment, type `napari -w micromanager` or `napari -w naparij Points`
3. View napari GUI

## Expected behavior

Icons showing e.g. the points layer, layer deletion trashcan show up.

## Environment

napari: 0.4.13
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:36:06) [MSC v.1929 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.2
SciPy: 1.7.3
Dask: 2022.01.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.3.0 - Build 20.19.15.4531
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- micromanager: 0.0.1rc6.dev9+g69c3bed.d20220117
- naparij: 0.2.2
- scikit-image: 0.4.13
- svg: 0.1.5

**Comment by ptbrown1729** [comment]
Per @tlambert03 suggestion, I created a fresh environment (see below) and I see the same behavior as mentioned above
```
conda create -n test -c conda-forge python=3.9.9 napari
conda activate test
pip install napari-micromanager
napari -w micromanager
```

**Comment by tlambert03** [comment]
OK, i was able to recreate this, but only on windows... and it _is_ a `napari micromanager` problem actually:

in a new env, just install napari and napari-j
```
conda create -n test -c conda-forge python=3.9.9 napari
conda activate test
pip install napari-j
```

this works fine
```
napari -w naparij Image
```

now just install napari-micromanager, and retry
```
pip install napari-micromanager
napari -w naparij Image
```

no icons...

A little backstory, napari-micromanager uses Qt `.ui` files to generate the gui.  Presumably when napari starts up, it loads all plugins (including napari micromanager), and _something_ about that way of loading a UI is having this effect.  I've never seen this happen before, but it only seems to happen on windows...

In any case, since this _does_ actually seem to be napari micromanager specific.  I'm going to close this issue, and we can pick it back up over in https://github.com/tlambert03/napari-micromanager/issues/88.

(to confirm, try

```
pip uninstall napari-micromanager
napari -w naparij Image
```

**Comment by ptbrown1729** [comment]
Following those steps also recovered the icons for me. Ok, I guess it is a napari-micromanager issue and not a napari issue

**Comment by tlambert03** [comment]
moreover, it somehow seems to only happen with the qt distribution (not just version) on conda forge:

this works fine

```
conda create -n test python=3.9
conda activate test
pip install napari[all] napari-micromanager
napari -w micromanager
```

even if I downgrade pyqt to <5.13 to match the newest version on conda it still works...
