### ISSUE TITLE
examples/points_over_time.py is broken after #3730

### ISSUE THREAD

**Issue by brisvag** [napari/napari#4035]
## 🐛 Bug

`git bisect` points to #3730 as the commit that broke the example `points_over_time`. Something is off about the `face_color_mode` and how it's set/reset. It doesn't seem to stick, so as the layer gets updated the face colors do not change. @andy-sweet , any quick idea on where to look for the issue?

## To Reproduce

Run the example and move the dims slider; nothing changes, whereas it should update point colors.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by andy-sweet** [comment]
I knew that the silence after that change was too good to be true :D As noted in the description, PR #3730 breaks a couple of behaviors.

The important one here is that we cannot rely on in-place mutation of `Layer.properties`, which in this example we do with `pts_layer.properties['value'] = np.asarray(values_table[:, column])`. I think it will work sometimes (in the case that `Series.to_numpy()` does not copy so that the returned numpy array has the same base as the dataframe memory block, but maybe not in this case.

The fix that seems to work for me is to use `pts_layer.features['value'] = np.asarray(values_table[:, column])` instead, which seems good to me.

As a part of fixing this issue, we should probably take a look at the other relevant examples to check they are not broken either.

@brisvag : I'm happy to assign myself and fix this issue, probably by the end of today. But if you feel like doing it, please assign yourself and I can review.

**Comment by andy-sweet** [comment]
This issue also makes me want to prioritize a more official deprecation of properties, but as we found out, those PRs can get complex. I can probably write a PR to deprecate the `properties` getter/setter, maybe the init parameter, but not the state field, so I will probably try to do that this week.

**Comment by brisvag** [comment]
> `pts_layer.properties['value'] = np.asarray(values_table[:, column])`

> The fix that seems to work for me is to use `pts_layer.features['value'] = np.asarray(values_table[:, column])` instead, which seems good to me.

I see; yeah this is a bit annoying, I feel like inplace editing is prevalent and important. We definitely need proper deprecation out, which is gonna be tricky indeed :)

I'll let you take care of this for now, since you're more familiar with the quirks, but please let me know if you'd like help!
