### ISSUE TITLE
Provide `Layer.current_features` and events for the new features API

### ISSUE THREAD

**Issue by jwindhager** [napari/napari#4064]
## 🚀 Feature

While `Layer.properties` and `Layer.property_choices` are in the process of being deprecated (?) in favor of the new `Layer.features` and `Layer.feature_defaults` properties, it would be nice to also have a replacement for `Layer.current_properties`.

Also, while `Layer.events` supports events for `properties` and `current_properties`, events for `features` and `feature_defaults` seem to be missing.

## Motivation

Dynamically reading/updating layer features of new objects before the new feature values are added to `Layer.features` (e.g. during drawing of shapes) is crucial to many plugins, especially for plugins reacting to `Layer.events.properties`.

Also, many plugins attach event handles to the `properties` and `current_properties` events, which may be deprecated (?) in favor of the new features API.

## Pitch

Add a `Layer.current_features` functionally similar to `Layer.current_properties`.

Provide events for `features` and `current_features`.

## Alternatives

Keep the current names (`Layer.current_properties`, events for `properties` and `current_properties`). However, this would introduce inconsistency with the new features API.

**Comment by andy-sweet** [comment]
Hi @jwindhager  - thanks for raising this.

You're right that the plan is to deprecate the `properties` attributes in favor of the `features` ones, though that hasn't happened yet due to the size of the change.

I opened an issue regarding the missing `features` event (#4079), which should be straightforward to add. I'll leave this one open to cover adding a new equivalent to the `current_properties` setter and an associated event, as I have a few clarifying questions about that.

The `current_properties` setter does two things in `Points` and `Shapes`.

1. It sets the property values that will be used for the next points/shapes added.
2. It updates the property values of the currently selected points/shapes with the new `current_properties`.

a.) Could we limit a new `feature_defaults` setter to only do (1)?
I think we have (2) to make the GUI change the currently selected points take on the new color when it's selected manually, but I think it would be clearer to separate the two behaviors in the API.

b.) Is the name `feature_defaults` OK as an alternative to `current_properties`?
Again, the idea is to distinguish between the default values that are used when new points are added, as opposed to the values that are currently selected.

c.) If I set `feature_defaults`, but the value I pass has different keys or dtypes to `features`, can we error?
I initially avoided defining a `feature_defaults` setter to automatically keep things consistent.

d.) If I set `features`, is it OK to reset `feature_defaults`?
This is related to (c), as it's about keeping the column names/dtypes in sync.

**Comment by jwindhager** [comment]
Hi @andy-sweet, thanks for splitting up the issue and giving this a thought!

> The `current_properties` setter does two things in `Points` and `Shapes`.
> 1. It sets the property values that will be used for the next points/shapes added.
> 2. It updates the property values of the currently selected points/shapes with the new `current_properties`.

Correct me if I'm wrong, but the way I understand the current behavior is that `current_properties` holds the property values of the current point/shape (singular!) in the process of being added. I think there is a small but important semantic difference: `feature_defaults` holds the default values (i.e., template) for any point/shape being added in the future, whereas `current_properties` holds the values for the actual point/shape instance being drawn right now. So, in a way, your (1) and (2) boil down to just (2), interpreting the point/shape in the process of being added as "real point/shape". Until now I thought of it as: `feature_defaults` populates `current_properties`, which is then used to fill `features`. Check out #4065 for an example how this is being leveraged by plugins at the moment. Also, I think it would be great if there was a functional way of populating `current_properties` (see #4065).

> a.) Could we limit a new `feature_defaults` setter to only do (1)? I think we have (2) to make the GUI change the currently selected points take on the new color when it's selected manually, but I think it would be clearer to separate the two behaviors in the API.
> 
> b.) Is the name `feature_defaults` OK as an alternative to `current_properties`? Again, the idea is to distinguish between the default values that are used when new points are added, as opposed to the values that are currently selected.

As explained, I think `feature_defaults` has a purpose different from `current_properties`. Please correct me if I'm wrong!

> c.) If I set `feature_defaults`, but the value I pass has different keys or dtypes to `features`, can we error? I initially avoided defining a `feature_defaults` setter to automatically keep things consistent.
>
> d.) If I set `features`, is it OK to reset `feature_defaults`? This is related to (c), as it's about keeping the column names/dtypes in sync.

I think that wouldn't be the best option: Sequentially modifying `features` and then `feature_defaults` (or the other way round) would then always lead to an inconsistent state (if one designs one as such), and not allowing the user to add anything would not be the goal here I assume :-) May I suggest to instead add the new key to `features` when the first point/shape with the new key from `feature_defaults` is being added? Similarly, I'd propose setting values for keys that are present in `features`, but not in `feature_defaults`, to `np.nan` when updating `features`.

Writing this, I realize that maybe one would want to rethink the whole `feature_defaults`/`current_properties`/`features` approach altogether...

**Comment by andy-sweet** [comment]
Thanks for the reply - the napari-roi plugin definitely helps me understand your thinking here.

> whereas `current_properties` holds the values for the actual point/shape instance being drawn right now.

From my perspective, either the point/shape exists (i.e. it has an entry in `data` and a row in `features`) or it doesn't. When you interact with the napari GUI, I think this is clear for points - you click to add a point, it appears, and it has an entry in data/features. 

Adding a shape in the GUI feels different because there is an act of adding or modifying the vertices/parameters of that shape until it's complete. But again, as soon as you start drawing, the shape exists, and has an entry in data/features.

In both cases, there is some intermediate state while the `data` setter is executing (e.g. the length of data and features are temporarily different), but I am strongly against exposing that.

> Writing this, I realize that maybe one would want to rethink the whole feature_defaults/current_properties/features approach altogether...

I think the interesting discussion here is about selection. When you add a point/shape, it is the last entry in data/features, but it also becomes the only selected element. Alternatively, you can select some existing points/shapes. It's here where I think `current_properties` takes on too much behavior/meaning as one property.

1. The getter returns the properties of the last selected things (which might be the currently selected things) that all had the same property values. If there has been no selection yet, it returns the default values it was initially populated with or modified to have using the setter.
2. The setter generally allows you to set the values that the `current_properties` getter returns. If there is a selection (and maybe under a few other conditions), it will also set the property values of the selected things to take on the given values.

The other problem I have with `current_properties` is that it leads to defining more attributes like `current_face_color`, `current_edge_color`, `current_size`, growing the public API, and maybe adding more complex behavior as describe above. We could also define `current_data` and keep going.

I haven't thought too much about selection, but my gut feeling is that we should expose the data/properties, expose the selection as something that can be used to index the data/properties, and let the user take it from there (e.g. `points.features['class'][points.selected_data]`.

> Sequentially modifying `features` and then `feature_defaults` (or the other way round) would then always lead to an inconsistent state

I'm not sure what you mean by inconsistent state. In the design I described, if `features` is set, then `feature_defaults` will be modified to have the same keys and dtypes as `features`, so we're consistent. If `feature_defaults` is set, the change will only go through if its keys and dtypes are the same as the columns in `features`, so again we're consistent.

My thought here is that you would know what features columns you want ahead of time, in which case you can just define them in `features` and `feature_defaults` will be populated automatically and can be modified in-place later. In some ways I see `feature_defaults` as an extra row of the `features` table, so I don't like decoupling them. But if that's really not the case, I suppose we can implement the merge-like behavior you described.

**Comment by andy-sweet** [comment]
The other thought I had here with respect to napari-roi is that you may actually care far more about detecting more detailed changes to `features` (i.e. row added at index, rows removed at indices, element changed at index) rather than the exact behavior of `feature_defaults` and `current_properties`. Is that right?

**Comment by jwindhager** [comment]
> From my perspective, either the point/shape exists (i.e. it has an entry in `data` and a row in `features`) or it doesn't. When you interact with the napari GUI, I think this is clear for points - you click to add a point, it appears, and it has an entry in data/features. Adding a shape in the GUI feels different because there is an act of adding or modifying the vertices/parameters of that shape until it's complete. But again, as soon as you start drawing, the shape exists, and has an entry in data/features.

Thanks for the explanations! Seems like I fundamentally misunderstood the interplay of `property_choices`/`feature_defaults`, `current_properties`, and `properties`/`features`. I was under the impression that `data`/`properties`/`features` would not be touched before drawing a shape is complete. I just verified myself that shapes are present already during creation and stand corrected. Makes me wonder how I didn't realize this when writing `napari-roi` :rofl: 

> I think the interesting discussion here is about selection. When you add a point/shape, it is the last entry in data/features, but it also becomes the only selected element. Alternatively, you can select some existing points/shapes. It's here where I think current_properties takes on too much behavior/meaning as one property.
>
> [...]
>
> The other problem I have with `current_properties` is that it leads to defining more attributes like `current_face_color`, `current_edge_color`, `current_size`, growing the public API, and maybe adding more complex behavior as describe above. We could also define `current_data` and keep going.

Indeed, now looking at `current_properties` as getter/setter for various sources (last selected, currently selected, future added, arbitrary values, ...), this property becomes very confusing. Also, your point of this leading to a bunch of `current_XYZ` is a very valid one. I think dropping the whole idea of `current_properties` may be worth a thought! In this case, it may be a good idea to check what plugins subscribe to the `current_properties` event for, to understand potential implications/use cases that neither of us have thought of yet.

> I haven't thought too much about selection, but my gut feeling is that we should expose the data/properties, expose the selection as something that can be used to index the data/properties, and let the user take it from there (e.g. `points.features['class'][points.selected_data]`.

Sounds very reasonable!

> In the design I described, if `features` is set, then `feature_defaults` will be modified to have the same keys and dtypes as `features`, so we're consistent. If `feature_defaults` is set, the change will only go through if its keys and dtypes are the same as the columns in `features`, so again we're consistent.

Ah, I didn't get the "one way" part before (setting `features` modifying `feature_defaults`, but not the other way round). Sounds reasonable to me, too!

> My thought here is that you would know what features columns you want ahead of time, in which case you can just define them in `features` and `feature_defaults` will be populated automatically and can be modified in-place later. In some ways I see `feature_defaults` as an extra row of the `features` table, so I don't like decoupling them. But if that's really not the case, I suppose we can implement the merge-like behavior you described.

Now that *I think* I understand better, I fully agree with you: raising an exception when accessing new columns in `feature_defaults` (which aren't yet present in `features`) should be the way to go, to make the user explicitly specify defaults for existing rows in `features` when adding new columns. The only case where this may be be a bit counter-intuitive is when `features` is still empty (e.g. after adding a `Shapes` layer), where plugin developers would have to do something like:

```python
layer = viewer.add_shapes()
layer.features["new feature"] = np.nan  # a bit unnecessary, because layer.features is still empty
layer.feature_defaults["new feature"] = 123  # only works after adding the column to layer.features
```

but I guess this is where the `add_shapes` arguments (`features`, `properties`, `property_choices`) come into play?

> The other thought I had here with respect to napari-roi is that you may actually care far more about detecting more detailed changes to features (i.e. row added at index, rows removed at indices, element changed at index) rather than the exact behavior of `feature_defaults` and `current_properties`. Is that right?

Indeed, nice catch! A more sophisticated event system would be useful (even though that wasn't the original intention of creating this issue). This becomes particularly obvious [here](https://github.com/BodenmillerGroup/napari-roi/blob/daf2f891dbfc9bd5038206726fb295e535ea7630/napari_roi/qt/_roi_layer_accessor.py#L35-L66), where I create copies of the entire `data` and `features`, modify them (e.g. add a row), and set them again, to make sure the `data` and `features` event handlers get called.

As a side note, it's also a bit weird that entries in `data` and `features` are linked by their `iloc`, which becomes a bit problematic when updating `data`: in this case, `features` is truncated to `len(data)` rows, even though shapes may have been removed from other positions than the end of the `data` array (e.g. when updating `data` with a new array with the first of `n>1` shapes deleted, see the linked source code above). But this is probably not too problematic overall, I guess, given that `data` is a fixed-size numpy array by design anyway... Happy to open a separate issue though, if you think this should be discussed in more detail!

**Comment by andy-sweet** [comment]
Thanks for the response - it helps me clarify what the needs are here. I also wanted to check that the coexistence of `features` and `properties` hasn't broken anything for you yet, as that wasn't clear from the comments so far.

> As a side note, it's also a bit weird that entries in `data` and `features` are linked by their `iloc`, which becomes a bit problematic when updating `data`: in this case, `features` is truncated to `len(data)` rows, even though shapes may have been removed from other positions than the end of the `data` array (e.g. when updating `data` with a new array with the first of `n>1` shapes deleted, see the linked source code above).

Yeah, I'm aware of that slightly strange behavior. I wrote up some ideas in #3779 to help make this more understandable and consistent, so maybe that's a good place to add ideas/comments?

**Comment by jwindhager** [comment]
Awesome, I'll have a look at #3779 then. Given that the `features` event is being tracked by #4079, dynamic population of `features` is being tracked by #4045, and `current_features` is probably not needed anymore, I'll close this issue for now. Feel free to reopen it when needed!
