### ISSUE TITLE
Bundle builds are failing with "cannot import name soft_unicode from markupsafe"

### ISSUE THREAD

**Issue by jni** [napari/napari#4117]
## 🐛 Bug

Our builds are failing due to a [new release 2.1 of markupsafe](https://pypi.org/project/MarkupSafe/#history) which appears to have broken jinja2, used by cookiecutter, used by briefcase. See e.g.

https://github.com/napari/napari/runs/5243771823?check_suite_focus=true#step:7:54

Looks like we need to require markupsafe<2.1, as it won't be fixed upstream. This is probably due to briefcase 0.3.1 requiring an old version of Jinja which doesn't have an upper pin on markupsafe.

https://github.com/pallets/markupsafe/issues/282
https://github.com/pallets/markupsafe/issues/283

**Comment by davidism** [comment]
You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by TheSegfault** [comment]
@davidism You do not belong here anti-semver dumb dumb, stop copy pasting ur poop everywhere

**Comment by jni** [comment]
@TheSegfault I wasn't particularly a fan of @davidism's earlier post, (different projects have different development styles, and anyway I'd tried to be careful not to make any asks of @davidism, who let's be clear is free to run the projects he maintains however he chooses) but yours is completely inappropriate and violates our [code of conduct](https://napari.org/community/code_of_conduct.html) which prohibits personal insults and which applies to all napari communication channels. Please refrain from any similar posts in the future.
