### ISSUE TITLE
Github CI of napari-plugins fail suddenly

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4119]
## 🐛 Bug

Hi all,

I'm observing that a couple of my plugins recently show a broken CI / tests (suddenly). I did not really change code, hence I'm suspecting that it might be related to the release of napari 0.4.14, but I'm not sure. Advice how to deal with these situations are very welcome. E.g. shall we pin the napari version we test against?

## To Reproduce

Here you see examples:

https://github.com/haesleinhuepf/napari-accelerated-pixel-and-object-classification/runs/5140005981?check_suite_focus=true

https://github.com/haesleinhuepf/napari-workflows/runs/5148389657?check_suite_focus=true#step:7:130

## Expected behavior

Is there an upgrade-guide for napari 0.4.14 so that I can fix my CI efficiently?

Again, advice would be helpful. I'm not a github-CI-pro, I'm an image-analyst.

**Comment by tlambert03** [comment]
the first one is probably an xvfb with qt issue (I'm not certain).  (Does it pass locally, just not on CI?)
We've generally had better luck with the xvfb action as [shown in the cookiecutter](https://github.com/napari/cookiecutter-napari-plugin/blob/5a99a539c82d0837908c6570056952cde92d6ec3/%7B%7Bcookiecutter.plugin_name%7D%7D/.github/workflows/test_and_deploy.yml#L55-L61).  So basically, don't install pytest-xvfb and instead, use this to run your tests:

```
  - name: Test
    uses: GabrielBB/xvfb-action@v1
    with:
      run: python -m pytest -v --cov=./ --cov-report=xml
```
But you may need to iterate a bit more on that one.  Let me know...

the second one is this issue: https://forum.image.sc/t/error-loading-napari-pyclesperanto-assistant/63208/6?u=talley

something in there is pulling down an old version of magicgui (0.3.4) but a new version of psygnal (0.3.0).  not sure which subpackage it is, so look through your deps and see if anything is pinning magicgui to an older version

> I'm not a github-CI-pro, I'm an image-analyst.

it's ok, we're all struggling through this together!  no need to keep defending yourself :joy:

**Comment by tlambert03** [comment]
> Is there an upgrade-guide for napari 0.4.14 so that I can fix my CI efficiently?

none of this is probably related to napari (let alone 0.4.14) so no guide available for this unfortunately, let's just figure it out together

**Comment by psobolewskiPhD** [comment]
> the second one is this issue: https://forum.image.sc/t/error-loading-napari-pyclesperanto-assistant/63208/6?u=talley
> 
> something in there is pulling down an old version of magicgui (0.3.4) but a new version of psygnal (0.3.0). not sure which subpackage it is, so look through your deps and see if anything is pinning magicgui to an older version

Isn't it actually napari 0.4.14? 
The napari depend on magicgui wasn't bumped until recently, after 0.4.14 was released...
https://github.com/napari/napari/pull/4082
https://github.com/napari/napari/commit/b78c37e4f4ad6ae5253d065dadd42e265ecf7449

**Comment by tlambert03** [comment]
it went from `magicgui>=0.3.3` to `magicgui>=0.3.6`... that `>=` there means that the newest magicgui will come regardless (just nothing less than 0.3.3 ... so if you just install napari 0.4.13, you should still be getting the newest magicgui (i.e. that didn't change)

**Comment by tlambert03** [comment]
it is quite odd though!  looking through the full repo and it's dependencies, I can't tell why magicgui 0.3.4 is getting installed yet.  That's definitely the answer here (i.e. getting magicgui >=0.3.6 will fix this), but haven't determined why it's not getting installed.  it even _is_ pulling in napari 0.4.14, which should be pulling in at least that version of magicgui, but it's not

**Comment by psobolewskiPhD** [comment]
Could it be caching? a cached magicgui 0.3.4 fulfilling 0.3.3 requirement?

**Comment by haesleinhuepf** [comment]
I may not have been clear in my issue description: I do not care so much about these particular issues. I'm sure they will be fixed after some time. Maybe I just have to rerun the CI. I'm more wondering how to prevent those issues in the future. Shall I pin the napari version in my plugins? Are there other alternatives?

**Comment by tlambert03** [comment]
that would be one general approach.  If you wish, you can pin all of your dependencies (and their dependencies) to an exact version that you know works.  This is a common approach in "applications" as opposed to "libraries".  You can look into tools like https://github.com/jazzband/pip-tools and use commands like `pip-compile` to generation a lock file that lists _all_ dependencies (and subdendencies)

you can read more here https://stackoverflow.com/questions/66751657/what-does-pip-compile-do-what-is-its-use

Note though: in doing this, you will effectively make your plugins "endpoints" that will likely not play well with any other plugins.  So, when you suggest to someone that they install your plugin, it may very well break other plugins.  This is the general state of things in python.  Allowing things to evolve without breakage is famously hard and there's no easy fix.  It's particularly hard in a "set of libraries" scenario, but much easier in an "application" scenario where you're not trying to interop with anyone else

**Comment by tlambert03** [comment]
> Shall I pin the napari version in my plugins?

just to reiterate, this is a general python packaging issue, not a napari issue.  And pinning napari would not have solved this, because napari _itself_ is trying to work well with the rest of the ecosystem, which means we do not hard-pin our dependencies, and any one of napari's dependencies (recursively) could also cause napari to essentially break without notice.  This is one reason we have a dedicated test that runs napari with pre-releases of all of the dependencies: https://github.com/napari/napari/blob/main/.github/workflows/test_prereleases.yml

it _does_ break from time to time, and then we read up on why it's failing and fix the issue.  It unfortunately just takes work to maintain!

**Comment by haesleinhuepf** [comment]
Thanks for the links Talley @tlambert03 ! my problem is, I need to limit time for fixing CIs. I understand that testing is useful.

Does it make sense to fix the napari version for tests only? Or is this a stupid idea?

**Comment by jni** [comment]
@haesleinhuepf

> Does it make sense to fix the napari version for tests only? Or is this a stupid idea?

I think the correct way to handle this is to have a test matrix: one with fixed dependencies (napari and otherwise), one with latest dependencies, and one with pre-releases. You should *not* get rid of the latest tests. Whether or not you have time to fix it, it's important to know whether your plugins are working with the latest version of napari. If you want to make sure that all your plugins *stay* working correctly for a specific version, then dedicate one specific build in the matrix to that. That's how we do our tests for our minimal dependencies ([entry in build matrix](https://github.com/napari/napari/blob/e13b96c40fb294c282f978c342c8dcf4150d776e/.github/workflows/test_pull_requests.yml#L67-L69), [dependecies section in build matrix](https://github.com/napari/napari/blob/e13b96c40fb294c282f978c342c8dcf4150d776e/.github/workflows/test_pull_requests.yml#L100-L107), [script to change >= to == in dependency list](https://github.com/napari/napari/blob/e13b96c40fb294c282f978c342c8dcf4150d776e/tools/minreq.py)).

Also note, as already noted by Talley, that you should potentially pin your entire environment using e.g. [pip-tools](https://pypi.org/project/pip-tools/), since pinning napari 0.4.12 will not prevent the installation of newer versions of psygnal, magicgui, etc.

> I need to limit time for fixing CIs.

[We all wish to limit our time spent fixing CIs](https://twitter.com/gcouprie/status/1493546959264698368?t=6Op4-HDD4v4Fw-yo7dnJJQ)! :joy: There are four ways to do this:

1. work in a slow moving ecosystem, say, FORTRAN.
2. have a small number of packages to maintain.
3. distribute the load among more people (the napari plugin grants were intended to help with this! They have for me, but I have far fewer packages than you!)
4. ignore breakages.

Pinning your CI dependencies is *exactly equivalent* to the last option. Ultimately, we would prefer if you didn't do this, as it would result in a large number of broken plugins. You *can*, however, ignore them temporarily, and, say, batch your CI fixing to once a month. But you should still have a signal on your repo that things are not working on the latest napari.

**Anyway, summary,** I suggest you have (minimum) three entries in your CI matrix:
- pinned dependencies
- latest dependencies
- prerelease dependencies

You are welcome to ignore "latest" failures until it is more convenient to fix, and be happy with green ticks on the pinned dependencies build, but unless you intend to never fix your plugins, you should leave "latest" in your test matrix.

As mentioned by @tlambert03, we are very happy to help you figure out the problem when breakages happen!

I'm going to close this as it is more a discussion than an issue, but feel free to keep discussing!

**Comment by haesleinhuepf** [comment]
Ok, great. Thanks for the hints @jni ! I'm happy to continue discussing in a closed issue as switching to FORTRAN is obviously no option.
