### ISSUE TITLE
Cannot install some plugins 

### ISSUE THREAD

**Issue by PMLLancao** [napari/napari#4129]
## 🐛 Bug

Hello I am trying to install some plugins ( e.g cell pose, Sdeconv, allencell segmented,) in the GUI version of  napari.
I am not using python to run it. 

I am not able to install any of these plugins and in the status window I got this error message:

```
ERROR: Failed building wheel for opencv-python-headless
Failed to build opencv-python-headless
ERROR: Could not build wheels for opencv-python-headless, which is required to install pyproject.toml-based projects
WARNING: You are using pip version 21.3; however, version 22.0.3 is available.
You should consider upgrading via the '/Applications/napari.app/Contents/Resources/Support/Python/Resources/bin/python3 -m pip install --upgrade pip' command.
```

I do not know how to code or use python so I do not know how to solve this issue.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.12
Platform: macOS-10.14.6-x86_64-i386-64bit
System: MacOS 10.14.6 (Mojave)
Python: 3.9.6 (default, Jul 31 2021, 05:03:56) [Clang 12.0.5 (clang-1205.0.22.9)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.9.2

OpenGL:
- GL version: 2.1 NVIDIA-12.0.24 355.11.10.50.10.103
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 1.0

Plugins:
- Measurements (Plot profile): 0.2.1
- Measurements (skimage regionprops): 0.2.9
- Segmentation (split/merge): 0.1.3
- Utilities (skimage regionprops): 0.2.9
- Visualization(B/C): 0.1.6
- animation: 0.0.2
- bbii-decon: 0.0.1
- bfio: 2.1.9
- bioformats: 0.2.1
- brainglobe-io: 0.1.3
- brainreg-standard: 0.1.3
- brainreg: 0.2.3
- brainreg_standard: 0.2.3
- cellfinder-2: 0.0.18
- cellfinder: 0.2.1
- console: 0.0.4
- itk-elastix_napari: 0.1.7
- napari-3d-ortho-viewer: 0.0.1
- napari-crop: 0.1.5
- napari-czifile2: 0.2.6
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-mahotas-image-processing: 0.1.1
- napari-nikon-nd2: 0.1.3
- napari-tiler
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari_czifile: 0.0.2
- nd2-reader: 0.0.6
- ndtiffs: 0.1.2
- ome-types: 0.2.9
- scikit-image
- svg: 0.1.6

 - Any other relevant information:

it takes a lot of time to install any plugin and I have trying to install this after downloading python (anaconda) but still the problem remains.

Is there a way to solve this?
Thank you
Regards

**Comment by Carreau** [comment]
Thanks for your question, 

I haven't yet been able to reproduce. Couple of notes while investigating:
 - opencv-python-headless does indeed not have wheels for 3.8 or above.
 - I see you have macos 10.14 – I had issues with compiling some things when I was on older versions.
  - It looks like your error links to `/Applications/napari.app/Contents/...` so it may be that your bundle install and anaconda install have weird interactions ?

You may want to jump on https://napari.zulipchat.com/ to ask for more immediate help if you need fast back and forth.

**Comment by tlambert03** [comment]
Since you mentioned that you don't code or use python, and you're using the bundled ("double clickable") application, i want to add a little additional background here:

There are _definitely_ things that individual plugins can do (or fail to do) that will make it essentially impossible to install them in the napari bundle.  Ultimately, those plugins will likely need to help you here, so I'd encourage you to also open an issue with any of the plugins you can't install.  You can point them to the [Best practices for plugins](https://napari.org/plugins/stable/best_practices.html) page.  

It's the second item in that page that you're running into here: basically, these packages depend on a package that requires a compilation step, and your computer doesn't have the required setup.  So it "tries" to build them for a long time and eventually fails.  

Some plugins will probably _have_ to depend on these packages (like opencv) that don't ship pre-compiled packages, which means that for now, these will continue to be hard packages for you to use in the bundled application.

I'll also note that just downloading and installing anaconda will _not_ help you here if you're using the bundled napari application (in your /Applications/) folder.  That is: the bundle won't automatically find and use anaconda, it has an independent python environment.  The developers of these plugins might be able to instruct you on how to set up an environment using conda that will allow their plugins to work, but you won't be able to use the napari bundle then.

We're generally working to try to make this stuff easier!  but there's lots of work left to do :)

**Comment by liu-ziyang** [comment]
hi @PMLLancao , we recently released a new packaging app with conda: https://napari.org/tutorials/fundamentals/installation.html#installing-as-a-bundled-app

I hope this resolves the issue. feel free to leave a comment if you still have trouble with the new packaging method
