### ISSUE TITLE
Add arrow to vectors in napari vector layer

### ISSUE THREAD

**Issue by biberger** [napari/napari#4149]
## 🚀 Feature
Add the feature that all vectors in a vector layer have arrows such that the direction they are pointing towards is clear.

## Motivation
It is very frustrating for me to debug my optical flow and related algorithms when I can not exactly see where the flow is pointing towards. You can see this in the image below.

![image](https://user-images.githubusercontent.com/89973708/155307817-74c20d09-a124-45c1-99c8-17afaca5900f.png)
![image](https://user-images.githubusercontent.com/89973708/155307960-6f2233bc-b497-4f02-be6e-3d8d0202a598.png)

Simple arrows would fix this and make my life a lot easier.

## Pitch

I want to have the option that every vector has an arrow at the tip such that the direction a vector is point to is clear.

**Comment by sofroniewn** [comment]
thanks for feature request! @brisvag curious what you think of this/ how you think it might be implemented

**Comment by jni** [comment]
Sorry about the inconvenience @biberger — indeed this has been on our mind since before Vectors was implemented — I still remember the meeting (2019!) where we said, let's just get it in and add arrowheads "soon". :joy: 

@sofroniewn iirc you implemented arrowheads for the axes (?), could that code be reused here?

**Comment by brisvag** [comment]
Actually, I just realized that the [windbarb visual in vispy](https://github.com/vispy/vispy/blob/main/vispy/visuals/windbarb.py) is already implementing a lot of this. I don't know if it works on in 3D and has everythong our vectors need...

**Comment by sofroniewn** [comment]
I could make an arrowhead out of a mesh - but our approach to vectors will change in #4005 - so best to let @brisvag take lead here and go with his recommendations

**Comment by quantumjot** [comment]
FWIW - I'd quite like to see this feature too!

**Comment by brisvag** [comment]
I'd love to work on it, but I have a lot on the plate already; I'd be happy to help out anyone who wants to tackle it, though.

**Comment by jules-vanaret** [comment]
Thank you all for your work on this issue. I had never used the vectors layer before but I am now working with velocity fields from optical flow like OP. As stated, the layer would benefit greatly from vector directionality. 
As #4005 is taking some time to be released, I made a quick and dirty "hack" on the meshing code to display a single triangle pointing in the right direction (instead of two triangles put next to each other to make a rectangle).

If anyone is interested (@biberger , @quantumjot), here it is. 
From napari's installation root, open `{path to napari}/napari/_vispy/layers/vectors.py`
The first step is to replace the function `generate_vector_meshes_2D` by

```
def generate_vector_meshes_2D(vectors, width, length, p=(0, 0, 1)):
  
    ndim = vectors.shape[2]
    nvectors = vectors.shape[0]

    vectors = np.reshape(copy(vectors), (-1, ndim))
    vectors[1::2] = vectors[::2] + length * vectors[1::2]

    vectors_starts = vectors[::2]
    vectors_ends = vectors[1::2]

    # To make the vertices of the triangles, I double the start
    # points, and add the end points in between.
    centers = np.repeat(vectors_starts, 2, axis=0)
    # 'centers' becomes of the form [start1, end1, start1, start2, end2, start2, ...]
    centers = np.insert(centers, range(1,len(centers),2), vectors_ends, axis=0)

    # The start points are then offset by a multiple of the normal
    # vector and the end points are left unchanged.
    offsets = segment_normal(vectors[::2], vectors[1::2], p=p)
    offsets = np.repeat(offsets, 2, axis=0)  
    signs = np.ones((len(offsets), ndim))
    signs[::2] = -1
    offsets = offsets * signs
    # 'offsets' becomes of the form [normal1, end1, -normal1, normal2, end2, -normal2, ...]
    offsets = np.insert(offsets, range(1,len(offsets),2), np.zeros((nvectors, ndim)), axis=0)

    vertices = centers + width * offsets / 2
    triangles = np.arange(len(vertices)).reshape((-1, 3)).astype(np.uint32)

    return vertices, triangles
```

This is essentially what is done in the original function but as I said before, instead of drawing two triangles (in 2D, or four triangles in 3D), it draws a single triangle. This code is still compatible with the "width" and "length" parameters. This also divides the number of polygons drawn by two in 2D and 3D.

The color of each triangle is computed in some other script, so to keep the changes restricted to only one file, the second step is to modify the function  `_on_data_change` (still in the same file). 
Simply replace
```
face_color = self.layer._view_face_color
```
by
```
face_color = self.layer._view_face_color[::2]
```
This solution is particularly dirty and not intended as a fix.
![new_vectors](https://user-images.githubusercontent.com/94963445/231820753-9fd8ae6e-b5ab-44d1-9116-9c92cc22e3ce.png)

Adding a checkbox to switch between the two styles of display directly on the layer interface should be doable. I could do it and share it as a plugin if someone is interested and if the new layer is planned to release in a somewhat long time @brisvag ?

**Comment by brisvag** [comment]
> if the new layer is planned to release in a somewhat long time @brisvag ?

That update is unfortunately on hold until someone more experienced than me can figure out how to ensure geometry shaders in opengl work seamlessly on all platforms. The code itself is pretty much ready actually, it's just a thing about environments and especially Apple being in their own world :(

---

This change is actually pretty nice, very low impact! We could still expose it as two modes with a switch, something like `line` vs `arrow`. This could then be replaced by the geometry shader version which could be expanded to have actual arrowheads.

If you have time to open a PR with just those changes, we can discuss there and actually look at the diff.

On the other hand, if you can and want to do this in a plugin, it's definitely a good way to get things working, keeping in mind that you're relying on private implementation details that might change in the future.

**Comment by jules-vanaret** [comment]
I will try to find the time to look into the checkbox implementation and make the PR next week. :)
Good luck with the shaders stuff, this unfortunately out of my abilities.

**Comment by jni** [comment]
I'm *totally* on board with this, thank you @jules-vanaret for playing with it! I love it! I'd even support a PR hardcoding the change from the lines, which I think are close to useless, without additional context. Directionless vectors, feels like a whole new field of mathematics needs to be invented to make sense of them... 😂 

But, a mode switch ComboBox would be great and there's lots of examples in the code. I would actually do a ComboBox rather than a checkbox in anticipation of having different depictions (lines, triangles, lines with arrowheads, ...)

Let me double @brisvag's offer for help — I have actually been *dying* for this issue to be resolved but the triangle solution didn't occur to me 😅, it's so simple... And pretty!

**Comment by jni** [comment]
btw I'd love if you gave 3D the same treatment! 😅 I think/hope it's similarly easy to adapt the existing code...

**Comment by brisvag** [comment]
> But, a mode switch ComboBox would be great and there's lots of examples in the code. I would actually do a ComboBox rather than a checkbox in anticipation of having different depictions (lines, triangles, lines with arrowheads, ...)

Agreed! I do like the simple line for some use cases where they are really small and direction os obvious (I use it do display basis vectors of particles in space).

> btw I'd love if you gave 3D the same treatment! sweat_smile I think/hope it's similarly easy to adapt the existing code...

This shouldn't be too hard; 3D creates quads as well, it's just that it makes 2 of them rotated by 90 degrees from one another, so the same logic should apply there, just "doubled up".

**Comment by jules-vanaret** [comment]
Thank you both for your enthusiasm ! :)
After reading my initial message, I realize that I was not precise enough in saying that this hack natively works in 3D. Indeed, as @brisvag stated, vectors are currently plotted in 3D by copying their 2D version (obtained with the function `generate_vector_meshes_2D`, and rotating the copy by 90 degrees around the vector axis. Because my version only changes stuff inside `generate_vector_meshes_2D`, the mechanism naturally extends to 3D.

I'll submit a version with the combo box as soon as possible. Depending on how straightforward this would be, it would seem natural for me to immediately include a second combo box used to choose on which "end" the vectors are centered (e.g centered on their starting point or on their ending points, or even on the middle).
