### ISSUE TITLE
Add docs on how plugins should depend on `napari`

### ISSUE THREAD

**Issue by dstansby** [napari/napari#4287]
## 📚 Documentation
It would be good to document how plugins should depend on `napari`. My understanding from the zulip chat is not at all. Perhaps an entry on https://napari.org/plugins/first_plugin.html#update-setup-cfg explaining this and the reasons for it would be a good solution?

Additionally, if "don't depend on napari" is the advice, https://napari.org/plugins/first_plugin.html#update-setup-cfg should be updated to remove `napari` from `install_requires` in `setup.cfg`!

**Comment by tlambert03** [comment]
which zulip chat?? :)

You can absolutely depend on napari!  But it's important to us that dependence on napari isn't mandatory.   The "first plugin" example is a good case where you must depend on napari (if you want to provide a notification via napari's API).

**Comment by tlambert03** [comment]
ok... seeing it now.    Juan's comment here is true:

> The vision with plugins is actually that libraries should be able to provide a plugin without depending on napari.

but that doesn't mean that you _shouldn't_ depend on napari as a rule.

**Comment by dstansby** [comment]
> which zulip chat?? :)

I didn't know there were > 1, added a link to the top post!

> You can absolutely depend on napari! But it's important to us that dependence on napari isn't mandatory. The "first plugin" example is a good case where you must depend on napari (if you want to provide a notification via napari's API).

That makes sense. In that case, is there a minimum version of `napari` that should be pinned for a `npe2` plugin to work? From https://github.com/napari/napari/commit/87161a0c0c4b097c6ab46da72dd4616accafbac5, it looks like it might be `napari>=0.4.13`?

**Comment by tlambert03** [comment]
To summarize, for anyone finding this, the answer to the original question is: 

Depend on napari exactly as you would any other package: if your plugin directly imports napari, add it to your install_requires, as described in the "your first plugin" guide.  If your plugin requires a specific version of the napari API, go ahead and pin the napari version too.

Note that _internally_, napari tries hard not to _force_ a plugin to import napari unnecessarily (such that a package like scikit-image could conceivably be a napari plugin without depending on napari).

From zulip, it looks like the key confusion here was "how does an npe2-only plugin declare that it doesn't support napari <0.4.13".  And there isn't a great answer there.  This probably won't be an issue for long, since anyone installing a non-bound version of napari after Jan 17 2022 will get a version that supports npe2.  however, for plugin devs:
- one could add a note to the readme stating that it requires napari >=0.4.13 (actually, this should be added to the [cookiecutter](https://github.com/napari/cookiecutter-napari-plugin))
- one _could_ add napari >= 0.4.13 to their deps, but that's less than ideal if you don't really import napari at all.
- as @jni pointed out. we could add logic to `napari-plugin-engine` to warn if it detects an npe2 plugin in an environment with napari < 0.4.13.

**Comment by tlambert03** [comment]
> I didn't know there were > 1, added a link to the top post!

(sorry, I meant which thread 😄 )

**Comment by tlambert03** [comment]
If it's ok with you, I'm going to close this, since the documentation is correct.  will open issues at cookiecutter and npe1
