### ISSUE TITLE
PyQt5 ImportError

### ISSUE THREAD

**Issue by Jose-Verdu-Diaz** [napari/napari#4294]
## 🐛 Bug

I'm sorry this issue does not follow the bug template, as it doesn't fit it very well.

I'm working in an app that integrates napari. Yesterday everything worked fine, but today I'm getting the following error when trying to run it:

```shell
--> napari.run()

ImportError: /home/pepv/anaconda3/envs/hyperion/lib/python3.10/site-packages/../.././libQt5Core.so.5: version `Qt_5.15' not found (required by /home/pepv/anaconda3/envs/hyperion/lib/python3.10/site-packages/PyQt5/QtCore.abi3.so)]()
```

What is turning me crazy is the following: when running the code in an **existing jupyter notebook in particular**, the code runs just fine and napari is launched. Running it into any other new or existing jupyter notebook returns the same error, even if executing the `%gui qt5` magic command. I have already checked that kernels are the same.

I'm using a conda environment with the folloring Qt related packages:

```
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.1                   pypi_0    pypi
pyqtchart                 5.12            py310hfcd6d55_8    conda-forge
pyqtgraph                 0.12.3                   pypi_0    pypi
pyqtwebengine             5.12.1          py310hfcd6d55_8    conda-forge
qt                        5.12.9               ha98a1a1_5    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
```

I know this is a very broad and n00b-like issue, but it doesn't make any sense for me that the error appeared overnight nor being able to run napari only in a specific notebook.

## Edit

I created a new environment and reinstalled all dependencies. Napari seems to run as it used to. I still don't understand the source of the issue.

**Comment by tlambert03** [comment]
Hi @Jose-Verdu-Diaz, glad you were able to get it fixed.

> I created a new environment and reinstalled all dependencies. Napari seems to run as it used to. I still don't understand the source of the issue.

The issue was very likely the fact that you ended up with PyQt5 installed from _both_ conda (which unfortunately names it `pyqt`) and PyPI (which names in `pyqt5`).  

```
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
```

This dual installation can happen if you had pyqt already installed in the environment from some other dependency, and then you run `pip install napari[all]`.  Because pip doesn't recognize `pyqt` as fulfilling the pyqt5 requirement, it installs over it, and causes the binary incompatibility that you saw.  The fix is to create a new environment as you found.  But just a heads up that you might run into it again if you frequently mix conda and pip with packages that pull down pyqt
