### ISSUE TITLE
Consider making "reset view" center dims sliders too

### ISSUE THREAD

**Issue by jni** [napari/napari#4374]
## 🚀 Feature

Based on the discussion in #4361, we should consider a user-friendly way to reset the view so that all layers are visible. In the case where layers don't have the same extent across non-displayed (slider) dims, we should try to find areas of overlap. If those don't exist, then we should choose the place with the most cross-layer overlap.

## Motivation

@psobolewskiPhD has pointed out that in some situations, one adds a layer but the contents of the layer are invisible, because it does not have the same extent as the currently-visible layer in a non-displayed dim. This can be confusing for users.

## Pitch

When pressing the reset view ('home') button, we would adjust not only the zoom and center of the camera, but also the position of the dims slider, to view as much of the current layers as possible.

## Alternatives

Not so much an alternative as a complementary strategy, but we could flash the dims (at layer-add time) or somehow display a preview/minimap that shows where in the dims other layers live.

Additionally, the ability to reset sliders when pressing home could be a preference, in case others want to reset the camera view but not the sliders.

Finally, this could be a separate button rather than reuse of the home button.

## Additional context

See discussion in #4361 and #4350

**Comment by jni** [comment]
@sofroniewn @tlambert03 I wonder what you both think of this? Would be good to close or have consensus on moving forward with it!

**Comment by tlambert03** [comment]
Fine with me to explore.  Seems like it could get into magic territory somewhat easily, but i see the value if it works well

**Comment by psobolewskiPhD** [comment]
So I'm actually iffy on this, largely because of the difference between an *on-open* or *on-create* behavior and a *on-click* behavior. 

> @psobolewskiPhD has pointed out that in some situations, one adds a layer but the contents of the layer are invisible, because it does not have the same extent as the currently-visible layer in a non-displayed dim. This can be confusing for users.

I find it frustrating/confusing when some command/process seemingly fails, but with no feedback. In this context, changing an *on-click* action the user needs to already be aware to use to possibly fix this doesn't really change much, in my opinion. For me going "oh yea, click home dummy" isn't any different from "oh yea, change the slider position dummy". It's the realization I need to click something extra that's the problem! I do admit I'm slow and not the most savvy user, so maybe an edge case...

On the other hand, reseting zoom & centering is actually kinda hard to do manually, so `reset_view` is really clutch. (In contrast to changing stack slice, which is easy and precise.)
I think that zoom/centering issues are likely to be *much* more common than data-reduction/dim-length issues. I know I can easily get over-eager with zooming or accidental swipes... I guess I'm just hopeless.

**Comment by jni** [comment]
LOL Ok, fair points. Well, in that case, I'm going to close this and suggest that napari/npe2#153 is the right solution for you, @psobolewskiPhD, and if your slider reset plugin ends up being the most popular plugin on the hub, then we'll build the behaviour into main! 😂 Thanks for your patience!
