### ISSUE TITLE
Versioned API documentation: proposal

### ISSUE THREAD

**Issue by melissawm** [napari/napari#4593]
## 📚 Documentation

In order to enable version-specific API documentation for napari, we need a place to host and archive it. Previously, this was done on napari/napari.github.io, and the proposal here is to enable that again - but this may change the way the docs are deployed.

As of now, this is the process:
- A PR is merged to the napari/napari `main` branch;
- The [Build and Deploy docs](https://github.com/napari/napari/blob/main/.github/workflows/deploy_docs.yml) action is triggered, and pushes the built html artifacts to the gh-pages branch of napari/napari.github.io, **overwriting** whatever content is already there.

One way we could orchestrate this process is the following:
- A PR is merged to the napari/napari `main` branch;
- The [Build and Deploy docs](https://github.com/napari/napari/blob/main/.github/workflows/deploy_docs.yml) action is triggered, and pushes the built html artifacts to the `dev` subfolder of the gh-pages branch of napari/napari.github.io, keeping the existing deployments for other versions.

This of course implies changing the subfolder structure of the current documentation (released versions would show up under `napari.org/<version>`, the latest release under `napari.org/stable`, and the current version under development would show under `napari.org/dev` or something similar.) This could mean a few broken links especially if people are linking from other pages to the napari docs.

Another change this would imply is an extra action item on releases, to set up the symlink from stable to the newest release.

cc @jni @neuromusic @codemonkey800

**Comment by lucyleeow** [comment]
I've just been working on this for the plugin skan (with the idea that it could pretty much be copied over to napari since the napari theme is based off of pydata theme) - it's pretty much working see: https://lucyleeow.github.io/skan/dev/, relevant PRs: https://github.com/jni/skan/pull/175 and https://github.com/jni/skan/pull/173/files

> and pushes the built html artifacts to the dev subfolder of the gh-pages branch of napari/napari.github.io, keeping the existing deployments for other versions.

would this keep all artifacts from all pushes to main?

Another option we could do is to  github actions to save tag commits to a folder named as per the tag e.g.
```
      - name: Deploy stable docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: startsWith(env.TAG, 'v')
        with:
          branch: gh-pages
          folder: doc/_build/html
          target-folder: ${{ env.DOC_DIR }}
          clean: true
```
Another action item that may need to be added to release is to update the [version switcher json file](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/configuring.html#add-a-json-file-to-define-your-switcher-s-versions) (unless we can get it auto-populated by github actions).

Relevant scipy PR adding the version switcher: https://github.com/scipy/scipy/pull/15380/files
