### ISSUE TITLE
Issue with protobuf? Force to protobug==3.19 fixes it...

### ISSUE THREAD

**Issue by cnstt** [napari/napari#4603]
## 🐛 Bug

When trying to load certain widgets of my napari plugin, this error appears:
```
RuntimeError: Failed to import command at 'napari_deepfinder._cluster_widget:ClusterWidget': Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

## To Reproduce

1. Try to open certain napari plugin widgets (Segmentation and Annotation widgets of https://github.com/deep-finder/napari-deepfinder)

## Expected behavior

These widgets should open normally and open indeed normally when I force protobuf==3.19

## Environment

napari: 0.4.16
Platform: Linux-5.17.6-200.fc35.x86_64-x86_64-with-glibc2.34
System: Fedora Linux 35 (Workstation Edition)
Python: 3.9.13 (main, May 18 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.4
SciPy: 1.7.3
Dask: 2022.05.2
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 515.43.04
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- napari-deepfinder: 0.0.1
- napari-svg: 0.1.6
- scikit-image: 0.4.16

**Comment by psobolewskiPhD** [comment]
This isn't a napari issue. 
It's actually because that plugin has a requirement (deepfinder) that requires tensorflow, which requires protobuf.
I ran into this setting up a fresh tensorflow env.
The latest version of protobuf introduced a breaking change and any package that used it and didn't specify a max version ended up breaking—which happened to include TF.
I believe TF 2.9.1 has fixed the pinning to prevent this, but not other TF versions. So they will happily install latest protobuf which they are not actually compatible with.
do `pip show protobuf` and you will see probably 4.x.y, while protobuf 3.20.1 is the latest one that can work.

**Comment by cnstt** [comment]
Thanks a lot for this answer! I didn't know at all about this issue with tensorflow, I will update the requirements, thanks a lot!

**Comment by psobolewskiPhD** [comment]
It looks like a few other TF versions are also fixed now:
https://github.com/tensorflow/tensorflow/releases
Looking at the `deepfinder` requirements, it hard pins `tensorflow==2.6.0` so that's why you had the issue.
Reporting the issue there to make it 2.6.5 (the final release of TF 2.6) or to also pin protobuf is probably the best way forward.

**Comment by cnstt** [comment]
> Looking at the `deepfinder` requirements, it hard pins `tensorflow==2.6.0` so that's why you had the issue.

Don't worry I am using a custom branch (which will probably get merged soon) which uses more up to date packages and I just pushed an update to use tensorflow 2.8.2. So it works perfectly fine now ;)
