### ISSUE TITLE
Issues raised by @stefanv while trying out napari

### ISSUE THREAD

**Issue by jni** [napari/napari#467]
This is just a placeholder for @stefanv to provide complete examples after his talk at the M&M conference.

- running dask-distributed concurrently with %gui=qt in IPython doesn't work. In his words, "I can very reliably kill the kernel when using napari and dask together". The gui_qt() context manager does not suffer from this.
- our labels colormap shuffle doesn't reliably separate nearby labels (that one's on me).
- #424 
- "I just did an add_image, and the labels from the layer BELOW are displayed OVER it. Then re-ordering the layer (dragging it to top, then back down) fixes it."
- adding incorrectly-transposed points (34 3D points -> 3 34D points) crashes napari after two minutes. We might want to do some magic here, especially if we do `add_points(np.nonzero(arr))` — perhaps we can detect tuple as a type and transpose in that case?
- the name keyword argument for napari.view is broken
- in his environment, running napari from Jupyter and opening the IPython built in terminal resulted in a blank panel.
- ~~@sofroniewn's latest layout fix in #466 didn't work for him *apparently*~~

Incidentally, I advised him to go back to 82f7ceb. We might want to release 0.1.4 based on that commit while we iron out all the issues with the IPython slider.

I'll let him use this list to create fleshed out issues with reproducible examples.

**Comment by stefanv** [comment]
Correction on one of my earlier observations: the fix in #466 worked.

**Comment by stefanv** [comment]
@jni I presume many of these can be closed by now?

**Comment by sofroniewn** [comment]
Some but not all, I can go through and call out in more detail / create new issues for the critical ones

**Comment by sofroniewn** [comment]
Looking over this I think the 3 remaining issues are:

> - running dask-distributed concurrently with %gui=qt in IPython doesn't work. In his words, "I can very reliably kill the kernel when using napari and dask together". The gui_qt() context manager does not suffer from this.
> - our labels colormap shuffle doesn't reliably separate nearby labels (that one's on me).
> - adding incorrectly-transposed points (34 3D points -> 3 34D points) crashes napari after two minutes. We might want to do some magic here, especially if we do add_points(np.nonzero(arr)) — perhaps we can detect tuple as a type and transpose in that case?

I will make a separate issue for the first one #679

For our labels colormap - that is likely due to the `num_colors` setting, increasing that will increase the separation, but will make things run slower. We have #204 to discuss improve the speed, so I will cross post this there too.

For the points one - we have now #480 which discusses some stuff on sizes - so I will cross post this comment there, though maybe it deserves it's own separate issue too

I will close this issue now though as I think further discussion can happen on the other issues and we have captured the major feedback, which was on a much older version

**Comment by jni** [comment]
@sofroniewn thanks for the triaging! I think the points transpose problem does require its own issue. I'll make it even though @stefanv promised to make it back in the day. ;) =P
