### ISSUE TITLE
napari design suggestions

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#469]
## ❓ Questions and Help

napari has the opportunity to get some design input from a couple designers at CZI. I'm creating this issue for us to discuss current design issues, suggestions, feedback, etc.

**Comment by kevinyamauchi** [comment]
What an awesome opportunity! I have listed a few things below that I think we could use some feedback on:

- **Usage pattern for the sidebars**: Currently, we have a sidebar on either side of the the canvas and we are not consistent in how each layer utilizes the UI elements in each one. For example, should one sidebar be dedicated for parameters that are applied to the entire layer and the other sidebar is for adjusting parameters that can be specific to elements in a layer? 
- **Labeling for the dim sliders**:  the dim sliders are confusing because don't have any labels. I think it would be useful to get some advice on the best way to label them (e.g., where to denote the axis, should we use ticks)
- **Standardization of UI elements**: I think it would be useful to set some "rules" for when to use what type of UI element (e.g., when to use a dropdown vs. radio buttons or slider vs. text box).

**Comment by sofroniewn** [comment]
@liaprins - has completed her design audit of napari and produced a truly incredible document with the feedback, included here as a pdf.

[Napari design audit.pdf](https://github.com/napari/napari/files/3598847/Napari.design.audit.pdf)

@kne42, @freeman-lab and I went over some of the main takeaways from the report today with Lia and we'll be going through it in more detail over the next week or two as we think about next steps etc. We can talk about it at our next team meeting and maybe we can get @liaprins to present on it next time she's at Biohub on a Thursday, as there's a lot to digest, but I encourage everyone (@royerloic @jni @kevinyamauchi @AhmetCanSolak @bryantChhun) to take a look.

I think we can then use a combination of discussion on this issue / creating new issues as needed to work through the feedback. During the meeting we had some good ideas about ways to unify the layer control buttons / sliders on the left and the layer properties that appear when you double click on a layer that I will create a new issue to discuss.

Finally I'll add that I'm incredibly excited to have this sort of feedback from a design expert as it can be rare to get it in a lot of academic / open-source projects and I think will make an enormous difference to the usability and ultimate success of napari.

**Comment by liaprins-czi** [comment]
@liaprins-czi

**Comment by liaprins** [comment]
Mentioning my CZI Github, so I can follow from it @liaprins-czi

**Comment by sofroniewn** [comment]
I'm closing this issue now. The vast majority of the changes from the design audit have been implemented. There are still some more minor ones that havn't, like improvements to a couple of the icons, but it will probably be worth doing a new design audit again soon. Particularly after we get all the dockable widgets and context menu stuff in, and we can always refer back to this issue at that point in time if needed
