### ISSUE TITLE
Hosted docs

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#473]
## 📚 Documentation

I think now would be a good time for us to start hosting our API docs on a public site. I view this as complimentary to, but connected to our current [tutorials page](https://napari.github.io/napari-tutorials/)

Using readthedocs is fine with me, I don't know if CZI will pay to remove adds, but that would be reasonable. Alternatively there is https://github.com/freeman-lab/minidocs made by our very own @freeman-lab or direct integration with our tutorials page.

Thoughts @kne42 @AhmetCanSolak @jni?

**Comment by sofroniewn** [comment]
There was a recent [discussion around hosted docs on twitter](https://twitter.com/choldgraf/status/1158848109465624576) that might be of interest too.

**Comment by jni** [comment]
I use [doctr](https://github.com/drdoctr/doctr) for the skan docs and really like it:

https://jni.github.io/skan/

That would be my recommendation. The only thing I haven't set up yet is multiple hosted versions, but I think that's not hard to do.

**Comment by kne42** [comment]
`doctr` looks super awesome but unfortunately we do not use travis, although i suppose we could set it up for this purpose. i am definitely in favor of self-hosting our docs if possible :)

it's also not terribly difficult to replicate this functionality ourselves, see [how scikit-image does it](https://github.com/scikit-image/scikit-image/blob/master/tools/travis/deploy_docs.sh)

since there are a number of issues with our docs' formatting and content, i would advise focusing on that prior to hosting them

sidenote: @jni are you the one who owns napari.org? we'll need your help to properly set up the GH pages on that domain :)

**Comment by jni** [comment]
@kne42 Is Doctr really travis only? Could we not adapt it to other CIs? And anyway, as you mention, we can have Travis just for docs, I don't think that's a big deal.

Yes I own napari.org, happy to change that to our gh-pages site once it's up and running!

**Comment by kne42** [comment]
@jni Yes, I inspected the code and it's only compatible with travis due to its reliance on its environment variables. We may define these in our config as a hack but that's not guaranteed to work.
