### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by constantinpape** [napari/napari#476]
## 🚀 Feature

Add benchmarks to monitor the performance of napari.

## Motivation

Keep track of performance to catch regressions and judge performance improvements for planned features like lazy rendering, better tiling or caching.
Moving the discussion from #318 here.

## Pitch

Benchmarks should be easy to run, maybe be part of the CLI and should cover
relevant use-cases like 2d/3d image rendering, pyramids, lazy sources and volume rendering.
Could also consider using [asv](https://github.com/airspeed-velocity/asv) for monitoring the performance.

## Additional context

cc @sofroniewn @bryantChhun

**Comment by sofroniewn** [comment]
Thanks for creating this issue @constantinpape. In the long run I'd like us to have full coverage for all our layer types for the benchmarks - shapes / vectors / points can all run into problems with 1000s or millions of objects depending on the details and we will want to understand those limits.

I also see a couple different things we'll want to measure.

- Each layer has a `.refresh` method that gets called whenever anything has changed that will effect what is displayed on the screen. This can trigger the thumbnail generation machinery which we want to make sure isn't slowing things down.

- There's also machinery for the dimensions - so going from looking at one z-plane to another

- There's just a camera zoom in / zoom out. This is done with vispy's machinery but probably good for us to monitor too. (For the pyramid layer it is more complex, so also good to have this in here).

- There's a `get_value` function that is used for cursor hovering - this is fast for image-like layers as you just have to grab the value of the image at the coordinate where we are hovering, but it can be slow for the shapes layer where you have to check is this coordinate inside any of the shapes.

- Changing the `layer.data` property, this was explored in #465 as it was very slow, and ultimately a work around was found by directly setting the vispy data property.

@jni @royerloic are there other high priority things we want to benchmark?

As to how to do this, I like something that integrates with our CI, but I'm very open to approaches / implementations. Maybe @kne42 has some ideas? I do think vispy does some benchmarking, so getting inspired from them makes sense, but I havn't looked into their approach

**Comment by jni** [comment]
> I like something that integrates with our CI, but I'm very open to approaches / implementations.

In the [original asv talk for SciPy 2014](https://www.youtube.com/watch?v=OsxJ5O6h8s0) (which is highly recommended), Michael Droetboom cautions against benchmarking in standard CI, because these are shared-CPU VMs where you have no guarantees about the load on the machine as you run your benchmarks, so you can get wildly diverging values between runs. Many SciPy projects run on pandas.pydata.org/speed, which is amazingly a single machine living in Tom Augspurger's basement; we lost a couple of weeks of benchmarking when his three-year old unplugged the machine undetected. :joy: Providing a dedicated machine for benchmarking would be a valuable contribution that CZI or CZ Biohub could make! ;) Benchmarks are relatively rare so the machine can be shared by many projects.

> I do think vispy does some benchmarking

We do so at scikit-image also, and @hmaarrfk wrote up a great guide on how to write and run benchmarks here: https://scikit-image.org/docs/dev/contribute.html#benchmarks

**Comment by hmaarrfk** [comment]
Sorry to chime in, but I would suggest defining a target image size and resolution you want to work with and data type. When developing certain algorithms for numpy, we found that certain things that did not sclae well for large images were very fast for small images and datasets. This often had to do with memory allocation and shuffling data around. Also, I would suggest maybe being a little forward thinking in the CPU you want to target. If the first release of napari will be in 202X, then maybe you can target a more modern processor than what manylinux targets.

**Comment by sofroniewn** [comment]
@jni - i'll look into what resources CZI might be able to provide for a "benchmarking machine"

@hmaarrfk thanks for weighing in - benchmarking for different target image sizes makes a lot of sense, there are different use cases that have different sizes, and different latencies maybe tolerable depending on use case. In general we'll want to understand and measure across the range that is meaningful to us

**Comment by kne42** [comment]
@jni Resources for the machine are not a problem. We mostly just want to figure out right now whether we want a physical machine or an ec2 instance.

**Comment by jni** [comment]
@kne42 as mentioned above, cloud vCPUs are not a good fit for benchmarking, because they might be shared across many applications. A benchmarking machine should be running nothing but the benchmarks.

**Comment by kne42** [comment]
@jni according to my colleagues, AWS offers [bare metal instances](https://aws.amazon.com/blogs/aws/new-amazon-ec2-bare-metal-instances-with-direct-access-to-hardware/), which offer direct access to the hardware without all of the virtualization on top

**Comment by jni** [comment]
Ah, thanks. I had a vague memory of this but I couldn't find information on that in the [EC2 instance types](https://aws.amazon.com/ec2/instance-types/), so I thought I must have imagined it!

**Comment by jni** [comment]
@sofroniewn I've just been sitting with my colleague @VolkerH, who (the good news) has effectively reimplemented a multispectral viewer of his in a few lines of napari. :tada: The bad news is that he's running into #569 and also drawing lines is quite sluggish. So those would be two things to benchmark ASAP. I imagine that model benchmarks and profiling would be possible here — set the mode to paint labels / draw lines and then trigger some mouse drag events?

I expect that the biggest issue with labels is my conversion to random floats. Unfortunately I think the fix there is to use the neuroglancer trick of (a) *viewing* the data as (nonsense) floats rather than *computing* "maximally dispersed" floats, and (b) using a custom colormapping shader to view those floats. ie not a trivial fix, and one that should go in VisPy. See #204. 

I can also try my hand at this thanks to your example benchmarks, but I have a few things on my plate to do first so just thought I'd report it for now.

**Comment by sofroniewn** [comment]
thanks for the heads up @jni - i'm happy to add some points / labels benchmarks (though adding them is just the beginning!!)

**Comment by sofroniewn** [comment]
We've now added benchmarking using [asv](https://asv.readthedocs.io/en/stable/using.html). There are definitely more benchmarks to add, but I am going to close this issue in favor of raising specific issues about particular performance issues and benchmarks we need to add rather than centralizing them all here.
