### ISSUE TITLE
Installation page dropdowns broken - makes it seem like instructions are missing

### ISSUE THREAD

**Issue by ianhi** [napari/napari#4782]
## 📚 Documentation

On the installation tutorial (https://napari.org/tutorials/fundamentals/installation.html) it looks like the code to install is missing

![image](https://user-images.githubusercontent.com/10111092/177401469-98cd97cf-fd16-4cb4-943b-ab6b10feb8a6.png)

on closer inspection these seem to be dropdowns that aren't folding properly. However, I only noticed that after looking a the source.

These should either be made to fold properly (and given a caret as indication that they can be expanded) or should just be permanent text.

**Comment by DragaDoncila** [comment]
Hi @ianhi thank you for raising this! We've noticed this and have an issue open tracking this problem over on the [napari-sphinx-theme](https://github.com/napari/napari-sphinx-theme/issues/99) repo (as it is an issue with the theme rather than the docs themselves). Totally agree it's super confusing and we're in the process of fixing. If it's ok with you I'll close this issue in favor of the existing issue on the other repo. 

Please don't hesitate to reopen, or to comment on the linked issue if you think there's something not being captured!
