### ISSUE TITLE
Deprecate add_image(multichannel=True)

### ISSUE THREAD

**Issue by jni** [napari/napari#481]
I originally proposed that we use `multichannel=` as a keyword argument for an RGB image layer to match scikit-image. However, in scikit-image, the meaning is more broad: a multichannel array is one where the last dimension is not a spatial dimension but rather different channels of information for the same spatial coordinates. In napari, we use it only to *specifically* mean RGB, so it's a bit of a misnomer.

I instead propose that we deprecate the RGB image layer *or* make it a different, separate layer. When `multichannel` is passed to add_image, what I suggest we do instead is split the channels axis into separate layers, with the mode automatically set to "additive", and different primary colors selected as the colormaps.

There's a lot of API surface to consider here, though. First, this would change the return signature, because we would need to return multiple layers instead of one. (One possible solution here that I haven't explored is the Composite pattern, so that a collection of layers can behave as a single layer.) So perhaps a different method to `add_image` needs to be created (e.g. `add_channels`).

Additionally, @sofroniewn raised the point that RGBA gives us the possibility of pixel-wise transparency, which would be hard to replicate without the RGBA vispy node. I don't have a good solution for this yet but I think we should think hard about it: perhaps something like `alpha_mask=` would be a good parameter to expose for *all* images, not just RGBA ones.

**Comment by sofroniewn** [comment]
@jni I like the concept of `add_channels` that is a convenience wrapper around multiple calls to `add_image` that allows you to add and `rgb` image as 3 color channels, or would allow you have add a `C x ....` array and expand along that C dimension with a provided or default list of colormaps.

I'm really not sure about the `rgba` support. unfortunately the `alpha_mask` is hard as that will require weird interactions with vispy (i.e. generating an rgba image even when we just want to use colormaps!!). i can poke around vispy a bit more, but there might not be a clean way to support this.

**Comment by sofroniewn** [comment]
@royerloic @jni @kevinyamauchi have we had further thoughts on this one? I'm still leaning towards dropping support from `add_image`, providing a convenience method `add_channels` that makes multiple calls to `add_image` looping over a list of colormaps when provided an axis to expand over, and doing some clever guessing / looking at metadata to decide is someone drags / drops an image if its rgb / rgba and if and how we should use `add_channels`.

It would also be nice to have to option to `expand_channels` or `group_channels` that would in the former case allow you to take a single nD image layer and expand along one of the axes to generate a collection of (n-1)D image layers all added to the viewer with different colormaps, or to take a selection of nD image layers and end up with a single (n+1)D image layer with one colormap. These operations would be inverses of each other and mirror the calls to `add_channels` and `add_image` respectively.

What do you both think? I'd like to settle this sooner rather than later, as I want us to lock down (at least for a little) some of the basic api fairly soon

**Comment by sofroniewn** [comment]
This has been addressed by #528
