### ISSUE TITLE
Test with make_napari_viewer suddenly break in github CI

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4876]
## 🐛 Bug
Hi all,

I have again a plugin where suddenly tests break in github CI case they use `make_napari_viewer()`. Locally, tests pass.

The error in very short is:

```
  src/napari_simpleitk_image_processing/_tests/test_function.py::test_something PASSED [ 16%]
  src/napari_simpleitk_image_processing/_tests/test_function.py::test_statistics PASSED [ 33%]
  src/napari_simpleitk_image_processing/_tests/test_function.py::test_statistics_with_viewer Fatal Python error: Aborted
```

```
    File "/home/runner/work/napari-simpleitk-image-processing/napari-simpleitk-image-processing/.tox/py39-linux/lib/python3.9/site-packages/_pytest/config/__init__.py", line 187 in console_main
    File "/home/runner/work/napari-simpleitk-image-processing/napari-simpleitk-image-processing/.tox/py39-linux/bin/pytest", line 8 in <module>
  Error: ERROR: InvocationError for command /home/runner/work/napari-simpleitk-image-processing/napari-simpleitk-image-processing/.tox/py39-linux/bin/pytest -v --color=yes --cov=napari_simpleitk_image_processing --cov-report=xml (exited with code -6 (SIGABRT)) (exited with code -6)
```

[more details](https://github.com/haesleinhuepf/napari-simpleitk-image-processing/runs/7554545218?check_suite_focus=true#step:7:69).

Maybe related:
#4797 

Any hint is welcome.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.15
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.8.1
Dask: 2022.7.1
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 - Build 30.0.101.1029
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- RedLionfish: 0.6
- bfio: 2.3.0
- console: 0.0.4
- napari-assistant: 0.3.10
- napari-curtain: 0.1.1
- napari-noise2self-adhoc2: 0.0.1
- napari-simpleitk-image-processing: 0.4.0
- napari-time-slicer: 0.4.9
- napari-tools-menu: 0.1.15
- napari-workflow-inspector: 0.2.2
- napari_skimage_regionprops1: 0.5.3
- napari_skimage_regionprops2: 0.5.3
- ome-types: 0.3.0
- scikit-image: 0.4.15
- svg: 0.1.6
```

 - Any other relevant information:

**Comment by Czaki** [comment]
hi @haesleinhuepf, The problem that you meet is connected with removing x11-utils from the default ubuntu runner host image. Because of the lack of this package, QApplication initialization fails that causing a visible stack trace. 

It was first reported here https://github.com/napari/napari/pull/4696#issuecomment-1182914689 with an explanation here https://github.com/napari/napari/pull/4696#issuecomment-1182988080 and fixed by @brisvag PR here https://github.com/tlambert03/setup-qt-libs/pull/57 (this paragraph is only to explain how and where it has handled by napari itself). 

So to fix this error you need to add `x11-utils` to your list of installed libraries. To avoid such problems in the future you may decide to stop managing the list of qt required libraries on your own side and switch to `tlambert03/setup-qt-libs` by adding this action in your YAML files:
```YAML
steps:
...
- uses: tlambert03/setup-qt-libs@v1
```

What is recommended for the plugin testing.

**Comment by brisvag** [comment]
I suggest we leave this open for some time so it's easier to find :)

**Comment by Czaki** [comment]
One additional place to visit in the future if a similar error happens. The pytest-qt has a troubleshooting section in their docs, that should contain an updated list of libs https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions

**Comment by haesleinhuepf** [comment]
Shall we add this link to the github-ci config in the cookiecutter template?

**Comment by Czaki** [comment]
I do not understand which link you mean? 
But currently cookiecutter template is using `tlambert03/setup-qt-libs@v1`

https://github.com/napari/cookiecutter-napari-plugin/blob/main/%7B%7Bcookiecutter.plugin_name%7D%7D/.github/workflows/test_and_deploy.yml#L37

**Comment by haesleinhuepf** [comment]
I've just tested your proposal @Czaki [here](https://github.com/haesleinhuepf/napari-simpleitk-image-processing/pull/12) and it works like a charm! Thanks for the instant feedback&support!

And how about adding https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions to the cookiecutter template?

**Comment by Czaki** [comment]
but what will be profit of this link if cookie-cutter already use @tlambert03 action for setup qt required libs, so troubleshooting is done on side of this action. Or you mean to add it somewhere in documentation?

**Comment by haesleinhuepf** [comment]
Your words @Czaki : 

> One additional place to visit in the future if a similar error happens.

**Comment by Czaki** [comment]
Yes, but I see that in your project, you use your own management list of libraries to be installed. This whole section is the result of my contribution to `pytest-qt` docs.  Looking at history, I assume that it will be as up-to-date as `tlambert03/setup-qt-libs` action. So if someone uses this action this webpage will not contain any helpful information. But if someone uses a self-curated libs list (that is not recommended), checking on this page should be faster than searching in napari issues. 

I love freedom that is given by python, but If you remember discussion in Twitter Bioimage Analysis people are complaining about this freedom, because early adapters do not know what to do, what option is easiest and there are to many things to read. And people feel lost or follow some outdated tutorials that lead to problematic solutions.

**Comment by kcpevey** [comment]
I can't quite tell if there is still an action item here. Can this be closed @Czaki / @haesleinhuepf ?

**Comment by Czaki** [comment]
The #5373 is partially related to this topic. It will allow finding all problematic places in the napari codebase.

**Comment by jni** [comment]
I think this can be closed, but @haesleinhuepf feel free to correct me. 😊
