### ISSUE TITLE
Toggling from 3D → 2D crashes napari eventually (in presence of visible surfaces layer)

### ISSUE THREAD

**Issue by kandarpksk** [napari/napari#4880]
## 🐛 Bug

Toggling from 3D → 2D crashes napari immediately or after scrubbing

## To Reproduce

1. Install the napari-bio-sample-data plugin
2. Open the sample image '3D nuclei' from the plugin
3. Switch from 2D → 3D → 2D (and napari will likely crash)
4. If napari doesn't crash, the image previews won't look right, and scrubbing will cause it to crash soon enough

The terminal only shows that there's a segfault. Here's a link to the error reported by macOS: https://docs.google.com/document/d/1NWTL0edbX0hpWUw7XkR2W5Ajn_tnsuSv69iEVQPRS1Y/edit?usp=sharing.

## Expected behavior

I expected to switch to 2D mode and be able to continue using napari.

## Environment

> napari: 0.4.16
> Platform: macOS-12.4-arm64-arm-64bit
> System: MacOS 12.4
> Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) [Clang 13.0.1 ]
> Qt: 5.15.4
> PyQt5: 5.15.7
> NumPy: 1.23.1
> SciPy: 1.8.1
> Dask: 2022.7.1
> VisPy: 0.10.0
> 
> OpenGL:
> - GL version: 2.1 Metal - 76.3
> - MAX_TEXTURE_SIZE: 16384
> 
> Screens:
> - screen 1: resolution 1800x1169, scale 2.0
> - screen 2: resolution 3440x1440, scale 1.0
> 
> Plugins:
> - console: 0.0.4
> - napari-bio-sample-data: 0.0.4
> - napari-svg: 0.1.6
> - scikit-image: 0.4.16

**Comment by psobolewskiPhD** [comment]
I can reproduce this on my M1 mac (12.4, dev branch of napari).
3d mode works but then going back to 2d yields:
`fish: Job 1, 'napari' terminated by signal SIGSEGV (Address boundary error)`

**Comment by liu-ziyang** [comment]
can also confirm I can reproduce this. I also have more information:

I played around with this data set, there are three layers:
The image layer, a label layer, and a surface layer.

the problem seems to be with the surface layer. when the surface layer is dropped or hidden, any toggling between 3D and 2D does not seem to be problematic. I also noticed the surface layer behaves strangely when being loaded at the beginning in 2D mode. 

The root of the problem seems to be with converting the 3D surface layer back to 2D. I am not sure if this problem is specific to this dataset though

**Comment by psobolewskiPhD** [comment]
> the problem seems to be with the surface layer.

Yup, I can confirm this on both live and main.

**Comment by psobolewskiPhD** [comment]
Here's a simple reproducer:
```
import napari
from napari.utils.colormaps import label_colormap

import numpy as np

vertices = np.array([[0, 0], [0, 20], [10, 0], [10, 10]])
faces = np.array([[0, 1, 2], [1, 2, 3]])
values = np.linspace(0, 1, len(vertices))
surface = (vertices, faces, values)

viewer = napari.view_surface(surface, colormap="red", ndisplay=3)  # add the surface
```
Toggle back to 2D.


Edit: If you toggle the visibility of the layer then the crash doesn't occur.
Here's the top of the macOS crash report (macOS 12.6, arm64)
```
Process:               python3.10 [34952]
Path:                  /Users/USER/*/python3.10
Identifier:            python3.10
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        fish [31007]
Responsible:           Terminal [31005]
User ID:               501

Date/Time:             2022-10-05 11:33:14.9167 +0200
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        4AEACC27-FA51-D3CF-97AE-7062E0B50CC2

Sleep/Wake UUID:       5502BDB7-3DAE-4EF8-BD4C-B1E2065431C0

Time Awake Since Boot: 220000 seconds
Time Since Wake:       1310 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [34952]

VM Region Info: 0 is not in any region.  Bytes before following region: 4309385216
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100dc0000-101094000    [ 2896K] r-x/r-x SM=COW  .../*/python3.10
```
Here's the macOS crash report:
https://gist.github.com/psobolewskiPhD/098f6f31a4dc0fd60e7cc86b648de9b5

Edit2: I get the same behavior on python 3.9

**Comment by andy-sweet** [comment]
I was able to reproduce this on my Intel mac.

I did some debugging mostly by removing/commenting code to try to identify what is causing this since the crash report could be caused by various things.

I found that commenting out the call to `VispySurfaceLayer._on_shading_change` in `VispySurfaceLayer._on_data_change` prevented the crash from occurring. In the reproducing example above `Surface.shading` will be `'flat'`, but with 2D display that is ignored. Then we change to 3D, that is used and passed through to vispy. But when we change back to 2D we [only try to change the vispy node's shading back to `None`](https://github.com/napari/napari/blob/9eeab55ac5cb8128c5ed91549ea010aeefd87736/napari/_vispy/layers/surface.py#L71), which may not actually happen.

I was pretty confident that always setting it `None` (e.g. by moving that outside of the `try` block) would fix this bug, but it didn't.

So I'm calling on @brisvag and @alisterburt for some more expertise here, as this might be related to some of the issues described in #3475 and #3494. If one of you or someone else takes over, feel free to reassign this issue.

**Comment by brisvag** [comment]
Uhm... The code above from @psobolewskiPhD does not cause any issues on my machine, even switching between 2d and 3d repeatedly.

Seeing how everyone having the issue is on a mac, and I'm not, my first thought is a problem  similar to what I think @alisterburt had in the past, where an uninitialized value in the shader had different values depending on the platform.

Can somone else not on a mac test this?

@psobolewskiPhD thanks for the report, but I have no clue how to even begin reading it xD

**Comment by psobolewskiPhD** [comment]
This was fixed by: https://github.com/napari/napari/pull/5642
