### ISSUE TITLE
master broken: missing node argument after automatic layer view creation

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#492]
## 🐛 Bug

All the examples on Master are currently broken - the error I get on `add_image.py` initially is 

```python
  File "/Users/nicholassofroniew/Github/napari/napari/_qt/qt_viewer.py", line 149, in _add_layer
    vispy_layer = VispyBaseLayer(layer)
  File "/Users/nicholassofroniew/Github/napari/napari/util/layer_view.py", line 52, in __new__
    return super().__new__(cls)
TypeError: Can't instantiate abstract class VispyBaseLayer with abstract methods _on_data_change
```

if i make this no longer an abstract method, the error i get is  

```python
  File "/Users/nicholassofroniew/Github/napari/napari/_qt/qt_viewer.py", line 149, in _add_layer
    vispy_layer = VispyBaseLayer(layer)
TypeError: __init__() missing 1 required positional argument: 'node'
```
which is because the `VispyBaseLayer` takes two arguments the layer and the node which doesn't seem to work out well with the approach of #488. We could drop the `node` argument and append it inside the layer specific `Vispy` views, but I defer to @kne42 on how to fix this. 

Unfortunately this was not caught by any of our existing tests, which I find really confusing (they all pass locally for me even though I get this error). Maybe @kne42 can also figure out some tests to add that will catch this too!

**Comment by kne42** [comment]
@sofroniewn Oops, sorry about that.

I was able to fix the error, which was due to the files not being run and therefore not registered. It's at [`kne42:layerview-import-fix`](https://github.com/kne42/napari/tree/layerview-import-fix) ([commit](https://github.com/kne42/napari/commit/26dd02f30b35ab7dbe6f0b0f87cd52a20db424d3)).

However, I discovered that due to some weird things that `PySide2` is doing with metaclasses, you cannot actually take arguments in the class definition line 😞. It does work with `PyQt5` though.

So to fix that we can do one of the following:
1. revert the entirety of #488
2. revert part of #488 with regards to the Qt files and keep it for the VisPy ones
3. refactor the Qt files such that they wrap the Qt objects instead of inheriting from them

I'm going to be on PTO for the rest of the day so if you want a quick fix you should go with 1)

**Comment by sofroniewn** [comment]
ok let's revert #488, merge, and then revisit early next week

**Comment by sofroniewn** [comment]
maybe #2) reverting just for qt is best if not too hard
