### ISSUE TITLE
Key-bindings stop working after increasing/decreasing label number

### ISSUE THREAD

**Issue by marshuang80** [napari/napari#500]
## 🐛 Bug

After clicking the "+" or "-" button for changing the labels, all key-bindings stop working until the user clicks somewhere else on the viewer. 

## To Reproduce

1. Increment label number 
2. Notice the highlighted label number
3. Try any keybinding
4. Click somewhere else on the viewer (empty parts of a layer)
5. Notice that the label number isn't highlighted anymore
6. Try keybinding again

## Expected behavior
Key-binding should work as usual after increasing label number. 

## Environment

 - napari Version (e.g., 1.1):
 - Ubuntu 18.04 LTS
 - Python version: 3.7

## Additional context

![Screenshot from 2019-08-30 10-49-11](https://user-images.githubusercontent.com/15271135/64041829-4e4e0b00-cb15-11e9-8792-ec9bae5fa327.png)

**Comment by sofroniewn** [comment]
@marshuang80 I've just tried reproducing this on the master version of napari, and while the selection of the new label # happens for me, all the keybindings still work though. This may have been fixed with #472 - and you should update your napari to see if it is still an issue.

There could also be a difference in how some of the focus stuff is handled across platforms (i'm on a mac), but first let's see how it goes for you with the latest version of napari

**Comment by sofroniewn** [comment]
It seems like this was not actually fully fixed but I have found a solution in #536 which uses 
`self.selectionSpinBox.setKeyboardTracking(False)` and the clearing and reseting focus in the callback. This will be fixed once that merges

**Comment by sofroniewn** [comment]
This has now been fixed in #536
