### ISSUE TITLE
keycombo preview in settings does not respect platform

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#5047]
## 🐛 Bug

Editing a keyboard shortcut in the preferences dialog shows 'Control' while editing then resolves to the platform specific '⌘' when the combo has been entered -> it would be nice if what was seen when editing already matched the platform specific keys

## To Reproduce

1. open napari on macos
2. preferences -> shortcuts
3. edit keybinding to something using ⌘ key

**Comment by Carreau** [comment]
See https://github.com/napari/napari/pull/5064 that should fix it.

**Comment by psobolewskiPhD** [comment]
Bumping this. As of #5103 the platform specific keybindings don't show at all on macOS 12.6:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/76622105/201518959-f637422e-4457-4f6f-bd69-751b36f14c15.png">

To make it more confusing, everywhere  `^` is shown, `command` actually works for the keybind, so it is just a display issue.
This includes the splash screen:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/76622105/201518999-c3ebc8e4-cb44-43b6-8836-93f073cdb2c6.png">

**Comment by psobolewskiPhD** [comment]
Ok, it seems like the keybind Meta<->Ctrl on macOS that Qt does is not properly accounted for in the settings.
When setting a new keybind in Preferences, say pressing `command-option-m` it shows `Ctrl-Alt-M` (command is read as control, which is what Qt does by default) and then when confirmed shows `⌘⎇M`, because napari displays `⌘` for Ctrl on macOS. **BUT** that keybind doesn't work, because it actually **is** binding `Ctrl⎇M` and only making a visual substitution and the swap isn't restored when trying to use the keybind.

This would be consistent for the display issue above: the keybinds display as `^` but work when pressing `⌘` because `^` is shown when Meta is bound and Meta is `⌘` on macOS. So in this case, things work, but the the swap was not accounted for properly in the visual.

**Comment by psobolewskiPhD** [comment]
Yeah, this is a different issue. I will make a new issue.
