### ISSUE TITLE
When starting the console, the terminal should have the focus

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5166]
## 🚀 Feature

After starting the console in napari, the keyboard-focus should be in the console window.

## Motivation

Whenever I start the console, I start typing and depending on which key I hit first, random stuff happens in napari. The reason is that the keyboard focus is not set to the console.

## Pitch

You can spare confusion in hundreds or thousands of napari users by setting the focus to the terminal after opening it.

**Comment by aganders3** [comment]
I agree this would be a nice behavior change.

The way I can see to do this right now involves changing [`toggle_console_visibility` here](https://github.com/napari/napari/blob/28e203c22d74b2e5642070ab71f1149dc7c74846/napari/_qt/qt_viewer.py#L906) like so:

```python
...
        if viz:
            self.dockConsole.raise_()
            self.console._control.setFocus()
...
```

I don't really like this though because it's reaching _through_ `napari_console.QtConsole` into `qtconsole` to reach `_control`.

Without going all the way upstream to `qtconsole` I think it might make more sense to add `self.setFocusProxy(self._control)` in napari-console and use `self.console.setFocus()` in napari `toggle_console_visibility`.

Maybe I am overthinking this, so please forgive my inexperience with the code if this is way off base!
