### ISSUE TITLE
Docs: improve discoverability of keyboard shortcuts

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#5172]
Related to https://github.com/napari/napari/pull/5155, it would also be better for the discoverability of shortcuts if the docs were substantially improved. 

There is some information here, but it's not very readable: https://napari.org/stable/guides/preferences.html?highlight=shortcuts#shortcuts

_Originally posted by @GenevieveBuckley in https://github.com/napari/napari/issues/5155#issuecomment-1267704686_

**Comment by Carreau** [comment]
Personally I don't think that docs is the best place t find keyboard shortcuts, especially since they can be platform specific or depends on what is focused, or what plugin is installed. I think we need to be a better job of showing them in the UI, and the docs should likely say: go to napari help menu and click on show-shortcuts to see all your current shortcuts.

**Comment by GenevieveBuckley** [comment]
This is a duplicate of https://github.com/napari/docs/issues/13, closing
