### ISSUE TITLE
Selecting points with unsortable features raises an error

### ISSUE THREAD

**Issue by brisvag** [napari/napari#5174]
## 🐛 Bug

An error is raised if one tries to select multiple points on a layer that has a feature column whose objects do not support ordering.

## To Reproduce

Create a simple layer like this:

```py
import napari
import numpy as np

class A:
    pass

v = napari.Viewer()
pl = v.add_points(np.array([[0, 0], [1, 1]]), features={'a': [A(), A()]})
```

Then try to select both points manually. This error is raised:

```py
File ~/git/napari/napari/layers/points/points.py:1245, in Points.selected_data(self, selected_data)
   1241 for k, v in self.properties.items():
   1242     # pandas uses `object` as dtype for strings by default, which
   1243     # combined with the axis argument breaks np.unique
   1244     axis = 0 if v.ndim > 1 else None
-> 1245     properties[k] = np.unique(v[index], axis=axis)
   1247 n_unique_properties = np.array([len(v) for v in properties.values()])
   1248 if np.all(n_unique_properties == 1):

File <__array_function__ internals>:180, in unique(*args, **kwargs)

File ~/venv/napari/lib/python3.10/site-packages/numpy/lib/arraysetops.py:272, in unique(ar, return_index, return_inverse, return_counts, axis)
    270 ar = np.asanyarray(ar)
    271 if axis is None:
--> 272     ret = _unique1d(ar, return_index, return_inverse, return_counts)
    273     return _unpack_tuple(ret)
    275 # axis was specified and not None

File ~/venv/napari/lib/python3.10/site-packages/numpy/lib/arraysetops.py:333, in _unique1d(ar, return_index, return_inverse, return_counts)
    331     aux = ar[perm]
    332 else:
--> 333     ar.sort()
    334     aux = ar
    335 mask = np.empty(aux.shape, dtype=np.bool_)

TypeError: '<' not supported between instances of 'A' and 'A'
```

This is caused by the use of `np.unique`, which is used to extract 'current_properties'. I don't have an immediate solution, but I don't think our attempt to get a value for `current_properties` should mess up our ability to select points themselves, since that machinery worked just fine.

@andy-sweet having worked on features, do you see any obvious solutions to this?

**Comment by andy-sweet** [comment]
`np.unique` returns the sorted unique elements of an array, so if the object being stored isn't sortable (as in this case) then we can't use it.

We don't actually want the sorted elements, so maybe we can do something like

```python
properties[k] = np.array(tuple(set(v[index])))
```

though that is likely slower.

Ultimately, we just want to do something if there is one unique value (i.e. update current properties). I'd probably vote for writing a simple helper function that either returns that one unique value or `None` if there's more than one value. It should be much faster than either of these approaches since it only needs a single pass over the data, on each iteration checking if the new value is the current unique value, and returning `None` early otherwise. If this is substantially faster, we should probably use it instead of `np.unique` for the other similar checks above.
