### ISSUE TITLE
Napari-console doesn't work when launching napari from jupyter

### ISSUE THREAD

**Issue by yunhal** [napari/napari#5211]
## 🐛 Bug

When launching napari from *ipython*, the terminal window is blank and is not responding (can't type).  However, it works just fine when launching napari from *python*. 

## To Reproduce

1. Create clean napari environment 

```
mamba create -n napari-clean python=3.10 napari --channel conda-forge --override-channels
```

2. Execute the example code below in ipython or jupyter notebook 

```
import napari
import numpy as np

arr = np.random.random((10,10,10))
viewer = napari.view_image(arr)
```

3. The terminal window in the napari program is blank and not responding. 

![image](https://user-images.githubusercontent.com/28872346/195675030-a10f2c87-a033-4402-8945-d6e32c4387cb.png)

## Expected behavior

I expected that the terminal window in the napari looks like below screenshot, which I took when opening napari from python (not ipython).

![image](https://user-images.githubusercontent.com/28872346/195675440-7f219c88-904f-4273-a271-57bae7dc36f1.png)

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.16
Platform: macOS-12.6-x86_64-i386-64bit
System: MacOS 12.6
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.3
SciPy: 1.9.1
Dask: 2022.9.2
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 ATI-4.8.101
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0

Plugins:
- console: 0.0.6
- napari-svg: 0.1.6
- scikit-image: 0.4.16
```

 - Any other relevant information:

**Comment by psobolewskiPhD** [comment]
First, let me say I agree with you that this is confusing—I've also run into this.
But, the idea is the ipython console is the one you should use to continue interacting with napari. In fact—to resolve this confusion—the button to open the console should be disabled! https://github.com/napari/napari/pull/4240
And yet you get a button and then a blank panel.
🤔 
Can you clarify if this is indeed ipython or jupyter? I can't reproduce with ipython.
Edit: Ok, it was jupyter right? I can reproduce with Jupyter.
And again the idea is you should use your notebook to interact with napari not the console, so it should be disabled.
(can you verify that if you use ipython it's disabled?)

Edit2: also, your expected behavior is the console when launching napari from the python REPL. This is actually broken if you type something into that console: https://github.com/napari/napari/issues/3338
It's really annoying! So I strongly suggest avoiding that workflow. 
Use ipython or jupyter and then keep using them or launch napari from the terminal and use the napari-console.

**Comment by yunhal** [comment]
I am sorry I wasn't entirely clear.  You are correct!  ipython gives disabled terminal, and jupyter gives you a button that doesn't actually work.

**Comment by psobolewskiPhD** [comment]
For the time being, I've made a PR to disable the button for the jupyter case so it's the same as ipython.
I'm not sure this helps you, can you maybe explain more what you'd actually expect and how you'd like to interact with napari, the console, and jupyter?
Edit: I also took the liberty to edit the issue title to better reflect the situation.
