### ISSUE TITLE
"Show only this layer" menu / double-click action

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5253]
## 🚀 Feature
If you have many layers open, it would be convienient if here was a menu such as "Show only this layer, hide all others"

## Motivation

For showing just one layer, it is complicated because you need to hide many other layers.

## Pitch

To spare time of users, it would be great if some convenience menus for this existed.

## Alternatives

The course attendee who reported that also proposed to use a mouse double-click on any layer to "show only this layer"

**Comment by psobolewskiPhD** [comment]
I agree, I think a `Hide other layers` contextual would be nice. Could maybe register it for a keybind. I can try to make such a PR, it's been on my list of things.
I'm not sure I like the double-click option, because that's an easy mess-up. Plus, i frequently click repeatedly on the Visibility toggle to flip it on and off to compare something....

@haesleinhuepf a workaround: if you're in the layer list, Command-A to select all or shift-click to get any layers you want to hide, then command-click the one you want to keep, so it's de-selected, then, right-click > Toggle visibility on the ones you want to hide.

Also, for the record, quite related: https://github.com/napari/napari/issues/2550.
Edit: Also related issue, with quite similar suggestion: https://github.com/napari/napari/issues/1338
and Design issue: https://github.com/napari/napari/issues/3284

**Comment by GenevieveBuckley** [comment]
+1 on this suggestion
