### ISSUE TITLE
New Label Layer emit a warning of invalid color

### ISSUE THREAD

**Issue by Carreau** [napari/napari#5311]
Since #5180, now that we rely on skimage newer version, we actually see warning about improper colors and colorspace. 

In particular we get "Color data out of range: Z < 0 in N pixels"

The warning in napari emanates from this line:

https://github.com/napari/napari/blob/1cc90a74211c6cbf3fc644da5866f9752cf1ac78/napari/utils/colormaps/colormap_utils.py#L361

And it seem that we are sampling colors outside of the lab space. Skimage goes via the XYZ space, and Z is negative for some of those colors, and then clipped to 0, then converted from XYZ to RGB. 

I'm not sure what the implications are – there are at least some improvement we can send upstream to skimage to tell us _which_ values are incorrect. 

_Originally posted by @Carreau in https://github.com/napari/napari/issues/5180#issuecomment-1306910267_

**Comment by andy-sweet** [comment]
On further investigation, it seems like @jni deliberately removed that check when the vendored code was added: https://github.com/napari/napari/pull/175/commits/d1bb7152cb8949d23ad4e41cacab13211f9e4a27

I wonder if we could just temporarily suppress the warning and add an implementation comment to explain why we might be outside of the valid range for the lab color space (I'm not capable of that yet!), rather than re-vendor the code. I looked at the diff between the vendored code removed in #5180 and the latest `colorconv.py` from scikit-image and there are lots of differences, though not sure how many of them would actually be relevant here.

> I'm not sure what the implications are – there are at least some improvement we can send upstream to skimage to tell us _which_ values are incorrect.

There's an open issue for that, so we could consider a contribution once we're capable of one: https://github.com/scikit-image/scikit-image/issues/1185

**Comment by andy-sweet** [comment]
> (I'm not capable of that yet!)

Actually, I don't think it's too complicated: `_color_random` calls `_low_discrepancy`, which should generate an Nx3 array where each element is in [0, 1]. The `LABMIN` and `LABRNG` values define a loose bounding box that encloses all the lab colors that can come from valid RGB uint8 3-tuples. By offsetting and multiplying by the random values in [0, 1] with those constants, we'll get a tuple that's within that box, but that might be an invalid lab color.

For our sampling strategy, some sort of clamping/projection to fix these invalid colors is good enough. So this justifies ignoring/suppressing the warning.

I may open a PR to suppress the warning, but will wait a few days to see if there are better/more informed ideas.

**Comment by Carreau** [comment]
I think it's fine if we suppress the warning with the context manager. At least it will be explicit. We will just have a non uniform sampling of the lab color space.
