### ISSUE TITLE
Glitches with 3D viewing

### ISSUE THREAD

**Issue by jni** [napari/napari#547]
## 🐛 Bug

Clicking the 3D viewing button when a 2D image is displayed causes napari to crash. It should either be a no-op or somehow view the data as a 2D plane in 3D, but it shouldn't crash!

Additionally, Ctrl-Y is not equivalent to pushing the button: the viewer doesn't crash, but instead displays a blank image (and the traceback is printed to the console).

Finally, even on 3D volumes, pressing Ctrl-Y does not update the 3D/2D icon.

## To Reproduce

```
python examples/add_image.py
```
then click the 2D/3D button, or press Ctrl-Y.

```
python examples/add_volume.py
```
then press Ctrl-Y, and note that the icon is not updated.

**Comment by sofroniewn** [comment]
The button changing with `Ctrl-Y` is now fixed with #536, and as discussed in #532 we need to extend 3D rendering capability for our 2D layers. We can do this inside our vispy view code by catching this case and "0-padding" what we send over.

In the long run we might also want to allow 2D layers to be overlaid in different places in the 3D volume, but that can come later.

**Comment by sofroniewn** [comment]
This is closed by #532
