### ISSUE TITLE
Visual Bug: Labels Layer Controls get squished when toggling 3D

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5472]
## 🐛 Bug

When toggling to 3D, the labels layer Layer Controls widget gains an extra line `rendering`.
However the widget doesn't resize for this, so it results in a visual bug of everything squished and partially cut off:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/76622105/212083289-a7333963-f66a-4875-bd11-e49965ef7a77.png">

If you manually expand the widget, it will look fine. However, in contrast to the 2D version of the widget, it will let you resize it vertically to be too small, squishing the contents again.

## To Reproduce

1. open napari
2. make a labels layer (can be empty)
3. toggle 3D

## Expected behavior

The widget should either resize to permit the extra line item or start out sufficiently large that when the line item is added the visual isn't squished.

## Environment

macOS 13.1, pyqt5, 0.4.17

**Comment by dalthviz** [comment]
Hi, I think this is related to https://github.com/napari/napari/issues/2337 I was checking it and seems like the issue is caused due to setting a `min-width` `and min-height` to the layers controls container at https://github.com/napari/napari/blob/4f1f6a0979b0489b566aed64008da493c3180ac9/napari/_qt/qt_resources/styles/02_custom.qss#L274-L275

I think removing that and instead setting it for the empty widget the container widget creates could help with this and https://github.com/napari/napari/issues/2337 (that will enable for the container widget to resize depending on its contents). Something like this:

```
QFrame#empty_controls_widget {
    min-height: 295px;
    min-width: 240px;
}

QtLayerControlsContainer {
    border-radius: 2px;
    padding: 0px;
    margin: 10px;
    margin-left: 10px;
    margin-right: 8px;
    margin-bottom: 4px;
}
```

With those changes this is the behavior on Windows:

![resize](https://user-images.githubusercontent.com/16781833/212141918-9867f93f-67ed-406b-9eaa-eee5b5094371.gif)

**Comment by psobolewskiPhD** [comment]
Ha! Beat me to it!
Looks great. 
I was trying to figure out how to get it to resize, in the meantime I was going to set the min-height off of the 3D widget.

Edit: I expect the other layer types will have nicer controls too now, because at present there is way too much space for them....

**Comment by dalthviz** [comment]
PR incoming then!
