### ISSUE TITLE
On main: new keybinds set by Preferences arn't saved 

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5579]
## 🐛 Bug

If you set a keybinding in the Preferences > shortcuts menu to a new binding, it's not saved.
After re-opening napari, the preference shows a blank where a keybind had been entered.
The settings file will also show a blank field.

## To Reproduce

Install napari main post https://github.com/napari/napari/pull/5103

1. Open napari
2. Edit a keybinding
3. Close napari	
4. re-open and check napari

## Expected behavior

Keybindings should be retained after relaunching.

## Environment

macOS 13.1, arm64, pyside6 (also happens with pyqt5)

## Additional context

If I manually edit the settings.yaml file to insert the shortcut, then it works, so the issue is with writing the new shortcut to the yaml.

**Comment by Czaki** [comment]
The problem comes from the setting dialog failing to update the shortcut setting. 
Changing settings in one section works because another mechanism of bind settings is used. 

`reset_view` is predefined, and `toggle_theme` is modified from the settings window. 

![obraz](https://user-images.githubusercontent.com/3826210/220579831-bb869bdd-1b67-4c83-8367-f7a254acda33.png)
