### ISSUE TITLE
Issues with coloring `Points` by feature with empty layer

### ISSUE THREAD

**Issue by brisvag** [napari/napari#5632]
## 🐛 Bug

Empty point layers and coloring by feature (which is necessary to be set up correctly when interactively picking points) have a few issues:

```py
import napari
pts = napari.layers.Points(features={'a': []}, face_color='a')
```
```
ValueError: Color "a" unknown
```

A different error happens if I do the following:
```py
import napari
pts = napari.layers.Points(features={'a': []})
pts.face_color = 'a'
```
```
RuntimeError: Event source-stack mismatch.
```

cc @andy-sweet, as this seems to be related to the property/feature swap.

**Comment by andy-sweet** [comment]
The first error is definitely related to the property/feature swap, though some form of this might have been present earlier.

My intuition is that the long term solution is to take that work over the line, replacing `ColorManager` (which is where the error is coming from) with `ColorEncoding`.

I might be able to provide short term fixes and workarounds, though it would help to have more context about the usage and the expected behavior.

Most importantly, since there no values or dtypes it's unclear what type of values are stored in column a and how they should be mapped to colors. E.g. are they real numbers that should be mapped using a continuous colormap, or categorical that should be mapped with a cycle?

**Comment by andy-sweet** [comment]
I can't reproduce the second error at 45044be5c04f79a7a59e2ce229e8ee97248ef4fc

Seems to be coming from [`EventEmitter`](https://github.com/napari/napari/blob/45044be5c04f79a7a59e2ce229e8ee97248ef4fc/napari/utils/events/event.py#L774) and may be related to some recent changes in #5307.
