### ISSUE TITLE
Point color sees changes to `feature_defaults` "late"

### ISSUE THREAD

**Issue by brisvag** [napari/napari#5634]
## 🐛 Bug

When setting feature defaults, I expect the next point I create to inherit the new default. While this is true for the features table, for some reason the `face_color` arrives 1 index too late to the party :P 

I would expect the following to result in 3 points respectively red, green and blue. 

```py
import napari
import numpy as np

v = napari.Viewer()

pts = v.add_points(
    features={'a': np.empty(0, int)},
    face_color_cycle=list('rgb'),
)
pts.feature_defaults['a'] = 0
pts.face_color = 'a'

pts.add([0, 0])
pts.feature_defaults['a'] = 1
pts.add([50, 50])
pts.feature_defaults['a'] = 2
pts.add([100, 100])

print(pts.features)
```

As you can see, the features table is correct. However, the points are red, red, green.

If you run `pts.refresh_colors()`, it will be fixed.

cc @andy-sweet (sorry, today I'm poking at your features code :P)

**Comment by andy-sweet** [comment]
Ah maybe this adds the context I needed for #5632!

The core issues here are that the points layer is still using `ColorManager` to generate color values and that the in-place modification of `feature_defaults` doesn't (and currently can't) trigger anything to happen (e.g. like informing `ColorManager` about the new value).

Like #5632, my choice of long term solution would be finish the style encoding work, though I don't have good ideas on short term fixes or workarounds (other than the hard refresh you discovered here).

**Comment by andy-sweet** [comment]
Also, this older issue maybe related to your usage: #4065

A short term fix for this issue may be to provide a `feature_defaults` setter as then we could detect the change and update the `ColorManager`.

**Comment by brisvag** [comment]
> A short term fix for this issue may be to provide a `feature_defaults` setter as then we could detect the change and update the `ColorManager`.

This would also solve issue 1 in #5632 then? If so, this seems pretty painless and easy to implement; or am I missing something?

**Comment by andy-sweet** [comment]
> This would also solve issue 1 in #5632 then? If so, this seems pretty painless and easy to implement; or am I missing something?

I'll have a go at this ~today~ tomorrow. The main reason I avoided it initially is that it will likely add a setter, initialization param, and event. And then we need logic to check that `feature_defaults` is compatible with `features` (and maybe similar logic when using the `features` setter) - I'll probably use the simplest logic I can and will raise rather than coerce user input too much.

**Comment by andy-sweet** [comment]
I did start working on this today, but a little late and I ran out of steam. But while I was working, I though of a possible alternative fix here that's related to #3779

Is the following what you really want?

```python
def test_empty_points_with_features():
    """See https://github.com/napari/napari/issues/5634"""
    points = Points(
        features={'a': np.empty(0, int)},
        face_color_cycle=list('rgb'),
    )

    points.add([0, 0], features={'a': 0})
    points.add([50, 50], features={'a': 1})
    points.add([100, 100], features={'a': 2})

    assert_colors_equal(points.face_color, list('rgb'))
```

Even it is, we could and probably should also do the `feature_defaults` setter, but wanted to get some more clarity on the desired usage here.

There's also another related idea in #4065 for some more context.

**Comment by brisvag** [comment]
> ```python
>     points.add([100, 100], features={'a': 2})
> ```

This would solve partally the issue (and is probably a generally useful thing), but it's also not quite solving the problem of adding points interactively (the real use case), instead of programmatically.

**Comment by andy-sweet** [comment]
I have a simpler fix for this specific bug that means the above example unmodified would work: https://github.com/napari/napari/commit/9a059700482360fa9a4480ed1d57d55c8f65b221

I feel like that's a better temporary solution that adding a `feature_defaults` setter, which would require a change to the code above and adds to our public API. Note that the reason there's a lag is because the `Points.data` setters calls the `Point.selected_data` setter and effectively does the same thing, but after the color has been added (so the next call to `add` gets the new feature value). I did try moving the call to the `selected_data` setter, but causes a different issue.

That simple fix won't fix #5632 and a `feature_defaults` initialization parameter would fix that, so I'm going to continue working on adding that and likely the setter.

**Comment by andy-sweet** [comment]
I started implementing `Points.feature_defaults` in https://github.com/andy-sweet/napari/pull/47

There is a simpler PR that fixes this bug, the other one, and something else that's related without introducing a setter: https://github.com/andy-sweet/napari/pull/46/

But since the validation/coercion logic of `feature_defaults` is not too bad yet, I'm OK with introducing it (though it doesn't help with the fundamentals of the bugs).

**Comment by brisvag** [comment]
I definitely like andy-sweet/napari#47; it feels intuitive to also have it as a property and especially as init parameter.

> though it doesn't help with the fundamentals of the bugs

Well, it sets up for a cleaner solution, right?

**Comment by andy-sweet** [comment]
My usual definition of clean is small and simple, whereas adding a `feature_defaults` setter makes the API larger and more complicated. But I do think it's more powerful and complete. In particular, I'm in favor of the initialization parameter, so once I put the effort in to handle, I guess it's not much worse to support the property setter too.

Therefore, I opened a draft PR on the main repo, so you and others can take a look at how this looks: https://github.com/napari/napari/pull/5646

Should be able to get it ready for review in the next couple of days.
