### ISSUE TITLE
Window resizes very wide if labels have lots of features

### ISSUE THREAD

**Issue by will-moore** [napari/napari#5639]
## 🐛 Bug

When I add a `labels` layer with `features` being a dataframe with lots of columns, mousing over the image in napari causes the window to resize to be VERY wide, so that the image vanishes off screen.

## To Reproduce

```
import napari
from skimage.data import binary_blobs
import pandas

viewer = napari.Viewer()
blobs = binary_blobs(length=100, volume_fraction=0.1, n_dim=2).astype('int8')

column_count = 100
row_count = 2
columns = ["col %s" % c for c in range(column_count)]
data = [list(range(column_count)) for r in range(row_count)]
features = pandas.DataFrame(data, columns=columns)

viewer._add_layer_from_data(blobs, {'features': features}, "labels")
napari.run()
```

![Screenshot 2023-03-16 at 13 29 36](https://user-images.githubusercontent.com/900055/225633682-cd65edd0-dd8e-4196-990b-7ed4a5bf8912.png)

## Expected behavior

No change in the window size

## Environment

Napari info...
```
napari: 0.4.17
Platform: macOS-12.2.1-x86_64-i386-64bit
System: MacOS 12.2.1
Python: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:42:20) [Clang 14.0.6 ]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.22.4
SciPy: 1.9.1
Dask: 2023.2.1
VisPy: 0.11.0
magicgui: 0.7.0
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1512x982, scale 2.0
```

```
$ pip freeze | grep napari
napari==0.4.17
napari-arboretum==0.1.1
napari-console==0.0.7
napari-matplotlib==0.2.1
-e git+ssh://git@github.com/ome/napari-ome-zarr.git@19eaf19cc5a04868c428f4ec88dc87f4bf8e1746#egg=napari_ome_zarr
napari-plugin-engine==0.2.0
napari-properties-viewer==0.0.2
napari-svg==0.1.6
```

**Comment by psobolewskiPhD** [comment]
Hi @will-moore 
Indeed, this is a really annoying bug!
The good news, this isn't a new issue (most recently reported here: https://github.com/napari/napari/issues/5617 ) and it's been already fixed here: https://github.com/napari/napari/pull/5451
🎉 
The problem of course is that the fix is merged, but not released yet.
So you can either install from `main` from this repo using pip:
`python -m pip install "git+https://github.com/napari/napari.git#egg=napari[all]"`
or use a Nightly release, which we do have on conda, for example:
`conda create -n napari-main -c "napari/label/nightly" -c conda-forge napari python=3.10`

Of course, there are still some unfinished aspects to `main` so beware of dragons!

**Comment by will-moore** [comment]
Great, thanks - and apologies for the duplicate issue.
