### ISSUE TITLE
contrast limits range equal to contras limits on setting

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#570]
## 🐛 Bug

If you explicitly set the contrast limits as a keyword argument to the layers list right now the range of the contrast limits slider gets set to the same value, which is quite annoying if you then need to adjust the sliders to be more extreme. I suggest that we set the range to be 10% smaller and 10% larger to give you a little extra room to adjust things.

This change will only affect the display and will be backwards compatible.

**Comment by jni** [comment]
@sofroniewn imho we should be quite a bit smarter about contrast limits. For one, I think for uint8 images the limits should always be set to 0-255 and the image should not be introspected in any way. In this case, adding 10% margins would be totally nonsensical.

Another idea would be something like `bit_depth` which could be set to e.g. 12 to then automatically adjust the sliders to 0-4095 without needing to type those numbers in.

**Comment by jni** [comment]
Also, I would not call this a bug at all, but a feature request. =)

**Comment by berl** [comment]
just found this issue and wanted to chime in:
the current space in the clims slider is pretty finicky for my data because (like a lot of fluorescence imaging) a ton of our information is down in the low intensity values. With the current 2-dots-and-bar slider, I don't have the flexibility to interactively adjust the low end without the 2 dots overlapping and becoming useless.   

I don't have a great solution here without going to the full zoomable histogram+slider widget similar to what's in pyqtgraph or micromanager

**Comment by jni** [comment]
In Quicktime, you can hard-press (or long press) when scrubbing on the movie position to "expand" the slider and have movement of the slider translate to finer movement of the time. We should definitely steal this idea.

**Comment by sofroniewn** [comment]
The larger pop-up slider feature and editable range labels has now been added in #837 so closing this issue
