### ISSUE TITLE
Events are not emitted when colors are changed manually

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#5718]
## 🐛 Bug

When the face color or the edge color of a points layer is changed from the layer control, the corresponding events are not emitted.

## To Reproduce

1. Add a points layer.
2. Run `viewer.layers[0].events.face_color.connect(lambda x: print(x))`
3. Change the face color in the layer control.

## Expected behavior

Events should be emitted as other properties.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17
Platform: Windows-10-10.0.22621-SP0
Python: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.23.5
SciPy: 1.9.1
Dask: 2023.3.2
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.6.2

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0
```

 - Any other relevant information:

**Comment by brisvag** [comment]
This is a combination of two things:

1. A bit of an inconsistency with the points layer control. Those values actually afftect the `current_face_color` and `current_size`, and not the `face_color` and `size`. There's been discussion about changing this, but there's also good reasons for this behaviour.
2. Even using the correct events, the events are not fired because the emitter is (wrongly) blocked. This is a bug! I just made a PR for this at #5722.
