### ISSUE TITLE
isosurface with napari

### ISSUE THREAD

**Issue by dreme** [napari/napari#572]
Can napari generate isosurfaces from a regular 3D array? That would be very cool (and useful)

**Comment by jni** [comment]
@dreme thanks for your interest in napari! Right now we don't compute isosurfaces automatically, but if you have them, they can be displayed via the `napari.Viewer.add_surface` method or `napari.view_surface` function. You can use `skimage.measure.marching_cubes_lewiner` to get compatible surfaces.

**Comment by sofroniewn** [comment]
@dreme you might actually be able to achieve this now using `add_image`, entering 3D display mode, and setting the rendering mode to be `iso` instead of `mip`, but we havn't tested this extensively. Right now you also can't set the threshold for the isosurface - it is computed as the mean of the array, though we should be able to expose that as a variable if desired (or I can tell you how to automatically set it from the console for testing purposes). Under the hood we are using the vispy volume function - http://vispy.org/visuals.html#vispy.visuals.VolumeVisual

As @jni noted though, if this isn't performing well you can precompute the isosurface and add them using a `Surface` layer.

Please let us know how you get on!

**Comment by dreme** [comment]
Thanks @jni and @sofroniewn for the quick responses.  I haven't actually installed **napari** yet, but when I get some free time I'll try the simpler solution that @sofroniewn suggested and get back to you. I'm not sure how to generate isosurfaces, but will try to look into it if the first solution falls over.

**Comment by sofroniewn** [comment]
For the `Image` layer, we should add a `threshold` slider that goes from `0` to `1` and that is only enabled when `layer.dims.ndisplay==3` and `layer.rendering=='iso'`. We should also make it so that the `rendering` dropdown box is only enabled when `layer.dims.ndisplay==3`.

This will significantly improve our 3D rendering functionality

**Comment by sofroniewn** [comment]
See this gif for the possibilities:
![iso_surface](https://user-images.githubusercontent.com/6531703/68642628-a618d300-04c3-11ea-97d2-4a12456d3fe4.gif)

**Comment by jni** [comment]
Nice work @sofroniewn! I have been quite discouraged in the past by the default isosurface rendering. This looks much better!

fwiw, the isosurface rendering in spimagine is gorgeous, so at some point it might be worth looking at those shaders and see whether we can port them to vispy.
