### ISSUE TITLE
New npe2 release 0.7.0 broke our typing action

### ISSUE THREAD

**Issue by jni** [napari/napari#5724]
## 🐛 Bug

Failed run link: https://github.com/napari/napari/actions/runs/4700373164/jobs/8335070666#step:5:12

Failure text:

```
mypy napari/settings napari/types.py napari/plugins
/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/npe2/plugin_manager.py:1: error: disable_error_code: Invalid error code(s): empty-body  [misc]
Found 1 error in 1 file (checked 22 source files)
make: *** [Makefile:10: typecheck] Error 1
Error: Process completed with exit code 2.
```

CC @tlambert03 @Czaki as I know nothing about this action 😂

**Comment by tlambert03** [comment]
that specific error is caused by napari using a pretty outdated version of mypy in the typing action (mypy==0.982 specified in `resources/requirements_mypy.txt`).   (`[misc]` is not an invalid error code for current versions of mypy.)

unless @Czaki want's to pick up maintenance of keeping napari type checks working, I'd say you might just consider dropping it

**Comment by Czaki** [comment]
Bugfix ready for review
