### ISSUE TITLE
GUI point size slider does not control size of points

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#5748]
## Two problems
1. Dragging the point size slider bar does not control the size of the points, and
2. Changing the point size in ipython does not update the position of the point size slider bar

## To reproduce
```python
import napari
import numpy as np

points = np.random.random((10,3))
viewer = napari.Viewer(ndisplay=3)
viewer.add_points = 
print(viewer.layers[-1])
print(viewer.layers[-1].size)  # shows an array of tens, the default point size value
```
Now drag the point size slider bar in the GUI and watch it fail to update the size of the points.
There's no change either when you query `viewer.layers[-1].size`.

However, you can update the point size from the terminal, eg:
```python
viewer.layers[-1].size = 30
```
...which does change the point size, but not the position of the point size slider bar (or the value reported there). I expected that the slider bar position should be updated, unless the size value was above or below the ends of the slider bar (in which case I guess it should be moved to the end?)

## Environment details
napari: 0.5.0a2.dev88+g95356e45
Platform: Windows-10-10.0.22621-SP0
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.4.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 528.02
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1600, scale 1.0

Settings path:
- C:\Users\Supervisor\AppData\Local\napari\napari-dev_8890fb02210b7dc05c421c3c65ceb0b896a7352b\settings.yaml#5685 

## Additional details
I have also seen this problem occur while working on a Mac.

**Comment by dalthviz** [comment]
Hi, I think this could be related with #5718 and seems like an explanation for the `size` attribute not updating was done at https://github.com/napari/napari/issues/5718#issuecomment-1507166668 by @brisvag . Following the comment there and the example code above, I checked and I think the slider is connected to the `current_size` attribute of the layer, so moving the slider updates the `current_size`. However, seems like changing the `current_size` attribute programmatically doesn't update the slider unless you have a selection

**Comment by Czaki** [comment]
Size slider is to control the size of new points.

**Comment by brisvag** [comment]
@jni further evidence that this behaviour is not intuitive, as discussed in [this comment thread](https://github.com/napari/napari/pull/5722#discussion_r1165758964)

**Comment by psobolewskiPhD** [comment]
> * Dragging the point size slider bar does not control the size of the points, and

I can't reproduce this? The slider controls size of any *selected points* or *new points*. I almost never use points, but this is as I'd expect from basically every other GUI program? So me this is intuitive. You make the layer, there's a size set, you make points you get that size. You want to change point size, select some points to change.

Only slightly odd thing is that when adding points, the last point added *is* immediately selected. So  you can easily end up changing its size inadvertently when intending to change the next point you place.

Now `viewer.layers[-1].size` weird — it changes the size of all existing points in a layer, regardless of selection, but *does not* affect new ones. Seems like a poor choice of name for a property? we're not changing the size of the layer...
But yes, then it's further weird because the slider will not update for any selected points, so when you then want to use the slider, the behavior is like a small glitch.

I think there is value in programmatically setting the size of:
1. all existing points -- in the GUI this would be shown by slider for both the + tool and the selection tool
2. all selected points (this can easily handle case 1, by select-all) -- shown by slider for the selection tool, with those points selected
3. new-to-be-placed points -- shown by slider for the + tool

**Comment by brisvag** [comment]
> You make the layer, there's a size set, you make points you get that size. You want to change point size, select some points to change.

You come at this from the perspective of only ever adding individual points manually. I typically add a whole point layer programmatically, and then might need to make them bigger. So I reach for the slider and nothing happens. Caught me (and other folks) off guard several times. Sure, I can use a shortcut to select all, but It's usually after a few seconds of "what??".

Maybe having all points be selected by default when a layer is created would solve most of these issues xD

> * all existing points -- in the GUI this would be shown by slider for both the + tool and the selection tool
> 
> * all selected points (this can easily handle case 1, by select-all) -- shown by slider for the selection tool, with those points selected
> 
> * new-to-be-placed points -- shown by slider for the + tool

Not sure I follow; you'd have a different slider depending on what mode you're in?

**Comment by Czaki** [comment]
But you also show an example where different point size was used and a simple moving slider should not destroy it.

**Comment by brisvag** [comment]
Just to make it clear: I'm not advocating to remove the ability to change the next and/or selected points only. I'm just saying that the GUI is not clear. If I reach for the layer attributes and I see `current_size` and `size`, it's quite obvious what they do.

If I then see `point size` in the gui, I assume it refers to the second, when it actually refers to the first.

**Comment by psobolewskiPhD** [comment]
(grrr, lost my post while writing, wtb something like zulip that stores in progress posts)

> You come at this from the perspective of only ever adding individual points manually. I typically add a whole point layer programmatically, and then might need to make them bigger.

🎯 
But, I still think this is exactly what should be handled by selection and then manipulating the slider. And Select All shortcut happens to work perfectly for this, even in + tool mode—though the points arn't visually selected for some reason (small separate issue, I mean our default visual selection is **really subtle** vs. edge color but it's just missing here).

> Maybe having all points be selected by default when a layer is created would solve most of these issues xD

I think this is reasonable and makes sense, especially if the visual was working to make the situation clear. As far as I can tell this is common behavior (illustrator, power point) that when you use a tool to draw/add something it's selected. Even here, when you add a new point using + tool, it's selected (ironically not the case for our Shapes layer—we could do this whole exercise there and get different behavior). So if you programmatically added 50 points, having them be selected makes sense?
Of course someone may not like that, because then when they go to add a new point and move the slider their freshly added points will change... So we should make sure there's an easy way to **deselect**. Currently, you need to toggle select tool and click somewhere (small separate issue, maybe make Command/Control-D the keybinding, that's default in Photoshop/Illustrator).

> Not sure I follow; you'd have a different slider depending on what mode you're in?

No, same slider, but it should reflect the mode in a sane fashion.
Try this, using GUI for simplicity:
1. make a new points layer, all default
2. make 2 or 3 points (+ tool). They will be size 10, default. *Note the last one you make is selected*
3. Adjust the slider to 40 or something. The last one you made will reflect this.
4. Make another point—it will reflect the new size. So far so good, for me everything makes sense.
5. Switch to Select tool. Select the first point you made. Slider still shows 40 or whatnot, when it should show 10, because that's the size of the selected point. Adjusting the slider does work and changes the size, but for me there is a disconnect there, an inconsistency. 

But for colors it works! When you select a point the colors will be reflected properly in the UI. You can do the above 5 steps using face color and the behavior is intuitive.

**Comment by brisvag** [comment]
> Switch to Select tool. Select the first point you made. Slider still shows 40 or whatnot, when it should show 10, because that's the size of the selected point. Adjusting the slider does work and changes the size, but for me there is a disconnect there, an inconsistency.

Yup, this is definitely a bug!

> if you programmatically added 50 points, having them be selected makes sense?

This already works; the problem is when creating a new layer. Maybe I'll open a PR with this.

**Comment by Czaki** [comment]
> > Switch to Select tool. Select the first point you made. Slider still shows 40 or whatnot, when it should show 10, because that's the size of the selected point. Adjusting the slider does work and changes the size, but for me there is a disconnect there, an inconsistency.
> 
> Yup, this is definitely a bug!

And what when have different size of points in selction?

**Comment by psobolewskiPhD** [comment]
> And what when have different size of points in selction?

Yes, this is a tricky case when you would have multiple selected points with all different sizes. Based on a few programs I've tried, it would show the value for the last selected item or no numerical value at all (MS Word does this with font size for example).

**Comment by brisvag** [comment]
I would vote for no value, set the slider to the middle, and then as soon as you move the slider everything selected gets resized.

**Comment by psobolewskiPhD** [comment]
> I would vote for no value, set the slider to the middle, and then as soon as you move the slider everything selected gets resized.

Sounds fine to me. This is a case where a typed value in the box would be the easiest, which should work, right?

**Comment by Czaki** [comment]
> I would vote for no value, set the slider to the middle, and then as soon as you move the slider everything selected gets resized.

I'm not too fond of this. For many projects, it will end with multiple problems. It should be median or dominant. Or at least the option to provide size by entering text to some text input, not only dragging the slider.

**Comment by brisvag** [comment]
Sure, that probably works best.

> Just to make it clear: I'm not advocating to remove the ability to change the next and/or selected points only. I'm just saying that the GUI is not clear. If I reach for the layer attributes and I see `current_size` and `size`, it's quite obvious what they do.
> 
> If I then see `point size` in the gui, I assume it refers to the second, when it actually refers to the first.

I think this is the immediate issue right now; I tried to add `current ...` to the gui labels [but people didn't like it](https://github.com/napari/napari/pull/5722#discussion_r1165758964); it would be nice to come up wioth something else to clarify this.

**Comment by dalthviz** [comment]
Just in case and for traceability, linking here an old issue I found that seems to be related to this: https://github.com/napari/napari/issues/702

**Comment by psobolewskiPhD** [comment]
Thanks for the heads up @dalthviz 
I think *consistency* is the key. If things are consistent then they can become intuitive and then additional widgets or labels are not needed.

**Comment by jni** [comment]
Yeah the symbol inconsistency stems from a VisPy limitation but iirc @brisvag removed that limitation recently? So we could make symbol behave like size. Not sure @brisvag will enjoy the consequences of his efforts if we do that though 🤣

**Comment by brisvag** [comment]
Symbol already behaves like size: #5312.

**Comment by GenevieveBuckley** [comment]
Let's move the design discussions to a separate thread. Continuing that here will mean they are not very discoverable.
