### ISSUE TITLE
Unexpected Keyword 'feature_defaults' in 'add_points'

### ISSUE THREAD

**Issue by constantinpape** [napari/napari#5789]
## 🐛 Bug

Calling `add_points` with the keyword argument `feature_defaults` does not work. It throws a TypeError because `feature_defaults` is not a valid keyword.
However, according to the doc it should be a valid keyword argument: https://napari.org/stable/api/napari.Viewer.html#napari.Viewer.feature_defaults

## To Reproduce

Can be reproduced with this sinippet:
```python
import napari
v = napari.Viewer()
v.add_points(data=[[0, 0], [1, 1]], feature_defaults=["True", "False"])
napari.run()
```
which throws:
```
Traceback (most recent call last):
  File "/home/pape/Work/playground/napari/check_points.py", line 3, in <module>
    v.add_points(data=[[0, 0], [1, 1]], feature_defaults=["True", "False"])
TypeError: add_points() got an unexpected keyword argument 'feature_defaults'
```

## Expected behavior

It opens the viewer with a point layer and the passed feature default values.

## Environment

This happens in a fresh installation from conda forge, using the latest napari version.
Here's the napari info:
```
napari: 0.4.17
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.4.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0
```

## Additional context

I ran into this while working on https://github.com/napari/docs/pull/145

**Comment by Czaki** [comment]
> However, according to the doc it should be a valid keyword argument: [napari.org/stable/api/napari.Viewer.html#napari.Viewer.feature_defaults](https://napari.org/stable/api/napari.Viewer.html#napari.Viewer.feature_defaults)

This links to attribute documentation, not constructor keywords arguments. 

However, the `feature_defaults`  keyword argument is added to the current main. (in #5646)

On 0.4.17 the `feature_defaults` are calculated based on feature values. 

@andy-sweet Did we want to backport it to 0.4.18, or is it somehow breaking?

**Comment by constantinpape** [comment]
> This links to attribute documentation, not constructor keywords arguments.

Ok, I see.

Trying
```python
...
points.feature_defaults = ["true", "false"]
```
fails in 0.4.17 with `AttributeError: can't set attribute 'feature_defaults'`, which sounds consistent with

> On 0.4.17 the feature_defaults are calculated based on feature values.

So it seems that updating the point annotation tutorial (https://github.com/napari/docs/pull/145) does not make sense until 0.4.18 is released.

**Comment by psobolewskiPhD** [comment]
*Edited since I was late*
Thanks for reporting! Indeed it appears that this is merged, but not release, see:
https://github.com/napari/napari/pull/5646

Please note that our docs are released/updated along with napari releases, so the example you are working on will become public on napari.org (stable) along side *the next napari release*. 

I've optimistically tagged that PR which was labeled bugfix with the 0.4.18 milestone, so it should be part of the next release, so everything should be good to go.
Note that `feature_defaults` expects a dict or dataframe, see:
https://napari.org/dev/api/napari.Viewer.html#napari.Viewer.add_points

Also, 😬 but the stable docs for *contributing* are not current, because of changes to the build system. So you need to look here (latest in the version selector at the top).
https://napari.org/dev/developers/documentation/index.html
You'll see that we now recommend using development napari install for contributing docs, exactly because of these types of issues.

So the best part forward is probably to update the example to reflect main and then it will be released along with the next napari version.
Alternatively, you could patch the stable docs here:
https://github.com/napari/napari.github.io/tree/gh-pages/0.4.17
but I don't think this case warrants it.

**Comment by constantinpape** [comment]
Thanks for the replies. I have updated my set-up now to the current `main` and there `feature_defaults` is available as a keyword argument of the constructor.
