### ISSUE TITLE
Incorrect interpretation of dimensions for viewing multichannel data

### ISSUE THREAD

**Issue by ngreenwald** [napari/napari#581]
## 🐛 Bug

When loading data with multiple channels, napari selects the first dimension as the channels dimension even when it represents rows, not channels

## To Reproduce

```
randoms = np.random.randint(0, 20, 1024*1024*5)
channels_first = randoms.reshape((5, 1024, 1024))
channels_last = randoms.reshape((1024, 1024, 5))

# example code for trying out napari functionality
with napari.gui_qt():
    viewer = napari.view_image(channels_last, rgb=False, name='channels_last')

```
## Expected behavior

Instead of displaying the data as 1024 distinct slices of size 5x1024, it should be displayed as 5 stacks fo 1024x1024. I imagine there is going to be a huge range of different shapes and data formats supplied to napari from different users, and setting up the exact logic to guess correctly is infeasible. Perhaps supplying a channels idx as an argument?

## Environment

 - napari Version (e.g., 1.0): 0.2

## Additional context

![image](https://user-images.githubusercontent.com/13770365/66705484-10c7ca80-ecdc-11e9-83f3-37b528dd2282.png)

![image](https://user-images.githubusercontent.com/13770365/66705490-289f4e80-ecdc-11e9-85c4-ee22e929c32d.png)

**Comment by sofroniewn** [comment]
Indeed that would probably be a good keyword argument to have. Right now you'd either need to click the "roll dimensions" button which is the button with the cube and the arrow on it near the bottom left, or you'd need to add a line to your code as follows:

```
import numpy as np
import napari


randoms = np.random.randint(0, 20, 1024*1024*5)
channels_first = randoms.reshape((5, 1024, 1024))
channels_last = randoms.reshape((1024, 1024, 5))

# example code for trying out napari functionality
with napari.gui_qt():
    viewer = napari.view_image(channels_last, rgb=False, name='channels_last')
    viewer.dims.order = [2, 0, 1]
```

That `order` parameter will do what you want, but right now it's not exposed on `view_image` or any of our `view_*` methods. It is exposed on `Viewer` which creates an empty Viewer object.

Proposal for @jni to consider - maybe we expose all the keyword args that are on `Viewer` right now (so `ndisplay`, `order`, and `title`), and put them on all our `napari.view_*` methods, so that the above could be done in one line. I would not add the `Viewer` keyword args to our `viewer.add_*` methods as they don't make sense there. If you like that proposal I can quickly implement it
