### ISSUE TITLE
"oblique" button when rendering a plane stopped working in 0.4.18

### ISSUE THREAD

**Issue by zoccoler** [napari/napari#6040]
## 🐛 Bug

In an Image layer, when there is a 3D image and 'depiction' is 'plane, the `oblique` button does not work anymore.
The keyboard shortcut 'O' still works.

There is a [post in image.sc](https://forum.image.sc/t/request-for-testing-napari-0-4-18-release-candidate/82833/25?u=zoccoler) showing the bug.

## To Reproduce

1. Add a 3D image to napari
2. Change 'depiction' to 'plane'
3. Click the 'oblique' button

## Expected behavior

The plane should be shown in a orthogonal view regarding the camera position. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

Environment details in the image.sc post.

 - Any other relevant information:
 
 It used to work in 0.4.17

## Additional context

This may impact a new feature in the [napari-crop plugin](https://github.com/biapol/napari-crop) 0.1.9, Cut with plane, which uses these buttons to change the plane normal interactively.

**Comment by dalthviz** [comment]
Hi, gave this a check and I think there is a need to define two different functions (one that will be triggered by the button click and one that will be triggered by the shortcut keystroke press and release). Seems like changing the code that defines de action logic from this:

https://github.com/napari/napari/blob/1335634c6b5701107fd4f47b371cf01c5d3c1dcc/napari/layers/image/_image_key_bindings.py#L37-L57

to something like this:

```python
@register_image_action(trans._('orient plane normal along view direction'))
def orient_plane_normal_along_view_direction(layer: Image):
    viewer = napari.viewer.current_viewer()
    if viewer is None or viewer.dims.ndisplay != 3:
        return

    layer.plane.normal = layer._world_to_displayed_data_ray(
        viewer.camera.view_direction, [-3, -2, -1]
    )


@Image.bind_key(KeyCode.KeyO, overwrite=True)
def dynamic_orient_plane_normal_along_view_direction(layer: Image):
    viewer = napari.viewer.current_viewer()
    if viewer is None or viewer.dims.ndisplay != 3:
        return

    def sync_plane_normal_with_view_direction(event=None):
        """Plane normal syncronisation mouse callback."""
        layer.plane.normal = layer._world_to_displayed_data_ray(
            viewer.camera.view_direction, [-3, -2, -1]
        )

    # update plane normal and add callback to mouse drag
    sync_plane_normal_with_view_direction()
    viewer.camera.events.angles.connect(sync_plane_normal_with_view_direction)
    yield
    # remove callback on key release
    viewer.camera.events.angles.disconnect(
        sync_plane_normal_with_view_direction
    )

```

Makes things work:

![oblique](https://github.com/napari/napari/assets/16781833/efcb5660-6606-4912-a861-cdbd0746f6e9)


Not totally sure why but, maybe is due to the `yield` usage that is only usable when the action trigger comes from a keystroke that I guess handles pressed and released events instead of just clicked as with the button?

**Comment by Czaki** [comment]
@dalthviz napari 0.4.18 still uses string defined shortcuts, not app model one.

It looks like all generator actions are broken (also on main).
