### ISSUE TITLE
[ipython] File > Save Screenshot... warns about replacing if extension is provided

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6078]
## 🐛 Bug

If a napari viewer is launched from ipython and you use File > Save Screenshot... then everything works fine if you just enter a file name, **but if you specify the extension**—out of habit or to change the file format—then napari will warn that the file already exists, even if it does not.
Regardless of choice, the file is created and everything works.

Looking carefully, when one clicks Save the screen flashes, the file appears in the list in the dialog, and the warning pops up--the dialog remains up.
It's like the file is created and then it tries a second time when it goes to close the dialog.

Edit:
On the other hand, *if you pass a filename that exists,* **but without extension**, it will correctly warn that the file exists, but if say `no` to overwriting, the dialog closes with: `WARNING: QDialog::exec: Recursive call detected`
If you *do pass a full name with extension*, it will correctly warn that the file exists, and saying `no` will return you to the dialog to modify the name—as expected.

## To Reproduce

1. launch ipython and use 
```
import napari
viewer = napari.Viewer()
```
3. open any sample image or add any layer
4. File > Save Screenshot...
5. enter a file name **with an extension** but make sure it's a unique name.

## Expected behavior

No warning should be raised if the file doesn't exist, the dialog should just disappear and the file should be created.
If the warning is raised and the user clicks `no` to not overwrite, the dialog should remain open so the user can change the name.

## Environment

```
napari: 0.4.18
Platform: macOS-13.4.1-arm64-arm-64bit
System: MacOS 13.4.1
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.25.1
SciPy: 1.11.1
Dask: 2023.7.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1800x1169, scale 2.0

Settings path:
- /Users/sobolp/Library/Application Support/napari/napari-418_d279d6cf5d4193876ed97858e757fe322037331b/settings.yaml

```

## Additional context

Other dialogs, like Save Selected Layer work fine.
Using the native dialog (when running napari from the command line) does not have this issue.

**Comment by dalthviz** [comment]
Hi, checking this, I think the overwrite warning comes from the Qt implementation of the non-native dialog: https://code.qt.io/cgit/qt/qtbase.git/tree/src/widgets/dialogs/qfiledialog.cpp?h=dev#n2664

Seems like since the save function is called inside the `accept` method before `super().accept()` causes the Qt non-native implementation to trigger an overwrite warning. The test I was working on at #6057 wasn't caching the error since there the save function was only checking the path returned and not saving anything. However, adding actually file creation makes the test fail.

Also, seems like replacing lines:

https://github.com/napari/napari/blob/a593ff73832d7beb2f428d84be8f6974e79b54e2/napari/_qt/dialogs/screenshot_dialog.py#L68-L69

With something like:

```python
        base_result = super().accept()
        self.save_function(save_path)
        return base_result 
```

Prevents the error. Will try to fix this error with #6057 if that is okay :)

**Comment by psobolewskiPhD** [comment]
@dalthviz you're awesome! Thanks!

**Comment by Czaki** [comment]
It should be:
```python
        base_result = super().accept()
		if base_result:
	        self.save_function(save_path)
        return base_result 
```

instead of

> ```python
>         base_result = super().accept()
>         self.save_function(save_path)
>         return base_result 
> ```
