### ISSUE TITLE
Consider using copier instead of cookiecutter

### ISSUE THREAD

**Issue by jni** [napari/napari#6122]
Some folks from the scientific Python ecosystem [seem to like it](https://social.juanlu.space/@astrojuanlu/110843482693869999).

One thing I like is that it has built-in support for updating projects when the template is updated: https://copier.readthedocs.io/en/stable/updating

Apparently [cruft](https://cruft.github.io/cruft/) does this for cookiecutter templates but that seems like a more complex tool chain since it's [not built into cookiecutter](https://github.com/cookiecutter/cookiecutter/issues/784#issuecomment-839115411).

I don't have a strong opinion here, just want to share something I came across that could be interesting to implement, since updating downstream projects is something we have needed a lot of.

**Comment by GenevieveBuckley** [comment]
I have a working PR here we can play with: https://github.com/napari/cookiecutter-napari-plugin/pull/165

(Note: CI tests currently failing because they rely on a mocked cookiecutter fixture. I'll try to see if there's an equivalent to pytest-cookies for copier projects)

**Comment by GenevieveBuckley** [comment]
> I'll try to see if there's an equivalent to pytest-cookies for copier projects

There is! https://pypi.org/project/pytest-copier/

**Comment by 12rambau** [comment]
I don't know exactly how I got there but as you were looking for the equivalent of pytest-cookies, note that the repository you are pointing to is not testing the exact same thing. 
On the other hand my https://github.com/12rambau/pytest-copie/ is the exact equivalent of the cookiecutter plugin.

**Comment by GenevieveBuckley** [comment]
> ...is not testing the exact same thing.

Can you elaborate, @12rambau? 
I haven't used either of these test packages before, so I'm not familiar with the details.

**Comment by 12rambau** [comment]
I was in the same situation as you: I wanted to move from cookiecutter to copier.

the missing piece was to regain the capacity to test the generated template. I was using pytest-cookie and it was doing a great job. I found https://pypi.org/project/pytest-copier/ and though it was doing the same but not only there is no documentation, but it's not testing the same things. It checks the copier template-related files when pytest-cookie creates the template and lets you then play with it (In my case I mainly launch nox test sessions). 

I ended up porting pytest-cookie myself to pytest-copie. The documentation describes extensively how to use it: https://pytest-copie.readthedocs.io/en/latest/).readthedocs.io/en/latest/

**Comment by GenevieveBuckley** [comment]
Discussed in the meeting today, and we plan to *not* merge this PR (because then anyone who tries to do `cookiecutter [https:`](https://github.com/napari/cookiecutter-napari-plugin.git` will have things break immediately) and instead upload the content to a new repository https://github.com/napari/napari-plugin-template

This will allow us to have a slow deprecation and switchover to the new method. Eg: we'll have a derprecation warning anytime someone uses this repository for a while, we'll update all the docs and workshop materials, maybe try to convince @DragaDoncila to reprise her talk [From code stub to napari hub in 30 minutes](https://www.youtube.com/watch?v=NL-VywidzXE) with (maybe we can even just keep the same talk and edit the relevant part to add a voiceover and text on screen with the new info).

**Comment by GenevieveBuckley** [comment]
Here is the PR against the new plugin template repo: https://github.com/napari/napari-plugin-template/pull/1

**Comment by jni** [comment]
ooh, this can be closed! See https://github.com/napari/napari-plugin-template! Thanks @GenevieveBuckley for taking the lead on this!
