### ISSUE TITLE
RangeSlider labels cut off when used with Napari

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#6160]
The following issue was posted at magicgui: https://github.com/pyapp-kit/magicgui/issues/575 by @multimeric, but I believe it has to do with napari stylesheets and not magicgui.  (but, if you need anything done at superqt to make it easier to fix in napari, let me know)

**Describe the bug**
When a `RangedSlider` is used inside Napari, many of the numbers appear to be cut off. See image 1.

**To Reproduce**
I have a repo that reproduces this here: https://github.com/multimeric/napari-magicgui-cutoff.

In brief, all you need to reproduce this is a Napari widget defined like this:
```python
from magicgui import magic_factory

@magic_factory(x={'widget_type': 'RangeSlider', 'max': 50})
def example_magic_widget(x: tuple[int, int]):
    print(f"you have selected {x}")
```

**Expected behavior**
I expect none of the labels to be cut off (see image 2)

**Screenshots**
![Screen Shot 2023-08-17 at 2 38 11 pm](https://github.com/pyapp-kit/magicgui/assets/5019367/c24e0131-871a-45cf-aa9b-2267b695af6a)

Compare this with a non-Napari version of a similar `magicgui` function:
![Screen Shot 2023-08-17 at 2 41 49 pm](https://github.com/pyapp-kit/magicgui/assets/5019367/f329a6d0-1475-4d82-8c34-54acd8daa0a8)

**Environment (please complete the following information):**
 - OS: MacOS 12.6 Monterey
 - backend: Qt 5.15.2
 - magicgui version: 0.7.2

-----

and my response, demonstrating the napari stylesheet is probably involved:

thanks for the clear issue @multimeric.  This is going to have to be solved on the napari side though (or possibly with communication via napari and superqt), since it's an issue with napari's style sheets.  For example, if I clear the napari stylesheet after adding it to napari:
```python
wdg = example_magic_widget()
viewer = napari.Viewer()
viewer.window.add_dock_widget(wdg)
viewer.window._qt_window.setStyleSheet("")
napari.run()
```

then the slider looks fine:
<img width="311" alt="Screen Shot 2023-08-17 at 7 11 39 AM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/64b7a28b-c8ea-4523-8506-24f46e110005">

so, it's possible that the napari style sheet is making some assumptions?

transferring this issue to napari.

**Comment by dalthviz** [comment]
Hi, just in case, I was able to reproduce this. Checking the napari style sheets definitions, seems like at least one of the rules that could be causing this is at https://github.com/napari/napari/blob/670c971c90d45f44157be46f68b9120d6425e2a2/napari/_qt/qt_resources/styles/00_base.qss#L267-L269

Since `min-width` is defined, [as the Qt docs note](https://doc.qt.io/qt-6/stylesheet-reference.html#min-width-prop), there is a possibility for the widget to be smaller than its contents.

With the rule:

![imagen](https://github.com/napari/napari/assets/16781833/262a6b85-97b7-4d03-aed5-71813f620f42)

Without the rule:

![imagen](https://github.com/napari/napari/assets/16781833/956d284f-82dd-43a8-9abb-42f3a78d7340)

Probably this rule was added to decrease the width of the line edits since shrinking the dockwidget/widget without the `min-width` rule decreases only the slider width (and maybe that's caused for another set of rules 🤔) :

![slider_width](https://github.com/napari/napari/assets/16781833/6d958265-fbae-4c66-8d8c-e09a63880525)

**Comment by dalthviz** [comment]
Note: Seems like setting `padding: 0px;` helps. So instead of https://github.com/napari/napari/blob/670c971c90d45f44157be46f68b9120d6425e2a2/napari/_qt/qt_resources/styles/00_base.qss#L267-L269

Defining the style the rule as:

```
QLabeledRangeSlider > QAbstractSpinBox {
    min-width: 5px;
    padding: 0px;
}
```

Prevents the spin boxes/slider labels to be cut off if enough space is available:

![slider_width_fix](https://github.com/napari/napari/assets/16781833/338a583e-a361-4985-9f3f-af0aff25cd41)
