### ISSUE TITLE
contrast slider only goes to 195

### ISSUE THREAD

**Issue by wiebkejahr** [napari/napari#624]
## 🐛 Bug
The contrast slider can only be adjusted to [min, max] = [0, 195].

## To Reproduce
1. load image stack (I tried with a tiff stack written by ImageJ: 16 bit, 4 dimensions)
2. data displays correctly; hovering with the mouse over a pixel displays the correct value
3. however, any pixels brighter than 195 are "white" (ie brightest color of the current colormap)
4. the contrast slider cannot be adjusted to any larger max values

## Environment
napari, 0.2.2
Qt, 5.9.6
NumPy, 1.17.2
SciPy, 1.3.1
VisPy, 0.6.1
scikit-image, 0.15.0
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python:   3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Backend:  PyQt5
GL version:  '2.1 INTEL-12.10.12'
MAX_TEXTURE_SIZE: 16384

**Comment by tlambert03** [comment]
I was actually considering making an issue about this earlier today, since I was confused about it as well.  The issue here is likely the line in `napari.util.misc.calc_data_range` that resorts to a rough estimate of the contrast limits if the image has more than 1e6 pixels (@wiebkejahr, what was the exact shape of your volume?):
https://github.com/napari/napari/blob/f747495fb45fb1d5c9eec339641d4be6a676e737/napari/util/misc.py#L272-L274

I think the 1e6 threshold might be a little bit strict.  I did some tests, and on my computer `calc_data_range` only took 2ms on cubic 100x100x100 volume.  If I relaxed it to 2e7, it took 20ms which still seems reasonable for a one-time call.  Of course that strategy only goes so far...

For very large data, perhaps there could be an attribute that stores whether clims were auto-calculated, and some event that recalculates if new data has been loaded into the view?  I know that could be a little tricky to do smoothly, but otherwise we're left with a clim range slider that will never contain some of the data.

**Comment by wiebkejahr** [comment]
>> that resorts to a rough estimate of the contrast limits if the image has more than 1e6 pixels

I was surprised why nobody had found that before, but that explains it :)

Dimensions are:
64x3x350x300 px
and especially the first planes are very dim.

I'm providing the dataset here:
https://seafile.ist.ac.at/f/c39ed737f4e24c0eb63e/
(don't want to clutter it directly into github since it's rather large)

**Comment by sofroniewn** [comment]
Thanks for catching this, I think our current approach with `napari.util.misc.calc_data_range` is suboptimal, but I'm not quite sure what to do - @jni has advocated for an approach where we look more at the dtype, i.e. is it uint8 etc., but I'm not 100% sure about that.

@tlambert03 we can certainly relax to 2e7, but curious if you or anyone else has alternative ideas for how to approach this

**Comment by tlambert03** [comment]
I agree, it's a bit hard to know how to handle it.  I do think it's important that the user need not to go into the console to access the full data range (at least on the current `_data_view`).  
Here are some options that we can 👍👎... and for the sake of discussion let's assume _very_ big data (such that directly calculating min/max would cause unacceptable lag in the UI)

- along @jni's dtype approach: if the dtype is `uint8` or `uint16`, then use the result from `calc_data_range` as the current `contrast_limits`, but set the `contrastLimitsSlider.slider_range` to the full dynamic range.
   _this would be a "full" solution for `uint` images... but not for float images.  Additionally it would create a crappy UX experience in the clim slider with `uint16` images unless we could also provide a finer-tuned slider, for instance on long-press as @jni mentioned in [#570](https://github.com/napari/napari/issues/570#issuecomment-544385722)._
- have `calc_data_range` return a tuple including whether it had to estimate or not, then if so, hook into `Image._set_view_slice` and update the `contrast_limits` range if the min/max of the current slice is outside of the bounds of the current `contrast_limits`.
   _this still doesn't work well if the user goes into volume view_
- rather than an event, have a `reset` button that the user can click to re-run `calc_data_range` on the current view. or a straight up pop-up window allowing them to enter the clims
   _while it muddies the ui a bit... i feel like providing direct user control like this is probably ultimately going to be necessary in a program like this_
- Add some buffer to the results from `calc_data_range` [e.g. 10%](https://github.com/napari/napari/issues/570#issue-502708939) to make this less likely.
   _would probably decrease the frequency of the problem... but doesn't really solve it_
- improve the `calc_data_range` function itself... use gpu/opencl if possible? 
   _i don't have any specific ideas on this_

edit ... one more thought:
- use the estimate from `calc_data_range` on data load... then start a background QThread to do the brute force calculation and update the ui when done.
   _i kinda like this idea.  It would provide an acceptable experience for most data.  Maybe not zarr array stuff, but most stuff._

**Comment by wiebkejahr** [comment]
Some thoughts to consider (coming from a microscopy background):
Given that standard scientific CMOS have 4 MP (cutting edge scientific cameras have 10 MP), and eg light sheet microscopy stacks typically contain on the order of 100 planes and/or hundreds of timepoints, I think that even 2e7 is still fairly strict. Would running a min/max to determine the range of the slider as the data is being loaded really be too slow? Loading a very large dataset, I expect having to wait and even a few seconds wouldn't bother me.
Looking at the data type would have the advantage that the slider will be "future proof" if users manipulate the data (eg rescale). However, especially microscopy images usually don't use the full available bit range: They're often 16 bit, but contain only a few hundred counts, so a slider scaling to 16 bit would be impractical to use. Maybe additional numeric controls would be nice?
I'm wondering how ImageJ/Fiji does it. Since I never found their contrast slider limits obtrusive, they must've found a reasonable way ...

**Comment by jni** [comment]
@wiebkejahr 

> Would running a min/max to determine the range of the slider as the data is being loaded really be too slow?

Yes, actually we changed from using the full data to the estimate precisely because it took forever to load e.g. Gokul's LLS dataset. 100GB at, say, 200MB/s 500s, or almost 10min. And the counterpoint is also important: speed is one of napari's founding principles, and it feels pretty magical to say, `napari.view_image(giant100gb_dataset)` and have it instantly show the first plane. This is the kind of experience we want to provide with napari.

> I'm wondering how ImageJ/Fiji does it. Since I never found their contrast slider limits obtrusive, they must've found a reasonable way ...

If I remember correctly, Fiji has a pop-up, which includes both sliders and numerical value entry.

My current thinking:

- use the dtype
- use the long-press for a finer control over the slider
- on e.g. double click, popup / slide-over to allow numerical editing of both the current min max and the min/max values of the slider.

@tlambert03 

> use the estimate from calc_data_range on data load... then start a background QThread to do the brute force calculation and update the ui when done.

I don't love this, for the same reason as above: it breaks for giant data, and we want napari to work great for giant data. Also remote data. And in many, many cases, it's a huge waste of resources. Running things in the background is sort of generally ok from a UX perspective, but it does slow other processes down, and uses battery power if you're on your laptop — often needlessly, in this case.

**Comment by tlambert03** [comment]
I agree for the most part.  but I think it's also reasonable to aim for a "it just works" experience for 90%  of use cases, while gracefully "giving up" for the giant/remote data case.  Working strictly within the principle of "performance-first", there is a lot of middle-ground between 1e6 pixels and a 100GB dataset.

**Comment by royerloic** [comment]
One simple solution is to add a margin around the approximate [min,max] values, for example by using: [min-epsilon,max+epsilon] with epsilon= 0.1*(max-min). This is also useful anyway because sometimes you want to go a little bit outside of the [min,max] range when adjusting contrast (think about outliers and the need to saturate a bit, etc...).

In theory, we should even be able to estimate a good upper-bound for epsilon that would guarantee that the true min and max are within the [min-epsilon, max+epsilon] range with high prob. Depending on the sampling  strategy I think there is a statistical sound way to make such an estimate.

**Comment by jni** [comment]
@wiebkejahr for uint8 data at least, this should have been fixed in #705. We'll work on the more general cases next. Thanks for the report and for your patience with this!

**Comment by sofroniewn** [comment]
With #837 and `0.2.10` we have significantly improved how the contrast limits range can be set both programmatically and from the GUI - by right clicking on the contrast limits slider to launch a full featured slider in a pop-up, so I am closing this issue. Please let us know if this solution has any problems for you though

**Comment by tischi** [comment]
Hi @sofroniewn @tlambert03,

May we ask what algorithm you currently use to set the contrast limits?

Experimentally we found for a unit16 3000 x 3000 pixel image:
`input range: 3, 56292 => contrast limits: 47, 17538`
This looks like you are using some quantiles for the contrast limits?!

And I think we found some issue with a _big 2D_ unit16 image that has 30000 x 30000 pixels.
`input range: 0, 63961 => contrast limits: 32, 712`
Here the upper value does not seem to make too much sense.

We are wondering what you currently do for such big 2D images (as you cannot resort to taking a subset of the planes for the computation of the contrast limits).

Thanks!

cc @sebgoti

**Comment by sofroniewn** [comment]
@tischi here is the standalone function that does the data range calculation https://github.com/napari/napari/blob/1f80f888318bebf72f034f59a947fe99cb3fc9d9/napari/layers/utils/layer_utils.py#L65-L137

It shouldn't be doing any quantile stuff - I'm surprised by `input range: 3, 56292 => contrast limits: 47, 17538`. Can you test that again using just the stand along function.

We do have to do some funny things for really big data so as to make sure we don't instantiate all of it

> And I think we found some issue with a big 2D unit16 image that has 30000 x 30000 pixels.

was this multiscale data? then maybe the upper value came from the lowest resolution?

we've definitely struggled with this function though. Hopefully you can reproduce any strange behavior with this function alone and then we can try and improve.
