### ISSUE TITLE
Callbacks when slider change

### ISSUE THREAD

**Issue by aasensio** [napari/napari#630]
Although Napari mouse events can be easily intercepted with decorators, other events are not so easily captured. I've managed to plot some features of the input n-cube in a separate PyQtGraph window as a response to mouse motion. However, I also want to do changes when the dimension sliders are changed. I've managed to connect a callback function with `viewer.dims.events.connect(update_slider)`. Is this considered the canonical way of doing that or are you thinking of exposing Qt events similarly to mouse events? Additionally, I only find the proper indices updated on real time on the `event._sources[0]._point`. Is this corrrect? Here you can find the code that updates the PyQtGraph window while moving the cursor on the Napari canvas.

    class stokes_plot(object):

        def __init__(self):
            self.left = 10
            self.top = 10
            self.title = 'Stokes Viewer'
            self.width = 640
            self.height = 400
        
            self.win = pg.GraphicsWindow(title="Signal from serial port") # creates a window

            self.plots = self.win.addPlot(title="Stokes I", row=0, col=0)
          
            self.lambda_pos = pg.InfiniteLine(pos=0, angle=90)
            self.plots.addItem(self.lambda_pos)

            self.curve_stokes = self.plots.plot()

        def plot(self, stokes, ind_lambda):        

            if (stokes is not None):
                self.curve_stokes.setData(stokes[0,:])
              
            self.lambda_pos.setValue(ind_lambda)
            
    if __name__ == '__main__':
        f = h5py.File('ar11967.h5','r')

        stokes = np.transpose(f['stokes'],axes=(0,3,1,2)) 
        nx, ny = stokes.shape[2:]

        with napari.gui_qt():
            viewer = napari.Viewer()

            stokesi = viewer.add_image(stokes[0,:,:,:], name='Stokes I')

            app = QtGui.QApplication([])
            stokes_1d = stokes_plot()

            def update_slider(event):
                ind_lambda, _, _ = event._sources[0]._point
                stokes_1d.plot(None, ind_lambda, plot_stokes=False)
            
            def action(viewer, event):
                ind_lambda, ind_x, ind_y = np.round(viewer.coordinates).astype('int')
                if ( (ind_x > 0) and (ind_y > 0) and (ind_x < nx) and (ind_y < ny) ):
                    stokes_1d.plot(stokes[:,:,ind_x,ind_y], ind_lambda)

            def check_exit(viewer, event):
                if (event.button == 2):
                    sys.exit()

            @viewer.bind_key('q')
            def exit(viewer):
                sys.exit()

            @stokesi.mouse_move_callbacks.append    
            def action_stokesi(viewer, event):        
                action(viewer, event)
            
            viewer.dims.events.connect(update_slider)    
            
            pg.QtGui.QApplication.exec_()

**Comment by sofroniewn** [comment]
Hi @aasensio - very exciting to see you building on top of napari in this way, and we definitely want to provide easy access to our event system to make this an even smoother process.

We're still figuring out how to do this in the best way possible - but you can get a sense of how we and others have been thinking about it in these two issues: https://github.com/napari/napari/issues/209#issuecomment-540775628 and https://github.com/napari/napari/issues/531#issuecomment-544766877

That first issue links out to some code that includes a custom callback triggered on movement of the dimensions slider - see this [line here](https://github.com/sofroniewn/image-demos/blob/2e3a75d6ebb069027e28e1023386ca9fe2f9a733/examples/image_annotations.py#L92).

The main difference with what you have is that were connecting to the specific `axis` event on `viewer.dims` rather than all the `dims` events, which I think will be much cleaner if you just want an event triggered when the slider is moved. The `axis` event will also contain a property `event.axis` that allows you to determine which axis was the one moved. The `point` property is the one that is updated during the movement of the sliders, but we tend to use the `indices` property as the will contain all the information about slicing if needed. It shouldn't make a difference here.

You might want to try some code like the following (note I havn't tested this)
```python
def update_slider(event):
    # only trigger if update comes from first axis (optional)
    if event.axis == 0:
        ind_lambda = viewer.dims.indices[0]
        stokes_1d.plot(None, ind_lambda, plot_stokes=False)

viewer.dims.events.axis.connect(update_slider)
```

Let us know if that works, or if you would prefer to get access to events in a slightly different way. Also if you had a gif / screenshot of what this looks like that you can post in the thread I'd be really curious to see it!!

**Comment by aasensio** [comment]
Hi @sofroniewn - your suggestion works nicely. Since it involves accessing objects from out of the function I wonder whether it makes more sense to provide this information via the `event` variable. Apart from that, I think it might be confusing for some people that mouse events are treated with decorators but the rest of Qt events are done with `connect`. Perhaps it makes sense to unify the approach to deal with events. Anyway, I'm really happy with napari and will use it extensively from now on. It's true that gives you a completely different view of the n-cube than simply doing 2D cuts. 

Here you have an example of napari and PyQtGraph together. The data is spectropolarimetry of a sunspot. Each layer refers to the four Stokes profiles that define polarization and are 3D cubes. The PyQtGraph window displays the spectra for two spectral lines at the selected (x,y) position. The vertical line shows the position of the slider.

![Oct-28-2019 09-27-34](https://user-images.githubusercontent.com/1766597/67667220-3fdd6d80-f965-11e9-86cb-37748be9df4e.gif)

**Comment by jni** [comment]
@aasensio :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: 

That's gorgeous! One of the things we want to add very soon is a histogram "drawer", so that's a fantastically useful demo for us! Do you have the source code available somewhere?

btw do you mind if I tweet this image??? With attribution of course. =)

**Comment by jni** [comment]
**Update:** Apologies if the code is the snippet above — I got the feeling from your response that you had updated it based on @sofroniewn's comment.

**Comment by aasensio** [comment]
Here is the [code](https://gist.github.com/aasensio/cb46290686a808c838bcabd01cf9bde2) with  @sofroniewn's suggestion. Feel free to tweet the image. I've been looking for a tool like this for ages :smile:

**Comment by sofroniewn** [comment]
Such a cool demo!! I think @d-v-b wanted something like this too.

> unify the approach to deal with events

Yup agree with this, I think we can make it such that you can use a decorator and we'll connect under the hood, possibly providing you access to `viewer` or `layer` depending on what you connect to. This would probably be the most consistent from an api standpoint

**Comment by berl** [comment]
@sofroniewn I like the ability to do the `connect`ing myself in my subclass of `napari.Viewer`
e.g.  when adding layers, `self.layers[-1].events.contrast_limits.connect(self.sync_clims)` to synchronized clims across layers.

  Ignorance showing here: I'm not sure how I would accomplish the decorator version of this ^^ inside my `viewer`.

**Comment by sofroniewn** [comment]
yeah, we'd have to see - I don't think the `connect` syntax would go away, we might just make it so you don't have to use it

**Comment by joaomamede** [comment]
This doesn't work in current napari version. viewer.dims.events.axis doesn't seem to exist anymore.
I tried this instead (to have timelapse info to update) but it fails

```
import numpy as np
import napari
from napari.qt import thread_worker
import time


def update_slider(event):
    # only trigger if update comes from first axis (optional)
    if event.axis == 0:
        #ind_lambda = viewer.dims.indices[0]
        time = viewer.dims.current_step[0]
        viewer.text_overlay.text = f"{time:1.1f} time"


viewer = napari.Viewer()
viewer.add_image(np.random.random((5, 5, 5)), colormap='red', opacity=0.8)
viewer.text_overlay.visible = True
viewer.dims.events.current_step.connect(update_slider)


napari.run()
```

**Comment by joaomamede** [comment]
This works:

```
import numpy as np
import napari
from napari.qt import thread_worker
import time


def update_slider(event):
    # only trigger if update comes from first axis (optional)
    print('inside')
        #ind_lambda = viewer.dims.indices[0]
    time = viewer.dims.current_step[0]
    viewer.text_overlay.text = f"{time:1.1f} time"


viewer = napari.Viewer()
viewer.add_image(np.random.random((5, 5, 5)), colormap='red', opacity=0.8)
viewer.text_overlay.visible = True
viewer.dims.events.current_step.connect(update_slider)


napari.run()
```

**Comment by tlambert03** [comment]
you were on the right track with `dims.events.current_step`... but the event object itself has changed too.  It no longer has an axis... 
doh... you beat me to it :)

```python
import numpy as np
import napari

viewer = napari.Viewer()
viewer.add_image(np.random.random((5, 5, 5)), colormap='red', opacity=0.8)
viewer.text_overlay.visible = True

@viewer.dims.events.current_step.connect
def update_slider(event):
    time = viewer.dims.current_step[0]
    viewer.text_overlay.text = f"{time:1.1f} time"

napari.run()

```

**Comment by sofroniewn** [comment]
@tlambert03 do we have this documented in our examples anywhere? Maybe we want to add an example and then close this issue?

**Comment by tlambert03** [comment]
don't think so, but #2750 would definitely help here!

**Comment by tlambert03** [comment]
> Maybe we want to add an example and then close this issue?

fine with me, @joaomamede, would you be willing to add this example in a PR?

**Comment by joaomamede** [comment]
I have no idea how to do that! (sorry the silence since May)

**Comment by sofroniewn** [comment]
Note for anyone coming to this issue, I think the only thing to do here is better document our events - #2750 could help here too

**Comment by TeunHuijben** [comment]
Sorry for coming back to this issue, it might just be me not being able to find it in the documentation. But can someone help me with finding the slider that caused the event? 

I can successfully connect a callback upon slider change: `viewer.dims.events.current_step.connect(my_func)`,
but then I am no longer able to detect the slider that caused the event using: `event.axis` within `my_func`. 

How can I find the slider that caused the event? 

Thanks a lot for the help :)

**Comment by jni** [comment]
Ha, don't apologise, this was a nice blast from the past. 😃 

So, in a sense, the "slider that caused the event" is not well-defined, because I can (e.g. from another plugin) do:

```
viewer.dims.point = (45, 20, 256, 256)
```

and change all axes at once, without touching a slider.

However, if you are only interested in users moving sliders around in the GUI, you can check `viewer.dims.last_used`, or `event.source.last_used` (`event.source` is just a reference to `viewer.dims`.)

If you want to get more sophisticated, on your end you can remember the previous value of the slider and then find out the axes that changed. That is probably the more general approach for cases where multiple axes are changed at once.

I hope that helps your use case!

In the meantime, I don't think this particular issue is a problem anymore (there's lots of examples out there for connecting to napari events, and current_step in particular), so I might close it. But feel free to keep asking questions here, on [Zulip](https://napari.zulipchat.com), or on [image.sc](https://forum.image.sc/tag/napari)!

And just btw @aasensio we never got to do our colormap overlays 😅 sorry about that! I think the machinery for doing that is very close right now. I could help you or someone in your group implement those. Feel free to shoot me an email if that would be helpful! 😊

**Comment by TeunHuijben** [comment]
Thanks @jni!! The solution for remembering the previous position works nicely :)
