### ISSUE TITLE
Wish for conda package

### ISSUE THREAD

**Issue by petrushy** [napari/napari#635]
## 🚀 Feature
It would be nice with a conda package for this tool

## Motivation

Conda packages simplifies installation and potential dependencies. It has become a popular way to install scientific python packages.

https://conda-forge.org/

**Comment by jni** [comment]
Thanks @petrushy for the suggestion! We are actually working on a conda-forge package here:

https://github.com/conda-forge/staged-recipes/pull/9983

Still need to figure out a bad interaction between PyQt5 and PySide2...

**Comment by petrushy** [comment]
Ah great :) I have unfortunately not experience in qt problems..

**Comment by sofroniewn** [comment]
@jni @jakirkham can this now be closed? I think napari can now be installed with

```
conda install -c conda-forge napari
```

When we make new releases to pip will conda-forge then automatically start using the newest release or do we need to do something to make that update? What is the recommended way after / during the release process to make sure the new conda-forge release works? Do we need to add something to our test script plan in napari/napari-release-tools#23 @jni. 

Apologies if these basic questions are answered in the conda-forge docs, but if we have to do anything at all we should add it to the napari release procedure docs otherwise i at least will forget.

Finally, it looks like both the feed-stock and the package are listed as BSD-03 (see here https://github.com/conda-forge/napari-feedstock), I just want to check that is ok and that we aren't actually distributing any LGPL Qt code ourselves here (in which case the license would have to be LGPL, as it will be for our bundled apps)

**Comment by sofroniewn** [comment]
@jni I am closing this based on comments above

**Comment by jakirkham** [comment]
Yeah sorry for the slow reply. I think this is solved already.
