### ISSUE TITLE
`show_info()` not working when running napari from a Jupyter notebook

### ISSUE THREAD

**Issue by LucaMarconato** [napari/napari#6455]
### 🐛 Bug Report

`show_info()` doesn't work when I run napari from a Jupyter notebook. Everything is fine when I run napari from a script. Below is code to reproduce this.

### 💡 Steps to Reproduce

Run this code in a Jupyter notebook and the click anywhere on the image.

```python
from napari.utils.notifications import show_info
import napari
from skimage import data

viewer = napari.Viewer()
layer = viewer.add_image(data.astronaut(), name='astro')

@layer.mouse_drag_callbacks.append
def update_tooltip(layer, event):
    show_info(f'{event.position}')
napari.run()
```

### 💡 Expected Behavior

On click, it should show the notification on the bottom like in the screenshot
<img width="1035" alt="image" src="https://github.com/napari/napari/assets/2664412/6969a591-088c-4ca8-a395-78a2322aa5cc">

### 🌎 Environment

napari: 0.4.16
Platform: macOS-13.4.1-arm64-arm-64bit
System: MacOS 13.4.1
Python: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.24.4
SciPy: 1.9.1
Dask: 2023.10.1
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2056x1329, scale 2.0

Plugins:
- napari-console: 0.0.9
- napari-matplotlib: 1.2.1.dev2+g7b6a4a4
- napari-spatialdata: 0.1.0
- napari-svg: 0.1.10
- scikit-image: 0.4.16

**Comment by Czaki** [comment]
Explanation:

Because jupyter starts ow qt event loop the `get_app()` called from `napari.run()` function does not connect `NapariQtNotification` dispatchers to `notification_manager` signals. 

https://github.com/napari/napari/blob/8ed7f4c62fa607ed1f832b140043559b0b4683d9/napari/_qt/qt_event_loop.py#L191-L197

In meantime, we update the guard in `NapariQtNotification.show_notification` to not trigger a notification if there is no main window in #4839  

https://github.com/napari/napari/blob/8ed7f4c62fa607ed1f832b140043559b0b4683d9/napari/_qt/dialogs/qt_notification.py#L380-L396

So we may should revisit our design decision.

**Comment by psobolewskiPhD** [comment]
I ran into this today. Pretty important use-case, particularly for keybindings, because printing prints to the Jupyter so it's not readily visible in napari if you are working on a smaller screen. Definitely should aim to fix this (lack of) interaction.

@Czaki Is there any workaround that could be used in the meanwhile?

**Comment by Czaki** [comment]
> OK, LOL, so **it works from iPython** but shouldn't.
> Here's the `_ipython_has_eventloop()`:

Did you run ipython with qtbackend? 



> @Czaki Is there any workaround that could be used in the meanwhile?

Manually perform this steep? 

```python
     notification_manager.notification_ready.connect( 
         NapariQtNotification.show_notification 
     ) 
```

And we should check if we could perform bind always. `if` was introduced in #2633

**Comment by psobolewskiPhD** [comment]
I  just typed `ipython` in my terminal in an env with just napari and jupyterlab. So I'm not sure what backend, but it returned `qt5` so safe to assume qt. i didn't run any magics.

**Comment by Czaki** [comment]
Ok. I see. 
We should dig now if the `if` guard is still needed.

**Comment by psobolewskiPhD** [comment]
What I don't get is why jupyter gets caught by that `if`
From jupyter, all that code works and `shell.active_eventloop` returns None, so the logic should fire, because `shell.active_eventloop == 'qt'` returns False

**Comment by psobolewskiPhD** [comment]
Dropping the `if` seems to work fine with jupyter and ipython, but I'm not sure how to test this better

**Comment by Czaki** [comment]
I think that you should make a PR with remove of this if. Then it will be present on main and maybe someone will report some problem if any exists.

**Comment by LucaMarconato** [comment]
I have tried https://github.com/napari/napari/pull/6882 and the problem is solved! Thanks a lot!
