### ISSUE TITLE
How to import matlab function /GUI into napari

### ISSUE THREAD

**Issue by jinxsfe** [napari/napari#6500]
### Overview of design need

Hi, I created a creating function for Matlab and built GUI for 3D virus particle detection. Still, my question is how to import the Matlab function & GUI that I created into Napari so that we can use it directly into Napari? are there any ways to solve that until now?

Thanks

**Comment by jni** [comment]
@jinxsfe integration with Matlab is not a design goal of napari, much less integration with a Matlab GUI — which I think is probably more or less impossible. My recommendation is that you build a small Python library (library, not UI) that calls out to your Matlab functions, and make a napari plugin using [magicgui](https://pyapp-kit.github.io/magicgui/) to wrap your Python code. There's a lot of tutorials to do this, for example [this one from the magicgui docs](https://napari.org/stable/guides/magicgui.html), [this YouTube video for how to turn Python code into a plugin](https://www.youtube.com/watch?v=NL-VywidzXE), and [this tutorial from the BiAPoL folks](https://biapol.github.io/Quantitative_Bio_Image_Analysis_with_Python_2022/day4c_crafting_napari_plugins/readme.html). Mathworks has some documentation for calling Matlab from Python [here](https://mathworks.com/products/matlab/matlab-and-python.html).

Longer term, I suggest just porting all your code to Python, as that will make it much easier to integrate with the wider scientific Python ecosystem. These days it is quite easy to port Matlab to Python, see e.g. [NumPy for Matlab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html).

Since this is not a napari issue, I am going to close it now, but feel free to ask more questions in this thread. Hopefully the above links help you get your work done!
