### ISSUE TITLE
Allow large image visualization 

### ISSUE THREAD

**Issue by YubinXie** [napari/napari#652]
## 🚀 Feature

When I load a large image, it gave error `PIL.Image.DecompressionBombError: Image size (322907280 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.`

I have seen this in other cases, which is due to the limit of PIL. 
## Motivation

In histology, whole slide image can be very large.

## Pitch

I think either hack the PIL package a little bit to remove the size limitation, other package to replace PIL for reading...

**Comment by AhmetCanSolak** [comment]
@YubinXie do you have an alternative way to read that big file into a numpy array? If so i would suggest read data in numpy array your way, then add to viewer in a script like in example scripts?

**Comment by YubinXie** [comment]
@AhmetCanSolak 

Actually I just found most packages use PIL as backend. We have to change the max pixel setting in PIL. It works after I put the following code in console.

'''
from PIL import Image
Image.MAX_IMAGE_PIXELS = 1000000000   
'''

**Comment by jni** [comment]
@YubinXie Thanks for the workaround! Given that this is expected behaviour and a general problem with PIL, I am inclined to close this. It might be worth raising an issue with PIL itself. At a minimum, the error message should describe this workaround.

@sofroniewn @AhmetCanSolak any thoughts? Would we want to increase that PIL maximum at napari import time? My impression is that this amounts to monkey patching, which is generally not well-regarded, *and* anyway, deciding on a reasonable limit is context-dependent...

**Comment by sofroniewn** [comment]
I agree this should be more with PIL, but thanks for raising @YubinXie. If we see people consistently having this problem we can revisit, add a note in documentation. I will close for now
