### ISSUE TITLE
default orange colormap should go black -> orange rather than white -> orange

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#6605]
### 🐛 Bug Report

Hey! The default cmap for 'orange' is white -> orange, this is in contrast to other colormaps named after colors (e.g. 'blue' which goes from black -> color)
<img width="177" alt="image" src="https://github.com/napari/napari/assets/7307488/54e8e8bc-5274-4b1e-80ee-e0ecae87c9d0">

This makes 'orange' not work well with 'blue' or other simple name cmaps

Looks like 'orange' = 'I_orange' so the fix is probably just to change the default behaviour of 'orange'?

### 💡 Steps to Reproduce

n/a

### 💡 Expected Behavior

blending should have just worked when adding images with simple name colormaps

### 🌎 Environment

napari: 0.4.18
Platform: macOS-14.1-arm64-arm-64bit
System: MacOS 14.1
Python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.3
SciPy: 1.11.4
Dask: 2024.1.0
VisPy: 0.12.2
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 88
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1512x982, scale 2.0

Settings path:
  - /Users/burta2/Library/Application Support/napari/libtilt_12b88b92109c30fc1b7095712e52e52ef14c583e/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

**Comment by psobolewskiPhD** [comment]
Where is that `orange` color map coming from? I don't have it in my 0.4.18:
<img width="342" alt="image" src="https://github.com/napari/napari/assets/76622105/b8368e36-c5e5-4604-abbf-b5530310e402">

```
napari: 0.4.18
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.2
SciPy: 1.11.4
Dask: 2023.12.1
VisPy: 0.12.2
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.3
npe2: 0.7.3

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-418_ff44c429019beeb6bb1d5a86a0c4c143d37e89da/settings.yaml

```

**Comment by alisterburt** [comment]
Hey @psobolewskiPhD - sorry for the delay here 

I just did this again in a fresh env and although the colormap is not there initially, it is there as soon as I've run

```python
viewer.add_image(a, colormap='orange')
```

there must be some mechanism for inferring colormaps by the nearest named colormap?

**Comment by psobolewskiPhD** [comment]
Hi @alisterburt 
This has turned into a really great puzzle that @Czaki and I have figured out.
So on 0.4.18 you are *actually* seeing the correct colormap--it should go from white to orange--because you are passing the proper name of an existing vispy colormap and  it so happens that the vispy `orange` colormap is from white to that orange hue:
https://github.com/vispy/vispy/blob/269ed1ac4d8126421fd5a7eb06a2996d63f46b17/vispy/color/colormap.py#L1070C5-L1070C30
(you can try `light_blues` to see that all SingleHue vispy colormaps go from white to the color, see the class here:
https://github.com/vispy/vispy/blob/269ed1ac4d8126421fd5a7eb06a2996d63f46b17/vispy/color/colormap.py#L608-L613 )

If you wanted black to orange on 0.4.18 you'd need to use `bop_orange` or construct it yourself using `vispy.color.Colormap`

**However** on `main` or o.4.19rc, this is different and using the string "orange" give you a black to orange colormap, because of https://github.com/napari/napari/pull/6102 
This PR added a feature of making a custom colormap when passing a **color name** and those colormaps are starting with black. Further, in this PR (inadvertently I assume) this custom colormap actually takes precedence over vispy and Matplotlib colormaps, so when you use "orange" you get the custom black to orange colormap rather than the proper vispy one. "orange" happens to be the only word that is both a color name and the proper name of a vispy colormap, so this is the only case where behavior will change.
So it's amazing you ran into it!

Hopefully this explanation means we can close this issue. But it also reminded us about that PR which isn't a bug fix like the rest of 0.4.19 so it's worth adding it to Highlights along with a note of the changed behavior. We can also consider whether a PR to swap the priority makes sense, but it would only affect that one color/colormap "orange".

**Comment by alisterburt** [comment]
hahaha, wonderful! Glad it was an interesting adventure and thanks for the update here :-)

**Comment by psobolewskiPhD** [comment]
The supreme irony in all of this is that the lookup from color name to a color hex is **also** via vispy:
https://github.com/vispy/vispy/blob/269ed1ac4d8126421fd5a7eb06a2996d63f46b17/vispy/color/_color_dict.py#L181
