### ISSUE TITLE
layers stay linked even after removal

### ISSUE THREAD

**Issue by Chris-N-K** [napari/napari#6619]
### 🐛 Bug Report

If you link two layers and remove one of them the link remains in the global _LINKED_LAYERS dictionary causing errors.

### 💡 Steps to Reproduce

1. Add two layers to the viewer
2. Link the two layers
3. Remove one layer
4. Either right click the remaining layer and click on `Select Linked Layers` to cause an error or check the `napari.layers.utils._link_layers._LINKED_LAYERS` global dictionary to see the remaining link ref

### 💡 Expected Behavior

The link ref should be removed if the corresponding layer is removed.

### 🌎 Environment

napari 0.4.18 and all 0.4.19rc

### 💡 Additional Context

There should be a event callback to remove the ref upon a layer `removed` event from the corresponding layer.

**Comment by Czaki** [comment]
There are two problems here. 

First. Layer is not deleted after removing from viewer. There is some reference that keeps it alive. 
Second. As we prepare for multicanvas we cannot assume that all linked layers will be in the layer list.

**Comment by psobolewskiPhD** [comment]
@Chris-N-K 
Thanks for the issue!
In testing this and #6622 I came across a number of other linked layer issues!
I've made a PR #6623 
Do you use them much? Can you see if anything is broken in your workflows?
I suspect they are not broadly utilized...

**Comment by Czaki** [comment]
The references are kept alive because of using local functions for synchronisation:

https://github.com/napari/napari/blob/737ae894b3e80d3bfdef47fd216811c7795042a6/napari/layers/utils/_link_layers.py#L123-L127

Both Qt, psyganl, and our napari Events are not keeping alive object if connected is by method. 
There is inner conversion to wekreference. But local functions are not easy to deal with them automatically. And local functions connected to signal will keep objects alive. 

> Do you know why the connected layer references live in a global variable and not in a layer property?

this is the only helper variable that stores weak reference and is used only for properly unlinking. Maybe it could live in distributed form in layers, but it is not a problem here.

**Comment by psobolewskiPhD** [comment]
BTW, I see strange behavior with _LINKED_LAYERS, maybe I don't understand it fully. It doesn't seem to update when unlinking.
This does work:
```
from napari.layers.utils._link_layers import get_linked_layers

get_linked_layers(viewer.layers[-1])
Out[2]: 
{<Points layer 'Points [1]' at 0x29e7f0050>,
 <Points layer 'Points [2]' at 0x2a9c3e0d0>}

....... delete Points [1] using GUI ...........

get_linked_layers(viewer.layers[-1])
Out[3]: 
{<Points layer 'Points [1]' at 0x29e7f0050>,
 <Points layer 'Points [2]' at 0x2a9c3e0d0>}
```
With my PR, this returns just the single linked layer properly.
