### ISSUE TITLE
Lazy loading of sub-regions of a 3D without a pyramid structure and using only TIFFs

### ISSUE THREAD

**Issue by raacampbell** [napari/napari#663]
## 🚀 Feature
Navigating very large datasets can currently be done using multiresolution zarr files or by loading whole image planes one at a time (similar to the way Fiji does this). The former requires data duplication and the second is slow. An intermediate approach, very helpful for certain datasets, is to generate a downsampled version of the image stack which is loaded into RAM and the user can navigate. When the user zooms in beyond a certain point, the viewer loads that portion from the full size image stack. 

## Motivation
The above approach is well suited to data that aren't isotropic. Image data can be stored as TIFFs and don't need to be converted into a new format. The downsampled stack the user navigates can be small (about 5% of the original dataset), so little extra disk space is needed.

We have created such a viewer in MATLAB ([MaSIV](https://github.com/SainsburyWellcomeCentre/masiv
) at the SWC and it has been very helpful for us. Unfortunately it handles only one channel at a time because image display in MATLAB is rather slow. We were thinking of porting MaSIV's loading strategy to [Lasagna](https://github.com/SainsburyWellcomeCentre/lasagna) (See #662 ) but we now are considering mothballing this software and moving to napari. 

It ought to be possible to quickly load sub-regions of a large tiff with [gdal](https://gdal.org/). The [`ReadAsArray` method is capable of reading a sub-region of a TIFF image rapidly](https://gis.stackexchange.com/questions/65840/subsetting-geotiff-with-python), so could be a way of implementing this. 

We may be able to help develop this feature if you can give a few pointers as to how best to approach it within napari's framework.

**Comment by d-v-b** [comment]
Probably your use case would be a special case of the general issue described in #318 -- if napari had an API for lazily rendering 2D tiles of an image, then you could define an image as a grid of (lazy) tiff tiles, and everything would just work (hopefully).

**Comment by sofroniewn** [comment]
Hi @raacampbell, better support for image pyramids / lazy loading is something that a number of users have requested, so working together on this would be great.

Also nice to hear from you again, we met out at the mesoscope workshop at Janelia a couple years back, and it would be great if the SWC was interested in using napari!!

We've had a feature request for autogenerating the pyramid when needed here https://github.com/napari/napari/issues/537 which we implemented, but this was for cases where you could fit the whole image in RAM, but a given slice was too big for the graphics card, or just too slow to work with.

Can you explain a little more:

> generate a downsampled version of the image stack which is loaded into RAM

Are you imagining that you'll be storing the downsampled data inside your tif? i.e. are you proposing a convention for tif with multiresolution data stored on disk, rather than generating that downsampled data on the fly each time you load the file (which maybe very slow). If so are you considering using any of the existing multiresolution tif conventions? There are some from the pathology community that [openslide](https://openslide.org/) can read - for example the data used in this [pathology challenge](https://camelyon16.grand-challenge.org/Data/). Or do you already have a tif convention established at the SWC that you want to read? I'm less familiar with GeoTIFF and gdal, but as you mention they might be useful here too.

Regardless, the best way to get this working within napari is to use [dask](https://dask.readthedocs.io/en/latest/) or some of the tricks in [dask image](https://dask-image.readthedocs.io/en/latest/) to wrap the loading of the data inside a dask array.

Thinking first about only your high resolution data, you want to use things like `dask.delayed` and `dask.array.from_delayed` to described how to do the reading of your data into the big array as is done in [`dask-image.imread`](https://dask-image.readthedocs.io/en/latest/_modules/dask_image/imread.html#imread).

If you can then get a list of dask arrays going from highest to lowest resolution you can then call
```python
my_list_of_dask_arrays = [highest_res, medium_res, low_res]
napari.view_image(my_list_of_dask_arrays, is_pyramid=True)
```
and it should just work!

**Comment by raacampbell** [comment]
Good to hear from you also, @sofroniewn 

The scheme is simple and effective goes like this:
* Raw data are 1 large TIFF for each optical plane and each channel. Say images are at 1x1x10 mics/pixel. 
* User generates a downsampled stack for each channel. We have used about 5 to 10 microns per pixel x/y in the past. Every z-plane is downsampled. Resulting stack is about 5 to 10 GB for a mouse brain (one channel).
* This stack is saved to disk. 
* The viewer loads the stack and the user can pan in X/Y and scroll through optical sections.
* When the user zooms beyond a defined amount, the viewer loads from the disk that region of the full size tiff and presents this to the user. 
* Optionally, data from adjacent optical planes can be cached. With this enabled the above scheme works well over the network. 

This has the advantage that the data aren't duplicated and it's surprisingly quick. It works very well for browsing things like coronal sections from serial-section 2p and annotating them, since these data are often not isotropic. It of course won't work if you want fast access to orthogonal views, but you already have a solution for this.

**Comment by sofroniewn** [comment]
Makes sense - I'd say give that a go with the lazy dask loading of the high-resolution information and then you'll just need to do

```python
napari.view_image([high_res_dask, downsampled_numpy_stack], is_pyramid=True)
```

right now napari will guess at where to make the resolution transition in the zoom, if it isn't in a good place let us know and we can improve the guessing or give you more control over it.

You might also want to checkout the [dask caching](https://docs.dask.org/en/latest/caching.html#automatic-opportunistic-caching) options too.

Let us know how it goes, especially if you run into trouble making that lazy dask array.

**Comment by raacampbell** [comment]
Ok, thanks. I don't have immediate plans to look into this, but if I do I will let you know. It's on my radar, for sure.

**Comment by liu-ziyang** [comment]
Hi there, I would like to close this issue to consolidate our recent effort on the async implementation plan. Thanks! (if you would like to know more about this plan, we are aggregating it here as a starting point: https://github.com/orgs/napari/projects/16)

**Comment by raacampbell** [comment]
Sure thing, thanks.
