### ISSUE TITLE
Shapes `Convert to Labels` layer list contextual menu is greyed out for new layer, need to reselect the layer

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6643]
### 🐛 Bug Report

If you add a shapes layer and draw some shapes and then right-click to try to Convert to Labels, the option is greyed out. 

<img width="712" alt="image" src="https://github.com/napari/napari/assets/76622105/e68e4b47-6446-4e92-b619-77d69dc73ff6">

This makes it hard to discover the usability of this menu option.
Deselecting and reselecting the layer makes it show properly.

<img width="326" alt="image" src="https://github.com/napari/napari/assets/76622105/83969681-6be7-4900-9957-8d326b7e03bc">

### 💡 Steps to Reproduce

1. Add a new Shapes layer
2. Draw a shape
3. Right-click to get the layer list contextual menu

### 💡 Expected Behavior

The Convert option should be available regardless if the layer was re-selected.

### 🌎 Environment

napari: 0.5.0a2.dev543+gad78ee21a
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.3
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

### 💡 Additional Context

Also occurs on 0.4.19
For Labels, Convert to Image is immediately functional without any re-selection.
For Images, Convert to Labels is immediately functional without any re-selection.

**Comment by psobolewskiPhD** [comment]
Yup, that's what I got in my debugging. 
This function:
https://github.com/napari/napari/blob/23110921d0f1ede34f927092d25ed9947fa25b68/napari/_app_model/context/_layerlist_context.py#L166-L167

**Comment by dalthviz** [comment]
So explicitly doing an update for the `selected_empty_shapes_layer` makes the action state (enabled/disabled) behave in the correct way. So, by doing something like this over the `show_context_menu`:

```python
    def show_context_menu(self, index, model, pos: QPoint, parent):
        """Show the layerlist context menu.
        To add a new item to the menu, update the _LAYER_ACTIONS dict.
        """
        if not hasattr(self, '_context_menu'):
            self._context_menu = build_qmodel_menu(
                MenuId.LAYERLIST_CONTEXT, parent=parent
            )

        layer_list: LayerList = model.sourceModel()._root
        ctx = get_context(layer_list)
        ctx.update(
            {
                "selected_empty_shapes_layer": _empty_shapes_layer_selected(
                    layer_list.selection
                )
            }
        )
        self._context_menu.update_from_context(ctx)
        self._context_menu.exec_(pos)
```

Checking, I think the context update is already being connected with to some of the layerlist events at https://github.com/napari/napari/blob/23110921d0f1ede34f927092d25ed9947fa25b68/napari/components/layerlist.py#L93-L108

Maybe there is another event that is not being connected there that could handle/detect when an item data changes? Or maybe a way to get the most up to date values/trigger keys recomputation from the context should be somehow implemented?

**Comment by psobolewskiPhD** [comment]
Hmm, I don't like updating just that one thing when we make the menu -- what about the other conditions? We may have other bugs due to the lack of sync.
I think connecting to data change would be bad too, because 99% of the time the update would be useless--could cause performance issues?

What I've been trying to do is trigger that update manually, when the menu is opened, so when `show_context_menu` is called in the delegate.
I don't really get this app model stuff though 😢

**Comment by dalthviz** [comment]
Following the idea to be able to trigger an update using the most updated selection values from the delegate, seems like adding to the `LayerListSelectionContextKeys` class definition a method to pass the selection which values want to be reflected over the context could help:

* At https://github.com/napari/napari/blob/4f4c063ae5dd79d6d188e201d44b8d57eba71909/napari/_app_model/context/_layerlist_context.py#L170 we could add to that class something like:

```python
    def update_by_selection(self, selection):
        """Update context with the given selection."""
        for k, get in self._getters.items():
            setattr(self, k, get(selection))
```

* Then the `LayerList` class definition at https://github.com/napari/napari/blob/4f4c063ae5dd79d6d188e201d44b8d57eba71909/napari/components/layerlist.py#L28 can have something like:

```python
    def selection_ctx_update(self):
        self._selection_ctx_keys.update_by_selection(self.selection)
```

* And then, from the layer delegate `show_context_menu` method at https://github.com/napari/napari/blob/4f4c063ae5dd79d6d188e201d44b8d57eba71909/napari/_qt/containers/_layer_delegate.py#L307 you could call this to be sure the layerlist selection context is actually up to date with the current layerlist selection:

```python
    def show_context_menu(self, index, model, pos: QPoint, parent):
        """Show the layerlist context menu.
        To add a new item to the menu, update the _LAYER_ACTIONS dict.
        """
        if not hasattr(self, '_context_menu'):
            self._context_menu = build_qmodel_menu(
                MenuId.LAYERLIST_CONTEXT, parent=parent
            )

        layer_list: LayerList = model.sourceModel()._root
        layer_list.selection_ctx_update()
        self._context_menu.update_from_context(get_context(layer_list))
        self._context_menu.exec_(pos)
```

Still not totally sure if there is a better approach/this a correct approach (my app-model knowledge is quite limited too 😅 ) but sharing the findings/possible fix I came up with. Here a branch if you want to give the code a more in context check: https://github.com/napari/napari/compare/main...dalthviz:napari:issue_6643

**Comment by lucyleeow** [comment]
I'll take a look!

**Comment by Czaki** [comment]
Why do we use a dict with context instead of calculating it dynamically? 

https://github.com/pyapp-kit/app-model/blob/7f853e606daee0356cc6751e6a6e882c7179724e/src/app_model/expressions/_context.py#L151-L153

```python
def get_context(obj: object) -> Context | None:
    """Return context for any object, if found."""
    return _OBJ_TO_CONTEXT.get(id(obj))
```

This is an error-prone approach. It is easy to forget connect any event.

**Comment by psobolewskiPhD** [comment]
Not sure I follow @Czaki but using `get_context` does not result in updated keys.
If I make an empty Shapes:
```python
from napari._app_model.context import get_context

get_context(viewer.layers)
Out[2]: Context({'num_selected_layers': 1, 'num_selected_layers_linked': False, 'num_unselected_linked_layers': 0, 'active_layer_is_rgb': False, 'active_layer_type': 'shapes', 'num_selected_image_layers': 0, 'num_selected_labels_layers': 0, 'num_selected_points_layers': 0, 'num_selected_shapes_layers': 1, 'num_selected_surface_layers': 0, 'num_selected_vectors_layers': 0, 'num_selected_tracks_layers': 0, 'active_layer_ndim': None, 'active_layer_shape': None, 'active_layer_is_image_3d': False, 'active_layer_dtype': None, 'all_selected_layers_same_shape': True, 'all_selected_layers_same_type': True, 'all_selected_layers_labels': False, 'selected_empty_shapes_layer': True}, {'num_layers': 1}, {}, SettingsAwareContext({}))
```
But then when I draw a Shape and run it again:
```
get_context(viewer.layers)
Out[3]: Context({'num_selected_layers': 1, 'num_selected_layers_linked': False, 'num_unselected_linked_layers': 0, 'active_layer_is_rgb': False, 'active_layer_type': 'shapes', 'num_selected_image_layers': 0, 'num_selected_labels_layers': 0, 'num_selected_points_layers': 0, 'num_selected_shapes_layers': 1, 'num_selected_surface_layers': 0, 'num_selected_vectors_layers': 0, 'num_selected_tracks_layers': 0, 'active_layer_ndim': None, 'active_layer_shape': None, 'active_layer_is_image_3d': False, 'active_layer_dtype': None, 'all_selected_layers_same_shape': True, 'all_selected_layers_same_type': True, 'all_selected_layers_labels': False, 'selected_empty_shapes_layer': True}, {'num_layers': 1}, {}, SettingsAwareContext({}))
```
Still see `'selected_empty_shapes_layer': True` maybe there is some caching?

**Comment by Czaki** [comment]
> Not sure I follow @Czaki but using `get_context` does not result in updated keys.

Yes, because `get_context` is returning some value from cache, instead of calculating them. 

So it is simple to forget about connecting some event, and you end with the wrong cached state.

**Comment by lucyleeow** [comment]
I think you've figured this out already but the layerlist context key values get updated because the `update` method, of the `LayerListSelectionContextKeys` parent `ContextNamespace`, is connected to `selection.events.changed`:

https://github.com/napari/napari/blob/23110921d0f1ede34f927092d25ed9947fa25b68/napari/components/layerlist.py#L100-L108

Note the `update` method looks like this:

https://github.com/napari/napari/blob/23110921d0f1ede34f927092d25ed9947fa25b68/napari/_app_model/context/_context_keys.py#L17-L20

@dalthviz i think you're totally right, this would be the most ideal solution:

> Maybe there is another event that is not being connected there that could handle/detect when an item data changes?

 I'm not familiar with layer events, is there such an event? A hack would be to connect the update event to the context menu 'about to show' event? Another hack would be to just 'manually' run the `LayerList._selection_ctx_keys.update` function in `show_context_menu` ? I think it is effectively similar to your solution [here](https://github.com/napari/napari/issues/6643#issuecomment-1932430668)

FYI Talley (who implemented this) did a high level documentation this in [Contexts and Expressions in napari](https://napari.org/dev/guides/contexts_expressions.html#napari-context-keys), the relevant section is probably 'Updating contexts'. I've also got a little section on this in my [app-model doc PR](https://github.com/napari/docs/pull/325) (suggestions welcome).

With regard to `get_context`, see: https://github.com/pyapp-kit/app-model/pull/142#issuecomment-1911503987, I think @DragaDoncila is right in her guess that it was implemented to lay the foundation for app-model keeping a registry for contexts in the future (currently it does not). Also that thread has some more interesting context discussion, but mostly about typing and syntax explanation.

**Comment by Czaki** [comment]
I still do not get the benefit of caching context. 
I have also checked the updating context instruction form https://napari.org/dev/guides/contexts_expressions.html#updating-contexts, and it will not work with events from layers. Because of this code:

https://github.com/napari/napari/blob/89f8194d3fa4eef620755804806ac69ef684df63/napari/_app_model/context/_context_keys.py#L17-L20

**Comment by psobolewskiPhD** [comment]
Seems like the simplest fix is then:
```
    def show_context_menu(self, index, model, pos: QPoint, parent):
        """Show the layerlist context menu.
        To add a new item to the menu, update the _LAYER_ACTIONS dict.
        """
        if not hasattr(self, '_context_menu'):
            self._context_menu = build_qmodel_menu(
                MenuId.LAYERLIST_CONTEXT, parent=parent
            )

        layer_list: LayerList = model.sourceModel()._root
		# update context keys of selected layers
        for key, get in layer_list._selection_ctx_keys._getters.items():
            setattr(layer_list._selection_ctx_keys, key, get(layer_list.selection))
        self._context_menu.update_from_context(get_context(layer_list))
        self._context_menu.exec_(pos)
```

**Comment by DragaDoncila** [comment]
I agree for now the bandaid fix is sufficient, and we can look at updating the contexts attached to layer selections in future. I didn't actually realize some of our context menu items depend on layer attributes.

Of course this complicates things, because it requires that the context be updated when layer data changes - which the context knows nothing about.

> A hack would be to connect the update method to the context menu 'about to show' event?

@lucyleeow this doesn't actually seem like a hack to me and seems like it would be the way forward, if it works. Iirc we connect other menu context updates on `aboutToShow` right? Should we not do it here also? I had a quick look but it wasn't clear to me how to make sure the event gets passed through. But evaluating context keys on `aboutToShow` seems way more sane to me than getting a `LayerData` context...

**Comment by lucyleeow** [comment]
> irc we connect other menu context updates on aboutToShow right

Yes we do! All the menubar items are connected to `aboutToShow`. And yes I think this is a nicer solution than 'manually' updating in `show_context_menu`. I don't know enough about layers and events to easily know how to implement this though. Also I don't quite follow:

> I had a quick look but it wasn't clear to me how to make sure the event gets passed through

Passed through to the `update` function?

Also what do you mean by:

> getting a LayerData context

As in adding another `ContextNamespace` subclass e.g., `LayerDataContextKeys` ? It does seem like this would ultimately be the most ideal solution. It may be useful in other places as well. Happy to look into this.

**Comment by DragaDoncila** [comment]
Lucy and I chatted about this today.

We realized we wouldn't be able to connect to `aboutToShow` for this, because that's being used to update `QModelMenu` from an updated context - not to update the context itself. 

We also had a look at all the keys in `LayerListSelectionContextKeys` and there's quite a few that rely not just on the selection state of the `LayerList` (which is what the menu knows about) but on layer properties of the selected and/or active layer. See [here](https://github.com/napari/napari/blob/main/napari/_app_model/context/_layerlist_context.py#L242-L259) for a couple.

Any of these keys **could** be invalidated by a change in the layer, but a change in the layer does not cause the `LayerList` to emit any events we can hook into - I think that makes sense. Based on that it may make sense to define a new `LayerContext` (or perhaps `SelectedLayerContext` and `ActiveLayerContext`?). These would be connected to the relevant layer events, and we would then need to update the right-click menu from these contexts. 

But there's still some stuff to think about with that idea, like throttling the context update callbacks so we don't bloat the layers and connecting/disconnecting the callbacks appropriately once layers leave the list so we don't end up with leaks. 

We should definitely go ahead with the bandaid fix for now - just leaving this here for consideration.

**Comment by Czaki** [comment]
> Any of these keys **could** be invalidated by a change in the layer, but a change in the layer does not cause the `LayerList` to emit any events we can hook into - I think that makes sense. Based on that it may make sense to define a new `LayerContext` (or perhaps `SelectedLayerContext` and `ActiveLayerContext`?). These would be connected to the relevant layer events, and we would then need to update the right-click menu from these contexts.

I do not think it is a good idea. Right click is really rare in the context of layers update, and we should calculate context on demand. Not recalculate it on every change.
The recalculation on every change with connecting/reconnecting events is error-prone and performance impacting (as you pointed).  

In general, we should only invalidate cache on event, recalculation of cache state should happen only on cache access.

**Comment by DragaDoncila** [comment]
> In general, we should only invalidate cache on event, recalculation of cache state should happen only on cache access.

@Czaki just making sure I understand, your suggestion is on layer events (or just selected layer events?), have a callback to something like `layerlistcontext.invalidate()`, and then when the user right clicks and we need to access the `layerlistcontext` we'll know that it's been invalidated (even though a `selection` event hasn't fired) and that'll prompt us to recompute the context keys?

**Comment by Czaki** [comment]
In general, the cache should store values already required by some computation. 
In this case I think that we should not cache context for layer list. It is too rarely used. 

In other situations invalidate should be connected to the event and calculation should happen when data are the first time needed by some context.

**Comment by lucyleeow** [comment]
I've opened this again as the fix is temporary and we should come up with a better solution after more thought in how.

**Comment by psobolewskiPhD** [comment]
Does it make more sense to add a reference in a higher level issue -- or make a new one that could better encapsulate the task?

**Comment by lucyleeow** [comment]
Probably, maybe a higher level one about contexts in general. It could document the invalidate idea (though implementation needs thought if we're going to use app model contexts keys) and mention need for a better solution for this. At the least this can be open until we open the next issue 😬

**Comment by lucyleeow** [comment]
https://github.com/napari/napari/issues/6516#issuecomment-1979821066 has reminded me of this issue.

Any new thoughts here? Are interested in going down the 'invalidate' idea in order to address @Czaki's [concern](https://github.com/napari/napari/issues/6643#issuecomment-1947541441) that we should calculate when context is needed (i.e., when a menu is clicked on) and NOT on layer change events.

I don't think the 'invalidate' idea would solve issue with layer data not updating though (as there is still no event to invalidate when data is added to a layer). So I think this issue should remain open...

**Comment by DragaDoncila** [comment]
> as there is still no event to invalidate the context, as there is no 'data in layer has changed' event in LayerList). 

In the case where `invalidate` would be used somehow, we **would** connect it to the layer data event and it would invalidate the cache for the `LayerList`. Then, when next we go to show the menu, we would access the `LayerListContext`, it would realize it had been invalidated, and it would therefore recompute all the context keys.

**Comment by lucyleeow** [comment]
Ah okay. Do you see any performance issues with connecting 'invalidate' function to layer data events? I know we would simply update a variable but if it is done very often, maybe it could cause problems? Just asking.

**Comment by DragaDoncila** [comment]
Yeah, I think we would want to debounce the function still, so that it only actually runs at most once every x milliseconds or centiseconds(?) or whatever. There's a `debounce` option in superqt but I'd have to look more carefully at how/if we could just use that.

**Comment by Czaki** [comment]
I still vote, That for context menu we should not depend on context cache, but calculate it on right lick. 

But if you want to cache it, then debouncing will be more expensive than cache clean.

**Comment by lucyleeow** [comment]
I think the 'invalidate' idea does not involve caching? It would just indicate that the current context is not valid and needs to be re calculated when it is next required (click on menu)?

**Comment by Czaki** [comment]
The current code only stores cache and does not contain any information of what to perform if the cache is empty. 

But yes, if cache storage could contain metadata how to calculate it and, in reality, do not save the computed version, it may work.
