### ISSUE TITLE
[Main] Unexpected slice display after adjusting hidden layer's slider position

### ISSUE THREAD

**Issue by fjorka** [napari/napari#6760]
### 🐛 Bug Report

Adjusting the slider while the layer is hidden and then making it visible again displays the previously visible slice, not the slice corresponding to the new slider position.

### 💡 Steps to Reproduce

1. Open sample Cells (3D+2Ch) 
2. Switch off the visibility of one of the layers (ex. nuclei)
3. Move the position of the slider
4. Swich on the visibility of the layer

### 💡 Expected Behavior

I would expect that after switching on the visibility of the layer the correct slice is displayed.

### 🌎 Environment

napari: 0.5.0a2.dev606+gb3e15c51
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:27:34) [MSC v.1937 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.3.1
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.2
in-n-out: 0.2.0
app-model: 0.2.5
npe2: 0.7.4

**Comment by psobolewskiPhD** [comment]
Just checked, this doesn't affect 0.4.19. I'll do some git bisect later to figure out where the source is, but I suspect it's the new slicing machinery for async (even though this occurs with async off).

**Comment by psobolewskiPhD** [comment]
Looks like it's 47b166cfa3dfd53691bbbc83d80d5426133aa4f0
#6080

**Comment by andy-sweet** [comment]
Should be able to take a look some time tomorrow.

**Comment by andy-sweet** [comment]
I have a simple/short fix in: https://github.com/napari/napari/pull/6766

But unfortunately, the explanation is a little more complicated and is related to fundamental differences between sync and async slicing. I tried to make a concise explanation in the PR description and in the code as a comment, but I'm happy to expand more here or on the PR.

The short explanation is that there is a fundamental difference between the way sync and async slicing works and that difference is the main cause of the bug. That is definitely my fault! And I think others anticipated these kinds of issues.

But I also think the difference is still worth keeping because it takes one step towards removing slice state from the layer. Of course, if it continues to generate bugs like these, then it's probably not worth it. But I hope we can make more progress towards moving slice state from the layer soon, so that the current sync slicing approach goes away.

**Comment by andy-sweet** [comment]
Also thanks so much for the clear bug description, reproducer, and bisect information here - it made fixing this bug so straightforward!
