### ISSUE TITLE
When all layers are removed, all roll locks should be removed

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#6792]
> Personally, I think when the LayerList goes to zero the locks should be removed, but I won't block on this point because I expect strong pushback on this from other core devs.

This could be done easily in [`Dims.reset`](https://github.com/napari/napari/blob/f9709d8a9eed8f1ab41596d71b7b29ee4390f64e/napari/components/dims.py#L377), which is called [in `ViewerModel` when the layers change and there are none of them](https://github.com/napari/napari/blob/f9709d8a9eed8f1ab41596d71b7b29ee4390f64e/napari/components/viewer_model.py#L489).

So I don't have an issue with this side-effect because there are existing related side-effects when removing the last layer.

@Chris-N-K : we've already asked so much of you here, so this is a non-blocking request. If you feel like adding it when making the latest updates, go for it! Otherwise, @psobolewskiPhD and I can make a follow up PR.

_Originally posted by @andy-sweet in https://github.com/napari/napari/issues/5986#issuecomment-2025530604_

**Comment by psobolewskiPhD** [comment]
Thinking out-loud:
would anyone expect locked dims axis status to be preserved after deleting all layers?

If you're chain open/closing different time series, maybe you would? or stacks with a `C` axis?
🤔 

Playing further, the issue only happens if you lock one of the two right-most (typically displayed) axes.

So for example, if you make a 3D stack and lock `0` In that case after you delete all layers, viewer.dims is:
```
viewer.dims
Out[2]: Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('1', '2'), rollable=(True, True), range=(RangeTuple(start=0.0, stop=2.0, step=1.0), RangeTuple(start=0.0, stop=2.0, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(0.0, 0.0), last_used=0)
```
So when it was 0, 1, 2 and 0 was rollable=False, and 1, 2, were rollable=True. With no layers it reverts to 2D mode, and uses right-most axes, so 1, 2 and not 0, 1, so I guess it's correct, but still 👀  Then when you open a new 3D image the new 0-axis is rollable by default (?)

But if you lock `1` and delete the layers you get:
```
viewer.dims
Out[1]: Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('1', '2'), rollable=(False, True), range=(RangeTuple(start=0.0, stop=2.0, step=1.0), RangeTuple(start=0.0, stop=2.0, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(0.0, 0.0), last_used=0)
```
So with the same logic as above, if you use right-most axes, you get 1 not rollable. So then when you open a new image, the locked 1 axis is still present and still not rollable--even a 2D one.
The same happens with axis 2 for a 3D stack.

So given that behavior, I think it's best to fix this to reset rollable when deleting all layers? just to avert confusion? after all, the most likely to be locked axes are probably anything but the right most...
