### ISSUE TITLE
Can't open zarr contains which contains any other than the expected files

### ISSUE THREAD

**Issue by imagejan** [napari/napari#6850]
### 🐛 Bug Report

Originally reported by @tibuch here: https://github.com/ome/napari-ome-zarr/issues/106

### 💡 Steps to Reproduce

> I have a zarr container with the following structure:
> 
> ```
> container.zarr
>     - 0
>     - .zattrs
>     - .zgroup
> ```
> 
> I can drag and drop this on napari and the data is opened.
> 
> However, if I add just another file like:
> 
> ```
> container.zarr
>     - 0
>     - test.txt
>     - .zattrs
>     - .zgroup
> ```
> 
> It fails with:
> 
> ```
> ValueError: Not a zarr dataset or group: /path/to/container.zarr/test.txt
> ```
> 
> In my opinion the plugin should only look at the files which are defined by the spec and ignore any other files.

### 🌎 Environment

napari: 0.4.19

**Comment by DragaDoncila** [comment]
The problem code is [here](https://github.com/napari/napari/blob/main/napari_builtins/io/_read.py#L129-L131). It tries to read everything in the directory that doesn't start with a `.`. We should either `try..except` this and only raise later if the `image` is empty, or find a better way to identify the arrays than paths that don't start with a `.`. @jni thoughts?

**Comment by jni** [comment]
> thoughts?

I actually have no memory of supporting multi-arrays at all, that's neat! 😜 

I think we can be a little more proactive in the iteration — we should only iterate *directories* in that list comprehension. So:

```
for subpath is sorted(os.listdir(path))
if not subpath.startswith('.')
and os.path.isdir(path)
and (os.path.exists(os.path.join(path, '.zarray'))
or os.path.exists(os.path.join(path, '.zgroup')))
```

At this point I think wrap `path` in a `pathlib.Path` to make that whole thing less of a mouthful, but you get my drift. Basically, only recurse subdirectories and only if they are actually zarr arrays or nested groups.

**Comment by DragaDoncila** [comment]
Great well, that should be an easy PR! 

@imagejan if you are at all interested in contributing this fix yourself, let us know and we can guide you through it. Otherwise one of the core team will get to it as soon as we can!

**Comment by d-v-b** [comment]
Is there any reason to not use the `zarr-python` api for listing groups and arrays here?

**Comment by jni** [comment]
> Is there any reason to not use the zarr-python api for listing groups and arrays here?

ignorance! 😂 Since @imagejan already opened #6857 which is strictly better than the current situation, I suggest we merge that, then iterate. Thanks for the suggestion @d-v-b, that's indeed the right path forward.

**Comment by d-v-b** [comment]
for reference, in `zarr-python` right now, [`contains_group`](https://github.com/zarr-developers/zarr-python/blob/9d046ea0d2878af7d15b3de3ec3036fe31661340/zarr/storage.py#L123) and [`contains_array`](https://github.com/zarr-developers/zarr-python/blob/9d046ea0d2878af7d15b3de3ec3036fe31661340/zarr/storage.py#L115) both do what you would expect for checking if a path denotes a group or array. 

Once you have a handle to a group, you can iterate over its sub-groups / sub-arrays with `Group.items()` (because `Group` is a `MutableMapping`, or just sub-arrays with `Group.arrays(https://github.com/zarr-developers/zarr-python/blob/9d046ea0d2878af7d15b3de3ec3036fe31661340/zarr/hierarchy.py#L659)`, or just sub-groups with `Group.groups(https://github.com/zarr-developers/zarr-python/blob/9d046ea0d2878af7d15b3de3ec3036fe31661340/zarr/hierarchy.py#L591)`. 

Note that some of this will change in v3, but not too drastically -- e.g., we might make `contains_array` / `contains_group` take a `zarr_format` keyword argument, since zarr v3 and zarr v2 arrays can co-exist in the same directory.
