### ISSUE TITLE
napari only opens first frame of SPE time series.

### ISSUE THREAD

**Issue by anntzer** [napari/napari#698]
## 🐛 Bug

When napari is made to open a SPE (https://imageio.readthedocs.io/en/stable/format_spe.html#spe) time series file, which e.g. imageio.volread reads as a proper 3d array (t, y, x), only the first frame is displayed.  Compare with e.g. opening a tiff time series, for which napari correctly displays a slider for selecting the frame number.

## To Reproduce

1. Run `napari /path/to/file.spe`.  Unfortunately I don't have a small file I can share right now.
2. Observe the behavior described above.

## Expected behavior

A slider for selecting the frame number appears.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari, 0.2.5
Qt, 5.13.2
NumPy, 1.17.4
SciPy, 1.3.2
VisPy, 0.6.2
scikit-image, 0.16.2
Platform: Linux-5.3.8-300.fc31.x86_64-x86_64-with-glibc2.10
Python:   3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0]
Backend:  PyQt5
GL version:  '3.0 Mesa 19.2.2'
MAX_TEXTURE_SIZE: 16384

 - Any other relevant information:

**Comment by sofroniewn** [comment]
Thanks for flagging @anntzer - our fileIO is still pretty early, though if `imageio.volread` does the right thing, we should be able to too. We'll look into it

**Comment by jni** [comment]
Yeah the problem here is that we are using `skimage.io.imread`, which uses `<backend>.imread`, where backend is either `tifffile` for tiffs or `imageio.imread` for everything else. See [this comment on skimage #4138](https://github.com/scikit-image/scikit-image/issues/4138#issuecomment-531054141) for more.

I honestly don't know what the right thing is here, because it's hard to tell ahead of time whether volread or imread is the correct call... Here's me reading a 3-channel tiff with different calls:

```python
In [1]: import imageio as iio                                                                                                 
In [2]: result = iio.volread('MAX_block6_tile.lsm_cropped.tif')                                                               
In [3]: result.shape                                                                                                          
Out[3]: (3, 1024, 1024)

In [5]: from skimage import io                                                                                                
In [6]: result2 = io.imread('MAX_block6_tile.lsm_cropped.tif')  # uses tifffile
In [7]: result2.shape                                                                                                         
Out[7]: (1024, 1024, 3)

In [8]: result3 = iio.imread('MAX_block6_tile.lsm_cropped.tif')                                                               
In [9]: result3.shape                                                                                                         
Out[9]: (1024, 1024)
```

**Comment by anntzer** [comment]
Wouldn't it work to always use imageio.volread (and check if the first dim is 1)?

**Comment by jni** [comment]
I've found tifffile to be a much more reliable loader for tiffs, so your question might be better suited for scikit-image, where we already implement the tifffile > imageio cascade. I don't think I want to repeat that logic here... Could you maybe raise an issue on the scikit-image repo?

@sofroniewn might have different ideas about how much we want to take on in napari proper.

**Comment by sofroniewn** [comment]
Ideally I’d much rather see something like this get solved upstream in skimage / imageio in a way where we don’t loose any of our existing functionality.

 I worry if we start trying to develop special case logic inside napari it will be hard to test and maintain, and either that logic is generic enough that it should be upstream or so special case that it should be in a special fileIO plugin

**Comment by anntzer** [comment]
To be honest, I sort of lost track of the layers between skimage, imageio, and tifffile/PIL.  I hope you (@jni) will consider the following (which is mostly addressed to you as a skimage devel rather than a napari devel) as constructive criticism but... why do skimage and imageio both vendor tifffile (different versions of it, as of master!) rather than depend on it? (they already have a dependency on numpy, which is something much more complex)  Why does imageio exist as something independent of PIL (which it mostly wraps), rather than having been contributed as PRs to pillow?  With all due respect, it's just too hard to keep track of all the different projects.
I guess that based on the above, I would agree with @sofroniewn's last comment -- adding yet another layer in napari would only make things worse.

**Comment by jni** [comment]
> why do skimage and imageio both vendor tifffile (different versions of it, as of master!) rather than depend on it?

Tifffile is essentially impossible to depend on, because development happens on Christoph Gohlke's computer, then it gets published to his homepage and to PyPI. The "issue tracker" is emailing Christoph. (Or, more often, pinging him on scikit-image.) For a while, Steven Sylvester tried to maintain a mirror on GitHub, but as you can imagine, mirrors are not a fun thing to maintain, so that effort was deprecated. (FYI I don't want to tag either of them because, honestly, Christoph's work has been an incredible boon to bioimaging in Python, and he is entitled to work as he chooses. If that's Don Knuth style, so be it. And Steven certainly has enough on his plate also, without rehashing a discussion he's probably seen dozens of times already.)

The current version of tifffile on PyPI does not support most compression schemes without also installing imagecodecs/imagecodecs-lite, neither of which provides wheels except for windows. For scikit-image, that's an unacceptable dependency. Hence, vendoring.

> Why does imageio exist as something independent of PIL (which it mostly wraps), rather than having been contributed as PRs to pillow?

Tifffile, and I imagine many other similar reasons. imageio was supposed to solve the same problem that skimage.io does, which is that there's lots of libraries, none of them provide NumPy arrays under a unified API. Pillow in particular, is more focused on "consumer" images than scientific ones. It does not depend on NumPy nor give you a NumPy array as an output. The goal was for skimage.io to eventually be replaced by imageio, but both of them have a maintenance burden that is too great, and a concerted effort to unify the two has not been made because there are plenty of other fires to put out.

**Comment by anntzer** [comment]
Thanks for the explanation, and sorry for distracting from the main issue at hand.  To be honest I am not convinced that the current state of things is optimal, but I cannot articulate this properly and do not wish to appear as belittling the very worthwhile work of the skimage community (in a broad sense), so let's close this side discussion.

**Comment by jni** [comment]
Oh I absolutely don’t think it’s optimal! I was merely trying to explain how we might have got to where we are by doing gradient descent along various axes and given various constraints. ;) And that it probably requires a *major* energy kick to move to another basin!

As to articulating where that other basin might be, I don’t think PIL and imageio are redundant, but I do think that skimage.io and imageio are redundant, and that would be where I would focus my efforts in the short term if I wanted to optimise further.

**Comment by jni** [comment]
I think this issue should now be resolved with an imageio reader plugin that uses volread by default, or maybe creates a custom lazy volread. See our [plugin docs](https://napari.org/docs/plugins/index.html) for more info.

**Comment by jni** [comment]
@anntzer Thanks for raising this issue. There's now several IO plugins for napari in the wild, and it should be easy to create one that suits your needs. ([link again](https://napari.org/docs/plugins/index.html)) Given that, I'm going to close this issue, but feel free to comment here if you have any different thoughts on how to fix the issue!
