### ISSUE TITLE
pyramid checking seems to be breaking lazy loading

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#699]
## 🐛 Bug
I was just trying to familiarize myself with napari's handling of zarr datasets using one of my big light sheet datasets... but it would hang indefinitely each time I added it.

I went back to the example in `zarr_nD_image.py`, but there too, as i increase the size of the zarr store, napari starts to hang upon `napari.view_image(data)`... regardless of whether I provide the `contrast_limits`, `rgb`  or  `is_pyramid=False` arguments.  Digging a bit more, it seems that, as of #556, it is impossible to avoid the callchain from `Image.__init__()` -> `get_pyramid_and_rgb()` -> `is_pyramid()` ... and that `is_pyramid()` call takes forever on a big zarr store.

Is this a regression or is `zarr_nD_image.py` now invoking `napari.view_image` incorrectly?

**Comment by jni** [comment]
@tlambert03 this is a known issue, in that @sofroniewn and I did know about it, but it appears I neglected to create an issue for it! :grimacing: Maybe it was on slack, or a comment on a different issue. Sorry about that!

Anyway, the problem is this line:

https://github.com/napari/napari/blob/8ce944a1dff680f4d06b238f7556211550ba1d4b/napari/util/misc.py#L68

`[... for d in data]` actually instantiates each `d` when `data` is a zarr array.

The workaround is to load the zarr file not with zarr.open, but with `da.from_zarr`.

The fix is to change that expression to be lazier. Additionally, `is_pyramid=False` should probably skip the check, but I'm not sure...

**Comment by tlambert03** [comment]
Ok thanks

**Comment by sofroniewn** [comment]
yeah @tlambert03 this is not great ... any suggestions / improvements would be appreciated. I think it's pretty natural for people to do what you did with `zarr` instead of `da.from_zarr` so we should do better than we do right now

**Comment by tlambert03** [comment]
I need to get much more familiar with the pyramid handling (and other general array-handling) parts of napari before I'd be able to make any sort of useful suggestions.  But in the short term, would it make sense to change the zarr example to use `da.from_zarr`?
https://github.com/napari/napari/blob/15deef08f1aea5e6a6951f7a83d4713f16070ed4/examples/zarr_nD_image.py#L14-L21

I also need to look back through #556 to understand why the `if pyramid:` check was removed in [`get_pyramid_and_rgb`](https://github.com/napari/napari/blob/15deef08f1aea5e6a6951f7a83d4713f16070ed4/napari/util/misc.py#L111).  If the user explicitly passes `pyramid=False`, why does `is_pyramid` still need to be called in [this line](https://github.com/napari/napari/blob/15deef08f1aea5e6a6951f7a83d4713f16070ed4/napari/util/misc.py#L138)?

**Comment by sofroniewn** [comment]
I guess the calling of `is_pyramid` was more of an input check, because it leads to this error if things don't match - https://github.com/napari/napari/blob/15deef08f1aea5e6a6951f7a83d4713f16070ed4/napari/util/misc.py#L167 but maybe that's a bad idea

Agree changing the zarr example to use `da.from_zarr` is a good idea.

**Comment by constantinpape** [comment]
I ran into this issue today as well and this also breaks lazy loading for other lazy input sources like `h5py` or `z5py` datasets. 
Maybe leave out this check if `is_pyramid is not None`? This might cause some downstream errors for inputs that are not consistent with the passed pyramid flag though. Or just perform the check for `tuple` and `list` inputs? This would cause issues if someone passes a pyramid format as np.object though.
