### ISSUE TITLE
AttributeError: 'VispyCanvas' object has no attribute 'measure_fps'

### ISSUE THREAD

**Issue by rjlopez2** [napari/napari#7035]
## 📚 Documentation

I cannot reproduce anymore the tutorial on how to display fps in the main canvas by the current [tutorial](https://napari.org/stable/gallery/viewer_fps_label.html)

I am receiving the following error (also displayed in the output of the tutorial):

```
Exception has occurred: AttributeError
'VispyCanvas' object has no attribute 'measure_fps'
  File "D:\Ruben\sandbox\napari-omaas\loctest_apdROIs_timestamp.py", line 19, in <module>
    o = napari_omaas.OMAAS(viewer)
AttributeError: 'VispyCanvas' object has no attribute 'measure_fps'
```

What is the recommended way to check and display the fps when rendering e.g time series of images?

**Comment by andy-sweet** [comment]
My guess is that your using the `main` branch of napari and not `v0.4.19`, right?

In that case, you can look at the same example on `main` by looking at the dev docs: https://napari.org/dev/gallery/viewer_fps_label.html

which should work.

Looks like that needs private access now, which is unfortunate. I could imagine that we'd be open to publicly exposing `measure_fps` on the canvas (so that the previous example continues to work), but this is not an area of the code I know well.

**Comment by rjlopez2** [comment]
Thanks for the fast reply.

This is the output of `napari  --info`
```
WARNING: pyqt5 already imported, cannot switch to pyside6
WARNING:vispy:pyqt5 already imported, cannot switch to pyside6
napari: 0.5.0a4
Platform: Windows-10-10.0.19044-SP0
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.4
SciPy: 1.14.0
Dask: 2024.6.2
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.6

OpenGL:
  - GL version:  4.6.0 NVIDIA 536.23
  - MAX_TEXTURE_SIZE: 32768
  - GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1080, scale 1.0

Optional:
  - numba not installed
  - triangle not installed

Settings path:
  - C:\Users\lopez\AppData\Local\napari\omaas_base_test_5e3ffa57acafb95873961019fba050cde5a9ccb0\settings.yaml
Plugins:
  - napari: 0.5.0a4 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-macrokit: 0.0.1 (2 contributions)
  - napari-mat-file-reader: 0.0.2 (4 contributions)
  - napari-matplotlib: 2.0.1 (10 contributions)
  - napari-omaas: 0.1.3 (12 contributions)
  - napari-sif-reader: 0.0.2 (4 contributions)
  - napari-svg: 0.2.0 (2 contributions)
```

my env was created with micromamba with the following .yml  template:
```
name: omaas_base_test
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyqt
  - pip:
    - git+https://github.com/napari/napari.git
    - "napari-omaas[gpu] @ git+https://github.com/rjlopez2/napari-omaas.git@motion_correction_optimap"
```

the additional plugin (napari-omaas) is using similar logic as the tutorial to display the FPS when rendering.

**Comment by andy-sweet** [comment]
Ah, you picked up the recently released alpha for v0.5 which has the change on `main` (whereas I assume the stable v0.4.19 does not).

To clarify, a quick fix is to use

```python
viewer.window._qt_viewer.canvas._scene_canvas.measure_fps(callback=update_fps)
```

though that's using two private parts of the API (`_qt_viewer`, `_scene_canvas`), so may change in the future.

I guess we would need to provide `viewer.measure_fps` or similar for a long term public API. That doesn't seem too bad, but this is definitely not my area of the code - maybe @melonora, @brisvag, or others have thoughts?

**Comment by melonora** [comment]
I can pick it up

**Comment by melonora** [comment]
Hi @rjlopez2, I opened a PR to fix the problem. If you would like to test it for your application. The way to use it would be as in the updated example that you can see in the PR.

**Comment by rjlopez2** [comment]
Thanks 
It looks like an *"easy"* fix.
I will check this out soon.
I was just wandering (only out of curiosity) that your suggestion also access the private method `(...)._scene_canvas` . Is this approach stable in mid-long term?
Cheers and thanks for the lift.

**Comment by melonora** [comment]
It does, but it is from within the napari code base itself :) . The _scene_canvas was code that I wrote back then in #5432  for the reason that we may want to also have a different canvas backend at some point and we still needed a class to then still be able to deal with the `mouse_events`. Ultimately with `_scene_canvas` you access the instance of a `NapariSceneCanvas` which ultimately is the actual Vispy canvas with the `measure_fps` method.

One of the reason for this being private is because otherwise the user could easily do all kinds of things with the canvas which we don't control so we can't guarantee a user doing things then causing errors due to that.

**Comment by melonora** [comment]
Hi @rjlopez2, due to future changes it was opted not to make this api change at the moment, for the discussion please see the PR:) For now though the way you can still get the fps by is by doing the following:
```viewer.window._qt_viewer.canvas._scene_canvas.measure_fps(callback=update_fps)```

This will still give the warning which we understand is annoying, but otherwise it could be that in 1 version we have to change the api again. Let me know if you encounter any problems!

**Comment by rjlopez2** [comment]
Alles Klar,

thank you very much for you support here, feel free to close this issue for the time being.

Cheers

**Comment by melonora** [comment]
No problem!
