### ISSUE TITLE
Don't depend on pyside

### ISSUE THREAD

**Issue by hmaarrfk** [napari/napari#704]
## 🚀 Feature
Depending on Pyside2 makes things easy to install, but if you already depend on qtpy, then maybe let the users decide which backend is best for them?

Just my 2 cents.

**Comment by tlambert03** [comment]
I kinda agree here.  I see that this creates a problem: how do you make an easy "one line install" for those who know nothing about Qt, while also preventing duplicate Qt backends for those who already depend on pyqt for other things.  

I _do_ think that it's really important for a beginner to just `pip install napari` and be off and running – even something like `pip install napari[pyside]` is undesirable – but when I went about trying to include support for napari in some of my other qt packages, I ran up against either needing to have both pyqt5 & pyside2 in the environment, or changing all my stuff over to pyside2.  @jni, do you have thoughts on how to approach that sort of thing?

**Comment by AhmetCanSolak** [comment]
If you guys want to use pyqt5 or another backend, you should first import the backend you want to use, then import *napari*. Since napari uses qtpy if before importing napari you have another backend imported pyside2 will not be able to import successfully.

About the reason of pyside2 choice, mainly licensing AFAIK. Correct me if i'm wrong @sofroniewn . As soon as we are not depending non-LGPL parts of pyqt5 it would be okay to switch backend and i love to do that too, personally i like pyqt5 better than pyside2.

**Comment by tlambert03** [comment]
I might be wrong... but I think the issue was not so much about _how_ to get qtpy (and therefore napari) to use the desired backend.  That much is straightforward.  and it's also not so much about using `pyside2` as the "go-to" default backend... that's also fine, particularly if it makes licensing easier.
I think it is an interesting discussion though as to whether installing napari will _force_ the user to have pyside2 installed in their environment (even if they then take steps to not use it).

**Comment by hmaarrfk** [comment]
> I think it is an interesting discussion though as to whether installing napari will force the user to have pyside2

^this

**Comment by AhmetCanSolak** [comment]
Good point @tlambert03 . But either way we need a backend by default. What could be an alternative? Do you have any suggestions?

**Comment by tlambert03** [comment]
nope!  😄   that's why in my first comment I said it creates a problem and punted to @jni :)
the only alternative I can think of would be to [declare pyside2 as an "extra"](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), and then have the readme say `pip install napari[pyside]` ... but I'm not necessarily promoting that, since I definitely think that napari should also try to be stupid easy for people to "just use".

**Comment by sofroniewn** [comment]
As noted above `pyside2`(LGPL)  is listed in our `requirements.txt` instead of `pyqt5` (GPL) only for licensing reasons, so our code can be redistributed as LGPL by others if they want, (you'll note that the code we write is actually BSD), and when we release the bundled napari app that will have `pyside2` inside it and be LGPL.

@AhmetCanSolak 

> As soon as we are not depending non-LGPL parts of pyqt5 

Do you have something in my mind here? I thought we weren't going to need any of the non-LGPL stuff (I'm not even too familiar with what is there, I thought it was really quite specialized stuff).

As to if users want to use `pyqt5` or `pyside2` that's totally up to them and we should continue to support both via `qtpy`. If you have both installed then you can switch between them with the environmental variable `QT_API`.

I can see though if you are already a `pyqt5` user you shouldn't be forced to install pyside2 - so how about the following approach:
```
pip install napari
```
still works as before installing our default `pyside2`, but
```
pip install napari[pyqt5]
```
now installs with `pyqt5` and does not install `pyside2`
We can also provide
```
pip install napari[pyside2]
```
for symmetry, but I think it is still important our default remains pyside2 for licensing reasons

The burden would then be on slightly more advanced users to specify `pyqt5` during the install process, and it would all still just work for beginner users with `pip install napari`.

@hmaarrfk @tlambert03 @AhmetCanSolak does this seem like a reasonable proposal?

**Comment by tlambert03** [comment]
I like that!

**Comment by hmaarrfk** [comment]
the thing i've learned, is that until you give people a one click installer, then they will always find your GUI hard to install.

Asking
```
python -m venv napari
source napari/bin/activate
pip install napari
```

then 

```
source napari/bin/activate
napari
```
is already too hard. So as far as package management goes, telling them to type `pip install napari pyside2` is just as hard as asking them to type `pip install napari`

**Comment by jni** [comment]
I've been wanting to get a bit more experience with pip extras. I think from the above, I like @sofroniewn's suggestion of:

pip install napari -> get PySide2
pip install napari[pyqt] or napari[pyqt5] -> get PyQt5
pip install napari[pyside] or pip install napari[pyside2] -> get PySide2

One variant that I would consider, but slightly dislike, is pip install napari -> get an informative RuntimeError that says that one of pyside2 or pyqt5 should be installed. However, I would prefer to avoid this particular form, for the same reasons that @sofroniewn enumerated. People who don't even read our instructions will try `pip install napari`. I would very much rather that didn't result in a non-functional install.

All this reminds me: I should get back to work on that conda-forge package... 😅

**Comment by tlambert03** [comment]
yeah, I think there's definitely something to be said for `pip install napari` over `pip install napari pyside2`.   It's of course easy enough to just state in the readme that you need to `pip install napari pyside2` ... but when someone is doing it from memory, and all they remember is napari, there will inevitably be times when they have errors, or say to themselves "`pip install what-was-it-again`??".  So I like putting the burden on the minority of developers who would like to be more in control of their environment, while also at least making it possible for them to get their desired environment _without_ doing `pip install napari pyqt5 && pip uninstall pyside2`

**Comment by AhmetCanSolak** [comment]
> 
> @AhmetCanSolak
> 
> > As soon as we are not depending non-LGPL parts of pyqt5
> 
> Do you have something in my mind here? I thought we weren't going to need any of the non-LGPL stuff (I'm not even too familiar with what is there, I thought it was really quite specialized stuff).
> 

Yes @sofroniewn you remember right. That's the Qt related part of things. I, personally, think it would be okay to have GPL pyqt5 too since napari is free and open source. To me it wouldn't be too much to ask users to open their source code when they have napari as dependency. I know many people prefer a more permissive license but IMO either with GPL or LGPL dependency we could be fine.

> @hmaarrfk @tlambert03 @AhmetCanSolak does this seem like a reasonable proposal?
I like the idea but this would complicate our license. As soon as we clarify the situation well it sounds okay to me.

and agree with @tlambert03 that `pip install napari pyside2` is hard to remember for the majority.

**Comment by ttung** [comment]
Unfortunately, a default requirement that can be overridden by an extra requirement is not possible.  Here's a [discussion](https://github.com/pypa/setuptools/issues/1139) about this subject.  The reason boils down to that packages distill their requirements into a static text file that is not very flexible.

A possibility is that on napari startup, it looks for pyside and pyqt, and if neither is found, it automagically installs pyside.  It would be a pretty hacky though, because it is assuming that `pip` is the right way to install a package when it may not be.

**Comment by jni** [comment]
@AhmetCanSolak PySide is already LGPL, which means that napari distributed as a bundle would have to be licensed as LGPL. Within the Python community, it's already a big ask. I don't want to get into a debate on the merits of licenses here (MPL is my favourite so far), but rather that if we are part of a particular community, in this case the scientific Python community, we should make an effort to play well with them, and that means BSD licensing.

For some reason my brain worked on this in a background thread (thanks @AhmetCanSolak! =P) and I think I see a way forward.

- rename napari `napari-base` in PyPI, and stop depending on PySide2. Issue a helpful RuntimeError if napari is run with no Qt backend.
- create extras so that `napari[PyQt5]`, `napari[PySide2]`, `napari[pyside]` etc all work as expected (getting only the desired backend)
- create a metapackage `napari` that either is an alias for `napari[PySide2]` (not sure if that's possible), or depends on both `napari-base` and `PySide2`.

Unless I'm missing something, the above should not be a huge amount of work on the packaging side and it should work!

**Comment by ttung** [comment]
> rename `napari` `napari-base` in PyPI, and stop depending on `PySide2`. Issue a helpful RuntimeError if napari is run with no Qt backend.

This is doable.

> create extras so that `napari[PyQt5]`, `napari[PySide2]`, `napari[pyside]` etc all work as expected (getting only the desired backend)

This is also doable.

> create a metapackage `napari` that either is an alias for `napari[PySide2]` (not sure if that's possible), or depends on both `napari-base` and `PySide2`.

If there is a `napari` package, it cannot depend on napari[PySide2].  If `napari` depends on `napari-base` and `PySide2`, then `napari[PyQt5]` will install `napari-base`, `PySide2`, and `PyQt5`.  Extras are always additive to the base package.

**Comment by jni** [comment]
> Extras are always additive to the base package.

Ah, of course! 🤦‍♂ D'oh! Do we then forget about extras and just make multiple packages and metapackages? `napari-pyside2`, `napari-pyqt` etc? Or do we spend our efforts lobbying the PyPA to implement alternative dependencies?

**Comment by tlambert03** [comment]
we could also make `napari` install `napari-base` and `pyside2` and those who don’t want pyside2 would have to do `napari-base[pyqt]`. This leaves the “burden” on those who want want we predict to be the slightly less common scenario.

**Comment by sofroniewn** [comment]
#1059 now makes it possible to install napari without pyside2. We'll be updating our docs accordingly, and so I am closing this issue
