### ISSUE TITLE
Handling of *compressed* in-memory zarr-arrays?

### ISSUE THREAD

**Issue by s-m-e** [napari/napari#710]
I have not found documentation on this issue, so please excuse this question.

I came across [this example](https://github.com/napari/napari/blob/4fbbca0dcdf9529ea55e08224e9962bf6f754bdf/examples/zarr_nD_image.py), which shows that `napari` can directly display in-memory zarr-arrays. In the example, the array is iniziallied like this: 

```python
data = zarr.zeros((102_0, 200, 210), chunks=(100, 200, 210))
```

`zarr` does in fact also allow compression for in-memory arrays (not only for on-disk storage). They can be initialized like this, for example:

```python
from numcodecs import Blosc
compressor = Blosc(cname = 'zstd', clevel = 3, shuffle = Blosc.BITSHUFFLE)
data = zarr.zeros((102_0, 200, 210), chunks = (100, 200, 210), compressor = compressor)
```

I am heavily using this feature in my day to day work for arrays that would, if handled uncompressed, out-grow a machine's memory by a factor of 2 to 10 (compression ratios of about 5x to 20x).

How does `napari` handle such datasets? Does it make sense to visualize them with `napari` or should I assume that most / all data is being decompressed in the process?

**Comment by sofroniewn** [comment]
@s-m-e it should work just fine!

I just ran the following minimal example
```python
import napari
from numcodecs import Blosc
import zarr
compressor = Blosc(cname = 'zstd', clevel = 3, shuffle = Blosc.BITSHUFFLE)
data = zarr.ones((102_0, 200, 210), chunks = (100, 200, 210), compressor = compressor)

with napari.gui_qt():
    viewer = napari.view_image(data, is_pyramid=False, contrast_limits=[0, 1])
```
and it worked well - though I just see a big white square ;-)

<img width="1200" alt="Screen Shot 2019-11-19 at 9 07 46 AM" src="https://user-images.githubusercontent.com/6531703/69168864-436b9c80-0aac-11ea-84a1-f5f297c59d63.png">

Note here I've added in a couple extra keyword arguments which can be good to explicitly set when working with big data. `is_pyramid=False` if your data is not multiresolution, and the `contrast_limits` as otherwise we have to guess them which triggers some compute.

Do you want to try it out and let us know if it doesn't work for you. If you run into problems we can definitely work on them as supporting big compressed data like this is a major anticipated use case.

**Comment by sofroniewn** [comment]
Also, apologies that are docs aren't quite so comprehensive yet, we will work on updating them soon!

**Comment by s-m-e** [comment]
Thanks for your reply. Yes, I also tested a similar, "simple" example and it just worked. With respect to testing on larger data, sure, I did. I ran some experiments on a test dataset - see details below.

# Environment

- i7-3740QM & 32 GB RAM
- NVidia K1000M (2GB)
- Linux 4.12 x86_64 (SUSE Leap 15.1)
- Python 3.7.4 (GCC 7)
- **napari 0.2.5**
- PyOpenGL 3.1.0
- zarr 2.3.2
- numcodecs 0.6.3
- numpy 1.17.0

# Dataset

- Uncompressed: 441 G
- Compressed: 34 G
- compression ratio: 13x

```
>>>> d
<zarr.core.Array '/data' (239316, 1100, 900) int16 read-only>
>>>> d.shape
(239316, 1100, 900)
>>>> d.chunks                                                                                                                
(24, 550, 450)
>>>> d.compressor 
Blosc(cname='zstd', clevel=3, shuffle=BITSHUFFLE, blocksize=0)
```

Positive values are data (technically `uint8`), negative values indicate errors / special conditions.

# Code

The code is opening the `zarr` dataset `d` and copying about half of it into memory in `d_`.

```python
import napari
import zarr
from numcodecs import Blosc
import tqdm
import os

path = 'data.zarr'
data = zarr.open(store = path, mode = 'r')
d = data['data']

l, c = 120000, 24 * 4
d_ = zarr.zeros(
    (l, *d.shape[1:]),
    dtype = d.dtype,
    chunks = d.chunks,
    compressor = Blosc(
        cname = 'zstd',
        clevel = 1,
        blocksize = 0
        )
    ) # Subset: 12 G compressed, 221 G uncompressed
for i in tqdm.trange(0, l, c):
    d_[i:i+c] = d[i:i+c] # Copy data from disk into memory
    
with napari.gui_qt():
    viewer = napari.view_image(
        d_,
        is_pyramid = False,
        contrast_limits = [0, 255],
        rgb = False,
        name = 'radar',
        )
```

In the above example, I can actually confirm that **the entire dataset `d_` is being decompressed before `napari` becomes responsive**. However, the decompressed data is not kept in memory - so `napari` basically works and does not kill my machine. The `viewer = napari.view_image ...` step requires about 3 to 4 minutes which matches the usual decompression time. Python's memory consumption is stable at 12 G (roughly equivalent to the size of the compressed dataset `d_`).

For comparison, I also experimented with the entire compressed dataset `d` directly from disk. Based on IO, the complete array is also being looked at by `napari` before it is shown. CPU load matches my experience from decompressing the entire dataset. Python's memory consumption is stable at around 300M, so although data is read and decompressed, the decompressed result appears not to be kept in memory. Filesystem driver's memory consumption goes up to 16G (50% of available RAM - ZFS default), also indicating that much more than file metadata (or `zarr` metadata plus a few chunks) is being read. At an average read speed of 100M/s I have to wait for 6 minutes until the array is being displayed and the `napari` window becomes responsive - which works just fine. While scrubbing through the data, Python's memory consumption remains stable at 300M and the experience is fluent.

I guess both procedures should work without `napari` looking at all data first. I'd say this is a bug.

**Comment by s-m-e** [comment]
Ok, I quickly traced it back to its root cause:

```
image.py 22: class Image
image.py 124: def __init__(...)
image.py 146: get_pyramid_and_rgb(...)
misc.py 111: def get_pyramid_and_rgb(...)
misc.py 138: currently_pyramid = is_pyramid(data)
misc.py 65: def is_pyramid(...)
misc.py 68: size = np.array([np.prod(d.shape) for d in data]) # reading all data
```

It's a design issue - less of a bug - in `get_pyramid_and_rgb`. The current design tries to provide a warning in line 167 saying that non-pyramid data was indicated but pyramid data was passed. The validation process, as it is, requires all data to be read. I am not entirely sure if there is an alternative to the currently used approach to line 68 in misc.py that would allow to keep this warning.

**Comment by sofroniewn** [comment]
Thanks for chasing this down @s-m-e and sorry if I didn't appreciate from your first question that

> the entire dataset d_ is being decompressed before napari becomes responsive

this is definitely a bug, we should not do this.

That check has caused some problems in other cases too - for example see this very recent discussion on dropping that check here https://github.com/napari/napari/issues/699#issuecomment-554658124. If you comment out this check can you confirm if we now don't also decompress all the data somewhere else?

I guess the decompression is happening because we aren't just calling `data.shape` here, which I guess zarr can do without decompression, but we're calling `[np.prod(d.shape) for d in data]` which is actually indexing into the array and then calling `shape` and we need to decompress to do that. Does that sound right?

Regardless I think its clear from multiple issues that this part of the code base needs to be improved. I'll give it some thought on exactly what we should do and a fix should go in soon

**Comment by s-m-e** [comment]
> If you comment out this check can you confirm if we now don't also decompress all the data somewhere else?

Swapping ... 

```python
misc.py 138: currently_pyramid = is_pyramid(data)
```

... with ...

```python
misc.py 138: currently_pyramid = pyramid
```

... solves my problem. Napari opens and shows images instantaneously. Confirmed.

> but we're calling `[np.prod(d.shape) for d in data]` which is actually indexing into the array and then calling shape and we need to decompress to do that. Does that sound right?

Yes. It's actually just the `for d in data` loop on its own, it's not even the access to `d.shape`. The loop extracts stuff from `data`. Where numpy would offer a (memory-) view object on `data`'s memory as `d` (no memcopy), zarr does not have a similar concept and must "copy" (i.e. read / decompress) data into new numpy arrays.

But I'd be surprised if there was not a better way to achieve the same without reading / decompressing all data. After all, it is meta data you're looking for ... *scratching my head*

**Comment by sofroniewn** [comment]
Ok, good to know this fixes the problem, we'll work on a solution that avoids this call, doesn't decompress, and add some tests to make sure that we don't start decompressing again. Thanks for help finding this!!

**Comment by sofroniewn** [comment]
We've come a long way with our multiscale handling since this issue was raised (including replacing `is_pyramid` with `multiscale` in the API). If you're still interested in this functionality I wonder @s-m-e if you could check this again? Otherwise maybe I or someone else on the team can try and look into this again cc @jni @DragaDoncila. Thanks!!

**Comment by s-m-e** [comment]
Sry for the late reply - just scrubbed through a compressed on-disk `zarr` array, 700G uncompressed, 54G compressed, using `napari` 0.4.16, `zarr` 2.13.3, `numcodecs` 0.10.2, `numpy` 1.23.4. It works just fine, `napari` shows up near instantaneous, memory usage of the Python process (3.10, conda-forge, on Ubuntu 22.04 LTS) never exceeding 500M (11G virtual). I guess this issue can be closed. Thanks for all the effort!
