### ISSUE TITLE
`min_req` tests failing due to `setuptools` release

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#7107]
So looking more at the [failure](https://github.com/napari/napari/actions/runs/10000405066/job/27642895582?pr=7106#step:13:603) with `min_req` tests, it looks like `setuptools` is doing an `Any` `import` from `typing_extensions`, and they released last night and we don't have an upper pin

```python
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/setuptools/_vendor/typeguard/_checkers.py", line 71, in <module>
      from typing_extensions import Any as SubclassableAny
  ImportError: cannot import name 'Any' from 'typing_extensions' (/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-cov/lib/python3.9/site-packages/typing_extensions.py)
```

_Originally posted by @DragaDoncila in https://github.com/napari/napari/issues/7106#issuecomment-2237912752_

**Comment by jni** [comment]
Ok, I was looking at why a new setuptools version would be importing Any from typing_extensions instead of typing, and indeed typing_extensions added Any in v4.4 because Any gained some functionality in Python 3.11:

https://typing-extensions.readthedocs.io/en/latest/index.html#typing_extensions.Any

> See [typing.Any](https://docs.python.org/3.12/library/typing.html#typing.Any).
>
>    Since Python 3.11, typing.Any can be used as a base class. typing_extensions.Any supports this feature on older versions.
>
>    Added in version 4.4.0: Added to support inheritance from Any.

Our minimum version for typing_extensions is 4.2, which causes the error.

It's a bit unfortunate that the build env and the test env are the same, or that setuptools is used during testing, but either way, bumping our typing extensions dependency to 4.4 should fix the problem.

**Comment by jni** [comment]
4.4 was released >18 months ago. I forget whether this satisfies SPEC0 but I say bump the thing and move on. 😂

**Comment by psobolewskiPhD** [comment]
Good catch @DragaDoncila

**Comment by Czaki** [comment]
`typing_extension` is vendored by setuptools https://github.com/pypa/setuptools/tree/main/setuptools/_vendor
So the problem is, why global one is used instead of vendored.

**Comment by jni** [comment]
Yeah I was noticing that too. But it shouldn't matter if the versions are matched. But also, what's the deal with Pydantic in the latest error message? 🤔

**Comment by Czaki** [comment]
@jni I don't know, we may merge #7110 to make CI green again. Then we may try to solve the problem later. Maybe https://github.com/pytest-dev/pytest/issues/12631 will provide additional information. 

I think that proper approach for #7103 will be bumping all requirements and find working combination.
