### ISSUE TITLE
[Keybind Settings] Cancel button doesn't discard changes

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7142]
### 🐛 Bug Report

First noted here: https://github.com/napari/napari/pull/7124#pullrequestreview-2204599374
If you change some shortcut keybindings and then decide you don't want to and press Cancel, the changes will persist nonetheless -- they will not be discarded.
Other changes, e.g. theme, are properly discarded if you press Cancel.

Similarly, the left button `Restore defaults` also does not restore changed keybindings--the one on the right `Restore all keybindings` does work correctly.

### 💡 Steps to Reproduce

Open the Shortcuts preference window.
Change a shortcut keybinding.
Press Cancel on the right to exit.
Re-open and see that the shortcut has been changed.
Change another shortcut and press `Restore defaults` on the right.
See that shortcuts have not been restored.

### 💡 Expected Behavior

Cancel should discard all changes and restore to my last state.
`Restore defaults` should restore all defaults, equivalent to `napari --reset`

### 🌎 Environment

napari: 0.5.0a2.dev359+g0907fdad5
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
Qt: 6.7.1
PyQt6: 
NumPy: 2.0.1
SciPy: 1.14.0
Dask: 2024.7.1
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.6

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.0a3.dev189+gc48deb2

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml
Plugins:
  - napari: 0.5.1.dev6+g62ef757a5 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)

**Comment by dalthviz** [comment]
Hi there, after some digging it seems like this is caused due to the shortcuts widget not implementing the `setValue` method. Currently, and most probably after #7027 (which moved from a rebuild widgets approach to one that update widgets following settings events), the preferences shortcuts widget doesn't react to settings updates that are triggered by buttons that just change the settings. So I think a possible fix is to enable/uncomment the call for the `ShortcutsWidget` `setValue` at https://github.com/napari/napari/blob/975759073cf81ca2de419e931416d07926aaa8c4/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py#L619

And implementing the `setValue` method over the `ShortcutEditor` class. It could look something like:

```python

    def setValue(self, state):
        for action, shortcuts in state.items():
            action_manager.unbind_shortcut(action)
            for shortcut in shortcuts:
                action_manager.bind_shortcut(action, shortcut)

        self._set_table(layer_str=self.layer_combo_box.currentText())

```

Doing the changes above I can see locally the following behavior:

![shortcuts_reset_cancel](https://github.com/user-attachments/assets/fd15e006-f53f-4fb0-af9d-dc11f32e64b6)

Also, while checking this seems, like there are other preferences widgets that have disabled/commented out the call to the `setValue` method when the widget state changes like `Extension2ReaderWidget` and `PluginWidget`. Maybe those also have issues related with reverting changes or restoring things to default values? 🤔
