### ISSUE TITLE
Keybinding conflict handling not consistent between viewer/layer contexts 

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#7210]
**Setting a layer keybinding to be the same as viewer**
E.g., The 'viewer' group/context has a key sequence 'A'. Switch to a layer group and try to set a keybinding to 'A' -> you get a conflict!

**Setting a viewer keybinding to be the same as a layer**
E.g., The 'Image' group/context has a key sequence 'A'. Switch to 'viewer' group and try to set a keybinding to 'A' -> it works!

Are we sure we want this non-bidirectional behaviour?

I understand in the first scenario, layer group keybindings take precedence over viewer group ones, so we want to prevent people from over-writing a keybinding.
BUT the same precedence (layer > viewer) also occurs when we allow user to set a viewer group keybinding to be the same as a layer. However we allow it in this case? In this case the new keybinding does not take precendence, but this may also be a problem for the user.
What about giving a warning in the first scenario instead?

Note also that if the user wanted to get around the first scenario they could do:

1. Change the conflicting 'viewer' group keybinding *temporarily* to 'B'
2. Switch the 'layer' group keybinding to 'A'
3. Switch the 'viewer' group keybinding *back* to 'A'

cc @DragaDoncila

**Comment by DragaDoncila** [comment]
Yeah I thought this was super weird that it doesn't go both ways. In fact I think I got caught out by this [when reviewing](https://github.com/napari/napari/pull/7124#issuecomment-2257321868)  #7124. I'm not sure why it's ok for a viewer to copy a layer keybinding and not the other way around... I feel like it would still lead to confusing behaviour for the user. @psobolewskiPhD thoughts?

**Comment by psobolewskiPhD** [comment]
It's definitely a bug I think. The conflict check should be bi-directional: viewer bindings are always available, so they would always clash with a layer. If a user wants to set a viewer binding that clashes they should be informed of the conflict and resolve it themselves IMO.
Same binding for different layers would be safe because layers are exclusive.

**Comment by lucyleeow** [comment]
> If a user wants to set a viewer binding that clashes they should be informed of the conflict and resolve it themselves IMO.

So you think the user should not be allowed to set a viewer binding that conflicts with a layer one?
I'm okay with this, just wondering if there is a case where the user may want to set both to the same sequence? E.g., a key sequence to do something when a e.g., Image layer is not active, and something else when it isn't?

**Comment by dalthviz** [comment]
Hi there, just in case, giving this a check I think this bug is due to the way `_get_layer_actions` is defined:

https://github.com/napari/napari/blob/cab7c661bef5daf9a74b312b390ea10715eefe63/napari/_qt/widgets/qt_keyboard_settings.py#L295-L303

To achieve a validation of layer vs viewer and viewer vs any layer keybinding maybe something like the following could be done:

```python
    def _get_layer_actions(self):
        current_layer_text = self.layer_combo_box.currentText()
        layer_actions = self.key_bindings_strs[current_layer_text]
        actions_all = layer_actions.copy()
        if current_layer_text != self.VIEWER_KEYBINDINGS:
            viewer_actions = self.key_bindings_strs[self.VIEWER_KEYBINDINGS]
            actions_all.update(viewer_actions)
        else:
            for group, keybindings in self.key_bindings_strs.items():
                if group != self.VIEWER_KEYBINDINGS:
                    actions_all.update(keybindings)
        return actions_all
```

![shortcuts_conflict](https://github.com/user-attachments/assets/4fd6fdf7-7ad3-4b43-9cf7-2fcfeef81c02)

> Edit: Small thing with conflict handling, the warning gives you the name of the conflict, but not where (viewer, which layer). Would be nice to improve that.

So something like this:

![shortcuts_conflict_extra_info](https://github.com/user-attachments/assets/db9eb261-3b06-4c49-bfcc-5a0a2a8fdb65)

?

**Comment by lucyleeow** [comment]
Just to confirm, what is the desired behaviour? Do we want to not allow viewer/layer conflicts? Or allow but warn the user that layer ones take precedence?

**Comment by psobolewskiPhD** [comment]
My vote is no viewer/layer conflicts in either direction.
It's not obvious--or intuitive--to me which would take precedence if we allowed conflicts.

**Comment by DragaDoncila** [comment]
@dalthviz I played with the branch and I think that's the behaviour we want, including pointing out which group has the conflict. Would be great to see a PR with the changes!

Also sidenote - what even is the `Ctrl` keybinding for...? What does `Reset scroll` do lol, I couldn't figure it out. It's also weird cause you can't set (on Mac at least) just `^` as a keybinding anyway.

**Comment by dalthviz** [comment]
> Would be great to see a PR with the changes!

Opened a PR :+1:

> Also sidenote - what even is the Ctrl keybinding for...? What does Reset scroll do lol, I couldn't figure it out.

Did a quick check related to the `Reset scroll` functionality and I think it means that when you press `Ctrl`/`Control` the dimension scrollbar that is selected gets triggered instead of the canvas zoom when using the mouse scroll wheel. So for example, if you run the `nD_image.py` example you can do something like the following:

![reset_scroll_functionality](https://github.com/user-attachments/assets/3f791422-991f-438e-af4a-b47d5a420bbf)

So when the mouse is over the canvas it always zooms in/out when doing a mouse scroll wheel input, but the selected dimension scroll bar is the one that gets the mouse scroll wheel input when `Ctrl` is being pressed. Maybe a better name/description for it is needed?

>  It's also weird cause you can't set (on Mac at least) just ^ as a keybinding anyway.

Regarding setting a single modifier shortcut, you need to press `Enter` (or any other of the keys that is not allowed to be part of a shortcut) to lock it in. So for example, to set `Ctrl`:

![set_single_mod_shortcut](https://github.com/user-attachments/assets/db908e5f-35eb-440e-8fe3-f1710cdc2862)

I think it should work in the same way over macOS but I will give a check. Anyhow, I think I'm gilthy of that behavior 😅 (most probably related with https://github.com/napari/napari/pull/6330). Let me know if that needs to get revisited!

**Comment by psobolewskiPhD** [comment]
@DragaDoncila I looked into reset_scroll while ago, I think it's a vestigial. I meant to make an issue and/or PR but dropped the ball as usual. The trick to setting a modifier-only keybind is to hold it and then press enter. I think it's undocumented on purpose because we don't want people doing it, but I use the old modifiers on labels layer all the time (shift for preserve, alt for erase, control for fill etc.)

**Comment by dalthviz** [comment]
Actually, did a further check and seems like the reset control action is not fully related with the behavior I described above :thinking: I think changing the scroll wheel behavior with Ctrl/Control is hardcoded at:

https://github.com/napari/napari/blob/6e292a8a05f2d195882288d4629695047896f20c/napari/components/_viewer_mouse_bindings.py#L1-L15

And seems like the reset scroll indeed resets the `_scroll_progress` flag/attribute:

https://github.com/napari/napari/blob/6e292a8a05f2d195882288d4629695047896f20c/napari/components/_viewer_key_bindings.py#L50-L60

But I'm not totally sure that is actually affecting the code over the `dims_scroll` function 🤔 

Created an issue #7232 to further discuss what to do with that action :+1:
