### ISSUE TITLE
Don't load big size images

### ISSUE THREAD

**Issue by Shogosuga** [napari/napari#731]
I tried to load 8000 EM images(each 4000 x 7000), but couldn't.
I also tried `napari.view_image(data, is_pyramid=False)` and `data.rechunk((1,100,100))` , but could not load in both methods.
So, please tell me the suitable method to solve this distress.
Thank you.

**Comment by sofroniewn** [comment]
@Shogosuga sorry you're running into problems. Have you tried also setting the `contrast_limits` ahead of time too? We need to get better about not accidentally computing on the whole dataset, but we've got some issues on that already.

Can you also confirm that the following works ok for you too
```python
import dask.array as da
import napari

data = da.random.random((8000, 4000, 7000), chunks=(1, 4000, 7000))
napari.view_image(data, is_pyramid=False, contrast_limits=[0, 1])
```

**Comment by Shogosuga** [comment]
Thank you!
I try `contrast_limits` and I can load all images.

I really appreciate for your kindness.

**Comment by sofroniewn** [comment]
Glad that made it work! I will leave this issue open though as we really need to fix it so that we don't choke so badly if that parameter is not passed

**Comment by sofroniewn** [comment]
I'm going to close this now as it seems like the `contrast_limits` issue have been fixed and the https://github.com/napari/napari/blob/dec5b9965d4a3fcea2d8314064465af14a97fec7/napari/layers/layer_utils.py#L25-L65
function doesn't take too long if big data is provided - both zarr and dask - see https://github.com/napari/napari/blob/dec5b9965d4a3fcea2d8314064465af14a97fec7/napari/layers/image/_tests/test_big_image_timing.py#L14-L25

If anyone is continuing to have to pass `contrast_limits` in order to avoid expensive computations can they please open a fresh issue with a minimal example so we can make sure that isn't still happening for people. You might still need to pass the `is_pyramid=False` or `is_pyramid=True` depending on your circumstances
