### ISSUE TITLE
Fix binder setup

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7331]
## 🧰 Task

Currently, the binder button spawns the linux desktop but the desktop icon for napari doesn't do anything.
If you open a console in the linux desktop and run napari that way, you get a traceback related to npe2.

The conda env file is wierd with way too much stuff specified rather than just napari pyqt and what's needed for jupyter?
https://github.com/napari/napari/blob/main/binder/environment.yml

Also, should switch to using https://github.com/jupyterhub/jupyter-remote-desktop-proxy
See, e.g. https://psobolewskiphd.github.io/i2k2024_napari_workshop/notebooks/spot_detection.html

**Comment by melissawm** [comment]
Maybe the setup for the napari-workshop-template can be reused as well?

**Comment by psobolewskiPhD** [comment]
Yup! That needs to be fixed too:
https://github.com/napari/napari-workshop-template/pull/41

**Comment by dalthviz** [comment]
Hi there, giving this a check, maybe the reason the dependencies are described individually instead of just installing napari is to have a preview over the binder instance of the latest dev version? Just in case, over Spyder we do that but we also have multiple badges so we can launch binder instances from the master/main and 6.x branches and also one to launch the latest released version:

![imagen](https://github.com/user-attachments/assets/532afcd6-6c82-49b2-9ee2-cf5963fee16b)
