### ISSUE TITLE
IndexError when mixing 2D and 3D layers and enabling transform mode

### ISSUE THREAD

**Issue by jni** [napari/napari#7333]
### 🐛 Bug Report

Turning on transform mode with layers of mixed dimensionality causes a crash when mousing over the canvas:

```pytb
WARNING: Traceback (most recent call last):
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/superqt/utils/_throttler.py", line 286, in _set_future_result
result = self._func(*self._args[: self._max_args], **self._kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/superqt/utils/_throttler.py", line 226, in weak_func
return method(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/_vispy/canvas.py", line 456, in _on_mouse_move
self._process_mouse_event(mouse_move_callbacks, event)
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/_vispy/canvas.py", line 417, in _process_mouse_event
mouse_callbacks(layer, event)
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/utils/interactions.py", line 169, in mouse_move_callbacks
mouse_move_func(obj, event)
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/layers/base/_base_mouse_bindings.py", line 31, in highlight_box_handles
layer._transforms[1:].set_slice(event.dims_displayed).inverse
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/utils/transforms/transforms.py", line 231, in set_slice
return TransformChain([tf.set_slice(axes) for tf in self])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/utils/transforms/transforms.py", line 231, in <listcomp>
return TransformChain([tf.set_slice(axes) for tf in self])
^^^^^^^^^^^^^^^^^^
File "/usr/local/Caskroom/miniforge/base/envs/cpt-lab/lib/python3.11/site-packages/napari/utils/transforms/transforms.py", line 928, in set_slice
scale=self._scale[axes],
~~~~~~~~~~~^^^^^^
IndexError: index 2 is out of bounds for axis 0 with size 2
zsh: abort python
```

### 💡 Steps to Reproduce

```python
import napari

viewer = napari.Viewer()
_ = viewer.add_points([[0., 0., 0.]], name="3Dlayer")
pt2 = viewer.add_points([[1., 1.]], name="2Dlayer")
pt2.mode = 'transform'

napari.run()
```

then mouse over the canvas.

### 💡 Expected Behavior

there should be no errors.

### 🌎 Environment

```
napari: 0.5.4rc4.dev0+gc73e9d5ec.d20241014
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 17:58:42) [Clang 17.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.2
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.3

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - napari: 0.5.4rc4.dev0+gc73e9d5ec.d20241014 (81 contributions)
  - napari-console: 0.1.0 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - skan: 0.11.2.dev38+g669eeba.d20241014 (4 contributions)
```

### 💡 Additional Context

Initially reported by @palvarezc in Zulip [here](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari.20with.20layers.20of.20different.20dimensions/near/476994158).

**Comment by jni** [comment]
@dalthviz, do you happen to have some cycles available this week to try to tackle this one? :grimacing: 🙏

**Comment by dalthviz** [comment]
Hi there, sorry for the late response (I was away attending some events/out of office the last couple of weeks)! Will check a fix for this :+1:

**Comment by jni** [comment]
No worries! It seems it's a busy time for all of us right now! 😅😅😅😮‍💨 I appreciate you looking! 😊

**Comment by dalthviz** [comment]
Checking this seems like the viewer sets as dims being displayed the higher dims available? So the error being experienced is caused since the displayed dims being retrieved are `[1, 2]` while the points 2d layer only has two dimensions so there is a mismatch related with the axes available which causes an index error when trying to slice the transform instance following the current dims being displayed. Checking why those dims are being retrieved as displayed, seems like that is the way the dims viewer slices the dims order array to retrieve the displayed dimensions:

https://github.com/napari/napari/blob/b9dc8dca1e1afa7567586e7ffa7a36cc7cd9fb6f/napari/components/dims.py#L287-L290

Not totally sure if adding a validation to the mouse bindings functions related with the transform box to show a message indicating that is not possible to transform the layer could be enough. So something like:

![imagen](https://github.com/user-attachments/assets/096d7585-e6af-4570-8878-0b6fc4e5a7ec)

Or maybe some sort of extra logic should be added over the mouse bindings functions related with the transform box to covert the dims displayed to an equivalent over the layer dims? 🤔

**Comment by andy-sweet** [comment]
Need to look at more detail around the bug here, but the display dims indexed in each layer (instead of being indexed in the shared world defined by `Dims`) should be available in `Layer._slice_input.displayed`. I'm hoping that could help with a fix!

**Comment by dalthviz** [comment]
Thanks for info! Did a naive attempt to use `Layer._slice_input.displayed` instead of `event.dims_displayed` over the mouse bindings functions that handle the transform logic (https://github.com/napari/napari/blob/main/napari/layers/base/_base_mouse_bindings.py) and with that no error is raised with interacting with the viewer :+1: However, seems like the layer transformation is limited to doing translations on only one axis?:

![transform_2d_3d_data](https://github.com/user-attachments/assets/e21152f4-f501-43cb-9966-b44108770229)

Maybe that makes sense since the value returned by `Layer._slice_input.displayed` is `[0, 1]` and the viewer displayed dims value is `[1, 2]` so at the end you are only able to interact with 1 axis of the 2d layer? 🤔

**Comment by andy-sweet** [comment]
> Maybe that makes sense since the value returned by `Layer._slice_input.displayed` is `[0, 1]` and the viewer displayed dims value is `[1, 2]` so at the end you are only able to interact with 1 axis of the 2d layer? 🤔

The integer values mean different things though.

`Layer._slice_input.displayed` are indices into the layer's local dimensions (there are 2), whereas `Dims.dims_displayed` (which I'm assuming is where the value of `event.dims_displayed` comes from - would be good to confirm though!) are indices into the shared world dimensions (there are 3).

We generally have a problem around dimension correspondence (can dig up the relevant issue), but I would have thought that a workaround is possible because similar correspondence transforms happen (hopefully successfully!) for other functionality (e.g. see `Layer.get_value`).

I'm not familiar with how the mouse bindings are actually called, but it might be worth checking `Layer.get_value` and similar parts of the code to check they handle the correspondence problem. Maybe that can be reused in these transform mode callbacks too?

**Comment by dalthviz** [comment]
Thanks for the extra input! That makes sense and in fact, following that, I think I was able to make things work! So basically when dealing with the layer transform indices the layer's local dimensions need to be used (by for example using `Layer._slice_input.displayed`) but when dealing with the mouse position the shared world dimensions indices still should be used (from `event.dims_displayed`). So for example over `highlight_box_handles`:

https://github.com/napari/napari/blob/b9dc8dca1e1afa7567586e7ffa7a36cc7cd9fb6f/napari/layers/base/_base_mouse_bindings.py#L21-L42

Something like this could be done:

```python
def highlight_box_handles(layer: 'Layer', event: Event) -> None:
    """
    Highlight the hovered handle of a TransformBox.
    """
    if len(event.dims_displayed) != 2:
        return

    # we work in data space so we're axis aligned which simplifies calculation
    # same as Layer.world_to_data
    world_to_data = (
        layer._transforms[1:].set_slice(layer._slice_input.displayed).inverse
    )
    pos = np.array(world_to_data(event.position))[event.dims_displayed]
    handle_coords = generate_transform_box_from_layer(
        layer, layer._slice_input.displayed
    )
    # TODO: dynamically set tolerance based on canvas size so it's not hard to pick small layer
    nearby_handle = get_nearby_handle(pos, handle_coords)

    # set the selected vertex of the box to the nearby_handle (can also be INSIDE or None)
    layer._overlays['transform_box'].selected_handle = nearby_handle
```

Doing similar changes all over the different functions handling the transform box logic/actions, is indeed possible for the transform mode to work even with the discrepancy between layers dimensions 🎉:

![transform_2d_3d_data_working](https://github.com/user-attachments/assets/39173ce4-c060-4ed4-9de5-ecadb0b4dae6)

Here a branch with the changes: https://github.com/napari/napari/commit/038a9fd9d1728d504169cabe420ac0a58f21853a

Let me know if that approach makes sense to open a PR!

**Comment by jni** [comment]
From a cursory look it makes sense to me, although I do find it worrisome that we are relying on slice input information on the layer. But I think it's the right solution for the current state of the architecture. So I say open the PR @dalthviz! For me it's important to get users unstuck quickly here. 😊 Thank you! And thanks @andy-sweet for the help! Love seeing these collaborations. 😊
