### ISSUE TITLE
Unable to open console in second viewer when opening two viewers

### ISSUE THREAD

**Issue by jni** [napari/napari#7413]
### 🐛 Bug Report

If you open two viewers, you can only open the console in one of them. In the other one, you get a blank space but no console.

<img width="1095" alt="Screenshot 2024-11-29 at 6 42 31 pm" src="https://github.com/user-attachments/assets/cebcf401-8773-4991-b026-3221f57d035b">

This is true regardless of whether you close the first viewer first.

### 💡 Steps to Reproduce

1. run this script

  ```python
  import napari
  
  viewer = napari.Viewer()
  #napari.run()  # uncomment to check sequential vs simultaneous behaviour
  viewer2 = napari.Viewer()
  napari.run()
  ```

2. open the console in one of the viewers
3. open the console in the other viewer

### 💡 Expected Behavior

the console should open in both viewers.

### 🌎 Environment

```
napari: 0.5.4rc4.dev0+gc73e9d5ec.d20241014
Platform: macOS-15.1.1-arm64-arm-64bit
System: MacOS 15.1.1
Python: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 17:58:42) [Clang 17.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.2
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
  - GL version:  2.1 Metal - 89.3
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.3

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - midi-app-controller: 0.0.13.dev6+g180a6ba (2 contributions)
  - napari: 0.5.4rc4.dev0+gc73e9d5ec.d20241014 (81 contributions)
  - napari-console: 0.1.1 (0 contributions)
  - napari-ome-zarr: 0.6.1 (2 contributions)
  - napari-signal-selector: 0.0.6 (10 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - skan: 0.12.1.dev4+g3d5da88 (4 contributions)
```

**Comment by Czaki** [comment]
This is a problem in jupyter qt_console, as there is a single console for session.

**Comment by jni** [comment]
Any ideas on whether we can do anything to circumvent this on our end? In the worst case, we should at least have an informative error message. But ideally it would be good to shut down the other console gracefully, or maybe even contribute upstream to be able to have multiple consoles (though I'm sure that is a huge can of worms).

**Comment by psobolewskiPhD** [comment]
@jni can you elaborate on your expected behavior? 
In that case where 1 script spawns 2 viewers, do you expect the two consoles to be the same? basically type into either and get whatever the effect, like if you spawned 2 viewers from ipython (in this case neither viewer has a console, but ipython controls both)?

**Comment by jni** [comment]
yeah I probably would expect a shared state/history, but not textual input/output. Similar to multiple jupyter notebooks connected to the same IPython kernel. I'm not 100% sure if what I'm asking is feasible or even reasonable. 😅

**Comment by Czaki** [comment]
It means that we need to reimplement console from scratch, or try open Issue in https://github.com/jupyter/qtconsole to get information from maintainers how to have two in process qt console instances.

**Comment by jni** [comment]
I mean I clearly favour the latter option. 😅

**Comment by dalthviz** [comment]
Hi there, checking this I think there is a missing line over `napari-console` to allow having multiple multiple consoles using the same kernel. So, over `napari-console` there is already some logic to connect to an existing kernel but is missing a call for `kernel_client.start_channels()` after line https://github.com/napari/napari-console/blob/463f828d5f4af732dfd87a7091d2ec4c8647af17/napari_console/qt_console.py#L135

Checking locally, if I add that missing line, I'm able to see the following:

![multiconsole_support](https://github.com/user-attachments/assets/f2a0e967-c6bf-46f4-a744-2fbea3dabc77)

Is that the expected behavior? Let me know!

**Comment by psobolewskiPhD** [comment]
I think that looks pretty amazing!!

**Comment by jni** [comment]
Me too! I am amazed! 🤯🤩😃

**Comment by jni** [comment]
I was riveted looking at your screenshare @dalthviz 🍿😍
