### ISSUE TITLE
Screenshot and Figure Export examples are grayscale, but should be color

### ISSUE THREAD

**Issue by TimMonko** [napari/napari#7425]
## 📚 Documentation

All napari.org examples using either `viewer.screenshot()` or `viewer.export_figure()` have layer images that are grayscale (see:  [Export Figure](https://napari.org/dev/gallery/export_figure.html#sphx-glr-gallery-export-figure-py),  [To Screenshot](https://napari.org/dev/gallery/to_screenshot.html#sphx-glr-gallery-to-screenshot-py), [Comparison of Screenshot and Figure](https://napari.org/dev/gallery/screenshot_and_export_figure.html#sphx-glr-gallery-screenshot-and-export-figure-py); locally, these examples properly show color. 

Examples which do not use these functions properly display layers with color (e.g. [Add Shapes](https://napari.org/dev/gallery/add_shapes.html#sphx-glr-gallery-add-shapes-py).

Interestingly this historical example, [napari without gui_qt](https://napari.org/dev/gallery/without_gui_qt.html), also has a grayscale canvas after using just the screenshot, but not adding the screenshot back as a layer.

Locally, taking a screenshot momentarily turns my canvas grayscale. Does this mean the examples aren't returning back to color after being made grayscale in the screenshot? In some ways this is a surprise because the examples go back to interacting with the viewer (implying, to me, that the viewer is maintained long enough to go back to color)

napari.org:
![sphx_glr_to_screenshot_001](https://github.com/user-attachments/assets/fe07703d-e495-42ff-88cc-bfbd43d9e571)

script run locally:
![image](https://github.com/user-attachments/assets/3d497e27-902d-44fb-adfc-cc63600a13b9)

**Comment by psobolewskiPhD** [comment]
Clearly the image file is RGB, because the layer list thumbnail is in color, so it's just the canvas.
Very wierd! 🦑 

> locally, these examples properly show color.

Do you mean when the scripts are run locally or when docs are built locally?

**Comment by TimMonko** [comment]
> Do you mean when the scripts are run locally or when docs are built locally?

Ah shoot, should have clarified the script. Still haven't set up building the docs locally (I should)

> Clearly the image file is RGB, because the layer list thumbnail is in color, so it's just the canvas. Very wierd! 🦑

> Edit: the whole canvas looks wierd--not black.

Exactly! These two things together suggest to me it's stuck in the 'grayscale screenshot' view. I wish I even knew where to start to find more insight, sorry!

**Comment by TimMonko** [comment]
Hmmm, if I get docs to build locally, I would start by testing `viewer.screenshot(flash=False)`.

Might get to this later tonight or tomorrow.

**Comment by psobolewskiPhD** [comment]
I built the docs locally and the napari viewer that popped up for that example when building the gallery appears like the screenshot! So it seems the screenshot being added to the viewer is being treated as grayscale when executed by the docs gallery building.
<img width="935" alt="image" src="https://github.com/user-attachments/assets/ffded970-0d79-4d9c-986a-d2f98dafa269">
(ignore the shape, it's because hiDPI screen)

**Comment by psobolewskiPhD** [comment]
Great minds think alike @TimMonko !
I noticed the flashing when I ran the example as a script. It makes no sense, but maybe the flash is much much slower so that the new layer is already added, but flash is happening still, and then the docs screenshot fires?
Anyhow 🎉 
<img width="925" alt="image" src="https://github.com/user-attachments/assets/3a0b230e-9d1e-4cc2-8968-07e3ca8d8a57">

**Comment by psobolewskiPhD** [comment]
I guess we should add `flash=False` and a comment that it's for the auto generated gallery.
That's the path of least resistance at least.
That or add a sleep? I tried 0.3 and it wasn't enough.

**Comment by psobolewskiPhD** [comment]
If you want to play with this, what I did was:
1. follow these instructions, making sure my napari was `-e`: https://github.com/napari/docs#quickstart-local-setup
2. make a branch of napari/napari (where the examples live) to test with
3. delete excess examples to make the build faster:
`find . -type f -name "*.py" ! -name "to_screenshot.py" -exec rm {} \;`
4. cd to napari docs repo dir and do `make docs`
5. `open docs/_build/html/gallery/to_screenshot.html`

**Comment by psobolewskiPhD** [comment]
You're right in this case the -e probably didn't do anything, because the example was just being pulled in.
But I think the `-e` would be good if you were working on napari itself, because then you could change branches or edit code and re-run building of docs and that live `napari` will actually be used to run the tutorial notebooks, the gallery, etc.
