### ISSUE TITLE
Linked multicanvas support

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#760]
## 🚀 Feature

A number of issues and people have requested multi canvas support, for example #561  and #662 representing two major use cases - #561 is something like our grid mode but now with linked cameras so that zooming in on one spot in one canvas causes the same zoom on all the canvas. In this mode you could still have one global dims model, each layer would get assigned exactly to one canvas, and you could have one global set of QtDims sliders that sliced through all the layers simultaneously in the same way. Supporting this wouldn’t be much of a breaking change and should be relatively straightforward.

#662 would enable simultaneous ortho views + 3D view (optional). Here you need a different dims slider for each of the 3 orthoviews and no dims slider for the 3D rendering. You also might still want to still have some global dims sliders, say if you we looking at ortho views of a volumetric time series and you wanted to always look at single time slice at in all the canvases. It’s a little unclear how we should best support this.

Another option is that people just want to look at different layers side by side with fully independent control of camera and sliders. I’m not sure if we want to support this (why not then have a tabbed viewer, or multiple viewers), but on the other hand why prevent it if people want it, and architecting the system for this generality could future proof us for new features, prevent overfitting to our biases and special casing. I’m inclined to give this a level of generality a go, and then we’d do the linking (and possibly removing of duplicate sliders etc) after.

Another thing we should also consider at this point are things like our 1D time series and histogram plots in #675. We have discussed whether these should be considered as “layers” or something special, and whether they should live in “DockWidgets” or the “MultiCanvas mode”. One thing to consider is if the mulitcanvas mode can accept “DockWidgets” so you could rearrange a grid of the “DockWidgets”. Clearly these objects would not have the same type of camera and dims slicing, but you might want the to be updatable from the dims model (i.e. when slider moves change the histogram). That might be custom code that differs use case by use case, but we still want to make sure it is possible.

To me, some big questions we need to answer first are - how generic do we make the multicanvas stuff? As noted above, I prefer starting with as generic as is still simple and then if we need to reduce functionality we can. That would mean that inside the main viewer widget there would be a QGridLayout where we can put whatever widgets we like and maybe DockWidgets so they can easily be rearranged. I think I would also still like to keep option for a global dims slider at the bottom, but it might be simpler to drop that too and just have each canvas have all the sliders they need right under them and then sync elsewhere. Certainly the idea of turning a `QHBoxLayout with a vispy canvas + QtDims model` into a reusable widget that can be moved around has some appeal too (say called `QtCanvas`). You could think of the main QtViewer as containing one of those QHBoxLayouts right now in the middle.

Next question is how do we think about the dims model when there can now be multiple views on the same layer. One option if to have `viewer.dims` become a list with one dims model (and QtDims) for each canvas. This is quite a simple, though major breaking change. Another option is we keep one dims model, but turn things like `order, ndisplay, point and indices` into lists. I’m not quite as sure about that one though.

I think then I’d also want to ability to have “layer copies” where data and most properties are shared but the `_data_view` can be different and each copy has its own vispy (this is maybe easier when each layer just has one Dims model). This would mean the layer would appear in the layer list each time it was in a canvas and each time with its own thumbnail for the different view. Do people like this idea, or is that weird? Again imagine the orthoview case. Would you like to see the layer just once or 3 or 4 times in the layers list. If just once then we might want to go with one Dims model that has lists inside. If we want 3 or 4 times we might want to go with layer copies.

We’d need an api to create multiple canvases, assign layers to each canvas. If a layer appears in multiple canvases it now gets multiple views and so it’s dims model expands in one of the ways described above, and we then need a way to link dims models and cameras across views as desired.

I think this actually all sounds pretty reasonable and I’d like to get going on it after we get this last burst of styling / widget PRs in. I think I’d start off with the changes to multicanvas and QGridLayout and ability to assign layers to different canvases while still having a global dims model. This will be not be too much of a breaking change and could still happen in `0.2`. We can then think more about the orthoview case and different Dims models for each canvas which might need to come in an `0.3` release.

What are peoples thoughts?

**Comment by tlambert03** [comment]
there's a lot here, so I might have missed some things, but some immediate thoughts:

> #662 would enable simultaneous ortho views + 3D view (optional). Here you need a different dims slider for each of the 3 orthoviews and no dims slider for the 3D rendering. You also might still want to still have some global dims sliders, say if you we looking at ortho views of a volumetric time series and you wanted to always look at single time slice at in all the canvases. It’s a little unclear how we should best support this.

I think ortho-views might be the most obvious/direct application for multi-canvas.  If I understand what you're proposing, it's the same I had been imagining: an additional slider for each new orthoview ... so a 3D image (in 2D view) would have 3 sliders instead of 1, (and each slider would affect the view of 2 of the three orthview canvases).  In 3D view, the sliders would all disappear, and the orthoview would be represented as different camera angles on the same scene.  (alternatively... in 3D view, the sliders could stay and we could do something like the quad view in paintera ... which I particularly like for 3D annotation).

> Another thing we should also consider at this point are things like our 1D time series and histogram plots in #675. We have discussed whether these should be considered as “layers” or something special, and whether they should live in “DockWidgets” or the “MultiCanvas mode”. One thing to consider is if the mulitcanvas mode can accept “DockWidgets” so you could rearrange a grid of the “DockWidgets”.

this might just be semantics, but I wouldn't try to somehow allow for our actual `QtViewerDockWidget` to be added to the canvas... rather, in the case of the 1D plots in #675 for instance, we might want to have multiple graphs next to each other.  And in that case it's not the Qt `DockWidget` we're duplicating, but the vispy `PlotWidget` (SceneCanvas).

> Next question is how do we think about the dims model when there can now be multiple views on the same layer.

as long as the different views are strictly orthogonal, as in an orthoviewer, I don't think we need a different model at all, but if we're considering arbitrarily different oblique views on the same layer, then the possibilities become quickly unmanageable and the only thing I can picture would be a different dims object per view... but then the GUI representation becomes quickly challenging.  I think I'd need to hear an obvious use case to wrap my head around the application there.

**Comment by tlambert03** [comment]
just took a look at this and wanted to put my thoughts somewhere (not ready for a PR yet, but i think this is one direction it could go).

for an orthoviewer, in`QtViewer`, instead of using `add_view` on the central_widget, use `add_grid` (which makes a [Vispy.scene.widgets.Grid](http://vispy.org/scene.html?highlight=grid#vispy.scene.widgets.Grid)) and add seperate `views` to the grid for XY, YZ, XZ:
```
        self.grid = self.canvas.central_widget.add_grid()
        self.viewXY = self.grid.add_view(row=0, col=0)
        self.viewYZ = self.grid.add_view(row=0, col=1)
        self.viewXZ = self.grid.add_view(row=1, col=0)
```

then in `QtDims._update_display`, all dimensions that have any representation in the orthoviewer (e.g. all three dimensions for a 3D stack) need to have their `slider_widgets` displayed.  

The `components.dims.Dims.displayed` property also needs to be aware of whether we're showing multiple orthoviews, because the `Dims.indices` property will need return a slice for _all_ dimensions if so.

`layers.image.Image._set_view_slice()` would then need to set not one, but three different `self._data_view`s: one for each of the ortho-slices.  I think that probably jives well with the proposed `datasource` that @d-v-b is working on in #792:  the `datasource` would know how to return each of the three orthoviews given the `dims.indices`.  In other words, this line in the image `_set_view_slice` would be modified to retrieve all the needed slices from the `datasource`.
https://github.com/napari/napari/blob/9ba2e7f55a2bdbff340d84788c994c1237d1c444/napari/layers/image/image.py#L499

The corresponding `VispyImageLayer` would then want to maintain not one, but three separate `ImageNode`s (and each of those three nodes would need to have their parent assigned as the corresponding `QtViewer.viewXY.scene`, `QtViewer.viewYZ.scene`, etc...).  There would also be three different cameras to link up to the VispyImageLayer (`QtViewer.viewXY.camera`, `QtViewer.viewYZ.camera`, etc..).  It would be nice to link those three cameras as well, such that zooming on one view zoomed on all three views.

`VispyImageLayer._on_data_change()` would then need to assign each of the three views generated by the Image model  in `_set_view_slice` with the corresponding `node.set_data` method.

For the sake of efficiency, it would also be important _not_ request a new data view on slider change for the axes that are not affected (i.e. the sliders that would have previously been hidden)

**Comment by sofroniewn** [comment]
High level thoughts - leveraging the `grid_view` that is built into vispy definitely seems worth exploring. I'm not too familiar with it, so need to learn more.

I'm now really coming around to the though that sliders should always be at the bottom of the whole viewer inside the sliders widget, i.e. there will never be sliders located within the little grid windows, and we show all the sliders needed to interact properly with the displayed info. This means that we don't need to think as much about the `GridLayout` being at the Qt layout but can maybe use the `grid_view` mentioned above.

The comments about `VispyImageLayer` and `Image` are well taken, but we want this to work for all our layer types and so I'd love if we could figure out how to do this without actually having to make many changes to our individual layer models, but instead think about some automated wrapping that could work for all of them

**Comment by liu-ziyang** [comment]
any objection closing this issue to consolidate multicanvas effort to https://github.com/orgs/napari/projects/16?

**Comment by sofroniewn** [comment]
> any objection closing this issue to consolidate multicanvas effort to https://github.com/orgs/napari/projects/16?

I think ok to close. I guess philosophy here is that with the new project board we have consolidated links to all the old issues and we should close the old ones as they aren't likely to be sites of continued discussion and it will make it easier to deal with the new issues and discussions that are coming in

**Comment by jni** [comment]
@potating-potato @sofroniewn I just realised that multi-scale, async, and multi-canvas (and I'm not sure if anything else) are being consolidated in a single project. These are quite orthogonal (pun not intended) concerns, and I think they should be separate projects.

**Comment by liu-ziyang** [comment]
> @potating-potato @sofroniewn I just realised that multi-scale, async, and multi-canvas (and I'm not sure if anything else) are being consolidated in a single project. These are quite orthogonal (pun not intended) concerns, and I think they should be separate projects.

I wish we had a chance to discuss the motivation behind async yesterday in the architecture working group. we consolidated slicing/async/multi-canvas to one project because they all spin off the slicing work as different use cases, and share some fundamental refactor requirements. I will pause on the consolidation and let's discuss this on the next architecture working group meeting

**Comment by sofroniewn** [comment]
I'm fine with either 3 projects or one project as long as if we split into 3 we're taking into consideration that some of the changes we make for one might have big impacts for the others. As @potating-potato says what they have in common is that they all require changes to our slicing model and it could be that we make a single change to slicing that will enable all of them.
