### ISSUE TITLE
Proposal: clean up napari.util.misc

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#761]
I noticed that `napari.util.misc` is getting a bit bloated and I think it would be good to clean it up a bit. To get the conversation rolling, I propose the following:

- create an image utils file
    - `is_rgb()`
    - `is_pyramid()`
    - `trim_pyramid()`
    - `should_be_pyramid()`
    - `get_pyramid_and_rgb()`
    - `fast_pyramid()`
- create a qt utils file
    - `mouse_press_callbacks()`
    - `mouse_move_callbacks()`
    - `mouse_release_callbacks()`
- move `format_doc()` into `napari.util.naming` (the only place it is used)
- move `interpolate_coordinates()` to the labels layer model folder or file (the only place it is used)
- `compute_max_shape()` doesn't appear to be used anywhere. delete?
- `segment_normal_vector()` doesn't appear to be used anywhere. delete?

**Comment by sofroniewn** [comment]
@kevinyamauchi I like this, but see #737 for some steps in that direction. Given the #737 also changes code though maybe we should do this PR first and then revisit #737.

I think `segment_normal_vector` is used in the shapes layer, but maybe no more. In general I think we should push some of the layer specific code into layer utils and qt specific code into qt utils, but curious how others think

**Comment by kevinyamauchi** [comment]
@sofroniewn , sorry I missed your changes in #737! I don't have a strong preference for if this or #737 is completed first. Once we decide the best refactor, it should be pretty quick, so we may be able to sneak this in while we figure out the best way forward with #737.

When I searched for `segment_normal_vector` in the repo, I only saw it in `napari.utils.misc`, but maybe I missed it. Do you know where it's used in the shapes layer?

**Comment by sofroniewn** [comment]
i guess `segment_normal_vector` and `compute_max_shape` were removed from the layer code and should be deleted.

I think we should do this refactor now and then i will adjust #737 (or make a new PR) as needed. It will make that PR easier to review.

Can you also remane -> `is_rgb` to `guess_rgb` and `is_pyramid` -> `guess_pyramid` and the other `is_*` to `guess_*` changes that are made in #737 will be better standardization of names across the repo.

you also need to put the contrast_limit calculation stuff somewhere too.

as you do the refactor can you also similarly refactor our tests too so that they match the new file organization

**Comment by kevinyamauchi** [comment]
Hello everyone. Based on our discussion today, I have come up with the plan below for the `napari.util.misc` refactor. Let me know what you think!

## Proposed refactor

- [ ] **/napari/util/misc.py** (used by multiple `napari.*` modules)
- `ensure_iterable()`
- `is_iterable()` (used by `ensure_iterable()`)
- `formatdoc()`
- `StringEnum`
- `camel_to_snake()`
- `CallDefault()`
- `CallSignature()`
- `callsignature`
- `str_to_rgb()`


- [ ] **/napari/util/interactions.py** (used by qt files)
- `ReadOnlyWrapper()`
- `mouse_press_callbacks()`
- `mouse_move_callbacks()`
- `mouse_release_callbacks()`
- `get_keybindings_summary()`
- `get_function_summary()` (used by `get_keybindings_summary()`)

- [x] **napari/layers/image/image_utils.py** (used exclusively by the image layers)
- `is_rgb()`
- `is_pyramid()`
- `trim_pyramid()`
- `should_be_pyramid()`
- `get_pyramid_and_rgb()`
- `fast_pyramid()`

- [x] **/napari/layers/labels/labels_utils.py** (used by exclusively the `Labels` model)
- `interpolate_coordinates()`

- [x] **/napari/layers/layers_util.py** (used by multiple layers)
- `increment_unnamed_colormap()`
- `calc_data_range()`
- `segment_normal()`

- [ ] **delete:** (unused functions)
- `compute_max_shape()`
- `segment_normal_vector()`

**In addition to moving files, I will:**
- update references
- update tests
- update the names for the pyramid functions as suggested by Nick above
- rename `shape_util.py` to `shapes_utils.py`

**Comment by sofroniewn** [comment]
Looks great to me @kevinyamauchi. Let's see if anyone else has any requested changes, @jni @kne42 otherwise I think you're good to get started.

it shouldn't be too hard to fix any merge conflicts with in-progress PRs (i'll take care of #737 when this is done) and it sets up a great framework for adding future util methods.

So nice to be able to do a first pass "review" here before any coding is done. Almost certainly will save time in the long run

**Comment by jni** [comment]
This list is great with the following possible exceptions:

- mouse_press_callbacks()
- mouse_move_callbacks()
- mouse_release_callbacks()
- get_keybindings_summary()
- get_function_summary() (used by get_keybindings_summary())

Those are currently used by our Qt viewer but there is nothing Qt about them. If we ever decide to build eg a web-UI, we might want to reuse some of this machinery. So, I'd move these to their own file, but I would not move them to Qt-land. They are not (from what I can tell) Qt specific. Thoughts?

**Comment by kevinyamauchi** [comment]
@jni , that’s a good point. I will put them into their own file in `napari/util`. Now the tricky part is the name...`interaction_utils.py`?

**Comment by sofroniewn** [comment]
if its inside the main `util` folder maybe just call it `interactions.py`

**Comment by kevinyamauchi** [comment]
Thanks for the feedback! 

I will get started making these changes now. I will also take advantage to add tests for any untested function along the way. To avoid a big PR with a bunch of files changed, I will make this in a series of PRs (one new util file per PR).

**Comment by sofroniewn** [comment]
@kevinyamauchi can you still make one more PR renaming
- [x] `vector_util.py` -> `vector_utils.py`
- [x] `shape_util.py` -> `shape_utils.py`
- [x] `_qt/util.py` -> `_qt/utils.py`
- [x] `_vispy/util.py` -> `_vispy/utils.py`
- [x] `util` -> `utils`
- [x] `napari/test/util.py` -> `napari/test/utils.py`

Then we have `utils` instead of `util` everywhere. I think consistency here makes it less confusing. @jni do you agree?

**Comment by kevinyamauchi** [comment]
Sounds good! I can get started on that later today.
