### ISSUE TITLE
Easier way to make points with no face color

### ISSUE THREAD

**Issue by henrypinkard** [napari/napari#762]
## 🚀 Feature

Minor improvement: I'm using napari to visualize results of a cell finding algorithm. Would like to use points layer to draw circles around detections. My instinct was to try something like this:

```viewer.add_points(yx, edge_color='magenta', face_color=None)```

But this throws an error. As far as I can tell, the way to accomplish this is to use the ring marker, but this doesn't seem the best way to outline circular objects if you also want to provide shape information. Thoughts?

**Comment by kevinyamauchi** [comment]
Hey @henrypinkard ! I think this should be possible. The `Points` layer wraps the vispy [`MarkersVisual`](https://github.com/vispy/vispy/blob/master/vispy/visuals/markers.py#L506-L586). The `face_color` can be set with a [`ColorArray`](https://github.com/vispy/vispy/blob/5fa85e0e9e639ce4282d04718fcd4c17de4d8e8d/vispy/color/color_array.py#L83) object, which has a alpha argument. We can make it such that when the `Points` layer `face_color` is set to `None`, the face color alpha is set to 0.  I _think_, this will make the face of the marker transparent. What do you think?

With regards to the ring marker, can you expand on what you mean by "doesn't seem the best way to outline circular objects if you also want to provide shape information"? You can pass a size to change the radius (can either by a single value that gets broadcasted to all markers in the layer or an array with sizes for each point).

```python
viewer.add_points(yx, edge_color='magenta', symbol='ring', size=size_array)
```

**Comment by henrypinkard** [comment]
Yeah sounds great!

Should have been a bit more clear on the second point. I just meant that if you want to 1) circle an object, 2) see the pixels within the circle, and 3) have the radius of the circle represent the object size, it is hard to do with the ring because by expanding the size in order to accomplish (2), you mess up (3) because both the inner and outer diameter enlarge simultaneously

**Comment by kevinyamauchi** [comment]
Got it, that makes sense. I have another issue I’m working on, but I can get to this next!

**Comment by sofroniewn** [comment]
This would be great. I'd prefer we use the explicit string `'transparent'` instead of the python variable `None` as we sometime use `None` to trigger a guess or a use another default setting - which is maybe not the best practice, but it would lead to ambiguity here

**Comment by jni** [comment]
I'm 👎 on "transparent", as it's not a color in any common color "dialects". (e.g. XKCD colors, the most extensive named color collection I know of, includes "dark forest green" but not "transparent".) We could just use `(0,) * 4`, and maybe None. I think None is fine, it can be the "default" when the actual default is properly specified in the signature.

**Comment by sofroniewn** [comment]
Passing `face_color = [0]*4` works right now on `Shapes` and `Points` (though setting `layer.face_color=[0]*4` fails on Points and we need to fix). Passing `(0,)*4` also should have worked, but throws an error which is definitely a bug and should be fixed in #774. Any 4-tuple fails right now, but a list of length 4 works. We should add tests to catch that too, and standardize this across layers using our colors.

@jni I was commenting more around a string representation that can be used within out color list, so users can say make shapes with no face color from the GUI.

![image](https://user-images.githubusercontent.com/6531703/70404316-82777880-19ee-11ea-8ae5-5ae09e6dbe2a.png)

I think the fact that `'transparent'` doesn't appear in a survey of RGB colors is actually a very good sign that it would be a good word for an RGBA color where A is 0 as no one will be confused by it. I think `'(0,) * 4'` would be strange for a name. I'm fine with the string `'None'` though if that is preferable to `transparent`. I'd just really prefer to avoid doing anything with the actual python variable `None` though as I just worry that shuts off so many options for us and creates so much ambiguity. That's why I still like `'transparent'`. We also might want to curate that list of vispy colors too as right now there are many more than needed and that drop down is hard to use.

An alternative idea which renders much of this discussion moot would be to move away from that drop down menu to a more traditional color swatch display or color picker tab. Qt actually provides a [`QColorDialog'](https://doc.qt.io/qt-5/qcolordialog.html) - see here

![image](https://user-images.githubusercontent.com/6531703/70405190-2c580480-19f1-11ea-862b-9fe620498f9f.png)

that I'm sure we could adapt and possibly combine with the context boxes @tlambert03 has recently implemented. Curious what @tlambert03 thinks of this discussion too.

If we knew that we were going to do something like this soon then we don't have to support either `'transparent'` or `None`.

**Comment by kevinyamauchi** [comment]
Feature added in in #782 .

**Comment by marcel-goldschen-ohm** [comment]
In napari 0.4.17 (vispy 0.11.0) in a conda environment on MacOS 13.1 (M1 Max) I cannot set a point's face color to be transparent independent of the edge color. I used to be able to do this by setting the alpha value of the face color, but this no longer has any effect, so perhaps something has changed recently? I can change the point opacity, but this changes both the edge color and the face color, and I want to only make the face transparent, not the edge. I tried to dig through the link to #782, but I could not find anything useful (there's a lot there, so maybe I missed it).

The inability to draw points as circles is pretty annoying, because the points occlude the selected parts that I want to see. I would think drawing points as rings with transparent faces would be something that many people would consider a standard feature for a library like this, but maybe I'm too niche ;) Anyway, if I'm missing something, please set me straight here. Otherwise, I think this issue needs to be reopened.

---
UPDATE: Actually, I can make the point faces transparent if I simply add a points layer by clicking the button in the UI and then manually add points. However, I cannot make the point faces transparent if I add a points layer by executing the following code in the napari console:

> import numpy as np
> spots = np.random.uniform(0, 256, (10, 2))
> viewer.add_points(spots, name='test spots', size=9, edge_width=1, edge_color='yellow', face_color=[0]*4)

After the above console commands, even manually attempting to set the face alpha in the UI does NOT work. In fact, I cannot change the face color at all, only the edge color.

Any suggestions?

---
SOLVED: Turns out setting edge_width=1 was occluding the point faces. This code used to work as I expected in a prior version of napari, so this threw me. Setting the edge_width_is_relative=False fixes this. Probably the default setting of edge_width_is_relative changed somewhere along the way. I don't think the current default is intuitive, but maybe it's just me.

Cheers
