### ISSUE TITLE
Physical coordinate systems

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#763]
## 🚀 Feature

There have been a number of requests from the community around supporting physical coordinates. Right now we have `scale` and `translate` properties and a scene graph so it will be possible, but we need to do some work around our APIs and bug-fixing to make it work well. We also have to make our scaling in Z work appropriately with our sliders and dims range. There have been a number of issues raised around this already, but I wanted to collect some of them here #614, #659, #640

I'm not sure if the vispy scene graph can handle rotations, but we should look into that. I'm fine with delaying on that for a bit too.  

@axtimwalde proposed the addition of a new coordinate system so we now have something akin to `layer`, `world`, and `canvas` coordinates. I know @jni has also discussed this with him too.

We can collect implementation / API ideas here.

**Comment by sofroniewn** [comment]
We should also fix #707 at this point too

**Comment by GenevieveBuckley** [comment]
This is of particular interest to me, and I may be able to help with example use cases & demo data here. 

I didn't catch Juan's conversation with Stephan, so subscribing here to get a better sense of people's thoughts.

**Comment by jni** [comment]
Yep so a little bit about how Big Data Viewer works, as I understood it/remember it.

Somewhat surprisingly, all of the rendering is CPU, not GPU-based. All of the speed is achieved through lazy rendering (as suggested by @d-v-b and @constantinpape) and async/non-blocking interactivity. There is a transformation from screen-pixel/canvas space to world space (typically, just a scaling, but in our case for e.g. grid mode, it could be more complicated, including a tiling), and from world space to the data space of each dataset/layer.

On each draw event, BDV steps through all the pixels, and for each pixel, it composes the transformations together to find the source location in the original data and grabs it. Here, Java has an advantage over Python in that the compiler inlines all of the transformations and it's reasonable to do them all for each individual screen pixel. In Python, we would need to find a way to vectorise this operation, or else move a chunk of code to numba. 

The other advantage they have is that the imglib2 data model is pretty excellent and again, efficient to access on a per-pixel level. Unlike a dask array, asking for a pixel value in an imglib2 array actually grabs it. The way they minimise IO is that the data source (which, like a dask array, can be virtual, backed by computation or IO) is transparently cached, so the first pixel grab is slow, but subsequent ones to the same block are fast.

To get the same level of responsiveness with our architecture is going to be pretty challenging, since we have this model of sending a whole slice in to the vispy visuals, so composing screen -> world and world -> data transforms becomes a bit more challenging.

I think the *easy* part is separating the concepts out in napari so that, in terms of the *design* of the library, its clear what system a coordinate refers to. Some of the challenges I see:

- Making certain UI decisions like, do the sliders refer to world coordinates or data/layer coordinates? I kinda think that the only consistent answer is world here, as soon as you have multiple layers with transforms.
- Figuring out how best to manage transforms. We want as much as possible to happen on the GPU (actually the vispy [transformation system](http://vispy.org/visuals.html#module-vispy.visuals.transforms) looks pretty thorough, which is great), but eventually, we need to be able to translate back from world coordinates to the CPU so we can load the appropriate bits of the data. This seems super tricky to me.
- Rearchitecting how we update the viewer so that changing views isn't blocking. Right now this last one is a big one, and could kind of happen independent of the transforms thing. Like, if I move the slider quickly and it's a slow process (e.g. Talley's live deconv example), we should be smart enough to toss out the intermediate tasks. The slider itself should never block waiting for the display. This might be reasonably straightforward to achieve with a task queue: rather than just calling np.array() on a dataset, add the call to np.array to a queue, and have that queue hold at most nlayers tasks. Then, as soon as a new event is triggered, drop running queue jobs and start again (unless the hash of the job hasn't changed).

Those were just high level, stream of consciousness thoughts, but I wanted to get them down for my own memory for when I finally start work on this.

**Comment by sofroniewn** [comment]
> On each draw event, BDV steps through all the pixels, and for each pixel, it composes the transformations together to find the source location in the original data and grabs it.

Indeed - moving towards this would be a major change which I don't think we're ready for, but good to put down that approach in this issue

> I think the easy part is separating the concepts out in napari so that, in terms of the design of the library, its clear what system a coordinate refers to. 

Agreed and we should do the easy stuff first. I think we are aligned here.

> do the sliders refer to world coordinates or data/layer coordinates? I kinda think that the only consistent answer is world here, as soon as you have multiple layers with transforms.

I think that is correct, though might be good to here from @will-moore who made this post https://forum.image.sc/t/napari-non-integer-step-size/31847/6. I think the slider itself will span world coordinates and then convert to `layer` indices to grab the data we need which then gets sent to vispy

> we need to be able to translate back from world coordinates to the CPU so we can load the appropriate bits of the data. This seems super tricky to me.

I feel like this is just about chaining some transforms / inverse transforms together and then doing some indexing, so maybe tricky, but all maths and super fast right? We don't actually have to do any of the transforms of the big arrays on the cpu unless I am missing something.

> Rearchitecting how we update the viewer so that changing views isn't blocking.

This would be super cool, but agreed is independent, and as I don't think we're going to the full pixelwise approach at this point should be considered as a separate issue. I think as people do more examples with dask compute this will be more important.

**Comment by tlambert03** [comment]
> > On each draw event, BDV steps through all the pixels, and for each pixel, it composes the transformations together to find the source location in the original data and grabs it.
> 
> Indeed - moving towards this would be a major change which I don't think we're ready for, but good to put down that approach in this issue

the index transformations doesn't seem like that hard of a challenge in its own, i feel like the major difference in the BDV case is the dependence on chunked data formats, right?  (i.e. even if we could easily calculate the indices in the original volume required to render any arbitrary slice, reading them from disk is the problem).  Either way, if I understand the conversation correctly, I ultimately like the general idea of making the "get_data_view" function responsible for mapping requested coordinates (in canvas/slider space) to world space, and some layer mapper also mapping to world space (accounting for physical pixel size).  it's just the indexing that becomes tricky.  If everything is in RAM, it's easy, but otherwise becomes very file format dependent.


> > do the sliders refer to world coordinates or data/layer coordinates? I kinda think that the only consistent answer is world here, as soon as you have multiple layers with transforms.
> 
> I think that is correct, though might be good to here from @will-moore who made this post https://forum.image.sc/t/napari-non-integer-step-size/31847/6. I think the slider itself will span world coordinates and then convert to `layer` indices to grab the data we need which then gets sent to vispy

i agree... as soon as you have two 3D image layers with different nZ and dZ, I can't think of how else you would overlay them but to have the sliders be world coords.  In the case of a single image layer volume with anisotropic voxels though, I think it should be relatively easy to do a better job of having the sliders step _only_ along valid indices in the underlying data.  (i.e. a single, 50-plane image should always have 50 sliders steps, regardless of `shape` settings).  Since that's mostly a slider issue, it might make sense to put that step-restriction logic in `QtDims`?

**Comment by GenevieveBuckley** [comment]
From our discussion at the hack day today, we decided this is the framework we think we should use for describing space(s) in napari:
* data (nD data, with pixels)
* world (nD spatial universe, with units)
* worldslice (a 2D plane cut through world, with units)
* canvas (what you see rendered on the screen, with canvas_pixels)

**Comment by sofroniewn** [comment]
That's great @GenevieveBuckley! I might refine this slightly to be

- data (nD data, with pixel units)
- world (nD spatial universe, with physical units)
- worldslice (a 2D or 3D plane or cube cut through world depending on number of displayed dimensions, with physical units)
- canvas (a 2D plane that you see rendered on the screen, with canvas_pixel units)

and I might prefer `screen` to `canvas` as it is less ambiguous to me, but I'm open.

At other places in the repo we've used the word `view` as in `_data_view` to capture the data after the `worldslice` is done. We could use `worldview`, but maybe `worldslice` is better and we should switch things like `_data_view` to be `_data_slice` too

**Comment by jni** [comment]
> and I might prefer screen to canvas as it is less ambiguous to me, but I'm open.

My first instinct was, sure, it is more intuitive to me also, but then I realised it's actually *more* ambiguous, because screen could be the whole *monitor* rather than just the bit occupied by the vispy canvas...

I do prefer slice to view...

**Comment by sofroniewn** [comment]
Oh right, completely see it now, (0, 0) for the screen is very different than (0, 0) for the canvas!! Canvas is the better choice for sure :-)

**Comment by d-v-b** [comment]
>     * data (nD data, with pixels)
> 
>     * world (nD spatial universe, with units)
> 
>     * worldslice (a 2D plane cut through world, with units)
> 
>     * canvas (what you see rendered on the screen, with canvas_pixels)

I find this a little muddled... sure, you can define a `worldslice` as a collection of points in a particular coordinate space with real units, but for this `worldslice` there is a corresponding `dataslice`, which is that same collection of points but mapped into data coordinates (e.g., array indices). Should there be an API-level recognition of both? These two slices are a really the same thing -- a grid of points, in one space, or another, related by a single transform. For simplicity I find it a lot easier to think about it from a transform-centric perspective, e.g.: 

* world coordinates (e.g., nanometers) map to data coordinates (array indices) via a _transform_.
* views of data are _generated_ by sampling data at points in data coordinates (e.g., array indexing)
* views of data should be _displayed_ in world coordinates (e.g. by composing the `data2world` transform with a `world2pixels` transform).
* views of data should be _changed_ by making perturbations defined in world coordinates, which become data coordinates via the transform. Concretely, this means that sliders in the gui should span a range defined in world coordinates, not array indices.

**Comment by jni** [comment]
@d-v-b I was thinking about it in terms of API. The data will be given as an nd volume with nd transform parameters: `scale`, for example, would be the vector (16ms, 1um, 200nm, 200nm) for a tzyx volume. So, it's straightforward to define a mapping from data to world.

In terms of the sliders, yes, I think we want them to be in world data coordinates in general. For example, if I stack multiple 3D volumes along the slicing direction, I want to be able to slice through all of them — data coordinates become meaningless once you have multiple layers that don't exactly overlay on each other: *whose* data are you slicing over?

So that's why I was thinking of data -> world -> worldslice (or with the arrows inverted). I guess you are saying that mapping to the space and slicing are two orthogonal operations? ie it's actually data -> world -> canvas, and slicing is something that happens on both world and data and needs to be synchronised?

I think the above ordering came about by looking at the modifications that happen to coordinates throughout napari. We need to be able to speak about coordinates in each of the above spaces unambiguously. I guess you are right that we need dataslice coordinates as a term. Would you say that's your main point above?

**Comment by d-v-b** [comment]
> So that's why I was thinking of data -> world -> worldslice (or with the arrows inverted). I guess you are saying that mapping to the space and slicing are two orthogonal operations? ie it's actually data -> world -> canvas, and slicing is something that happens on both world and data and needs to be synchronised?

I'm not sure what the arrows mean here... maybe it's easier to explain with code? How do you see the API looking? Here's a rough idea of how I envision things: 

```python
# set slider position to 1 mm on the z axis; equivalent to user clicking on slider 
viewer.sliders[0].position = .001

# a method of the image layer class, called when we need to update the clipping plane / volume
def slider_changed(self):
  # update clipping plane based on new slider position, e.g. translate by .001 along 0th axis 
  self.clipper.update(self.sliders)

  # sample the data using the updated clipping plane. 
  # the datasource converts world coordinates to data coordinates. 
  # this function can be lazy / async, based on simple array indexing or interpolation-based
  # resampling for non-axis aligned clipping planes. pyramid handling would also happen in here.
  view = self.datasource.sample(self.clipper)
  
  # i'm not sure where the view goes next... assigned to a property of the viewer class?
  # added to a queue? not sure.
  self.do_thing_with_view(view)
      
```

* The viewer only knows about world coordinates
* The viewer has a clipping plane, defined in world coordinates, that gets moved around by user input (maybe this is what you meant by worldslice?)
* The datasource has a method that takes a clipping plane and returns data sampled on that plane. Internally, the datasource will transform the clipping plane to data coordinates and decide how to resample the data appropriately.
* The datasource is stateless w.r.t. to resampling -- it doesn't track the current position of the clipping plane. So the same datasource could be resampled by multiple different clipping planes in the same layer (e.g., for orthoviews).

Does this rough sketch match how you are thinking about things? For work reasons I'm digging around the neuroglancer codebase, so I will be very interested to see how this stuff gets solved over there.

**Comment by sofroniewn** [comment]
We've come a long way in the past year, and with PRs like #1660 we now finally have a proper physical coordinate system in world coordinates.

#1616 will add support for affine transforms, and #854 a camera model. We still havn't got support for non-orthogonal reslicing and arbitrary clipping planes. Looking at the list above from @d-v-b 

> - The viewer only knows about world coordinates

Achieved

> - The viewer has a clipping plane, defined in world coordinates, that gets moved around by user input (maybe this is what you meant by worldslice?)
> - The datasource has a method that takes a clipping plane and returns data sampled on that plane. Internally, the datasource will transform the clipping plane to data coordinates and decide how to resample the data appropriately.

Not yet achieved, but would be done if/ when we support non-orthogonal reslicing and arbitrary clipping planes.

> - The datasource is stateless w.r.t. to resampling -- it doesn't track the current position of the clipping plane. So the same datasource could be resampled by multiple different clipping planes in the same layer (e.g., for orthoviews).

Also not yet achieved, but we will be investigating when we support multiple canvases, and we will definitely move in this direction.

**Comment by sofroniewn** [comment]
I will close this issue though as the main goal of supporting a physical coordinate system has now been achieved and it will probably be easiest to continue discussion of those other topics on issues like #320 for non-orthogonal slicing and #1353 for stateless slicing.
