### ISSUE TITLE
ColorArray as face_color errors

### ISSUE THREAD

**Issue by HagaiHargil** [napari/napari#774]
## 🐛 Bug

When trying to use a `ColorArray` for different point colors an error is raised by `napari`. Perhaps related to #762.

## To Reproduce

```python
points = np.array([[10, 10], [20, 20]])
ca = vispy.color.ColorArray(['red', 'blue'])

with napari.gui_qt():
    v = napari.view_points(points, face_color=ca)  # ValueError
````

Interestingly, a list as `face_color` works, i.e. `face_color=['red', 'blue']`.

## Expected behavior

The `ColorArray` should grant each point its designated color.

## Environment

`napari 0.2.6, python 3.7, vispy 0.6.2`

## Additional context

The full traceback from the code is the following, perhaps suggesting that `napari` doesn't transfer the right array to `vispy`:
```shell
Traceback (most recent call last):
  File "/home/hagai/Code/napari/nan_example.py", line 24, in <module>
    v = napari.view_points(points, face_color=ca)
  File "/home/hagai/Code/napari/napari/view_layers.py", line 233, in view_points
    visible=visible,
  File "/home/hagai/Code/napari/napari/components/viewer_model.py", line 666, in add_points
    self.add_layer(layer)
  File "/home/hagai/Code/napari/napari/components/viewer_model.py", line 386, in add_layer
    self.layers.append(layer)
  File "/home/hagai/Code/napari/napari/util/list/_model.py", line 56, in append
    self.events.added(item=object, index=len(self) - 1)
  File "/home/hagai/Code/napari/napari/util/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/hagai/Code/napari/napari/util/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/hagai/Code/napari/napari/util/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/hagai/Code/napari/napari/_qt/qt_viewer.py", line 148, in _add_layer
    vispy_layer = create_vispy_visual(layer)
  File "/home/hagai/Code/napari/napari/_vispy/util.py", line 33, in create_vispy_visual
    visual = layer_to_visual[type(layer)](layer)
  File "/home/hagai/Code/napari/napari/_vispy/vispy_points_layer.py", line 29, in __init__
    self._on_data_change()
  File "/home/hagai/Code/napari/napari/_vispy/vispy_points_layer.py", line 89, in _on_data_change
    scaling=True,
  File "/home/hagai/miniconda3/envs/napari_dev/lib/python3.7/site-packages/vispy/visuals/markers.py", line 553, in set_data
    face_color = ColorArray(face_color).rgba
  File "/home/hagai/miniconda3/envs/napari_dev/lib/python3.7/site-packages/vispy/color/color_array.py", line 148, in __init__
    rgba = _user_to_rgba(color, clip=clip)
  File "/home/hagai/miniconda3/envs/napari_dev/lib/python3.7/site-packages/vispy/color/color_array.py", line 55, in _user_to_rgba
    color = np.atleast_2d(color).astype(np.float32)
ValueError: setting an array element with a sequence.
```

**Comment by HagaiHargil** [comment]
From some basic debugging, it seems like `set_data` [here](https://github.com/napari/napari/blob/a166f3119248a7249133eb704401ff7aee1c14fe/napari/_vispy/vispy_points_layer.py#L82) is expecting a string or a single tuple as the `face_color` argument, but instead it has a `ColorArray` at hand.

Also, to circumvent the issue one can use `colors = [color.rgba.ravel() for color in colors]`, assuming that `colors` is a `ColorArray`. Then `colors` can be used as the `face_color` argument.

**Comment by sofroniewn** [comment]
Hmm yeah I guess we hardcoded some assumptions there. Given that we currently all people to pass vispy colormaps to the `colormap` property for custom colormaps, it probably makes sense to allow people to pass a vispy `ColorArray` to our `color` like properties.

@kevinyamauchi @jni do you agree with this? In which case we should fix and standardize across all the layers which accept colors (`Vectors`, `Shapes`, `Points`) and add tests to each layer

**Comment by HagaiHargil** [comment]
I'll be happy to tackle this PR myself with a bit of guidance.

**Comment by jni** [comment]
Yep, I'm 👍 on this proposal. Thanks for reporting @HagaiHargil and even more for offering to fix! =)

**Comment by kevinyamauchi** [comment]
Thanks for raising this, @HagaiHargil ! I agree that we should allow people to pass custom colors to set `*_color` properties in our layers. I have listed a few thoughts below. Please let me know what you all think!
- Do we want users to pass `ColorArray` objects or is it preferable to allow users to pass RGBA tuples (or some other format)? As far as I can tell, from the user perspective, the `vispy` `ColorArray` would basically be a container for the RGBA tuple. If that is the case, accepting the RGBA tuple directly would save the user an import.
- It would be nice if there was a "transparent" default so that users can pass something simple (e.g., `None` or `'transparent'`) and the color is set with alpha=0 (see #762).
- I am not sure the best thing to display in the viewer dropdown menus when the user sets the `face_color` with a custom `ColorArray`. Perhaps we add something generic to the list (e.g., "custom") and that gets set when the user sets the parameter with a `ColorArray`? It could be cool if clicking the color swatch opened up a UI (not a popup :P ) for setting the RGBA tuple. Thoughts?

@HagaiHargil, it would be awesome if you took this on! I am happy to chat more if you have questions.

**Comment by HagaiHargil** [comment]
The only reason I was even aware of vispy's `ColorArray` is that the documentation for `face_color` states that users can pass a `ColorArray` instance for the colors of individual points.

I think that we should be able to allow list-like containers of 3- and 4-tuples, as well as `ColorArray`s, since they're quite easily constructed from numpy arrays and lists. I'll start tackling this issue soon.

**Comment by kevinyamauchi** [comment]
Sounds great! Let me know if you have any questions or run into any issues!
