### ISSUE TITLE
Better generalize keybindings

### ISSUE THREAD

**Issue by kne42** [napari/napari#785]
The current keybindings system could be made more general. Right now, it's mainly optimized for the viewer and layers. This creates awkward situations for different modes (see https://github.com/napari/napari/pull/780#discussion_r356111992) and will create awkward situations in the future for plugin developers.

This can be accomplished by:
- making the keybinding handling system more generalized (for example, right now, all of it lives in the `QtViewer` class)
- allowing multiple keymaps to be chained together. for example, say you have the movie mode activated while having a points layer selected. then the functions called when the keybinding is pressed will check in the following order: movie instance keymap -> movie class keymap -> points instance keymap -> points class keymap -> viewer instance keymap -> viewer class keymap

Thoughts?

**Comment by jni** [comment]
@kne42 

> will check in the following order

like a Keybindings path! I like it. =) I thought that was what we had now. 😂 One thing I want to make sure of is that keybindings are "overwritten", not compounded. e.g. in matplotlib, when you add a keybinding, if it already exists, now your shortcut does two things. There is no indication that your keybinding was already "taken". This drove me nuts while I figured that out! And it made my code uglier because I had to go and manually remove keybindings I didn't care about.

**Comment by kne42** [comment]
Yeah, we definitely want to overwrite the existing keybindings or it will get way too confusing. It will only call the first function it finds in that search path matching the keybinding pressed :)

**Comment by sofroniewn** [comment]
Sounds good to me @kne42. Will this cause any breaking changes to our existing system? Or is it strictly more general

**Comment by kne42** [comment]
@sofroniewn there may be some changes on the user end mainly to do with how keymaps are represented

**Comment by kne42** [comment]
I think instead of using that whole `InheritedKeymap` mess, I'd like to just use regular dictionaries instead, and the whole "active keymap" can be calculated elsewhere.

**Comment by sofroniewn** [comment]
Sounds good, we can wait for ‘0.3’ to merge

**Comment by kne42** [comment]
@sofroniewn what do you mean by that?

**Comment by sofroniewn** [comment]
I meant this discussion sounds great and you should start work on it as soon as you want, but if there end up being breaking changes we might want to wait to merge until we bundle a bunch of breaking changes together (see discussion here https://github.com/napari/napari/pull/773#pullrequestreview-328582585 and here https://github.com/napari/napari/pull/686#issuecomment-553154422) and call it `0.3` rather than just merge as soon as it is finished. If there are no breaking changes it can just go in when it is done and the next `0.2.x` release. I wouldn't worry too much about that now though, and we can discuss this closer to the time it is ready. Does that sound reasonable? I may have misunderstood your reply
