### ISSUE TITLE
Unify layers.ipynb and demo.py example

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#84]
## ❓ Questions and Help

Right now our notebook and scripting examples use slightly different versions of the api `imshow` and `add_image`. These should be unified.

In general we should think about what examples we want and what testing we want to ensure all our code is working properly.

**Comment by sofroniewn** [comment]
Curious what peoples thoughts on the examples are? One thing I think we're agreed on is that we want the scripting examples and the ipython examples to be the same (as far as possible) and that we're going to start using something like `jupytext` soon (see #67). I think we also agree that we want to start providing some of our own images, and drop `skimage` as a dependency.

For now though I'm wondering if people want one long demo that opens multiple viewers each highlighting different functionality? Do we want one long demo that only opens on viewer and does all our interactivity inside of it. Probably hard to achieve for the scripting mode where everything executes at once. Or do we want lots of small examples, each only opening one viewer and each just highlighting one aspect of the functionality?

I lean towards the later option and having a couple smaller examples, like highlighting multidimensional images, or rgb images, or color blending across layers, or markers, or markers and images combined. What's a list that people want to see?

I'm sure we'll be revisiting this many times, but improving things now could help focus our refactoring efforts and ensure that we're all on the same page with-respect to functionality etc. It could also help us as we think more about testing.

**Comment by kne42** [comment]
The script and interactive APIs differ primarily because interactive sessions provide their own Qt event loops whereas scripts must manually start the event loop with `QApplication.exec_()`, which is a blocking process.

While I definitely agree that the script API should be _similar_ to the interactive's, I don't necessarily think that we should necessarily have the same API for both. `matplotlib` tried to and their API is super clunky.

I propose that we use [context managers](http://book.pythontips.com/en/latest/context_managers.html) to improve scripts' API:
```python
with gui.imshow(image1) as viewer:
    viewer.imshow(image2)
```

This mirrors a typical interactive workflow:
```python
>>> viewer = gui.imshow(image1)
>>> viewer.imshow(image2)
```

Behind the scenes, this would require `Viewer` to implement the `__enter__` and `__exit__` methods, executing `QApplication.exec_()` upon exit to start the event loop.

**Comment by AhmetCanSolak** [comment]
> 
> I propose that we use [context managers](http://book.pythontips.com/en/latest/context_managers.html) to improve scripts' API:
> 
> ```python
> with gui.imshow(image1) as viewer:
>     viewer.imshow(image2)
> ```
> 
> This mirrors a typical interactive workflow:
> 
> ```python
> >>> viewer = gui.imshow(image1)
> >>> viewer.imshow(image2)
> ```
> 

I think it is a good idea. It is also useful for testing. 

However, aside from `viewer.imshow()` we should provide a way to create gui without adding an image layer? Am I right? correct me if got our discussions wrong.

**Comment by bryantChhun** [comment]
I am all for lots of small examples, very much like how vispy publishes their examples.

I'm also willing to write a bunch of these and/or tests for the scripting side of things.

**Comment by sofroniewn** [comment]
With #153 and #128 we have now addressed this issue
