### ISSUE TITLE
Quitting Qt app instance after exiting napari.gui_qt context

### ISSUE THREAD

**Issue by irahorecka** [napari/napari#893]
I am curious how to properly exit a napari GUI application in a Jupyter Notebook environment without:
1) Force quitting 
2) Restarting the kernel

Thanks!

**Comment by tlambert03** [comment]
can you provide a bit more info about what you're doing (i.e. the code you're using to launch napari, and what you're expecting to happen)?
normally, simply closing the napari window is sufficient to terminate cell execution and carry on with the rest of the notebook.

**Comment by irahorecka** [comment]
Hi Talley, thank you for getting back to me. Here's the code I'm running in Jupyter Lab (Python 3.7.3)

```
import os
import napari
from dask_image.imread import imread

tiff_dir = os.getcwd()
stack = imread(f"{tiff_dir}/images/*.tif")
with napari.gui_qt():
    napari.view_image(stack,
                     contrast_limits=[0,2000],
                     is_pyramid=False)
```

When I close napari (close window button (red) in upper left window), I can reopen it by re-executing this code. However, in my MacOS dock, the napari application icon lingers. I have to force quit the application (right-click the icon --> force quit) to remove it from my dock. An alternative method is to restart the kernel in my Jupyter Lab.

**Comment by tlambert03** [comment]
ahh, I see.  it's the dock icon you're talking about, thanks that helps.
Yes there might be a stray Qt event loop still running after closing that main window that we could potentially clean up.  But we also need to make sure we don't clobber other processes using the same qt loop.  This clarifies it enough though thanks!

I would say that in the meantime, while we look into it, that icon down there is probably not hurting much, and I suspect it's using almost no resources, and will naturally close itself when you close the jupyter kernel.

**Comment by kne42** [comment]
hi @ irahorecka, for usage in Jupyter you should be omitting the `napari.gui_qt` context manager and using the `%gui pyside2` or `%gui qt5` line magic, according to your preference

regardless, this will still cause the same issue since it will be IPython keeping the event loop alive. according to the documentation, you should be able to shut off the event loop with just a `%gui` call, but I have tried it myself and it does not work (all Qt processes freeze instead)

**Comment by tlambert03** [comment]
is there something specifically wrong about using the context manager in jupyter?

It's always worked for me, and I don't know why, but the magic has actually _not_ worked for me in a jupyter notebook (possible this has something to do with my using jupyter lab, or perhaps using `nb_conda_kernels` for environment management in jupyter?)  though the magic does work for me in an ipython session.  Also is `%gui pyside2` [valid](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-gui)?  I get `Invalid GUI request 'pyside2'`

**Comment by kne42** [comment]
Oh right, my bad it's `%gui qt`, I forgot what we changed it to 😅 

The problem with the context manager is that it's a blocking process due to the `app.exec_()` call on exit (at least last time I checked, which to be fair, was like a year ago). Using the `%gui qt` magic on the other hand won't block your next cell.

**Comment by sofroniewn** [comment]
Sounds like from the comment in https://github.com/napari/napari/issues/919#issuecomment-579471058 the original issue of @irahorecka has now been resolved and so I will close this. If anyone wants to discuss this further we can always reopen it.
