### ISSUE TITLE
Where do qt elements get connected to functions

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#92]
## ❓ Questions and Help

My question has two main parts to it. The first is where to qt elements get connected to functions? What I mean by this is right now take one of the buttons like out `QAddLayerButton` this needs to get connected to the function that actually adds the layer. It was previously done inside the `_layer_buttons` file inside the `qt` folder, but now in the latest on #90 I have moved it to inside the `_viewer` file which is not inside the `qt` folder. Basically - should this sort of logic be happening on files inside the `qt` folder or on files outside the `qt` folder. I lean towards the latter - I think it keeps the files in the `qt` folder then much simpler, and not having to do with the logic of the gui but just the actual elements that are getting rendered.

As a second part of this question - should the `viewer` or higher level object be passed as an input to the classes in the `qt` folder. I.e. should `dimensions` be passed to the `QtDimensions` class in the `qt` folder. Right now we do it in a whole bunch of places, but maybe as part of the refactor we should prevent this. Preventing this then forces us to put all the connection logic into the files outside the `qt` folder and means the files in the `qt` folder are just responsible for laying out the widgets and any self contained styling and logic.

What are peoples thoughts about this? @AhmetCanSolak @kne42 @royerloic @jni

**Comment by jni** [comment]
@sofroniewn I have literally no thoughts on this. =P

One thing did strike me:

> Right now we do it in a whole bunch of places, but maybe as part of the refactor we should prevent this.

Without fully grasping the architecture now or what you're proposing, this sounds good to me. Single points of control are a Honking Good Idea.

**Comment by sofroniewn** [comment]
It's really a question about what lives in `QtDimensions` vs `Dimensions` or in `QtLayer` vs `Layer` or in `QtLayerList` vs `LayerList` and whether the non-qt object should be passed to the qt object on constructions. To be more explicit - if you look at the current state of #90

In the `_dimensions` file in the `qt` folder is the following
```python
class QtDimensions(QWidget):
    def __init__(self, viewer):
```
and within that class `viewer` gets used in a couple of places. Instead should those usages be moved out of that file and into the `Dimensions` class?

In comparison in `_control_bars.py` within the `qt` folder it is just the following
```python
class QtControlBars(QWidget):
    def __init__(self):
```
and the file is very simple, creating the `qt` elements and doing the layouts and stylings. All our custom logic is inside the `ControlBars` class.

The `QtLayerList` vs `LayerList` is a particularly strong case of quite a lot of custom and complex logic happening inside the `QtLayerList`. Should all of this be pulled out into the `LayerList`?

Similarly all the elements in `QtLayer` get connected inside the `QtLayer` class not the `Layer` class. Should that be pulled out into `Layer` class too? One argument against is that now these two files will really depend on each other. When you create the layer you'll want to start connecting everything. I guess there is an optional if statement that you can use to check if a `_qt` element has been created and if so connect away, and if not ignore.

All in all I prefer pulling all the custom logic out of our `Qt` classes so that they don't need to be passed their parent object on construction and we avoid the circular dependencies that @royerloic talked about and will make those files very clean but I want to run this by everyone first.

**Comment by kne42** [comment]
I was considering maybe even taking a page from @royerloic’s reply https://github.com/Napari/napari-gui/pull/88#issuecomment-447415295 and making this all more modular by using another listener pattern here. Not sure if it’s a bit overkill tho.

In that case, all abstract viewer functionality would be housed directly inside of the viewer and Qt rendering objects such as QtDimensions would listen in for updates.

**Comment by sofroniewn** [comment]
@kne42 that seems reasonable to me, I'd have to see it to really understand. In the mean time do you think I should continue pulling logic out of the Qt classes? We can wait until we've merged #88 and #90.

**Comment by jni** [comment]
Thanks very much for the explanation @sofroniewn! That is clearer. I think it's a very good idea. If, say, in 5 years we decide that PyQt is no longer the way to go and we should switch to Kivy, this kind of separation will make that process much less painful.

I'm less sure about the listener pattern since that directly depends on PyQt anyway...

**Comment by kne42** [comment]
It can be but it doesn’t have to. We can always create our own event system
or just steal vispy’s :P

**Comment by royerloic** [comment]
A few general principles to keep in mind:
i) It is often a good idea for the UI to know about the machinery but not for the machinery to know about the UI. Something has to know about something, for sure, but why choose one over the other? First, the UI is really a 'view' and should be optional. This makes it possible to have the machinery operate headless which is always a good idea. New UI architectures can be easily swapped in. 
ii) So, how do we have the machinery 'control' the UI? we simply have the UI register listeners to the machinery, so that the machinery can notify the UI.
iii) 'import separation': one hint that things are not designed as they should is when you import all sort of packages from everywhere, like qt and non qt from qt and non qt classes. Using listener schemes and other interfacing startegies can reduce mixed imports and leads to a clean design where for example a few well defined classes and packages import qt classes, and no other classes do...
iv) In python listeners in the form of closures/lambdas are trivial to implement and so it is very easy for us to implement our own listener schemes. Nevertheless, I think it is ok to use Pyqt's scheme as long as we satisfy rule (i) and (iii)
v) A pattern that I have used with great success in ClearControl is that of UI classes that are peers of non-UI classes. The UI class takes the non-UI class as constructor argument. The non-UI class does not 'know' about it, but there is a generic mechanism for interfacing that lets the non-UI (machinery) class communicate with the UI. The non-UI peer class can perfectly operate without UI. Simulated non-UIpeer classes can be used for testing the UI.

Hope these meta comments can be adapted to the discussion above and shed some light on the design choices that are being made.

**Comment by sofroniewn** [comment]
Ok nice, these are great general principles. As we go through the refactor and #90 and beyond we should be thinking about how we are applying them.

**Comment by AhmetCanSolak** [comment]
> iii) 'import separation': one hint that things are not designed as they should is when you import all sort of packages from everywhere, like qt and non qt from qt and non qt classes. Using listener schemes and other interfacing startegies can reduce mixed imports and leads to a clean design where for example a few well defined classes and packages import qt classes, and no other classes do...

Totally agreed. I think it is not only for UI/non-UI related imports but in general true. Except util-like pieces, it is bad sign to  importing same thing in many occasions.

> 
> Hope these meta comments can be adapted to the discussion above and shed some light on the design choices that are being made.

Thank you @royerloic. I encourage everybody to come up with such meta comments and discussion. This way we can push implementation forward more stable.

**Comment by sofroniewn** [comment]
Hi all, I was looking around for some examples of pyqt5 apps built using a model / view like architecture and I found this one [blog post](https://www.pythonforthelab.com/blog/step-by-step-guide-to-building-a-gui/) and [repo](https://github.com/PFTL/website/tree/master/example_code/22_Step_By_Step_Qt/AI_camera_model) that I think is quite nice.

Here the `model` gets passed to the `view` on construction, though it is possible to pass it as None. The view is able to read properties directly from the model. The view is able to change properties of the model by calling `set` methods on the model (there are no events here). The view never directly changes properties of the model. The model knows nothing about the view, and in their simple example has no way to update the view directly.

**Comment by sofroniewn** [comment]
Trying to take that example and the guiding principles from @royerloic, and get into the specifics for napari it seems that our architecture should consist of non-UI and UI peer classes (I like this terminology) where the UI (equivalent to the `view`) takes the non-UI (equivalent to the `model) on construction and adds it as a property.

The UI class can then read anything it needs from the non-UI class simply by looking inside it.

Question 1) Is the UI class allowed to directly change the non-UI class or does it have to use a set method that the non-UI class provides, i.e. inside the non-UI class which of the following do we have 
```python
model.xyz = value
```
or
```python
model.set_xyz(value)
```

Question 2) The non-UI class needs to communicate updates with the UI class. Expanding on some comments from @kne42, if we use the pyqt event system all out non-UI objects now have to become Qt objects in order to emit events. Is this undesirable? It would make switching out from Qt harder in the future. Or do we want to use the Vispy event system? We are already doing this in a couple places and it works fine, but it weds us very strongly to vispy. Or do we want to role our own or add an independent 3rd party system as a dependency?

Question 3) Right now the UI class also gets imported into the non-UI class and appended on there as `_qt`. This seems to break some of the separation that we were trying to enforce. The non-UI class now knows about the UI. Is it ok for it to just be a property and we don't ever want to go into it inside our developer code, or is there a way to get rid of it entirely? Right now we often access the view from inside the model, by going `model._qt.foo` it seems like this behavior should be eliminated and replaced by the event system mentioned above.

Question 4) Finally as our model is hierarchical - there is viewer, layers, dimensions, controlBars, layer but they in turn have viewer as properties on them, when we are in a UI class are their rules about which non-UI class we can be modifying or if anything fair game? I.e. inside the UI-dimensions can we only modify non-UI-dimensions or can we modify non-UI-layers, non-UI-viewer etc. as needed. Can the UI objects emit events that can be listened to by anyone - this is how I am doing the status_bar updates now, but it might break our other patterns.

**Comment by kne42** [comment]
1) I think that the only thing that discourages directly setting the attributes is that the UI class should be updated whenever the non-UI class is swapped out. However, this is fine in Python since we are using `property`s and can call the update code in our "functional" attribute access.

2) We should definitely not go with the Qt event system outside of Qt classes, especially considering that we would have to make more objects Qt (ew!). I also agree that being dependent on `vispy`'s event system is not ideal. We can either create our own event system from scratch or just copy/paste what `vispy` has.

3) I think we should just get rid of it entirely.

4) I think that all UI components should be agnostic to the existence of anything but themselves and their respective non-UI components. The non-UI components will handle communication/updating among each other and then those changes will be passed down to the UI via the event system. For example, when a slider is dragged, it will update the dimensions non-UI component, which will then update the viewer's "view point," which will then update the canvas UI component.

**Comment by kne42** [comment]
I think that, as @sofroniewn is touching on, we should definitely address is how we’re structuring the project as a whole. @AhmetCanSolak you’re the expert here, what are your thoughts?

I think a definite first is that we need to move away from the whole concept of matching Qt and non-Qt components as 1:1 pairs. I think that we should adopt more of a one-to-many protocol where information from a central object is dispatched to all of the Qt objects which can be structured as necessary.

From what I’ve read, the MVC pattern does look pretty appealing and I’ll write up my thoughts later on how that might fit into the project.

**Comment by royerloic** [comment]
Strongly support @kne42 last comment!

**Comment by sofroniewn** [comment]
I'm open to moving away from the matching pairs concept, but regardless PR #90 is now in pretty good shape (using the matching pairs, but otherwise trying to be more like a MVC pattern) and I think we should review and merge those changes first.

If we then want to adopt more of a one-to-many system that's fine, but we should start making those changes with #90 as a base and not the current master.

**Comment by kne42** [comment]
Of course! I’ll review it shortly :)

**Comment by AhmetCanSolak** [comment]
@sofroniewn thank you for questions to discuss. I will be replying the @kne42 's answers since already she answered some questions exactly in a way i would answer.

> 1. I think that the only thing that discourages directly setting the attributes is that the UI class should be updated whenever the non-UI class is swapped out. However, this is fine in Python since we are using `property`s and can call the update code in our "functional" attribute access.
> 2. We should definitely not go with the Qt event system outside of Qt classes, especially considering that we would have to make more objects Qt (ew!). I also agree that being dependent on `vispy`'s event system is not ideal. We can either create our own event system from scratch or just copy/paste what `vispy` has.
> 4. I think that all UI components should be agnostic to the existence of anything but themselves and their respective non-UI components. The non-UI components will handle communication/updating among each other and then those changes will be passed down to the UI via the event system. For example, when a slider is dragged, it will update the dimensions non-UI component, which will then update the viewer's "view point," which will then update the canvas UI component.
>
> I think that, as @sofroniewn is touching on, we should definitely address is how we’re structuring the project as a whole. @AhmetCanSolak you’re the expert here, what are your thoughts?
>
> From what I’ve read, the MVC pattern does look pretty appealing and I’ll write up my thoughts later on how that might fit into the project.

I want to address these together. MVC definitely good idea. But as far as i understand we want UI to be updated when we use API or vice versa. Hence, we need double binding for almost everything on UI. There is a very-well known solution to this problem. Having a model with observable pattern. This is usually called as MVVM. In short idea is observing changes in model and notify controller and views respectively. I couldn't find a widely known `pyqt5` implementation of this architecture but maybe there is, if not we can implement it (I agree using vispy's event system is bad idea and possibly Qt event system alone will not be sufficient for us). This discussion can also give direction to structuring the project. UI components can help to structure views/Qt classes and we will be choosing controllers and models according to our expectations on API/functionalities. 

In case you guys would enjoy to follow this way, I will give a brief example to propagate the discussion(maybe better to have a separate issue or meeting, i love to discuss these more together).

<hr>
i.e: Lets say UI has only 4 main components: Canvas(middle top), control sliders(left), layerlist(right) and slicing sliders(middle bottom). Then it would make sense to have 4 separate QtWidget classes for these 4 components. Which will be views in our case.


We would need a layerlist model in that case for the component on right and we will need a layer model for rest of three components(depending on the desired functionality maybe this layer model could be something like a mergedlayer model for those selected layers in layerlist component). 

For controllers, obviously the functionality really differs between control sliders on left and slicing sliders on middle bottom area of screen. We would need separate controllers for them which will be relating to possibly same layer model/models.  

Implementation of observables and MVVM-C type of architecture presumed. 
<hr>

This is just a minimal sample walkthrough on how we can work for restructuring with MVVM architecture in mind. I love to hear your feedback/comments. 

> 3. I think we should just get rid of it entirely.

Totally agreed @kne42 .

> I think a definite first is that we need to move away from the whole concept of matching Qt and non-Qt components as 1:1 pairs. I think that we should adopt more of a one-to-many protocol where information from a central object is dispatched to all of the Qt objects which can be structured as necessary.

i agree that we should stop 1:1 matching ui/non-ui classes. I think we can separate gui into certain gui components and then decide on non-ui classes considering the gui components and API needs. Current codebase I believe easy to transform into this way of modularization.

**Comment by jni** [comment]
@AhmetCanSolak 

> But as far as i understand we want UI to be updated when we use API or vice versa. Hence, we need double binding for almost everything on UI.

I thought the whole idea behind the emitters/listeners pattern was that if we update the model using the API, the model "emits" that change, without knowing what views exist. Then you can have as many viewers as you like without the model having to know about them?

I am a noob at GUI programming so forgive me if that is a noob question!

Incidentally, I'm not super clear on what is the model and what is the view here, but my idea is:

- model: layer list, associated attributes, selected slices and slicing mode, selected contrast adjustments.
- view: the UI that displays all this
- (view: the code in the jupyter notebook that interacts with the API?)

As I understand it, I don't think we need to have any links from the model object to any Qt elements of any description? As long as the Qt elements "listen" for changes in the model, we should be ok?

**Comment by AhmetCanSolak** [comment]
> > But as far as i understand we want UI to be updated when we use API or vice versa. Hence, we need double binding for almost everything on UI.
> 
> I thought the whole idea behind the emitters/listeners pattern was that if we update the model using the API, the model "emits" that change, without knowing what views exist. Then you can have as many viewers as you like without the model having to know about them?
>
> ... 
>
> As I understand it, I don't think we need to have any links from the model object to any Qt elements of any description? As long as the Qt elements "listen" for changes in the model, we should be ok?

You are right. If views able to manipulate model directly, what you are saying would be enough. If not, then we need double way binding. I'm not sure about this on all views. Love to discuss this in next meeting.

**Comment by sofroniewn** [comment]
We have now successfully separated our Qt files from our Model files
