### ISSUE TITLE
Black is still a color in the label colormap => Some labels are not displayed

### ISSUE THREAD

**Issue by jluethi** [napari/napari#983]
## 🐛 Bug

When displaying label images with a label of value 305, that label is not displayed in the viewer. When colors are shuffled, it appears (see images below). It also is still visible in the thumbnail. It looks like 305 is black in the default colormap. Black with translucency is not displayed. The same happens for 915, 1525, 1902 etc. in the standard colormap

## To Reproduce

1. Create a label image with a label of value 305
2. Display this image in napari by using `add_labels`

When originally displayed:
<img width="1200" alt="OriginalLabelMap" src="https://user-images.githubusercontent.com/18033446/74759054-7cb4d380-5278-11ea-85d8-fdf587583ccb.png">
After shuffle colors:
<img width="1200" alt="PostShuffleColors" src="https://user-images.githubusercontent.com/18033446/74759061-7e7e9700-5278-11ea-91c4-6dadb599c72f.png">

Here's a simpler case with an image generated in code:
```lbl = np.zeros((20, 20))
lbl[:, :10] = 304
lbl[:, 10:20] = 305
viewer = napari.Viewer()
viewer.add_labels(lbl)
```
![1](https://user-images.githubusercontent.com/18033446/74759553-3f047a80-5279-11ea-9eba-964ec72218a5.png)

Notice how the thumbnail still shows both labels, but the 305 label is not visible in the viewer until the colormap is shuffled.
After a color shuffle:
![2](https://user-images.githubusercontent.com/18033446/74759628-5f343980-5279-11ea-95fd-15c0968b947a.png)

## Expected behavior
All labels should be visible when used in the default mode, with translucent blending. Therefore, black should be removed from the label colormap except for value 0. Currently, they still occur at some pattern all over the colormap, relatively sparsely.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.2.11
Platform: Darwin-19.3.0-x86_64-i386-64bit
Python: 3.7.4 (default, Aug 13 2019, 15:17:50) [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.13.2
PySide2: 5.13.2
VisPy: 0.6.4
NumPy: 1.17.4
SciPy: 1.3.3
scikit-image: 0.16.2
Dask: 2.9.0

GL version: 2.1 INTEL-14.4.23
MAX_TEXTURE_SIZE: 16384

We reproduced this on Mac & Windows, in napari 0.2.6, 0.2.10 & 0.2.11

(cc @HessMax who also helped with narrowing down this bug)

**Comment by sofroniewn** [comment]
Opps, that's not so good, sorry about that. I could try and make a quick fix inside https://github.com/napari/napari/blob/56ab67d009b6f8a46a049a262aecf199d3d81cb0/napari/utils/colormaps/colormaps.py#L173, but I think I might use this as a driver to make a push on #713 (maybe @jni when I see you the week after next you can help me take that one over)

**Comment by jni** [comment]
Thanks for the detailed report, @jluethi! Yep, definitely a bug in the way we "hacked" regular image display to display labels. Any value too close to zero after "hashing" from labels to floats in [0, 1] will map to 0.

@sofroniewn #713 is a bit of a mess, whereas I think this could be an easy fix: map the low-discrepancy sequence to 0.05-1 rather than 0-1. I'll try to submit a bug fix soon. Of course, that in no way precludes discussing #713 next week!

**Comment by jni** [comment]
@sofroniewn fixing now. The fix is easy, it looks like we just need to tweak the values here:

https://github.com/napari/napari/blob/56ab67d009b6f8a46a049a262aecf199d3d81cb0/napari/utils/colormaps/colormaps.py#L102

The colormap we currently use has 256 values iirc, so it should be sufficient to clip at 1/128 rather than the current value of 10^-5.

**Comment by jni** [comment]
Actually, I take it back, clipping is the wrong approach here: it'll make all the values in [0, 1/128] map to the same color. which is bad. Anyway, still an easy fix, just a bit different. =) Hold please!

**Comment by VolkerH** [comment]
In this context, I think the glasbey colormap would be most suited for label images, there is already an issue here:
https://github.com/napari/napari/issues/454
